project:
  type: website

profile:
  default: english
  group: [english, russian]
  
execute: 
  echo: false
  message: false
  warning: false
        
format:
  html:
    theme: cosmo
    embed-resources: true
    page-layout: full
