
```{r}
checkdown::check_question(answer = 'смещение; кривой; совокупного; спроса; вправо/влево', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смещение; кривой; совокупного; спроса; вправо/влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кривая; совокупного; спроса; сдвигается; вправо', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; спроса; сдвигается; вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'закон; убывающей; предельной; производительности', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закон; убывающей; предельной; производительности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; цен; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'эластичность; спроса; по', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность; спроса; по',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'смещение; кривой; совокупного; предложения; влево', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смещение; кривой; совокупного; предложения; влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'сдвигает; кривую; совокупного; спроса', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвигает; кривую; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'операции; с; ценными; бумагами', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'операции; с; ценными; бумагами',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальные; располагаемые; денежные; доходы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; располагаемые; денежные; доходы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'оценки; равновесной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценки; равновесной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'предельный; доход; продукта; труда', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; доход; продукта; труда',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'цена; за; единицу; товара', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена; за; единицу; товара',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'стратегическое; планирование; социально-экономического; развития', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стратегическое; планирование; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'стимулирование; инновационного; экономического; роста', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стимулирование; инновационного; экономического; роста',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'общий; спрос; на; деньги', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'общий; спрос; на; деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'изменение; общего; уровня; цен', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение; общего; уровня; цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'уравнение; кривой; совокупного; спроса', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уравнение; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'смещение; кривой; совокупного; предложения; вправо', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смещение; кривой; совокупного; предложения; вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'экспорт; товаров; за; границу', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экспорт; товаров; за; границу',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'на; данном; уровне; цен', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на; данном; уровне; цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'изменение', 
                          title = '#### Экономисты классической школы придерживаются мнения об отсутствии существенного воздействия шоков совокупного спроса на ____________ (**изменение**) объема производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'величина; реального; предложения; денег', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величина; реального; предложения; денег',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальная; цена; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная; цена; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рыночная; стоимость; товаров; и; услуг', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночная; стоимость; товаров; и; услуг',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кривая; совокупного; спроса; смещается', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; спроса; смещается',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'предельная; норма; технологического; замещения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная; норма; технологического; замещения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; общего; уровня; цен', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; общего; уровня; цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'асимметричное; влияние; денежно-кредитной; политики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'асимметричное; влияние; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'цена; выше; предельных; издержек', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена; выше; предельных; издержек',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'факторы; развития; межбюджетных; отношений', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; развития; межбюджетных; отношений',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'спецификация; макроэкономических; целевых; параметров', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спецификация; макроэкономических; целевых; параметров',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'чувствительность; спроса; на; деньги', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'чувствительность; спроса; на; деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'национальная; модель; экономического; роста', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальная; модель; экономического; роста',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'на; основе; уровней; социально-экономического; развития', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на; основе; уровней; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'неожиданные; шоки; денежно-кредитной; политики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'неожиданные; шоки; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'модернизация; реального; сектора; экономики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'модернизация; реального; сектора; экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'наклон; кривой; совокупного; спроса', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'наклон; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'асимметрия; развития; цифровой; экономики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'асимметрия; развития; цифровой; экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'производство', 
                          title = '#### Предположим, что совокупные расходы на ____________ (**производство**) общественного товара составляют 900 долларов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производство',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; номинальной; денежной; массы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; номинальной; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'оценка; эффективности; инвестиционных; проектов', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценка; эффективности; инвестиционных; проектов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'мировая; реальная; процентная; ставка', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальный; спрос; на; деньги', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный; спрос; на; деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; реальной; заработной; платы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'методы; оценки; теневой; экономики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'методы; оценки; теневой; экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'инструменты; налогового; стимулирования; ', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инструменты; налогового; стимулирования; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'государственное; регулирование; территориального; развития', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственное; регулирование; территориального; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'фактор; укрепления; межгосударственных; отношений', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактор; укрепления; межгосударственных; отношений',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'значение; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'значение; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'ожидаемая; реальная; процентная; ставка', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'предельный; доход; равняется; предельным; издержкам', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; доход; равняется; предельным; издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'принцип; убывающей; предельной; полезности', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'принцип; убывающей; предельной; полезности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальный; обменный; курс; рубля', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный; обменный; курс; рубля',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'валовым доходом', 
                          title = '#### Экономическую прибыль надо отличать от бухгалтерской прибыли, которая представляет собой разницу между ____________ ____________ (**валовой, доход**) и явными издержками на ресурсы, используемые в производстве.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'валовым доходом',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'механизмы; акселерации; социально-экономического; развития', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'механизмы; акселерации; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; реальной; заработной; платы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'равен; ожидаемому; уровню; цен', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равен; ожидаемому; уровню; цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'индекс; развития; человеческого; потенциала', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекс; развития; человеческого; потенциала',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'предельные; издержки; равны; цене', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные; издержки; равны; цене',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'суммой', 
                          title = '#### Банковская прибыль определяется как разница между ____________ (**сумма**) процентов, взимаемых с заемщиков за предоставленный кредит, и суммой процентов, выплачиваемых вкладчикам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'суммой',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рынок; новых; фирм; ', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок; новых; фирм; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'сдвиг; кривой; совокупного; спроса', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'цена; превышает; предельные; издержки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена; превышает; предельные; издержки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'мировая; цена; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; цена; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'импорт; товаров; на; внешние; рынки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'импорт; товаров; на; внешние; рынки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'ключевые; факторы; оценки; должностей', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ключевые; факторы; оценки; должностей',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальные; диспропорции; экономического; пространства', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; диспропорции; экономического; пространства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'зависимость; между; инфляцией; и', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'зависимость; между; инфляцией; и',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'снижение; реальной; заработной; платы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'падение; цен; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падение; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'значения; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'значения; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кривая; предельного; продукта; труда', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; предельного; продукта; труда',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'эластичность; спроса; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность; спроса; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'ставка; реальной; заработной; платы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'депозитам', 
                          title = '#### При этом вероятность дефолта каждого отдельного банка оказывает влияние на агрегированный показатель вероятности дефолта в банковской системе и на процентные ставки по ____________ (**депозит**) и кредитам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'депозитам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'ожидаемая; реальная; процентная; ставка', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'инвестиционный; проект; по', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционный; проект; по',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'средняя; цена; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'средняя; цена; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'влияние; волатильности; инфляции; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние; волатильности; инфляции; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'государственная; поддержка; нефтегазохимических; кластеров', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственная; поддержка; нефтегазохимических; кластеров',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'отрицательный; наклон; кривой; совокупного; спроса', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отрицательный; наклон; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'балансовый; канал; денежно-кредитной; политики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'балансовый; канал; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'мировая; реальная; процентная; ставка', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'ставка; реальной; заработной; платы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальные; денежные; доходы; населения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; денежные; доходы; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'снижение; цен; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кривая; долгосрочного; совокупного; предложения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; долгосрочного; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'уровень; реальной; заработной; платы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'новая; модель; экономического; роста', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новая; модель; экономического; роста',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'повышение; цен; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышение; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'процентная; ставка,; обеспечивающая; равновесие', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная; ставка,; обеспечивающая; равновесие',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'темпы; роста; реального; ввп', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпы; роста; реального; ввп',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'сдвиг; кривой; совокупного; спроса; вправо/влево', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг; кривой; совокупного; спроса; вправо/влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'исполнительные; органы; государственной; власти', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'исполнительные; органы; государственной; власти',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'сдвиг; кривой; совокупного; предложения; вправо', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг; кривой; совокупного; предложения; вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; скорости; роста; денежной; массы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; скорости; роста; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; объемов; государственных; закупок', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; объемов; государственных; закупок',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; темпа; роста; денежной; массы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; темпа; роста; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; реальной; денежной; массы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кредитам', 
                          title = '#### Банки в силу ограничений по достаточности капитала вынуждены повышать процентные ставки по ____________ (**кредит**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кредитам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'теория; реального; экономического; цикла', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теория; реального; экономического; цикла',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'цена; равна; предельным; издержкам', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена; равна; предельным; издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'валютный; канал; денежной; трансмиссии', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'валютный; канал; денежной; трансмиссии',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'принцип; убывающей; предельной; производительности', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'принцип; убывающей; предельной; производительности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'сдвиг; кривой; совокупного; предложения; влево', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг; кривой; совокупного; предложения; влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальные; денежные; доходы; населения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; денежные; доходы; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'доходность; рынка; ценных; бумаг', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доходность; рынка; ценных; бумаг',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'сдвигает; кривую; совокупного; спроса', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвигает; кривую; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'ценой', 
                          title = '#### Если инвестор продает облигацию, не дожидаясь погашения, то величина Р представляет собой разницу между ____________ (**цена**) продажи и ценой приобретения облигации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценой',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реализации; стратегии; социально-экономического; развития', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реализации; стратегии; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'в; виде; заработной; платы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; виде; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'значения; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'значения; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'модель; малой; открытой; экономики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'модель; малой; открытой; экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'эффекты; единой; денежно-кредитной; политики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффекты; единой; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'точка; пересечения; кривых; спроса', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'точка; пересечения; кривых; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'годовым "потолком', 
                          title = '#### Маржа представляет собой разницу между ____________ ____________ (**годовой, ", потолок**)" MFF и годовым бюджетом ЕС.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'годовым "потолком',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'выбор; между; инфляцией; и', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выбор; между; инфляцией; и',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'построение; модели; совокупных; расходов', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'построение; модели; совокупных; расходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'закон; убывающей; предельной; полезности', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закон; убывающей; предельной; полезности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'работы; классиков; экономической; теории', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'работы; классиков; экономической; теории',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рассчитывается; как; разница; между', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рассчитывается; как; разница; между',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; номинальной; денежной; массы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; номинальной; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кривая; совокупного; спроса; смещается; вправо/влево', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; спроса; смещается; вправо/влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'государственному долгу', 
                          title = '#### Высокие процентные ставки увеличивают процентные выплаты по ____________ ____________ (**государственный, долг**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственному долгу',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'в; среднем; на; душу; населения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; среднем; на; душу; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'шок; цен; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'шок; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'выпуск; товаров; для; внутреннего; потребления', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выпуск; товаров; для; внутреннего; потребления',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'теория; реального; экономического; цикла', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теория; реального; экономического; цикла',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кредитам', 
                          title = '#### Реальная процентная ставка, которую мы используем, – процентная ставка по ____________ (**кредит**), скорректированная на инфляцию, измеряемую дефлятором ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кредитам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'доход; равен; предельным; издержкам', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доход; равен; предельным; издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Какое влияние окажет изменение совокупного предложения на ____________ ____________ (**уровень, цена**) и реальный объем производства?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'финансирование; дефицита; государственного; бюджета', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансирование; дефицита; государственного; бюджета',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'максимальной ценой', 
                          title = '#### Мы определили излишек потребителя как разницу между ____________ ____________ (**максимальный, цена**), которую человек готов заплатить за товар, и рыночной ценой этого товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'максимальной ценой',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'измерение; уровня; экономического; развития', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'измерение; уровня; экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'высокий; уровень; экономического; развития', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокий; уровень; экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальная; процентная; ставка; равна', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная; процентная; ставка; равна',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кредит', 
                          title = '#### Информационная функция дает участникам рынка через постоянно меняющиеся цены и процентные ставки на ____________ (**кредит**) объективную информацию о спросе и предложении товаров и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кредит',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'пространственная; связность; экономической; активности; с', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пространственная; связность; экономической; активности; с',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'долгосрочная; кривая; совокупного; предложения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'долгосрочная; кривая; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'динамика; цен; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'динамика; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'новая; модель; государственного; управления', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новая; модель; государственного; управления',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'предельный; доход; равен; предельным; издержкам', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; доход; равен; предельным; издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'эффект; переноса; ключевой; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффект; переноса; ключевой; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Процентная ставка, выплачиваемая государством, обычно служит ориентиром для остальных процентных ставок в ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; реальной; денежной; массы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'депозитов', 
                          title = '#### Снижающиеся ставки сокращают процентный доход от ____________ (**депозит**), что ухудшает положение богатых домохозяйств, так как большая доля их доходов зависит от сбережений на депозитах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'депозитов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кривая; совокупного; предложения; сдвигается; вправо', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; предложения; сдвигается; вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'среднедушевые; денежные; доходы; населения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'среднедушевые; денежные; доходы; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'предельный; продукт; труда; равен', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; продукт; труда; равен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'краткосрочная; кривая; совокупного; предложения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'краткосрочная; кривая; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'трансмиссионный; механизм; денежно-кредитной; политики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'трансмиссионный; механизм; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'в; среднем; за; год', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; среднем; за; год',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'высокие; темпы; экономического; роста', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокие; темпы; экономического; роста',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'мировая; реальная; процентная; ставка', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'уравнение; кривой; совокупного; спроса', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уравнение; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'предельная; норма; технического; замещения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная; норма; технического; замещения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'увеличение; реальной; процентной; ставки', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'полномочия; органов; государственной; власти', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'полномочия; органов; государственной; власти',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'стоимостью', 
                          title = '#### Одной из существенных проблем развития банковского сектора является разница между ____________ (**стоимость**) заемных ресурсов и процентной ставкой по вкладам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стоимостью',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'федеральная; служба; государственной; статистики', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'федеральная; служба; государственной; статистики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кривая; совокупного; спроса; сдвигается; вправо/влево', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; спроса; сдвигается; вправо/влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальная; ставка; процента; равна', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная; ставка; процента; равна',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'факторы; вызывающие; сдвиг; кривой', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; вызывающие; сдвиг; кривой',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'рост; реальной; заработной; платы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'альтернативное; приобретение; товаров; для; перепродажи', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'альтернативное; приобретение; товаров; для; перепродажи',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'отрезок; кривой; совокупного; предложения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отрезок; кривой; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'эластичный; спрос; по; доходу', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичный; спрос; по; доходу',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'в; среднем; по; стране', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; среднем; по; стране',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'темпы; прироста; реального; ввп', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпы; прироста; реального; ввп',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'кривая; краткосрочного; совокупного; предложения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; краткосрочного; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'уровень; цен; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'внутренние; цены; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутренние; цены; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'финансовые; обязательства; перед', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые; обязательства; перед',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'экономическая; оценка; эффективности; инвестиций', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономическая; оценка; эффективности; инвестиций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'взаимные; фонды; денежного; рынка', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'взаимные; фонды; денежного; рынка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'концепции; долгосрочного; социально-экономического; развития', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'концепции; долгосрочного; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'предельный; продукт; капитала; равен', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; продукт; капитала; равен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'прогнозирование; чистой; процентной; маржи', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'прогнозирование; чистой; процентной; маржи',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'ставка; процента; равна; нулю', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка; процента; равна; нулю',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'падение; мировых; цен; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падение; мировых; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'реальные; располагаемые; денежные; доходы', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; располагаемые; денежные; доходы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'развитие; мировых; финансовых; институтов', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитие; мировых; финансовых; институтов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```


```{r}
checkdown::check_question(answer = 'факторы; влияющие; на', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; влияющие; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

