
```{r}
checkdown::check_question(answer = stringr::str_split('при любом уровне ВВП выше; равновесного реальный объем производства будет; превышать совокупные расходы, что приведет; к незапланированным инвестициям в товарные запасы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при любом уровне ВВП выше; равновесного реальный объем производства будет; превышать совокупные расходы, что приведет; к незапланированным инвестициям в товарные запасы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('снижение темпов; роста цен; отнюдь не; означает увеличение реальных доходов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение темпов; роста цен; отнюдь не; означает увеличение реальных доходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('минимум на; этой кривой; наблюдается при; уровне производства Q0', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'минимум на; этой кривой; наблюдается при; уровне производства Q0',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('уменьшение предложения ресурсов; приведет к росту; цен на них; и смещению кривой совокупного предложения влево', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уменьшение предложения ресурсов; приведет к росту; цен на них; и смещению кривой совокупного предложения влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('функциональная зависимость между величиной; заработной платы и объемом; спроса на труд выражается; в кривой спроса на труд', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функциональная зависимость между величиной; заработной платы и объемом; спроса на труд выражается; в кривой спроса на труд',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('на рисунке; представлена кривая,; отражающая уровень; цен и рост реального объема производства', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на рисунке; представлена кривая,; отражающая уровень; цен и рост реального объема производства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('все показатели оборачиваемости; используются для определения; скорости движения денежных; средств по различным текущим счетам предприятия', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'все показатели оборачиваемости; используются для определения; скорости движения денежных; средств по различным текущим счетам предприятия',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('это подразумевает снижение уровня бедности, ускоренное формирование; среднего класса, переключение акцента в инвестициях в; пользу человеческого капитала, рост реальных доходов населения; и на этой основе увеличение степеней свободы экономического поведения резидентов края', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'это подразумевает снижение уровня бедности, ускоренное формирование; среднего класса, переключение акцента в инвестициях в; пользу человеческого капитала, рост реальных доходов населения; и на этой основе увеличение степеней свободы экономического поведения резидентов края',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('как мы показали, долгосрочная; нейтральность денег подразумевает, что; сокращение номинальной денежной массы; на 10% снизит внутренний уровень цен на 10%', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'как мы показали, долгосрочная; нейтральность денег подразумевает, что; сокращение номинальной денежной массы; на 10% снизит внутренний уровень цен на 10%',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая совокупного; предложения увязывает; величину предлагаемого; совокупного объема производства с уровнем цен', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая совокупного; предложения увязывает; величину предлагаемого; совокупного объема производства с уровнем цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('если темп роста номинальной; денежной массы превышает инфляцию,; то темп роста реальной; денежной массы положительный и темп роста ВВП также', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'если темп роста номинальной; денежной массы превышает инфляцию,; то темп роста реальной; денежной массы положительный и темп роста ВВП также',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('чтобы найти размер вклада; работника в общий доход; фирмы, мы должны перевести; предельный продукт труда в стоимость предельного продукта', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'чтобы найти размер вклада; работника в общий доход; фирмы, мы должны перевести; предельный продукт труда в стоимость предельного продукта',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при этой более высокой заработной плате фирмы захотят; нанять меньше работников и сократят величину спроса на; труд до LD2 (точка В), а домохозяйства захотят; предложить больше труда, и величина предложения труда возрастет до L2S (точка С)', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при этой более высокой заработной плате фирмы захотят; нанять меньше работников и сократят величину спроса на; труд до LD2 (точка В), а домохозяйства захотят; предложить больше труда, и величина предложения труда возрастет до L2S (точка С)',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('конкуренция на внутренних рынках включает в; себя: 1) конкуренцию регионов за привлечение; компаний по переработке углеводородов; 2) конкуренцию; компаний за использование ресурсов и за позиции на внутреннем рынке', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конкуренция на внутренних рынках включает в; себя: 1) конкуренцию регионов за привлечение; компаний по переработке углеводородов; 2) конкуренцию; компаний за использование ресурсов и за позиции на внутреннем рынке',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при; росте; уровня; цен фактический объем выпуска снижается', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при; росте; уровня; цен фактический объем выпуска снижается',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в качестве повышения объективизации оценки; структуры экономического развития монопрофильных территорий; проведено сопоставление уровня занятости на; крупных и средних предприятиях с показателями развития малого бизнеса', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в качестве повышения объективизации оценки; структуры экономического развития монопрофильных территорий; проведено сопоставление уровня занятости на; крупных и средних предприятиях с показателями развития малого бизнеса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('домохозяйства получают; трудовой доход; и процентный; доход в виде дивидендов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'домохозяйства получают; трудовой доход; и процентный; доход в виде дивидендов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при любом ожидаемом уровне инфляции; рост реальной процентной ставки приводит; к росту номинальной процентной ставки; и вызывает снижение величины спроса на деньги', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при любом ожидаемом уровне инфляции; рост реальной процентной ставки приводит; к росту номинальной процентной ставки; и вызывает снижение величины спроса на деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('с более высоким уровнем применения инструментов МПП (Чили и; Колумбия) чувствительность динамики темпов общего и валютного кредитования к; шокам цен на сырьевые товары ниже, что также свидетельствует; в пользу более активного внедрения МПП в ресурсных странах с формирующимися рынками', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'с более высоким уровнем применения инструментов МПП (Чили и; Колумбия) чувствительность динамики темпов общего и валютного кредитования к; шокам цен на сырьевые товары ниже, что также свидетельствует; в пользу более активного внедрения МПП в ресурсных странах с формирующимися рынками',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('волатильность; реагирует; на; изменение цен на нефть', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'волатильность; реагирует; на; изменение цен на нефть',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сильный экономический спад последовал; за решением председателя ФРС; Волкера сократить темп прироста; денежной массы в 1979 г', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сильный экономический спад последовал; за решением председателя ФРС; Волкера сократить темп прироста; денежной массы в 1979 г',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('генерируемые потоки наличных; денежных средств в; сфере услуг пассажирских; автотранспортных перевозок сложно отследить', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'генерируемые потоки наличных; денежных средств в; сфере услуг пассажирских; автотранспортных перевозок сложно отследить',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост номинального; спроса на; объем производства; вызывает увеличение уровня цен', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост номинального; спроса на; объем производства; вызывает увеличение уровня цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('каршеринг-компании стараются выделиться более; удобным сервисом, более низкой; ценой, новыми моделями автомобилей; или бонусами для своих клиентов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'каршеринг-компании стараются выделиться более; удобным сервисом, более низкой; ценой, новыми моделями автомобилей; или бонусами для своих клиентов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('у каждого продавца объем предложения будет; меняться в зависимости от цены: чем; выше цена, тем, при прочих равных; условиях, выше размер предложения на рынке данного товара', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'у каждого продавца объем предложения будет; меняться в зависимости от цены: чем; выше цена, тем, при прочих равных; условиях, выше размер предложения на рынке данного товара',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая ABCD, называемая границей области; производственных возможностей, показывает максимально возможные; объемы производства предметов потребления и; средств производства при полном использовании всех имеющихся ресурсов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая ABCD, называемая границей области; производственных возможностей, показывает максимально возможные; объемы производства предметов потребления и; средств производства при полном использовании всех имеющихся ресурсов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('пакет компенсации за труд, предлагаемый монопсонистом; и состоящий из заработной платы, средств; на охрану труда и прочих дополнительных; льгот, менее ценен, чем соответствующий пакет при конкуренции', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пакет компенсации за труд, предлагаемый монопсонистом; и состоящий из заработной платы, средств; на охрану труда и прочих дополнительных; льгот, менее ценен, чем соответствующий пакет при конкуренции',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('теория человеческого капитала описывает прямые и; косвенные вложения денежных средств в образование; и профессиональную подготовку работников, что приводит; в будущем к более высокой оплате труда', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теория человеческого капитала описывает прямые и; косвенные вложения денежных средств в образование; и профессиональную подготовку работников, что приводит; в будущем к более высокой оплате труда',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эффект замещения, субституции —; изменение структуры потребления в; результате изменения цены одного; из товаров, входящих в потребительский набор', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффект замещения, субституции —; изменение структуры потребления в; результате изменения цены одного; из товаров, входящих в потребительский набор',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('более пологой или более крутой; будет кривая LM, когда норма; резервирования зависит от реальной ставки; процента по сравнению со случаем, когда норма резервирования постоянна', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'более пологой или более крутой; будет кривая LM, когда норма; резервирования зависит от реальной ставки; процента по сравнению со случаем, когда норма резервирования постоянна',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предприятие зависит; от поставок; изделий, необходимых; для производства продукции', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предприятие зависит; от поставок; изделий, необходимых; для производства продукции',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эластичность рыночного спроса при; таком выпуске равна единице,; а общая выручка достигает; максимума, что при нулевых затратах тождественно максимуму прибыли', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность рыночного спроса при; таком выпуске равна единице,; а общая выручка достигает; максимума, что при нулевых затратах тождественно максимуму прибыли',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эффект дохода уменьшает; величину предложения труда,; когда рост ставки; реальной заработной платы делает работника богаче', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффект дохода уменьшает; величину предложения труда,; когда рост ставки; реальной заработной платы делает работника богаче',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('высокая инфляция стимулирует перевод накоплений в наличную валюту, что ведет; к повышению спроса на нее и, как следствие, к падению; курса рубля, а затем росту цен, вызывая асимметрию во взаимодействии; государственного и частного секторов экономики, поскольку заставляет каждого из них функционировать по разным правилам', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокая инфляция стимулирует перевод накоплений в наличную валюту, что ведет; к повышению спроса на нее и, как следствие, к падению; курса рубля, а затем росту цен, вызывая асимметрию во взаимодействии; государственного и частного секторов экономики, поскольку заставляет каждого из них функционировать по разным правилам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('прибыль; максимальна,; когда; предельный доход равняется предельным издержкам', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'прибыль; максимальна,; когда; предельный доход равняется предельным издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('наиболее существенное влияние диверсификация; занятости оказывает на реальные; доходы населения, которые росли; быстрее в регионах, где увеличивался уровень диверсификации', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'наиболее существенное влияние диверсификация; занятости оказывает на реальные; доходы населения, которые росли; быстрее в регионах, где увеличивался уровень диверсификации',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('китай выводит число международных; патентных заявок на рекордно; высокий уровень, растет спрос; на охрану товарных знаков и промышленных образцов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'китай выводит число международных; патентных заявок на рекордно; высокий уровень, растет спрос; на охрану товарных знаков и промышленных образцов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('состояние внешнеторговых связей; – один из; важнейших показателей развития; интеграционных процессов на территории Евразийского экономического союза', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'состояние внешнеторговых связей; – один из; важнейших показателей развития; интеграционных процессов на территории Евразийского экономического союза',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('монетарная теория считает; одним из основных; средств регулирования экономики; изменение денежной массы и процентных ставок', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'монетарная теория считает; одним из основных; средств регулирования экономики; изменение денежной массы и процентных ставок',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('национальный доход (national income); — в США это; доход, который создается в; производстве товаров и услуг резидентами США', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальный доход (national income); — в США это; доход, который создается в; производстве товаров и услуг резидентами США',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('для анализа; поведения рыночных; цен можно; использовать кривые рыночного спроса и предложения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'для анализа; поведения рыночных; цен можно; использовать кривые рыночного спроса и предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('хотя в долгосрочном периоде связи между; инфляцией и безработицей нет, в краткосрочном; периоде существует проблема выбора между инфляцией; и безработицей, которая наглядно отражается кривой Филлипса', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'хотя в долгосрочном периоде связи между; инфляцией и безработицей нет, в краткосрочном; периоде существует проблема выбора между инфляцией; и безработицей, которая наглядно отражается кривой Филлипса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('изменения положения кривых; спроса и предложения; являются причиной наблюдаемых; сезонных изменений равновесных цен и количества товара', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменения положения кривых; спроса и предложения; являются причиной наблюдаемых; сезонных изменений равновесных цен и количества товара',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('допустим, что ожидаемая; инфляция равна нулю,; поэтому спрос на; деньги зависит только от реальной ставки процента', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'допустим, что ожидаемая; инфляция равна нулю,; поэтому спрос на; деньги зависит только от реальной ставки процента',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('никакое повышение уровня цен; на этом вертикальном отрезке; кривой совокупного предложения не; приведет к увеличению реального объема производства', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'никакое повышение уровня цен; на этом вертикальном отрезке; кривой совокупного предложения не; приведет к увеличению реального объема производства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эмпирические работы показывают, что спрос; на деньги, а следовательно, и; скорость обрашения действительно систематически реагируют; на изменения ставок процента и уровня реального дохода', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эмпирические работы показывают, что спрос; на деньги, а следовательно, и; скорость обрашения действительно систематически реагируют; на изменения ставок процента и уровня реального дохода',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('промежуточное потребление; – стоимость; товаров и; услуг, израсходованных в процессе производства', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промежуточное потребление; – стоимость; товаров и; услуг, израсходованных в процессе производства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('прогрессивный ход; развития экономики; зависит от; внутренних и внешних факторов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'прогрессивный ход; развития экономики; зависит от; внутренних и внешних факторов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('общий; уровень; цен; остается неизменным', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'общий; уровень; цен; остается неизменным',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кейнсианцы согласны, что жесткость цен; на рынке совершенной конкуренции не; возникнет, но указывают, что совершенная; конкуренция существует в относительно небольшой части экономики', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кейнсианцы согласны, что жесткость цен; на рынке совершенной конкуренции не; возникнет, но указывают, что совершенная; конкуренция существует в относительно небольшой части экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('однако прямое государственное вмешательство; в международные операции порождает; множество экономических издержек, включая; снижение доступа к иностранным товарам и кредитам', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'однако прямое государственное вмешательство; в международные операции порождает; множество экономических издержек, включая; снижение доступа к иностранным товарам и кредитам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('согласно выдвинутому им тезису,; темпы инфляции, вызываемой ростом; заработной платы, находятся в; тесной взаимосвязи с уровнем безработицы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'согласно выдвинутому им тезису,; темпы инфляции, вызываемой ростом; заработной платы, находятся в; тесной взаимосвязи с уровнем безработицы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в точке Е” и номинальная денежная масса,; и уровень цен изменились в одной и; той же пропорции, оставив реальную денежную массу; и, следовательно, ставку процента и совокупный спрос неизменными', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в точке Е” и номинальная денежная масса,; и уровень цен изменились в одной и; той же пропорции, оставив реальную денежную массу; и, следовательно, ставку процента и совокупный спрос неизменными',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при прочих равных условиях такие; изменения способны привести к росту; цены облигаций правительства, одновременно снижая; дисконтные процентные ставки по этим бумагам', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при прочих равных условиях такие; изменения способны привести к росту; цены облигаций правительства, одновременно снижая; дисконтные процентные ставки по этим бумагам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('более того, проекты этих законов разрабатываются разными; ведомствами, они слабо увязаны друг с другом; в идейном и концептуальном планах, хотя и; направлены на совершенствование государственного регулирования территориального развития страны', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'более того, проекты этих законов разрабатываются разными; ведомствами, они слабо увязаны друг с другом; в идейном и концептуальном планах, хотя и; направлены на совершенствование государственного регулирования территориального развития страны',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('может ли экономическая; открытость положительно влиять; на региональное развитие; и снижение уровня бедности', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'может ли экономическая; открытость положительно влиять; на региональное развитие; и снижение уровня бедности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('повсеместно; произошло; падение; реальных доходов населения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повсеместно; произошло; падение; реальных доходов населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эти уравнения показывают, что и в; дефляторе ВНП и в индексе потребительских; цен сравнивается текущая цена определенного набора; товаров с ценой того же набора в базисном году', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эти уравнения показывают, что и в; дефляторе ВНП и в индексе потребительских; цен сравнивается текущая цена определенного набора; товаров с ценой того же набора в базисном году',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('перспективы стратегического развития; региона предопределяются величиной; и эффективностью использования; его социально-экономического потенциала, а также внешними факторами', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'перспективы стратегического развития; региона предопределяются величиной; и эффективностью использования; его социально-экономического потенциала, а также внешними факторами',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельный продукт фактора в; денежном выражении показывает прирост; общего дохода в результате; использования Еще одной (дополнительной) единицы переменного фактора L', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт фактора в; денежном выражении показывает прирост; общего дохода в результате; использования Еще одной (дополнительной) единицы переменного фактора L',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('произошла трансформации; роли валютного; канала денежной; трансмиссии в новейшей истории России', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'произошла трансформации; роли валютного; канала денежной; трансмиссии в новейшей истории России',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('наемные работники могут быть осведомлены о; размере текущей заработной платы, но не; об общем уровне цен в стране,; что затрудняет определение уровня реальной заработной платы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'наемные работники могут быть осведомлены о; размере текущей заработной платы, но не; об общем уровне цен в стране,; что затрудняет определение уровня реальной заработной платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('если государственные расходы не; изменяются, то снижение налогов; должно в конце концов; быть компенсировано ростом налогов в будущем', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'если государственные расходы не; изменяются, то снижение налогов; должно в конце концов; быть компенсировано ростом налогов в будущем',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в этом случае; уравнение показывает, что; люди будут ожидать; роста уровня инфляции в будущем', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в этом случае; уравнение показывает, что; люди будут ожидать; роста уровня инфляции в будущем',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('так же как растет количество труда, предлагаемого; индивидуумами при увеличении их ставки реальной заработной; платы, совокупное предложение труда растет при увеличении; ставки реальной заработной платы в целом по экономике', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'так же как растет количество труда, предлагаемого; индивидуумами при увеличении их ставки реальной заработной; платы, совокупное предложение труда растет при увеличении; ставки реальной заработной платы в целом по экономике',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('экономика; находится; на; кривой производственных возможностей', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономика; находится; на; кривой производственных возможностей',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при низкой безработице ФРС рассматривала высокие; темпы инфляции в качестве главной проблемы,; стоящей перед экономикой, и приняла решение; ограничить инфляцию за счет сокращения совокупного спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при низкой безработице ФРС рассматривала высокие; темпы инфляции в качестве главной проблемы,; стоящей перед экономикой, и приняла решение; ограничить инфляцию за счет сокращения совокупного спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('а как; влияет увеличение; реальной процентной; ставкина национальные сбережения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'а как; влияет увеличение; реальной процентной; ставкина национальные сбережения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('первоначально более; высокий рост; номинальной денежной; массы ведет к росту ВВП', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'первоначально более; высокий рост; номинальной денежной; массы ведет к росту ВВП',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('вспомним соотношение между; номинальной и реальной; ставками процента: i; = r + π e', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'вспомним соотношение между; номинальной и реальной; ставками процента: i; = r + π e',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при предположении, что функция спроса носит; линейный характер, уравнение кривой спроса может; быть представлено в следующем общем виде:; Q D = a- b . Р', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при предположении, что функция спроса носит; линейный характер, уравнение кривой спроса может; быть представлено в следующем общем виде:; Q D = a- b . Р',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предлагаемые ориентиры по уровню инфляции; впервые скорректированы с учетом негативного; влияния волатильности инфляции и различаются; для стран с разным уровнем государственного участия в экономике', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предлагаемые ориентиры по уровню инфляции; впервые скорректированы с учетом негативного; влияния волатильности инфляции и различаются; для стран с разным уровнем государственного участия в экономике',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в чем проявляется; различие между арбитражерами,; хеджерами и спекулянтами,; действующими на валютном рынке', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в чем проявляется; различие между арбитражерами,; хеджерами и спекулянтами,; действующими на валютном рынке',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в долгосрочной перспективе устойчивое изменение темпов; роста денежной массы ведет к изменению; роста инфляции и номинальной процентной ставки; в том же направлении и на ту же величину', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в долгосрочной перспективе устойчивое изменение темпов; роста денежной массы ведет к изменению; роста инфляции и номинальной процентной ставки; в том же направлении и на ту же величину',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('итак, цена фактора; производства — труда,; земли или капитала; — равна стоимости предельного продукта этого фактора', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'итак, цена фактора; производства — труда,; земли или капитала; — равна стоимости предельного продукта этого фактора',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в итоге мы; получаем оценки равновесной; процентной ставки для; России в рамках основных существующих подходов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в итоге мы; получаем оценки равновесной; процентной ставки для; России в рамках основных существующих подходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('однако субъекты экономики ожидают высоких; темпов инфляции как раз потому,; что текущая и перспективная денежно-кредитная; и финансово-бюджетная политика правительства подтверждает их оценки', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'однако субъекты экономики ожидают высоких; темпов инфляции как раз потому,; что текущая и перспективная денежно-кредитная; и финансово-бюджетная политика правительства подтверждает их оценки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('особенно интересные возможности обещает теория эффективной; заработной платы, которая утверждает, что многие; фирмы могут платить заработную плату выше; равновесного уровня, чтобы добиться лояльности со стороны рабочей силы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'особенно интересные возможности обещает теория эффективной; заработной платы, которая утверждает, что многие; фирмы могут платить заработную плату выше; равновесного уровня, чтобы добиться лояльности со стороны рабочей силы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при очень низком; значении процентной ставки; весь прирост предложения; денег поглощается спекулятивным спросом на деньги', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при очень низком; значении процентной ставки; весь прирост предложения; денег поглощается спекулятивным спросом на деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('часто искать подрядчиков для аутсорсинга транснациональные корпорации; стремятся не в развитых странах, а в; развивающихся, где имеются хорошо подготовленные специалисты, готовые; с большой отдачей работать за невысокую заработную плату', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'часто искать подрядчиков для аутсорсинга транснациональные корпорации; стремятся не в развитых странах, а в; развивающихся, где имеются хорошо подготовленные специалисты, готовые; с большой отдачей работать за невысокую заработную плату',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в период войн; и других кризисов; правительства часто вводят; контроль над ценами на жизненно важные товары', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в период войн; и других кризисов; правительства часто вводят; контроль над ценами на жизненно важные товары',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('достижение целевого уровня; темпа роста денежной; массы считается наиболее; важной задачей центрального банка', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'достижение целевого уровня; темпа роста денежной; массы считается наиболее; важной задачей центрального банка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при увеличении объема; производства увеличивается объем; трансакций людей, что; приводит к увеличению спроса на деньги', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при увеличении объема; производства увеличивается объем; трансакций людей, что; приводит к увеличению спроса на деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('придется увеличить объем; производства, что показано; горизонтальными стрелками, направленными; вправо от уровня производства в 250 единиц', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'придется увеличить объем; производства, что показано; горизонтальными стрелками, направленными; вправо от уровня производства в 250 единиц',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('по мере развития страхового рынка в первую; очередь достигается точка оптимума по темпам роста; экономики (Y1), затем по волатильности темпов роста; ВВП (Y2) и, наконец, по показателю системных банковских кризисов (Y4)', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по мере развития страхового рынка в первую; очередь достигается точка оптимума по темпам роста; экономики (Y1), затем по волатильности темпов роста; ВВП (Y2) и, наконец, по показателю системных банковских кризисов (Y4)',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('необходимо выполнить задачу; по созданию «цифровой; экономики» и условий; для развития «виртуального бизнеса»', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'необходимо выполнить задачу; по созданию «цифровой; экономики» и условий; для развития «виртуального бизнеса»',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('так как количество товаров и; услуг, на которое предъявляется спрос; при каждом данном уровне цен,; увеличивает­ся, кривая совокупного спроса сдвигается вправо', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'так как количество товаров и; услуг, на которое предъявляется спрос; при каждом данном уровне цен,; увеличивает­ся, кривая совокупного спроса сдвигается вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('некоторые источники утверждают, что налоговые льготы способствуют; уязвимости экономики, так как снижение налоговой нагрузки; для бизнеса может вызвать значительный рост государственных; заимствований для обслуживания текущих обязательств в ближайшие годы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'некоторые источники утверждают, что налоговые льготы способствуют; уязвимости экономики, так как снижение налоговой нагрузки; для бизнеса может вызвать значительный рост государственных; заимствований для обслуживания текущих обязательств в ближайшие годы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сдвиг кривой LM вызывается изменением; уровня цен, что приводит к; изменению величины реального предложения денег; и поэтому воздействует на равновесие на рынке активов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг кривой LM вызывается изменением; уровня цен, что приводит к; изменению величины реального предложения денег; и поэтому воздействует на равновесие на рынке активов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('здесь содержится очень важное; соотношение: издержки сокращения темпа; инфляции на 1% за; любой отрезок времени составят 1/4 единиц ВНП', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'здесь содержится очень важное; соотношение: издержки сокращения темпа; инфляции на 1% за; любой отрезок времени составят 1/4 единиц ВНП',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('изменение денежной массы в; краткосрочном периоде повлияет на; реальные переменные, например выпуск,; Еще до того, как цены получат шанс приспособиться', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение денежной массы в; краткосрочном периоде повлияет на; реальные переменные, например выпуск,; Еще до того, как цены получат шанс приспособиться',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('далее рассмотрим элементы; институциональных соглашений на; внутреннем рынке ТБД,; обеспечившие достижение высокого уровня качества', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'далее рассмотрим элементы; институциональных соглашений на; внутреннем рынке ТБД,; обеспечившие достижение высокого уровня качества',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('по своему номинальному; значению минимальная заработная; плата неуклонно росла; в течение последних 60 лет', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по своему номинальному; значению минимальная заработная; плата неуклонно росла; в течение последних 60 лет',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('основными показателями совокупного выпуска и; совокупного дохода являются: валовой внутренний; продукт (ВВП); валовой национальный продукт; (ВНП); чистый внутренний продукт (ЧВП); чистый национальный продукт (ЧНП)', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'основными показателями совокупного выпуска и; совокупного дохода являются: валовой внутренний; продукт (ВВП); валовой национальный продукт; (ВНП); чистый внутренний продукт (ЧВП); чистый национальный продукт (ЧНП)',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('альтернативным способом выражения равновесия на товарном; рынке является следующее условие: величина предложения; товаров должна быть равна величине спроса; на товары домашних хозяйств, фирм и государства', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'альтернативным способом выражения равновесия на товарном; рынке является следующее условие: величина предложения; товаров должна быть равна величине спроса; на товары домашних хозяйств, фирм и государства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('но что происходит в случае,; когда экономика США открыта для; торговли и мировая цена на; алюминий выше или ниже внутренней цены в долларах', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'но что происходит в случае,; когда экономика США открыта для; торговли и мировая цена на; алюминий выше или ниже внутренней цены в долларах',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('общие; и; предельные; издержки равны нулю', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'общие; и; предельные; издержки равны нулю',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в краткосрочной перспективе изменения; скорости роста денежной массы; воздействуют как на уровень; выпуска, так и на инфляцию', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в краткосрочной перспективе изменения; скорости роста денежной массы; воздействуют как на уровень; выпуска, так и на инфляцию',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('экономические интересы - это; та платформа, которая служит; основанием и главным стимулом; для создания и развития организаций', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономические интересы - это; та платформа, которая служит; основанием и главным стимулом; для создания и развития организаций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('дело в том, что; рынок факторов производства складывается; из трех видов рынка:; рынка труда, рынка земли, рынка капиталов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дело в том, что; рынок факторов производства складывается; из трех видов рынка:; рынка труда, рынка земли, рынка капиталов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('положение, что для каждого блага с эластичностью; спроса по доходу меньше 1(0 < EJD; < 1) должно существовать благо с EJD; > 1 для конкретного потребителя, называется законом Энгеля', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'положение, что для каждого блага с эластичностью; спроса по доходу меньше 1(0 < EJD; < 1) должно существовать благо с EJD; > 1 для конкретного потребителя, называется законом Энгеля',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('какое воздействие; оказывает политика; жесткой реальной; заработной платы на фактический объем производства', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'какое воздействие; оказывает политика; жесткой реальной; заработной платы на фактический объем производства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в задаче мы будем использовать данные; о кривой доходности, для того чтобы; оценить, действительно ли на фондовых рынках; ожидали, что Волкер сможет снизить темпы инфляции', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в задаче мы будем использовать данные; о кривой доходности, для того чтобы; оценить, действительно ли на фондовых рынках; ожидали, что Волкер сможет снизить темпы инфляции',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('вообще говоря, для любого; значения объема производства увеличение; реального предложения денег снижает; реальную процентную ставку, обеспечивающую равновесие на рынке', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'вообще говоря, для любого; значения объема производства увеличение; реального предложения денег снижает; реальную процентную ставку, обеспечивающую равновесие на рынке',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рассматривается также; гипотеза о; единой ставке; номинальной заработной платы в экономике', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рассматривается также; гипотеза о; единой ставке; номинальной заработной платы в экономике',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реклама часто влияет; на эластичность спроса; по цене, и; это нужно принимать в расчет', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реклама часто влияет; на эластичность спроса; по цене, и; это нужно принимать в расчет',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('другим примером; чистого эффекта; дохода является; увеличение ожидаемой будущей реальной заработной платы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'другим примером; чистого эффекта; дохода является; увеличение ожидаемой будущей реальной заработной платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('существует также мнение, что средний; получатель заработной платы склонен питать; некоторые иллюзии, когда одновременно возрастают; и номинальная заработная плата, и уровень цен', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'существует также мнение, что средний; получатель заработной платы склонен питать; некоторые иллюзии, когда одновременно возрастают; и номинальная заработная плата, и уровень цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ожидаемый; уровень; цен; приспосабливается к фактическому уровню цен', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемый; уровень; цен; приспосабливается к фактическому уровню цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('общественные; экономические; ресурсы; используются для производства продукции монополии', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'общественные; экономические; ресурсы; используются для производства продукции монополии',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('поиск порогового уровня инфляции, превышение; которого ведет к ее отрицательному; влиянию на рост, является традиционным; для исследования воздействия инфляции на долгосрочную динамику выпуска', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'поиск порогового уровня инфляции, превышение; которого ведет к ее отрицательному; влиянию на рост, является традиционным; для исследования воздействия инфляции на долгосрочную динамику выпуска',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в соответствии с работами, посвященными оценке; воздействия изменчивости инфляции на реальный сектор; экономики, предельный негативный эффект волатильности инфляции; может увеличиваться по мере роста ее уровня', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в соответствии с работами, посвященными оценке; воздействия изменчивости инфляции на реальный сектор; экономики, предельный негативный эффект волатильности инфляции; может увеличиваться по мере роста ее уровня',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('подразумевается, что налоговые льготы в; России, например, перенос убытков на; будущие налоговые льготы, применяются в; результате модернизации производства, приобретения нового высокотехнологичного оборудования', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'подразумевается, что налоговые льготы в; России, например, перенос убытков на; будущие налоговые льготы, применяются в; результате модернизации производства, приобретения нового высокотехнологичного оборудования',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('процент изменения; величины спроса; больше процента; изменения цены товара', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процент изменения; величины спроса; больше процента; изменения цены товара',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('к положительным сдвигам можно отнести более высокие; по сравнению с прожиточным минимумом темпы прироста; среднедушевых денежных доходов населения, что в условиях; низкого уровня инфляции должно обеспечить рост реальных денежных доходов населения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'к положительным сдвигам можно отнести более высокие; по сравнению с прожиточным минимумом темпы прироста; среднедушевых денежных доходов населения, что в условиях; низкого уровня инфляции должно обеспечить рост реальных денежных доходов населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('при данном; обменном курсе; импортные пошлины; снижают внутренний спрос на импорт', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при данном; обменном курсе; импортные пошлины; снижают внутренний спрос на импорт',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('регулирование; потоков; денежных; средств составляет основу макроэкономической политики', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'регулирование; потоков; денежных; средств составляет основу макроэкономической политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('поскольку MRTS LK — это наклон изокванты фирмы, то; конкурентное равновесие на рынке факторов может возникнуть только в; том случае, если каждый производитель использует труд и капитал; так, что наклоны изоквант равны друг другу и отношению цен двух факторов производства', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'поскольку MRTS LK — это наклон изокванты фирмы, то; конкурентное равновесие на рынке факторов может возникнуть только в; том случае, если каждый производитель использует труд и капитал; так, что наклоны изоквант равны друг другу и отношению цен двух факторов производства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('уравнение показывает, что предельный продукт; труда есть разница в объемах; производства при использовании L +1; и при использовании L единиц труда', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уравнение показывает, что предельный продукт; труда есть разница в объемах; производства при использовании L +1; и при использовании L единиц труда',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('исходным понятием для законодательства; о финансовых рынках становится; национальное и транснациональное движение; денежных средств от инвестора к реципиенту инвестиций', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'исходным понятием для законодательства; о финансовых рынках становится; национальное и транснациональное движение; денежных средств от инвестора к реципиенту инвестиций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост денежной массы; вызывает рост инфляции,; а последняя приводит; к увеличению ставки процента', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост денежной массы; вызывает рост инфляции,; а последняя приводит; к увеличению ставки процента',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('налоговая система Японии; поощряет сбережения, предусматривая; невысокие ставки налога; на доходы от капитала', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговая система Японии; поощряет сбережения, предусматривая; невысокие ставки налога; на доходы от капитала',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в соответствии с эффектом Фишера,; если номинальная ставка процента составляет; 7%, а темп инфляции равен; 5%, то реальная ставка процента равна 12%', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в соответствии с эффектом Фишера,; если номинальная ставка процента составляет; 7%, а темп инфляции равен; 5%, то реальная ставка процента равна 12%',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('как; эти; квоты; подействовали на мировой рынок', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'как; эти; квоты; подействовали на мировой рынок',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в мире; растет спрос; на альтернативу; долгу, номинированному в долларах США', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в мире; растет спрос; на альтернативу; долгу, номинированному в долларах США',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кейнсианцы считали,; что экономику; можно стабилизировать; путем увеличения государственных расходов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кейнсианцы считали,; что экономику; можно стабилизировать; путем увеличения государственных расходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('пол Самуэльсон и Роберт Солоу опубликовали; в журнале статью «Анализ антиинфляционной политики»,; в которой они сообщали о наличии; аналогичной обратной зависимости между инфляцией и безработицей для экономики США', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пол Самуэльсон и Роберт Солоу опубликовали; в журнале статью «Анализ антиинфляционной политики»,; в которой они сообщали о наличии; аналогичной обратной зависимости между инфляцией и безработицей для экономики США',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('потребление некоторых товаров, например соли, почти; не зависит от изменения цены, а; потребление других, таких, как жилье, оказывается; в гораздо большей зависимости от ее изменения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребление некоторых товаров, например соли, почти; не зависит от изменения цены, а; потребление других, таких, как жилье, оказывается; в гораздо большей зависимости от ее изменения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('стабилизация ситуации в экономике; страны в целом и; сельском хозяйстве в частности; сопровождалась снижением объемов производства в хозяйствах населения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стабилизация ситуации в экономике; страны в целом и; сельском хозяйстве в частности; сопровождалась снижением объемов производства в хозяйствах населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('одной из причин, почему значительная часть накоплений России; в предыдущие 6—7 лет направлялась именно за границу,; является то, что не удалось в этот период,; несмотря на высокие доходы, существенно снизить уровень инфляции внутри страны', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'одной из причин, почему значительная часть накоплений России; в предыдущие 6—7 лет направлялась именно за границу,; является то, что не удалось в этот период,; несмотря на высокие доходы, существенно снизить уровень инфляции внутри страны',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в результате резких колебаний; на рынке криптовалют внутренние; цены в стране, использующей; такую валюту, могут быть очень нестабильными', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в результате резких колебаний; на рынке криптовалют внутренние; цены в стране, использующей; такую валюту, могут быть очень нестабильными',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предположим, что изначально; уровень инфляции в; экономике составляет 3%,; а естественный уровень безработицы равен 6%', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предположим, что изначально; уровень инфляции в; экономике составляет 3%,; а естественный уровень безработицы равен 6%',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('для оценки уровня жизни населения субъектов РФ, разработки; и реализации региональных социальных программ, планирования темпов роста; заработной платы, пенсий, социальных пособий, а также составления; бюджетов используют понятия минимального потребительского бюджета (МПБ) и бюджета прожиточного минимума', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'для оценки уровня жизни населения субъектов РФ, разработки; и реализации региональных социальных программ, планирования темпов роста; заработной платы, пенсий, социальных пособий, а также составления; бюджетов используют понятия минимального потребительского бюджета (МПБ) и бюджета прожиточного минимума',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('основной причиной пониженных душевых показателей; потребления на территории СФО стали,; по-видимому, пониженные темпы роста заработной; платы и денежных доходов в целом', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'основной причиной пониженных душевых показателей; потребления на территории СФО стали,; по-видимому, пониженные темпы роста заработной; платы и денежных доходов в целом',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('равновесие в долгосрочном; периоде достигается в; точке пересечения кривой; совокупного спроса с долгосрочной кривой совокупного предложения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесие в долгосрочном; периоде достигается в; точке пересечения кривой; совокупного спроса с долгосрочной кривой совокупного предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; стране; достаточно; сахара для удовлетворения спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; стране; достаточно; сахара для удовлетворения спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сложное положение нефтедобывающих компаний; характеризовалось одновременными шоками падения; мировых цен на энергоресурсы; и добровольными ограничениями в рамках сделки ОПЕК+', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сложное положение нефтедобывающих компаний; характеризовалось одновременными шоками падения; мировых цен на энергоресурсы; и добровольными ограничениями в рамках сделки ОПЕК+',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('скорость обращения денег определяется как; частное от деления номинального ВВП; (уровня цен Р, умноженного на; реальный объем производства Y) на номинальную денежную массу М', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'скорость обращения денег определяется как; частное от деления номинального ВВП; (уровня цен Р, умноженного на; реальный объем производства Y) на номинальную денежную массу М',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('нет оснований полагать, что; отказ от чистого инфляционного; таргетирования в пользу гибридного; препятствует достижению цели по инфляции', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'нет оснований полагать, что; отказ от чистого инфляционного; таргетирования в пользу гибридного; препятствует достижению цели по инфляции',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в соответствии с; эффектом Фишера реальная; ставка процента равна; номинальной ставке процента плюс темп инфляции', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в соответствии с; эффектом Фишера реальная; ставка процента равна; номинальной ставке процента плюс темп инфляции',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('пример показывает, сколько процентов; реального годового ВНП следует; принести в жертву ради; сокращения инфляции на один процентный пункт', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пример показывает, сколько процентов; реального годового ВНП следует; принести в жертву ради; сокращения инфляции на один процентный пункт',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост уровня цен меньше роста; номинальной денежной массы, реальное предложение; денег растет, понижая реальные процентные; ставки и увеличивая совокупное количество товаров', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост уровня цен меньше роста; номинальной денежной массы, реальное предложение; денег растет, понижая реальные процентные; ставки и увеличивая совокупное количество товаров',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('анализ краткосрочной кривой совокупного предложения; позволяет получить представление об объеме; предложения товаров и услуг в; краткосрочном периоде при каждом данном уровне цен', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'анализ краткосрочной кривой совокупного предложения; позволяет получить представление об объеме; предложения товаров и услуг в; краткосрочном периоде при каждом данном уровне цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('но если ВВП; не меняется, то; уменьшит реальную денежную; массу и сдвинет кривую LM вверх', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'но если ВВП; не меняется, то; уменьшит реальную денежную; массу и сдвинет кривую LM вверх',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('дефлятор ВНП и; индекс потребительских цен; дают различную информацию; об общем уровне цен в экономике', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дефлятор ВНП и; индекс потребительских цен; дают различную информацию; об общем уровне цен в экономике',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('даже для товара,; который составляет большую; долю бюджета, эффект; дохода от изменения цены иногда будет небольшим', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'даже для товара,; который составляет большую; долю бюджета, эффект; дохода от изменения цены иногда будет небольшим',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('выбор базисного года может; иметь важное значение при; расчете роста реального объема; производства, на который оказывает воздействие изменение уровня цен', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выбор базисного года может; иметь важное значение при; расчете роста реального объема; производства, на который оказывает воздействие изменение уровня цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('Если государственные расходы выросли на 100; единиц и величина мультипликатора равна 2,; то равновесный доход должен увеличиться на; 200 единиц при каждом уровне ставки процента', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'Если государственные расходы выросли на 100; единиц и величина мультипликатора равна 2,; то равновесный доход должен увеличиться на; 200 единиц при каждом уровне ставки процента',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('безработица, возникающая в результате поиска; работы, заметно отличается от той,; которая вызывается законами о минимальной; заработной плате, деятельностью профсоюзов и эффективной оплатой труда', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'безработица, возникающая в результате поиска; работы, заметно отличается от той,; которая вызывается законами о минимальной; заработной плате, деятельностью профсоюзов и эффективной оплатой труда',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('фирмами используется; стратегия продажи; товаров высокого; качества по высокой цене', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фирмами используется; стратегия продажи; товаров высокого; качества по высокой цене',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('объем дополнительных поступлений; зависит как от; цены на товар,; так и от предельного продукта труда', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем дополнительных поступлений; зависит как от; цены на товар,; так и от предельного продукта труда',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('фирмы, в свою очередь, направляя; полученные средства на рынок факторов; производства, производят оплату труда работников,; осуществляют арендные платежи, а также выплачивают прибыль своим владельцам', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фирмы, в свою очередь, направляя; полученные средства на рынок факторов; производства, производят оплату труда работников,; осуществляют арендные платежи, а также выплачивают прибыль своим владельцам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('аналогично кривой спроса на труд фирмы кривая; совокупного спроса на труд наклонена вниз, показывая,; что увеличение реальной заработной платы в экономике; снижает общее количество труда, которое хотят использовать фирмы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'аналогично кривой спроса на труд фирмы кривая; совокупного спроса на труд наклонена вниз, показывая,; что увеличение реальной заработной платы в экономике; снижает общее количество труда, которое хотят использовать фирмы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('следующим весьма распространенным видом; налоговых льгот в Казахстане; являются налоговые освобождения, которые; в основном распространяются на налог на прибыль', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'следующим весьма распространенным видом; налоговых льгот в Казахстане; являются налоговые освобождения, которые; в основном распространяются на налог на прибыль',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('комплементарные блага —; взаимодополняемые блага: увеличение; цены одного блага; ведет к падению спроса на другое благо', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'комплементарные блага —; взаимодополняемые блага: увеличение; цены одного блага; ведет к падению спроса на другое благо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост уровня цен в стране по; сравнению с мировым уровнем ведет к; увеличению импорта и снижению экспорта, следовательно,; к снижению совокупного спроса и сдвигу кривой совокупного спроса влево', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост уровня цен в стране по; сравнению с мировым уровнем ведет к; увеличению импорта и снижению экспорта, следовательно,; к снижению совокупного спроса и сдвигу кривой совокупного спроса влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('напротив, уменьшение основного капитала ведет к снижению производитель­ ности, сокращению; объема предлагаемых товаров и услуг и сдвигу долгосрочной кривой совокупного; предложения влево. Мы обсуждали, что долгосрочный экономический рост детерминируют множество; факторов, включая полити­ ку в отношении сбережений, инвестиций, образования, технологии, междуна­', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'напротив, уменьшение основного капитала ведет к снижению производитель­ ности, сокращению; объема предлагаемых товаров и услуг и сдвигу долгосрочной кривой совокупного; предложения влево. Мы обсуждали, что долгосрочный экономический рост детерминируют множество; факторов, включая полити­ ку в отношении сбережений, инвестиций, образования, технологии, междуна­',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая краткосрочного совокупного предло-; жения имеет положительный наклон,; поскольку предполагается, что при; изменении уровня цен номинальная зароботная плата остается постоянной', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая краткосрочного совокупного предло-; жения имеет положительный наклон,; поскольку предполагается, что при; изменении уровня цен номинальная зароботная плата остается постоянной',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('если уровень цен выше,; чем ожидалось, производители ошибочно; считают, что относительные цены; товаров, которые они поставляют на рынок, выросли', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'если уровень цен выше,; чем ожидалось, производители ошибочно; считают, что относительные цены; товаров, которые они поставляют на рынок, выросли',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('количественная теория денег гласит, что номинальный; объем ВНП пропорционален денежной массе, или,; что то же самое, спрос на; денежные средства в реальном выражении пропорционален реальному объему ВНП', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'количественная теория денег гласит, что номинальный; объем ВНП пропорционален денежной массе, или,; что то же самое, спрос на; денежные средства в реальном выражении пропорционален реальному объему ВНП',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в точке; Е, однако,; нет избыточного; спроса на товары', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в точке; Е, однако,; нет избыточного; спроса на товары',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('экономический рост может носить устойчивый характер,; когда совокупный спрос и совокупное предложение; растут синхронно, либо принимать различные неустойчивые; формы, если нарушается динамическое равновесие между спросом и предложением', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономический рост может носить устойчивый характер,; когда совокупный спрос и совокупное предложение; растут синхронно, либо принимать различные неустойчивые; формы, если нарушается динамическое равновесие между спросом и предложением',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('график, или кривая равновесия денежного; рынка, показывает все сочетания ставки; процента и уровней дохода, при; которых спрос на реальные балансы равен их предложению', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'график, или кривая равновесия денежного; рынка, показывает все сочетания ставки; процента и уровней дохода, при; которых спрос на реальные балансы равен их предложению',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в данный момент времени работница знает, что текущая ставка; заработной платы равна 12 долларов в час, но она; не знает всех цен в экономике и, следовательно, не; знает общего уровня цен, а поэтому не знает реальную заработную плату', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в данный момент времени работница знает, что текущая ставка; заработной платы равна 12 долларов в час, но она; не знает всех цен в экономике и, следовательно, не; знает общего уровня цен, а поэтому не знает реальную заработную плату',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('венгрия одобрила законодательство,; которое снижает ставку; налога на прибыль; с 16% до 15% с 2016 года', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'венгрия одобрила законодательство,; которое снижает ставку; налога на прибыль; с 16% до 15% с 2016 года',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('суть программы заключается в том, что ЕЦБ будет; осуществлять закупку активов (ценных бумаг государств и корпоративного; сектора) до тех пор, пока Совет управляющих не; увидит устойчивую корректировку инфляции на уровне целевой (2% в среднесрочной перспективе)', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'суть программы заключается в том, что ЕЦБ будет; осуществлять закупку активов (ценных бумаг государств и корпоративного; сектора) до тех пор, пока Совет управляющих не; увидит устойчивую корректировку инфляции на уровне целевой (2% в среднесрочной перспективе)',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('каковы будут; сумма долга; и величина; процента, скорректированные с учетом инфляции', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'каковы будут; сумма долга; и величина; процента, скорректированные с учетом инфляции',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('также в тройку наиболее часто; отмечаемых предпринимателями неудач государства вошли; «неспособность остановить снижение реальных доходов; населения» и «продолжение пенсионной реформы» (10% и 7%, соответственно)', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'также в тройку наиболее часто; отмечаемых предпринимателями неудач государства вошли; «неспособность остановить снижение реальных доходов; населения» и «продолжение пенсионной реформы» (10% и 7%, соответственно)',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('влияние может быть как; прямым (в виде валютной; интервенции), так и косвенным; (через регулирование объема денежной массы и процентных ставок)', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние может быть как; прямым (в виде валютной; интервенции), так и косвенным; (через регулирование объема денежной массы и процентных ставок)',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сохраняются возможности; для финансирования; перспективных проектов; по развитию инфраструктуры', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сохраняются возможности; для финансирования; перспективных проектов; по развитию инфраструктуры',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('мы будем; разбирать выбор; комбинации факторов; производства, сводящей к минимуму издержки фирмы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мы будем; разбирать выбор; комбинации факторов; производства, сводящей к минимуму издержки фирмы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('стремление России стать полноценным; членом международной торговой системы; вызывает необходимость соответствия производимых; товаров и услуг мировым требованиям', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стремление России стать полноценным; членом международной торговой системы; вызывает необходимость соответствия производимых; товаров и услуг мировым требованиям',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('если предельные издержки на приобретение; фактора больше, чем его предельный; продукт в денежной форме, для; максимизации прибыли фирме следует уменьшить количество данного фактора', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'если предельные издержки на приобретение; фактора больше, чем его предельный; продукт в денежной форме, для; максимизации прибыли фирме следует уменьшить количество данного фактора',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('rolex построит; три мануфактуры; в Швейцарии,; чтобы удовлетворить спрос на продукцию', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'rolex построит; три мануфактуры; в Швейцарии,; чтобы удовлетворить спрос на продукцию',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('новосибирская область; достигла высоких; темпов роста; производства и потребления', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новосибирская область; достигла высоких; темпов роста; производства и потребления',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в разработанной модели воздействия инфляции; и ее волатильности на экономический; рост государство влияет на решения; домохозяйств, устанавливая налог на процентный доход от сбережений', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в разработанной модели воздействия инфляции; и ее волатильности на экономический; рост государство влияет на решения; домохозяйств, устанавливая налог на процентный доход от сбережений',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('скользящее фиксирование предполагает, что; реальный валютный курс К; = РИ(Р/е) остается неизменным,; поскольку обесценение компенсирует различие в уровнях инфляции', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'скользящее фиксирование предполагает, что; реальный валютный курс К; = РИ(Р/е) остается неизменным,; поскольку обесценение компенсирует различие в уровнях инфляции',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кроме того, на фондовом рынке; неоднократно наблюдался неоправданно высокий спрос; на необеспеченные облигации, который всегда; заканчивался падением рынка при ухудшении экономической ситуации', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кроме того, на фондовом рынке; неоднократно наблюдался неоправданно высокий спрос; на необеспеченные облигации, который всегда; заканчивался падением рынка при ухудшении экономической ситуации',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('инфляция имеет и социальные последствия, она ведет к; перераспределению национального дохода, является как бы сверхналогом на; население, что обусловливает отставание темпов роста номинальной, а; также реальной заработной платы от резко возрастающих цен на товары и услуги', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляция имеет и социальные последствия, она ведет к; перераспределению национального дохода, является как бы сверхналогом на; население, что обусловливает отставание темпов роста номинальной, а; также реальной заработной платы от резко возрастающих цен на товары и услуги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('последующий отклик целевых показателей (обычно это; показатели реального сектора экономики – параметры; инвестиций, потребления, чистого экспорта, совокупного выпуска; и иных) – это неподконтрольный регулятору этап работы трансмиссионного механизма', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'последующий отклик целевых показателей (обычно это; показатели реального сектора экономики – параметры; инвестиций, потребления, чистого экспорта, совокупного выпуска; и иных) – это неподконтрольный регулятору этап работы трансмиссионного механизма',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('по этим простым причинам спрос; на реальные балансы увеличивается по; мере роста уровня реального дохода; и снижается по мере роста ставки процента', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по этим простым причинам спрос; на реальные балансы увеличивается по; мере роста уровня реального дохода; и снижается по мере роста ставки процента',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение текущей ставки реальной; заработной платы в целом; по экономике вызывает рост; предложения труда по двум причинам', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение текущей ставки реальной; заработной платы в целом; по экономике вызывает рост; предложения труда по двум причинам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая предельных издержек; пересекается с кривыми; средних переменных и; средних совокупных издержек в точках их минимумов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая предельных издержек; пересекается с кривыми; средних переменных и; средних совокупных издержек в точках их минимумов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('большое значение для; устойчивого развития экономики; регионов Севера имеет; восполнение запасов минерального сырья', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'большое значение для; устойчивого развития экономики; регионов Севера имеет; восполнение запасов минерального сырья',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('должно ли небольшое увеличение уровня безработицы вести; к небольшому повышению темпов роста денежной массы; или политика не должна реагировать до тех; пор, пока прирост безработицы не будет значительным, скажем, более 1%', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'должно ли небольшое увеличение уровня безработицы вести; к небольшому повышению темпов роста денежной массы; или политика не должна реагировать до тех; пор, пока прирост безработицы не будет значительным, скажем, более 1%',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('десятипроцентное увеличение реальной денежной массы М/Р; не приводит к сдвигу кривой IS; или линии FE, потому что объем; производства и реальная процентная ставка остаются постоянными', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'десятипроцентное увеличение реальной денежной массы М/Р; не приводит к сдвигу кривой IS; или линии FE, потому что объем; производства и реальная процентная ставка остаются постоянными',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('когда Вы или кто-либо; из Ваших друзей ищете; работу на полставки, сколько; недель в среднем на это уходит', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'когда Вы или кто-либо; из Ваших друзей ищете; работу на полставки, сколько; недель в среднем на это уходит',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('косвенные налоги; частично или; полностью переносятся; на цену товара или услуги', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'косвенные налоги; частично или; полностью переносятся; на цену товара или услуги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('какова роль; денег как; ликвидного актива; в становлении и развитии рыночной экономики', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'какова роль; денег как; ликвидного актива; в становлении и развитии рыночной экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('условием качественной подготовки; и переподготовки кадров; является сотрудничество образовательных; организаций ДПО и предприятий реального сектора экономики', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'условием качественной подготовки; и переподготовки кадров; является сотрудничество образовательных; организаций ДПО и предприятий реального сектора экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сдерживающая фискальная; политика направлена; на борьбу; с инфляцией спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдерживающая фискальная; политика направлена; на борьбу; с инфляцией спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('необходимо осознавать, что неизбежное следствие; жесткой монетарной политики, направленной на; снижение темпов инфляции, — повышение; уровня безработи­цы и сокращение объемов производства', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'необходимо осознавать, что неизбежное следствие; жесткой монетарной политики, направленной на; снижение темпов инфляции, — повышение; уровня безработи­цы и сокращение объемов производства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('показана имеющая отрицательный наклон кривая; спроса на труд, которая означает,; что фирмы предъявляют спрос на; тем большее количество труда, чем ниже реальная заработная плата', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'показана имеющая отрицательный наклон кривая; спроса на труд, которая означает,; что фирмы предъявляют спрос на; тем большее количество труда, чем ниже реальная заработная плата',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('глобализация рынков; способствует высокому; уровню эффективности; производства и обращения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'глобализация рынков; способствует высокому; уровню эффективности; производства и обращения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('объем выпуска находится; на равновесном уровне; в том случае,; если совокупный спрос равен объему производства', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем выпуска находится; на равновесном уровне; в том случае,; если совокупный спрос равен объему производства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('от краткосрочной перспективы мы переходим; к условно наиболее долгосрочной перспективе,; в которой скорость роста денежной; массы является и будет являться постоянной', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'от краткосрочной перспективы мы переходим; к условно наиболее долгосрочной перспективе,; в которой скорость роста денежной; массы является и будет являться постоянной',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('снижение темпа роста; номинальной денежной массы; ведет к более; низкому росту ВВП и более высокой безработице', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение темпа роста; номинальной денежной массы; ведет к более; низкому росту ВВП и более высокой безработице',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('утверждается, что фирмы и рабочие; подошли к ожиданию высокой инфляции; в будущем и в свете; своих ожиданий выдвигают и отстаивают свои требования', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'утверждается, что фирмы и рабочие; подошли к ожиданию высокой инфляции; в будущем и в свете; своих ожиданий выдвигают и отстаивают свои требования',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('денежные власти; устанавливают номинальную; процентную ставку; с помощью правила Тейлора', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные власти; устанавливают номинальную; процентную ставку; с помощью правила Тейлора',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в этом разделе; мы представляем четыре; основные модели совокупного; предложения в порядке, соответствующем хронологии их разработки', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в этом разделе; мы представляем четыре; основные модели совокупного; предложения в порядке, соответствующем хронологии их разработки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

