
```{r}
checkdown::check_question(answer = stringr::str_split('уровень; реальной; заработной; платы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('величина; реального; предложения; денег', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величина; реального; предложения; денег',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('формирование; будущего; разумного; потребления', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'формирование; будущего; разумного; потребления',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('мировая; реальная; процентная; ставка', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('полномочия; органов; государственной; власти', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'полномочия; органов; государственной; власти',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('смещение; кривой; совокупного; предложения; вправо', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смещение; кривой; совокупного; предложения; вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рациональное; потребление; товаров; и; услуг', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рациональное; потребление; товаров; и; услуг',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('стратегическое; планирование; социально-экономического; развития', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стратегическое; планирование; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('факторы; развития; межбюджетных; отношений', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; развития; межбюджетных; отношений',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('механизмы; акселерации; социально-экономического; развития', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'механизмы; акселерации; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('смещение; кривой; совокупного; предложения; влево', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смещение; кривой; совокупного; предложения; влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; реальной; денежной; массы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('прогнозирование; чистой; процентной; маржи', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'прогнозирование; чистой; процентной; маржи',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('наклон; кривой; совокупного; спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'наклон; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('пространственное; распределение; экономической; активности', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пространственное; распределение; экономической; активности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('шок; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'шок; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('высокая; доля; добавленной; стоимости', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокая; доля; добавленной; стоимости',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальные; диспропорции; экономического; пространства', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; диспропорции; экономического; пространства',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('устойчивого; развития; сельских; территорий', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивого; развития; сельских; территорий',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; виде; заработной; платы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; виде; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('особенности; функционирования; бюджетной; системы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'особенности; функционирования; бюджетной; системы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('приводит; к; увеличению; объема', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'приводит; к; увеличению; объема',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельная; норма; технического; замещения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная; норма; технического; замещения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('трудового; потенциала; северных; регионов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'трудового; потенциала; северных; регионов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('значения; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'значения; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('экономическая; оценка; эффективности; инвестиций', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономическая; оценка; эффективности; инвестиций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('среднедушевые; денежные; доходы; населения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'среднедушевые; денежные; доходы; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальные; денежные; доходы; населения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; денежные; доходы; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('деятельность; субъектов; бюджетного; планирования', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'деятельность; субъектов; бюджетного; планирования',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ставка; реальной; заработной; платы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('новая; модель; государственного; управления', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новая; модель; государственного; управления',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; долгосрочного; совокупного; предложения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; долгосрочного; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('переменная,; которая; принимает; значение', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'переменная,; которая; принимает; значение',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эластичность; спроса; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность; спроса; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('налог; на; добавленную; стоимость', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налог; на; добавленную; стоимость',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('развитие; мировых; финансовых; институтов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитие; мировых; финансовых; институтов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('мировая; реальная; процентная; ставка', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('объем; оборота; розничной; торговли', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем; оборота; розничной; торговли',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('асимметрия; развития; цифровой; экономики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'асимметрия; развития; цифровой; экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('распределение; прямых; иностранных; инвестиций', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'распределение; прямых; иностранных; инвестиций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('уравнение; кривой; совокупного; спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уравнение; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('темпы; прироста; реального; ввп', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпы; прироста; реального; ввп',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличивать; спрос; на; технику', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличивать; спрос; на; технику',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; объемов; государственных; закупок', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; объемов; государственных; закупок',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('влияние; на; распределение; бюджетных; средств', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние; на; распределение; бюджетных; средств',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('распределение; продукции; жёстко; регулируется', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'распределение; продукции; жёстко; регулируется',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальная; ставка; процента; равна', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная; ставка; процента; равна',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ставка; процента; равна; нулю', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка; процента; равна; нулю',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('выпуск; товаров; для; внутреннего; потребления', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выпуск; товаров; для; внутреннего; потребления',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('исполнительные; органы; государственной; власти', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'исполнительные; органы; государственной; власти',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('страны; с; переходной; экономикой', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'страны; с; переходной; экономикой',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('структура; валовой; добавленной; стоимости', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'структура; валовой; добавленной; стоимости',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельный; доход; равен; предельным; издержкам', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; доход; равен; предельным; издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('приводит; к; уменьшению; объема', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'приводит; к; уменьшению; объема',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('на; фактическое; конечное; потребление', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на; фактическое; конечное; потребление',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальная; цена; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная; цена; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; реальной; заработной; платы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('стимулирование; инновационного; экономического; роста', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стимулирование; инновационного; экономического; роста',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('бюджетная; система; Российской; Федерации', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'бюджетная; система; Российской; Федерации',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('за; счет; бюджетных; ассигнований', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'за; счет; бюджетных; ассигнований',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('доходность; рынка; ценных; бумаг', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доходность; рынка; ценных; бумаг',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('факторы; внешней; среды; влияющие', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; внешней; среды; влияющие',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('процентная; ставка,; обеспечивающая; равновесие', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная; ставка,; обеспечивающая; равновесие',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('распределение; ресурсов; между; производителями', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'распределение; ресурсов; между; производителями',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельный; продукт; труда; равен', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; продукт; труда; равен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('средняя; цена; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'средняя; цена; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельный; доход; равняется; предельным; издержкам', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; доход; равняется; предельным; издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('факторы; вызывающие; сдвиг; кривой', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; вызывающие; сдвиг; кривой',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ожидаемая; реальная; процентная; ставка', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('индекс; развития; человеческого; потенциала', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекс; развития; человеческого; потенциала',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('принцип; убывающей; предельной; полезности', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'принцип; убывающей; предельной; полезности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('влияние; волатильности; инфляции; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние; волатильности; инфляции; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('банк; увеличивает; предложение; денег', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'банк; увеличивает; предложение; денег',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('распределение; электроэнергии; на; предприятии', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'распределение; электроэнергии; на; предприятии',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальные; располагаемые; денежные; доходы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; располагаемые; денежные; доходы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('взаимные; фонды; денежного; рынка', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'взаимные; фонды; денежного; рынка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('концепции; долгосрочного; социально-экономического; развития', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'концепции; долгосрочного; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('государственное; регулирование; территориального; развития', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственное; регулирование; территориального; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('импорт; товаров; на; внешние; рынки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'импорт; товаров; на; внешние; рынки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('экспорт; товаров; за; границу', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экспорт; товаров; за; границу',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; безразличия; показывает,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; безразличия; показывает,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; сфере; распределения; активов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; сфере; распределения; активов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('индекс; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекс; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; совокупного; спроса; смещается; вправо/влево', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; спроса; смещается; вправо/влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('темпы; роста; реального; ввп', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпы; роста; реального; ввп',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; среднем; за; год', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; среднем; за; год',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('краткосрочная; кривая; совокупного; предложения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'краткосрочная; кривая; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельные; издержки; равны; цене', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные; издержки; равны; цене',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ставка; реальной; заработной; платы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; совокупного; спроса; смещается', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; спроса; смещается',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; номинальной; денежной; массы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; номинальной; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('доход; увеличивается; на; 5%', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доход; увеличивается; на; 5%',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; среднем; по; стране', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; среднем; по; стране',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('значение; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'значение; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('долгосрочная; кривая; совокупного; предложения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'долгосрочная; кривая; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('цена; за; единицу; товара', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена; за; единицу; товара',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('никак; не; влиять; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'никак; не; влиять; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('закон; убывающей; предельной; производительности', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закон; убывающей; предельной; производительности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('влиять; друг; на; друга', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влиять; друг; на; друга',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('работы; классиков; экономической; теории', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'работы; классиков; экономической; теории',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('мировая; цена; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; цена; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('повышение; эффективности; бюджетных; расходов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышение; эффективности; бюджетных; расходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; качестве; примера; можно; привести', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; качестве; примера; можно; привести',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('факторы; влияющие; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; влияющие; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('оценки; равновесной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценки; равновесной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('полученные; результаты; показывают,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'полученные; результаты; показывают,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('зависит; от; того,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'зависит; от; того,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('теория; реального; экономического; цикла', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теория; реального; экономического; цикла',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сдвиг; кривой; совокупного; спроса; вправо/влево', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг; кривой; совокупного; спроса; вправо/влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('спецификация; макроэкономических; целевых; параметров', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спецификация; макроэкономических; целевых; параметров',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличиваться; по; мере; накопления; средств', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличиваться; по; мере; накопления; средств',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('государственная; поддержка; нефтегазохимических; кластеров', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственная; поддержка; нефтегазохимических; кластеров',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('факторы; развития; межбюджетных; отношений', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; развития; межбюджетных; отношений',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рыночная; стоимость; товаров; и; услуг', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночная; стоимость; товаров; и; услуг',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('региональное; распределение; прямых; доходов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'региональное; распределение; прямых; доходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('наклон; линии; бюджетного; ограничения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'наклон; линии; бюджетного; ограничения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('точка; пересечения; кривых; спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'точка; пересечения; кривых; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('доход; равен; предельным; издержкам', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доход; равен; предельным; издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('уравнение; кривой; совокупного; спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уравнение; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('стимулы; к; трудовой; деятельности', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стимулы; к; трудовой; деятельности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ключевые; факторы; оценки; должностей', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ключевые; факторы; оценки; должностей',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('индекс; физического; объема; ВВП', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекс; физического; объема; ВВП',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('трансмиссионный; механизм; денежно-кредитной; политики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'трансмиссионный; механизм; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сдвигает; кривую; совокупного; спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвигает; кривую; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; Филлипса; показывает,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; Филлипса; показывает,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('изменение; общего; уровня; цен', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение; общего; уровня; цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('инструменты; налогового; стимулирования; ', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инструменты; налогового; стимулирования; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('отрицательный; наклон; кривой; совокупного; спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отрицательный; наклон; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('фактор; укрепления; межгосударственных; отношений', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактор; укрепления; межгосударственных; отношений',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('федеральная; служба; государственной; статистики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'федеральная; служба; государственной; статистики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('методы; оценки; теневой; экономики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'методы; оценки; теневой; экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('измерение; уровня; экономического; развития', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'измерение; уровня; экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('закон; убывающей; предельной; полезности', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закон; убывающей; предельной; полезности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; свою; очередь; приводит; к', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; свою; очередь; приводит; к',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('во; многом; зависит; от', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'во; многом; зависит; от',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('потребления; основных; продуктов; питания', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребления; основных; продуктов; питания',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('повышение; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышение; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('пространственная; связность; экономической; активности', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пространственная; связность; экономической; активности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; совокупного; спроса; сдвигается; вправо/влево', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; спроса; сдвигается; вправо/влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эластичность; спроса; по', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность; спроса; по',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сдвиг; кривой; совокупного; предложения; вправо', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг; кривой; совокупного; предложения; вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; скорости; роста; денежной; массы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; скорости; роста; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реализации; стратегии; социально-экономического; развития', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реализации; стратегии; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('падение; мировых; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падение; мировых; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эффективность; использования; бюджетных; средств', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффективность; использования; бюджетных; средств',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ожидаемая; реальная; процентная; ставка', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ставка; процента; равна; нулю', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка; процента; равна; нулю',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ожидаемая; реальная; процентная; ставка', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('национальная; модель; экономического; роста', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальная; модель; экономического; роста',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ожидаемая; норма; чистой; прибыли', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; норма; чистой; прибыли',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рынок; новых; фирм; ', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок; новых; фирм; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельный; продукт; капитала; равен', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; продукт; капитала; равен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; общего; уровня; цен', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; общего; уровня; цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('за; вычетом; потребления; основного; капитала', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'за; вычетом; потребления; основного; капитала',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('новая; модель; экономического; роста', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новая; модель; экономического; роста',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('использование; трудового; потенциала; населения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'использование; трудового; потенциала; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('мировая; практика; показывает,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; практика; показывает,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальный; спрос; на; деньги', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный; спрос; на; деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('зависит; от; ставки; ', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'зависит; от; ставки; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('уровень; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; темпа; роста; денежной; массы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; темпа; роста; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; ВВП; ведет; к', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; ВВП; ведет; к',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельная; норма; технологического; замещения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная; норма; технологического; замещения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('динамика; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'динамика; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('данные; о; распределении; численности; работников', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'данные; о; распределении; численности; работников',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('асимметричное; влияние; денежно-кредитной; политики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'асимметричное; влияние; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рассчитывается; как; разница; между', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рассчитывается; как; разница; между',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличиваться; на; величину; начисляемых; процентов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличиваться; на; величину; начисляемых; процентов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('операции; с; ценными; бумагами', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'операции; с; ценными; бумагами',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; значительной; степени; зависит', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; значительной; степени; зависит',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('значения; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'значения; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличиваться; более; чем; на; половину', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличиваться; более; чем; на; половину',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('на; данном; уровне; цен', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на; данном; уровне; цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличиваться; с; ростом; доходов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличиваться; с; ростом; доходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('валютный; канал; денежной; трансмиссии', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'валютный; канал; денежной; трансмиссии',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сдвигает; кривую; совокупного; спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвигает; кривую; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('неожиданные; шоки; денежно-кредитной; политики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'неожиданные; шоки; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('напрямую; зависит; от; ', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'напрямую; зависит; от; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эластичный; спрос; по; доходу', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичный; спрос; по; доходу',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('конечное; потребление; домашних; хозяйств', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конечное; потребление; домашних; хозяйств',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эффект; переноса; ключевой; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффект; переноса; ключевой; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('балансовый; канал; денежно-кредитной; политики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'балансовый; канал; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('на; основе; уровней; социально-экономического; развития', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на; основе; уровней; социально-экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('проведенный; анализ; показывает,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'проведенный; анализ; показывает,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('мировая; реальная; процентная; ставка', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая; реальная; процентная; ставка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('теория; реального; экономического; цикла', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теория; реального; экономического; цикла',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальные; денежные; доходы; населения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; денежные; доходы; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('снижение; реальной; заработной; платы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('равен; ожидаемому; уровню; цен', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равен; ожидаемому; уровню; цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('мировой; опыт; показывает,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой; опыт; показывает,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('высокие; темпы; экономического; роста', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокие; темпы; экономического; роста',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; теории; потребления; рынка', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; теории; потребления; рынка',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('формирование; цепочек; добавленной; стоимости', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'формирование; цепочек; добавленной; стоимости',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('приводит; к; снижению; объема', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'приводит; к; снижению; объема',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('цена; выше; предельных; издержек', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена; выше; предельных; издержек',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('финансовые; обязательства; перед', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые; обязательства; перед',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('внутренние; цены; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутренние; цены; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('принцип; убывающей; предельной; производительности', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'принцип; убывающей; предельной; производительности',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; реальной; заработной; платы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('приводит; к; сокращению; объема', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'приводит; к; сокращению; объема',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ожидаемая; продолжительность; жизни; населения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; продолжительность; жизни; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('смещение; кривой; совокупного; спроса; вправо/влево', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смещение; кривой; совокупного; спроса; вправо/влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; реальной; процентной; ставки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; процентной; ставки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('предельный; доход; продукта; труда', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный; доход; продукта; труда',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('снижение; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальный; обменный; курс; рубля', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный; обменный; курс; рубля',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; номинальной; денежной; массы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; номинальной; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('в; среднем; на; душу; населения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; среднем; на; душу; населения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('высокий; уровень; экономического; развития', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокий; уровень; экономического; развития',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эффективность; использования; бюджетных; расходов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффективность; использования; бюджетных; расходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; совокупного; спроса; сдвигается; вправо', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; спроса; сдвигается; вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('оценка; эффективности; инвестиционных; проектов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценка; эффективности; инвестиционных; проектов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('модернизация; реального; сектора; экономики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'модернизация; реального; сектора; экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('построение; модели; совокупных; расходов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'построение; модели; совокупных; расходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('на; основе; полученных; ', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на; основе; полученных; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('приводить; к; росту; потребления', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'приводить; к; росту; потребления',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('отрезок; кривой; совокупного; предложения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отрезок; кривой; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальная; процентная; ставка; равна', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная; процентная; ставка; равна',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('падение; цен; на', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падение; цен; на',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('эффекты; единой; денежно-кредитной; политики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффекты; единой; денежно-кредитной; политики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; реальной; заработной; платы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; реальной; заработной; платы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('реальные; располагаемые; денежные; доходы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные; располагаемые; денежные; доходы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('общий; спрос; на; деньги', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'общий; спрос; на; деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; предельного; продукта; труда', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; предельного; продукта; труда',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('расходы; на; социальные; нужды', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расходы; на; социальные; нужды',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('цена; равна; предельным; издержкам', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена; равна; предельным; издержкам',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('склонность; к; потреблению; снижается', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'склонность; к; потреблению; снижается',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; краткосрочного; совокупного; предложения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; краткосрочного; совокупного; предложения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('финансирование; дефицита; государственного; бюджета', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансирование; дефицита; государственного; бюджета',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сдвиг; кривой; совокупного; предложения; влево', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг; кривой; совокупного; предложения; влево',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('ставка; процента; ведет; к', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка; процента; ведет; к',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('кривая; совокупного; предложения; сдвигается; вправо', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая; совокупного; предложения; сдвигается; вправо',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('увеличение; реальной; денежной; массы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение; реальной; денежной; массы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('рост; дохода; ведет; к', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост; дохода; ведет; к',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('сдвиг; кривой; совокупного; спроса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиг; кривой; совокупного; спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('альтернативное; приобретение; товаров; для; перепродажи', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'альтернативное; приобретение; товаров; для; перепродажи',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('чувствительность; спроса; на; деньги', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'чувствительность; спроса; на; деньги',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('цена; превышает; предельные; издержки', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена; превышает; предельные; издержки',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```


```{r}
checkdown::check_question(answer = stringr::str_split('результаты; исследования; показывают,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'результаты; исследования; показывают,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

