```{r}
#| include: false

library(tidyverse)
library(htmltools)
readxl::read_xlsx("data/word_profiles.xlsx") |> 
  filter(!is.na(lemma)) |> 
  mutate(lemma = str_extract(lemma_for_site, "^.*?(?=( -))"),
         lemma = ifelse(is.na(lemma), lemma_for_site, lemma),
         lemma = str_remove_all(lemma, "\\(.*?\\)")) ->
  df
```


::: {.panel-tabset}

## Существительные

```{r}
#| results: asis
#| layout-ncol: 3

df |> 
  filter(wl_type == "NOUN") |> 
  distinct(lemma, lemma_for_site) |> 
  arrange(lemma) |> 
  filter(!is.na(lemma)) ->
  nouns

if(nrow(nouns) %% 3 == 2){
  nouns |> 
    bind_rows(tibble(lemma = "", 
                     lemma_for_site = "")) ->
    nouns
}

walk2(nouns$lemma, 
      nouns$lemma_for_site,
      function(lemma, lemma_for_site) {
        htmltools::a(lemma_for_site, href = str_c(lemma, ".html")) |>
          htmltools::div(class = "col") |>
          print()
  }
)
```


## Прилагательные

```{r}
#| results: asis
#| layout-ncol: 3

df |> 
  filter(wl_type == "ADJ") |> 
  distinct(lemma, lemma_for_site) |> 
  arrange(lemma) |> 
  filter(!is.na(lemma))->
  adjs

if(nrow(adjs) %% 3 == 2){
  adjs |> 
    bind_rows(tibble(lemma = "", 
                     lemma_for_site = "")) ->
    adjs
}


walk2(adjs$lemma, 
      adjs$lemma_for_site,
      function(lemma, lemma_for_site) {
        htmltools::a(lemma_for_site, href = str_c(lemma, ".html")) |>
          htmltools::div(class = "col") |>
          print()
  }
)
```


## Глаголы

```{r}
#| results: asis
#| layout-ncol: 3

df |> 
  filter(wl_type == "VERB") |> 
  distinct(lemma, lemma_for_site) |> 
  arrange(lemma) |> 
  filter(!is.na(lemma))->
  verbs

if(nrow(verbs) %% 3 == 2){
  verbs |> 
    bind_rows(tibble(lemma = "", 
                     lemma_for_site = "")) ->
    verbs
}

walk2(verbs$lemma, 
      verbs$lemma_for_site,
      function(lemma, lemma_for_site) {
        htmltools::a(lemma_for_site, href = str_c(lemma, ".html")) |>
          htmltools::div(class = "col") |>
          print()
  }
)
```

:::