
```{r}
checkdown::check_question(answer = stringr::str_split('деятельность; субъектов; бюджетного; планирования', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'деятельность; субъектов; бюджетного; планирования',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('особенности; функционирования; бюджетной; системы', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'особенности; функционирования; бюджетной; системы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('эффективность; использования; бюджетных; расходов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффективность; использования; бюджетных; расходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('наклон; линии; бюджетного; ограничения', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'наклон; линии; бюджетного; ограничения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('факторы; развития; межбюджетных; отношений', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы; развития; межбюджетных; отношений',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```
