```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Ускорение роста населения не приведет к ____________ (**повышение**) подушевого дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'старению', 
                          title = '#### Это приведет к дальнейшему ____________ (**старение**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'старению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уменьшению', 
                          title = '#### Введение налога на товар приводит к ____________ (**уменьшение**) объема продаж на рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уменьшению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'улучшению', 
                          title = '#### Более высокий рост производительности приводит к ____________ (**улучшение**) инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'улучшению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению', 
                          title = '#### Цепочка финансового посредничества должна привести к ____________ (**изменение**) ставок кредитов и депозитов для предприятий и населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'дальнейшему', 
                          title = '#### Все это приводило к ____________ (**дальнейти**) росту цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дальнейшему',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению', 
                          title = '#### Непосредственной причиной разрыва модернизационных процессов в Китае стали иноземные вторжения XIII и XVII вв., которые привели к ____________ (**изменение**) политической культуры и деволюции социальных институтов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'более низкой', 
                          title = '#### Более высокий темп роста денежной массы приводит к ____________ ____________ (**более, низкий**) реальной ставке процента в краткосрочной перспективе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'более низкой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возникновению', 
                          title = '#### Высокая степень расслоения в обществе приводит к ____________ (**возникновение**) социальных рисков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возникновению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'избыточному спросу', 
                          title = '#### Любое другое отношение цен приведет к ____________ ____________ (**избыточный, спрос**) на один товар и избыточному предложению другого товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'избыточному спросу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'удорожанию', 
                          title = '#### Повышение косвенных налогов приводит к ____________ (**удорожание**) импорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'удорожанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'такому', 
                          title = '#### Увеличение темпа роста денежной массы приводит к ____________ (**такой**) же увеличению уровня инфляции и номинальной ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'такому',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Это обусловливает сжатие экономики других стран и в свою очередь приводит к ____________ (**снижение**) спроса на экспорт первой страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сдвигу', 
                          title = '#### Увеличение пенсий не приводит к ____________ (**сдвиг**) кривой совокупного спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвигу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уменьшению', 
                          title = '#### Рабочим становится ясно, что повышение уровня цен привело к ____________ (**уменьшение**) реальной заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уменьшению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### Снижение процентных ставок приводит к ____________ (**рост**) инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### Денежные мероприятия, направленные на снижение уровня безработицы до уровня ниже естественного, быстро (но не мгновенно) приведут к ____________ (**рост**) инфляции, но не сократят безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возникновению', 
                          title = '#### Накопление этого вЕщества в атмосфере ведет к ____________ (**возникновение**) «парникового эффекта», способного вызвать рост температур по всему земному шару.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возникновению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возрастанию', 
                          title = '#### Увеличение реальной процентной ставки приводит к ____________ (**возрастание**) желаемого уровня сбережений у домашних хозяйств.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возрастанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'максимальной прибыли', 
                          title = '#### В этом разделе мы выясним, как можно использовать информацию о доходах и издержках, чтобы принять верное решение, которое приведет к ____________ ____________ (**максимальный, прибыль**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'максимальной прибыли',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потере', 
                          title = '#### Такая политика приводит к ____________ (**потеря**) эффективности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потере',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'быстрым изменениям', 
                          title = '#### Полное освобождение цен должно привести к ____________ ____________ (**быстрый, изменение**) их уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'быстрым изменениям',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'к увеличению', 
                          title = '#### Более высокие частные расходы требуют более низкой равновесной ставки процента: более низкая ставка процента ведет ____________ ____________ (**к, увеличение**) инвестиций и, таким образом, к более высоким частным расходам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'к увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'к снижению', 
                          title = '#### При данном ожидаемом в будущем валютном курсе и иностранной ставке процента рост внутренней ставки процента ведет ____________ ____________ (**к, снижение**) валютного курса (к удорожанию валюты).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'к снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Поразительно то, что ослабление обменного курса более чем на 10% в ряде кварталов не привело к ____________ (**повышение**) эффекта переноса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Переход к модели со структурными разрывами ведет к ____________ (**снижение**) среднего 𝑝-значения до 31,8%, а соотношение значимых разниц в качестве прогнозов сохраняется.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уменьшению', 
                          title = '#### Налог на единицу выпуска приведет к ____________ (**уменьшение**) предложения конкурентной фирмы, поскольку приводит к увеличению ее предельных затрат.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уменьшению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению', 
                          title = '#### Осуществление задач экономической политики может привести к ____________ (**изменение**) экономической системы, ее совершенствованию или разрушению.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению', 
                          title = '#### При значительных изменениях цен будет проявляться влияние эффекта дохода, что приведет к ____________ (**изменение**) спроса на оба товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Более высокая степень неопределенности приводит к ____________ (**снижение**) депозитных ставок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'появлению', 
                          title = '#### По окончании войны союзники потребовали от Германии выплаты значительных репараций. Эти платежи привели к ____________ (**появление**) бюджетного дефицита, который правительство Германии, естественно, покрывало за счет печатания большого количества денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'появлению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'колебаниям', 
                          title = '#### Поведение участников валютного рынка приводит к значительным ____________ (**колебание**) валютного курса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'колебаниям',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сокращению', 
                          title = '#### Хотя сокращение пособий по безработице и уменьшит размер фрикционной безработицы, а снижение минимальной заработной платы приведет к ____________ (**сокращение**) безработицы ожидания, такая политика негативно отразится на наиболее нуждающихся группах населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сокращению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению', 
                          title = '#### Развитие товарно-денежных отношений привело к ____________ (**изменение**) формы перераспределительных отношений,— они стали носить преимущественно денежный характер.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'что', 
                          title = '#### Это приводило к тому ____________ (**что**) в некоторые моменты на рынке возникал недостаток предложения валюты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'что',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'колебаниям', 
                          title = '#### Если меры экономической политики выбраны удачно, шоки не приведут к ____________ (**колебание**) дохода и занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'колебаниям',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Как и для кредитора, для заемщика эффект замены, порождаемый снижением ставки процента, ведет к ____________ (**увеличение**) текущего потребления, так как ценность текущего потребления относительно ценности будущего потребления снизилась.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### Падение эффективности советской модели экономики было связано с исчерпанием трудовых ресурсов и низкой эластичностью замЕщения между капиталом и трудом, что привело к ____________ (**падение**) совокупной производительности факторов производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### Резкое сокращение производства и платежеспособности предприятий привело к ____________ (**падение**) спроса на научно-технические разработки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'скачку', 
                          title = '#### Проблемы с предложением нефти на мировом рынке привели к резкому ____________ (**скачок**) цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'скачку',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'смЕщению', 
                          title = '#### Тот факт, что некоторые компании объявили дефолт по своим облигациям до наступления срока их погашения (не смогли выплатить купон), может привести к ____________ (**смещение**) оценок в сторону: эти компании, вероятно, более восприимчивы к шокам ДКП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смЕщению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесие', 
                          title = '#### Цена изменяется, чтобы привести в ____________ (**равновесие**) спрос и предложение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Увеличение инфляции выше оптимального темпа приводит к значительному ____________ (**снижение**) налоговой базы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### Расширительные операции на открытом рынке, благодаря которым центральный банк увеличивает предложение денег, покупая облигации, ведут к ____________ (**рост**) цены облигаций и соответственно — к снижению ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конкурентоспособности', 
                          title = '#### Протекционистская поддержка не привела к ____________ (**конкурентоспособность**) отраслей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конкурентоспособности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Высокий уровень совокупного спроса приводит к ____________ (**увеличение**) цен и заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### Такие изменения способны привести к ____________ (**рост**) цены облигаций правительства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### При прочих равных условиях такие изменения способны привести к ____________ (**рост**) цены облигаций правительства (Минфина), одновременно снижая дисконтные процентные ставки по этим бумагам, тем самым сокращая предельные издержки фондирования правительства или госбанков на рынке денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Увеличение инвестиций приводит к ____________ (**увеличение**) национального продукта или дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'появлению', 
                          title = '#### Правительство устанавливает уровень минимальной заработной платы, что приводит к ____________ (**появление**) вынужденной безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'появлению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'приведем', 
                          title = '#### В качестве примера ____________ (**привести**) инвестиции в акции или облигации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'приведем',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### При этом фискальная экспансия стимулировала рост совокупного спроса без негативного побочного влияния на ставки процента, что могло бы привести к ____________ (**падение**) инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'появлению', 
                          title = '#### Социально-пространственная сегрегация города на примере рынка жилой недвижимости Новосибирска в нормативном регулировании этой сферы привели к ____________ (**появление**) крупных проектов по комплексному освоению территории (и одновременно к появлению экономических границ, обусловленных экономической целесообразностью освоения окраинных территорий городов), наметилось зарождение тенденции редевелопмента (строительство взамен сноса ветхого жилья).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'появлению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'удорожанию', 
                          title = '#### Это также усложняет эксплуатацию и ведет к ____________ (**удорожание**) древесных лесных ресурсов, актуализирует проблемы лучшего их использования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'удорожанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сокращению', 
                          title = '#### Но эти убытки подтолкнут к выходу из отрасли, что приведет к ____________ (**сокращение**) предложения и повышению цены продукта до тех пор, пока убытки не будут ликвидированы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сокращению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### К середине 2001 г. это падение в инвестиционных расходах стало достаточно ощутимым, чтобы привести к ____________ (**падение**) общего спроса на товары и ВВП — экономика США вступала в рецессию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потере', 
                          title = '#### Это неизбежно приведет к ____________ (**потеря**) времени функционирования станков и соответственно к снижению объема выпускаемой продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потере',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'к росту', 
                          title = '#### При данном предложении денег рост дохода ведет ____________ ____________ (**к, рост**) спроса на деньги и к росту ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'к росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'к снижению', 
                          title = '#### Закон Энгеля описывает ситуацию, когда рост дохода ведет ____________ ____________ (**к, снижение**) доли расходов на приобретение товаров первой необходимости (продовольствие) при неизменной системе предпочтений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'к снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Без индексации заработной платы более низкая безработица ведет к ____________ (**повышение**) заработной платы, что, в свою очередь, повышает цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Высокие банковские кредитные ставки приводят к ____________ (**увеличение**) периода окупаемости проектов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'исходя', 
                          title = '#### Эти примеры приводят нас к следующему выводу: в общественной жизни люди ведут себя, ____________ (**исходить**) исключительно из своих частных интересов, что не всегда в итоге приводит к результату, отвечающему интересам общества в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'исходя',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### Растущий объем дохода приводит к ____________ (**рост**) инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению', 
                          title = '#### Поскольку эти факторы определяются точкой пересечения кривых спроса и предложения, то все, что способствует изменению или перемЕщению этих кривых, естественно, приведет к ____________ (**изменение**) и равновесных цен, и количества товаров, причем эти изменения вполне предсказуемы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возникновению', 
                          title = '#### Рост цены экспортного товара приводит к ____________ (**возникновение**) прибыли в этом секторе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возникновению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Стимулирующая монетарная политика теперь приведет к ____________ (**повышение**) валютного курса, т.е. к удешевлению валюты на 10%, т.е. гораздо большему эффекту.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'отдалению', 
                          title = '#### Так, парируя вполне ожидаемые критические замечания по поводу того, что переход к одноуровневой структуре крупных муниципалитетов неизбежно ведет к ____________ (**отдаление**) местной власти от населения, сторонники идеи слияния муниципалитетов обычно указывают на простую и доступную возможность легкого преодоления этого недостатка путем организации сети «местных комитетов, консультационных и иных дополнительных офисов» с минимальным штатом служащих, предоставляющих определенный набор услуг, консультирующих местных жителей или отвечающих на их вопросы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отдалению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'тому', 
                          title = '#### Приватизация государственных предприятий привела к ____________ (**то**), что правительство потеряло прибыли предприятий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'тому',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению', 
                          title = '#### Изменения предложения в экспортном секторе приводят к ____________ (**изменение**) относительных цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### Снижение спроса приводит к ____________ (**падение**) загрузки мощностей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величины', 
                          title = '#### Изменение спроса привело к изменению ____________ (**величина**) предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величины',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возрастанию', 
                          title = '#### Высокие темпы роста населения привели к резкому ____________ (**возрастание**) доли стран Азии, Латинской Америки и Африки в мировом сообществе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возрастанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Мы оказались под воздействием благоприятного шока производительности, который приводит к ____________ (**увеличение**) объема производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Рост безработицы ведет к ____________ (**снижение**) заработной платы ниже стоимости рабочей силы, которая делает невыгодным применение машин.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'к более крупным', 
                          title = '#### Более высокая ставка процента ведет ____________ ____________ ____________ (**к, более, крупный**) дефицитам, к более быстрому росту соотношения долга и т.д.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'к более крупным',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'смЕщению', 
                          title = '#### Это усложняет реализацию экономической политики и приводит к ____________ (**смещение**) региональных статистических ориентиров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смЕщению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'тому', 
                          title = '#### Внесение изменений в содержание проекта создает риск неконтролируемого роста содержания, который приводит к ____________ (**то**), что проект не может успешно завершиться.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'тому',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### План Брэйди вместе с падением процентных ставок привел к ____________ (**снижение**) долгового бремени.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'образованию', 
                          title = '#### Хотя этот процесс может продолжаться сколь угодно долго, он не приводит к ____________ (**образование**) неограниченного количества денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'образованию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'образованию', 
                          title = '#### Установление максимальной цены приводит к ____________ (**образование**) избыточного спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'образованию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'максимальному увеличению', 
                          title = '#### Выбирайте инвестиционные решения, которые приведут к ____________ ____________ (**максимальный, увеличение**) богатства акционеров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'максимальному увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сокращению', 
                          title = '#### Сокращение конечного потребления в развитых странах привело к ____________ (**сокращение**) импорта из стран-экспортеров потребительской продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сокращению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Внедрение природоохранных технологий и осуществление природоохранных мероприятий на предприятиях и объектах ТЭК восточных районов приведут к ____________ (**снижение**) их вклада в загрязнение окружающей среды к 2030 г. в 1,5-2 раза по сравнению с 2010 г. и к повышению экологической эффективности ТЭК востока страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### При данном росте номинальной денежной массы снижение инфляции ведет к ____________ (**рост**) реальной денежной массы, снижению номинальной ставки процента, увеличению ВВП до естественного уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Введение квоты приводит к ____________ (**повышение**) внутренней цены выше мировой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'исчезновению', 
                          title = '#### Современная НТР неизбежно ведет к ____________ (**исчезновение**) традиционного рабочего класса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'исчезновению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### Поскольку доля доходов от внешнеэкономической деятельности в доходах федерального бюджета в последние годы близка к 40%, в доходах консолидированного бюджета находится на уровне 18-22%, сокращение экспорта российских товаров и услуг приведет к ____________ (**падение**) доходов федерального бюджета и хозяйствующих субъектов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Ужесточение монетарной политики приводит к ____________ (**повышение**) обменного курса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'приведем', 
                          title = '#### В качестве примера ____________ (**привести**) регионы с высоким уровнем инновационного потенциала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'приведем',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потерям', 
                          title = '#### В отношении последнего результата хотелось бы отметить, что таргетирование базовой инфляции ведет к более низким ____________ (**потеря**) благосостояния при LCP, несмотря на существование в этой модели дополнительного источника неэффективности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потерям',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению', 
                          title = '#### Все это привело к ____________ (**изменение**) воспроизводственных процессов в странах мировой периферии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня', 
                          title = '#### Снижение ключевой процентной ставки приводит к повышению ____________ (**уровень**) риска в банковском секторе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### Отмена крепостного права привела к ____________ (**рост**) продуктивности зернового хозяйства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### Падение спроса, вызванное отсутствием крупных международных проектов, приводит к ____________ (**падение**) качества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инфляции', 
                          title = '#### Компенсирование продолжающегося быстрого роста спроса всего лишь приведет к ____________ (**инфляция**), не сопровождающейся высоким реальным ростом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Торговля приведет к ____________ (**снижение**) цены высокотехнологичных товаров и снижению заработной платы высококвалифицированных работников.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Неоднородность товаров и разнообразие потребителей ведут к ____________ (**увеличение**) материального благосостояния.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### Эти операции привели бы к ____________ (**падение**) цен в Лондоне и их повышению в Нью- Йорке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возрастанию', 
                          title = '#### Данный процесс приводит к ____________ (**возрастание**) рисков в финансовой системе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возрастанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'тому', 
                          title = '#### Эффект замЕщения всегда приводит к ____________ (**то**), что покупаемое количество и цена товаров изменяются обратно пропорционально.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'тому',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'системному кризису', 
                          title = '#### Дальнейшее развитие по инерционному пути в новых условиях хозяйствования неизбежно приведет к ____________ ____________ (**системный, кризис**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'системному кризису',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'смЕщению', 
                          title = '#### Изменение одной (или более) из этих детерминант, или факторов изменения предложения, приведет к ____________ (**смещение**) кривой предложения продукта либо вправо, либо влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смЕщению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### Увеличение государственных расходов приводит к ____________ (**рост**) ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возрастанию', 
                          title = '#### Увеличение спроса на заемные средства привело к ____________ (**возрастание**) процентной ставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возрастанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'неправильным методам', 
                          title = '#### Поверхностное представление о причинах инфляции ведет к ____________ ____________ (**неправильный, метод**) борьбы с этим явлением.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'неправильным методам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возрастанию', 
                          title = '#### Кроме того, поскольку снижение уровня безработицы означает, что увеличение числа работников, производящих товары и услуги, при любом заданном уровне цен ведет к ____________ (**возрастание**) объема предложения товаров и услуг, долгосрочная кривая совокупного предложения перемещается вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возрастанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Инвестиционные проекты приводят к ____________ (**увеличение**) амортизируемых активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### При гибких валютных курсах расширительная фискальная политика ведет к ____________ (**увеличение**) ВВП, повышению ставки процента и удорожанию внутренней валюты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'удорожанию', 
                          title = '#### Но основной вывод останется прежним — рост внутренней ставки процента по отношению к иностранной ведет к ____________ (**удорожание**) внутренней валюты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'удорожанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Более высокая ожидаемая инфляция приводит к ____________ (**увеличение**) доходности по альтернативным активам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'результаты оценки', 
                          title = '#### В качестве примера приведем ____________ ____________ (**результат, оценка**) неравенства доходов, задекларированных 29 членами Правительства РФ и 66 сотрудниками Администрации Президента Российской Федерации в 2015 и 2016 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'результаты оценки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'привести', 
                          title = '#### В качестве примера можно ____________ (**привести**) автомобильную отрасль.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'привести',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Несоответствие в квалификации и месте жительства могут приводить к ____________ (**увеличение**) структурной безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Резкие колебания стоимости финансовых активов часто приводят к ____________ (**снижение**) стабильности банковской системы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту', 
                          title = '#### Укрепление курса может приводить к ____________ (**рост**) импорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конкуренции', 
                          title = '#### Сразу отметим роль в «счастливом конце» этой истории Второй поправки и специфической оружейной культуры в США, которая привела к ____________ (**конкуренция**) оружия и на полигонах в самой Америке, и на поле боя во Вьетнаме.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конкуренции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменениям', 
                          title = '#### По мнению автора, в Х–ХIII вв. в Китае начался процесс ранней модернизации, прерванный впоследствии иноземными вторжениями, которые привели к ____________ (**изменение**) политической культуры и деволюции социальных институтов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменениям',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'возрастанию', 
                          title = '#### Международная торговля ведет к ____________ (**возрастание**) экономического благосостояния нации, так как выгода победителей превышает убытки проигравших.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'возрастанию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ухудшению', 
                          title = '#### Высокие темпы роста могут привести к ____________ (**ухудшение**) качества экономического роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ухудшению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Рост совокупного спроса приведет к ____________ (**повышение**) уровня цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'дальнейшему ухудшению', 
                          title = '#### «Утечка мозгов» приведет к ____________ (**дальнейший, ухудшение**) положения страны, которую покидают наиболее квалифицированные работники.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дальнейшему ухудшению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению', 
                          title = '#### Если вы прослушали курс по основам экономической теории, вы знаете, что кривые предложения обычно имеют восходящий наклон, поскольку более высокие цены ведут к ____________ (**увеличение**) производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'большому дефициту', 
                          title = '#### Даже если бы президент Рейган знал, что его политика приведет к ____________ ____________ (**большой, дефицит**) бюджета, он все равно продолжил бы ее.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'большому дефициту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'созданию', 
                          title = '#### Образование ЕС привело к ____________ (**создание**) отдельного экономического порядка в рамках Общего рынка, что не могло не отразиться на мировом экономическом порядке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'созданию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'скачкообразному увеличению', 
                          title = '#### Важным фактором, способным оказать влияние на динамику и структуру внешних взаимодействий Дальнего Востока, как отмечалось в докладе господина Такаси Ядзимы, может стать вступление России в ВТО, которое приведет к ____________ ____________ (**скачкообразный, увеличение**) торгового оборота и насыщению экономического взаимодействия с многочисленными государствами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'скачкообразному увеличению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'пропорциональному изменению', 
                          title = '#### Изменение предложения денег привело бы к ____________ ____________ (**пропорциональнь, изменение**) номинального дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пропорциональному изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### В первые пореформенные десятилетия он придерживался фритредерской доктрины и эволюционировал к протекционизму только к концу 1870-х гг. под влиянием мирового экономического кризиса, который привел к ____________ (**падение**) прежней популярности идей свободной торговли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитию', 
                          title = '#### Новые машины требовали все больших источников энергии, что приводило к ____________ (**развитие**) соответствующих отраслей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'к сокращению', 
                          title = '#### Не решает проблему и экспорт продукции в другие страны, поскольку это может привести ____________ ____________ (**к, сокращение**) частного экспорта сельхозпродукции из данной страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'к сокращению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'приведем', 
                          title = '#### В качестве примера ____________ (**привести**) воду, топливо  и электричество.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'приведем',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширению', 
                          title = '#### Фискальная политика не приводит к ____________ (**расширение**) деловой активности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Построение альтернативных оценок, как и скрупулезный анализ проблем измерения инфляции, может со временем привести к ____________ (**повышение**) доверия к официальным оценкам, что, в свою очередь, может способствовать заякориванию инфляционных ожиданий в России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению', 
                          title = '#### Более высокая ставка процента снижает планируемые инвестиции, что в свою очередь приводит к ____________ (**снижение**) национального дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'существенному росту', 
                          title = '#### Банк России перешел к режиму полностью плавающего курса рубля, что вначале привело к ____________ (**существенный, рост**) его волатильности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'существенному росту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'понижению', 
                          title = '#### Сокращение спроса и объема производства приводит к ____________ (**понижение**) внутренней процентной ставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'понижению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'привести', 
                          title = '#### В качестве примера можно ____________ (**привести**) перераспределение общественного богатства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'привести',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'различным уровням', 
                          title = '#### Системы организации контроля и стимулирования могут приводить к ____________ ____________ (**различный, уровень**) коррупции в рамках государственных институтов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'различным уровням',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению', 
                          title = '#### Установление минимума заработной платы на монопсоническом рынке труда может привести к ____________ (**повышение**) ставок заработной платы, не вызывая безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'созданию', 
                          title = '#### Мировой опыт пространственной концентрации научно-инновационной деятельности очень позитивный и это привело к ____________ (**создание**) в регионах и городах мира глобальной системы основных элементов инновационной и технологической инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'созданию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению', 
                          title = '#### Инфляция приводит к падению реального спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

