```{r}
checkdown::check_question(answer = 'дохода', 
                          title = 'Полярной противоположностью случаю горизонтальной кривой ГМ, который предполагает, что кредитно-денежная политика не может повлиять на уровень ____________ (**доход**), является случай вертикальной кривой ГМ. Кривая ГМ имеет вид вертикали, когда спрос на деньги совершенно нечувствителен к уровню ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'старшего профессора', 
                          title = 'Изменение выигрыша от академической деятельности никак не влияет на выбор ____________ ____________ (**старший, профессор**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'старшего профессора',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на результаты', 
                          title = 'Данный факт позволяет подчеркнуть ключевую особенной байесовской статистики, а именно — возможность учета ранее накопленного опыта. Ранее накопленный опыт никак не влияет ____________ ____________ (**на, результат**) экспериментов, проведенных по «классическому» сценарию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на результаты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'адресата', 
                          title = 'Было замечено лишь то, что брак влияет на выбор ____________ (**адресат**) для самораскрытия: обычно женатые раскрывают меньше информации родителям и друзьям, чем неженатые.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'адресата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'деятельность инновационных компаний', 
                          title = 'Далее представлены основные барьеры, которые негативно влияют на ____________ ____________ ____________ (**деятельность, инновационный, компания**), причем выявлены различия в действии этих барьеров между этапами создания и развития инновационного бизнеса для компаний-лидеров и компаний-последователей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'деятельность инновационных компаний',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = 'Кривая долгосрочного спроса более эластична, чем кривая краткосрочного спроса. Наличие у потребителей большего количества времени на раздумье влияет на ____________ (**цена**), определяя ее тенденцию к усредненной цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'друга', 
                          title = 'Тем не менее общий уровень цифровизации экономики тесно связан с уровнем экономического развития страны, причем они влияют друг на ____________ (**друг**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'друга',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'региональных экономик', 
                          title = 'Все это негативно влияет на развитие ____________ ____________ (**региональный, экономика**), так как образуется замкнутый круг: нехватка инвестиций - низкая капитализация экономического сектора - нехватка инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'региональных экономик',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'текущие расходы', 
                          title = 'Ожидания домохозяйств, связанные с ситуацией на рынках товаров и услуг, также влияют на ____________ ____________ (**текущий, расход**) и на сбережения. В частности, ожидания роста цен ведет к снижению сбережений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'текущие расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = 'Хотя золото и является воспроизводимым благом, его годовая добыча составляет около 2% всего имеющегося количества и поэтому золотопромышленники практически не могут влиять на ____________ (**цена**) своей добычи; она определяется спросом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'отдачи', 
                          title = 'расчеты показали, что фактор возраста негативно влияет на размер ____________ (**отдача**) для специалистов средних и старших возрастов, т.е. получивших советское высшее образование: они зарабатывают сегодня меньше, чем молодежь, закончившая вузы в последние 10-15 лет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отдачи',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных активов', 
                          title = 'Что понимается под инвестиционным рынком и как качество этого рынка влияет на выбор ____________ ____________ (**инвестиционный, актив**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных активов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'компании', 
                          title = 'Отзывы сотрудников влияют на выбор ____________ (**компания**) как места получения опыта работы, поэтому важно, чтобы ее коллектив участвовал в привлечении студентов, например, через информирование.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'компании',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'модели', 
                          title = 'Отраслевые особенности фирмы, характер и формы конкуренции на рынке, уровень специфичности используемых активов влияют на выбор ____________ (**модель**) партнерских взаимодействий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'модели',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'безработицы', 
                          title = 'Мы рассмотрим причины безработицы и увидим, как государственная политика влияет на уровень ____________ (**безработица**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'безработицы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных', 
                          title = 'Изменения предложения денег влияют на величину ____________ (**процентный**) ставок, что, в свою очередь, влияет на инвестиционные расходы и совокупный спрос.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'организации-разработчика', 
                          title = 'Применяемый подход и предпочитаемый тип стратегии неизбежно влияют на выбор ____________ ____________ (**организация, -, разработчик**), на процедуру разработки, обсуждения и утверждения стратегии, на ее сопровождение и конечное использование.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'организации-разработчика',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кредитный риск', 
                          title = 'Способность государства выполнить свои долговые обязательства напрямую влияет на ____________ ____________ (**кредитный, риск**) по ним и определяется динамикой госдолга и активов, которые могут быть использованы для его обслуживания.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кредитный риск',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'друга', 
                          title = 'Существуют сомнения, соответствует ли в принципе концепция контрафактической причинности сложной природе социальных явлений, где все переменные одновременно влияют друг на ____________ (**друг**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'друга',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экспорта', 
                          title = 'Влияние девальвации на чистый экспорт зависит Еще и от фактора времени. Так, в краткосрочном периоде (при исходном чистом нулевом экспорте) понижение обменного курса мало влияет на величину ____________ (**экспорт**) и импорта, а баланс товаров и услуг ухудшается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экспорта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = 'Как качество товаров влияет на спрос? Какие факторы влияют на объем ____________ (**спрос**) и объем предложения?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = 'В итоге ни один фермер и ни один покупатель не могут существенным образом повлиять на ____________ (**цена**) пшеницы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребителей', 
                          title = 'При рассмотрении каждого из этих способов мы проанализируем, насколько при этом увеличивается прибыль фирмы, а также как это влияет на благосостояние ____________ (**потребитель**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребителей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'качество жизни', 
                          title = 'Сложившаяся система организации местного самоуправления напрямую влияет на ____________ ____________ (**качество, жизнь**) сельского населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'качество жизни',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = 'Среди исследователей нет консенсуса о том, как скорость исполнения заявок влияет на изменение ____________ (**цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономические условия', 
                          title = 'Поскольку экономика США является одной из самых передовых, кризис в других странах может негативно повлиять на ____________ ____________ (**экономический, условие**) внутри США.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономические условия',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'результаты работы банка', 
                          title = 'Эти высокие издержки, в свою очередь, негативно влияют на ____________ ____________ ____________ (**результат, работа, банк**): ограничивают рыночный потенциал, снижают доходность и т. д.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'результаты работы банка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = 'Тем самым ожидания влияют на объем ____________ ____________ (**совокупный, спрос**), который важен для динамики зарплат и других затрат компаний в экономике (это в итоге находит отражение в измеряемой инфляции).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'агломерацию', 
                          title = 'Два источника «чистых» (неденежных) экстерналий Маршалла — доступность труда и технологий, или в более современных терминах то, что относится к категориям «обмена», «совмЕщения» и «обучения», — также влияют на ____________ (**агломерация**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'агломерацию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = 'Как политика фискальной экспансии в США влияет на ____________ (**экономика**) стран, которые являются нашими основными торговыми партнерами?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'трансфер', 
                          title = 'Развитие экономики знаний: роль инновационных проектов в программе реиндустриализации региона мер, введение Западом санкций против России существенно влияет на ____________ (**трансфер**) технологий и возможности импорта и экспорта продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'трансфер',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'молодежной', 
                          title = 'Также О. Демидовой и М. Синьорелли было показано, что выделенные факторы по-разному влияют на уровень ____________ (**молодежный**) безработицы в западных и восточных регионах РФ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'молодежной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'благосостояние', 
                          title = 'Результаты подтверждают, что режим гибкого обменного курса в целом лучше влияет на ____________ (**благосостояние**), чем режим фиксированного обменного курса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'благосостояние',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = 'Глобализация хозяйственной деятельности в теории при совершенной конкуренции, равенстве условий положительно влияет на развитие ____________ (**экономика**) отдельных стран и всего мира.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рождаемость', 
                          title = 'В России каждое последующее поколение обладает худшим потенциалом здоровья, чем предыдущее, причем болезни и нездоровье интенсивно перемещаются в сторону детства. Предстоящее вступление в репродуктивный период относительно малочисленных поколений 1990-х годов рождения с худшим здоровьем может негативно повлиять на ____________ (**рождаемость**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рождаемость',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитие', 
                          title = 'Пространство чрезвычайно инерционно, для формирования новых функций регионам требуется длительное время, а разовые инвестиции, даже масштабные, несущественно влияют на ____________ (**развитие**), если они не дополняются устойчивым улучшением институтов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень', 
                          title = 'Кроме фактора удаленности от Москвы одновременно значительное влияние оказывает фактор унаследованных различий: накопленный за предшествующие периоды развития социально-экономический и демографический потенциал характеризуется сильной территориальной неоднородностью, что также влияет на ____________ (**уровень**) цен на жилье в отдельных муниципальных образованиях области.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конкурентоспособности', 
                          title = 'Определены факторы, препятствующие устойчивому экономическому росту макрорегиона, осложняющие инвестиционную политику, влияющие на уровень ____________ (**конкурентоспособность**) экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конкурентоспособности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'человеческого потенциала', 
                          title = 'Подобные тенденции негативно влияют на развитие ____________ ____________ (**человеческий, потенциал**) Сибири и ее городов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'человеческого потенциала',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'трансмиссионные механизмы', 
                          title = 'Добавление в модель межотраслевого взаимодействия между фирмами довольно существенно влияет на ____________ ____________ (**трансмиссионный, механизм**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'трансмиссионные механизмы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'состояние природной среды', 
                          title = 'Формирование градостроительных структур и транспортный менеджмент также существенно влияют на ____________ ____________ ____________ (**состояние, природный, среда**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'состояние природной среды',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'условия бизнеса', 
                          title = 'В условиях интеграции в мировую экономику приток внешних финансовых ресурсов положительно влияет на ____________ ____________ (**условие, бизнес**) и определяет степень доверия к экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'условия бизнеса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень безработицы', 
                          title = 'Предполагается, что выбор той или иной политики способен существенно повлиять на ____________ ____________ (**уровень, безработица**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень безработицы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень инвестиций', 
                          title = 'Помимо этого, мы установили, что компании обрабатывающей промышленности сталкиваются с ограничением ликвидности: ставка процента отрицательно влияет на ____________ ____________ (**уровень, инвестиция**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень инвестиций',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'определение статуса', 
                          title = 'Еще одной проблемой, не имеющей однозначного решения среди экономистов, является установление связи между понятием «экономическая модель» и «экономическая теория», что также влияет на ____________ ____________ (**определение, статус**) экономической модели в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'определение статуса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'результаты', 
                          title = 'Эти изменения не столь велики и несущественно влияют на ____________ (**результат**) расчетов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'результаты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'распределение общественных ресурсов', 
                          title = 'Соотношения расходов показывают относительные приоритеты государственных услуг: местные власти могут существенно влиять на ____________ ____________ ____________ (**распределение, общественный, ресурс**), нежели на местный уровень благосостояния.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'распределение общественных ресурсов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной', 
                          title = 'Рынок совершенной конкуренции — рынок однородного товара с множеством продавцов и покупателей, на котором действия любого из них не влияют на уровень ____________ (**рыночный**) цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'продукции', 
                          title = 'В отличие от отрасли с неизменными затратами, в которой рост выпуска не влияет на цены ____________ (**продукция**) в длительном периоде, в отрасли с возрастающими затратами рост объема выпуска сопровождается повышением цен продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'устойчивой', 
                          title = 'То есть внешние стимулы в достаточной мере влияют на формирование ____________ (**устойчивый**) мотивации к фандрейзинговой деятельности, а значит, внутренняя среда УСО в целом благоприятна для формирования мотивации фандрейзера.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = 'Очевидно, что изменение цены одного товара влияет на объем ____________ (**спрос**) не только данного, но и других товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на труд', 
                          title = 'Кривая спроса на труд не изменится, поскольку данные меры непосредственно не влияют на спрос ____________ ____________ (**на, труд**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на труд',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на поступки', 
                          title = 'Каждый также знает, что его собственное поведение никак не повлияет ____________ ____________ (**на, поступок**) другого человека.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на поступки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиции', 
                          title = 'Кредитно-денежная и фискальная политика влияет на ____________ (**инвестиция**) путем воздействия на желаемую величину капитала, хотя и с длительными задержками.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены сделок', 
                          title = 'Таким образом, закон стоимости, проявляющийся в различиях национальной и интернациональной стоимости производства товаров, непосредственно влияет на ____________ ____________ (**цена, сделка**) мирового рынка и является движущей силой МРТ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены сделок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = 'Не соперничество в установлении цены, а отсутствие возможности влиять на ____________ (**цена**) является ключевым моментом в современной трактовке понятия конкуренции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'со стороны', 
                          title = 'Факторы, которые влияют на спрос ____________ ____________ (**со, сторона**) многих потребителей, также имеют влияние на рыночный спрос.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'со стороны',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'зкономические и финансовые', 
                          title = 'Какие факторы влияют на ____________ ____________ ____________ (**зкономический, и, финансовый**) решения домашних хозяйств?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'зкономические и финансовые',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупную факторную', 
                          title = 'Расходы на НИОКР на душу населения, как и следовало ожидать, положительно влияют на совокупную факторную производительность. Но это нельзя сказать про индекс бюджетных расходов (наблюдается обратная связь): повышение бюджетных расходов негативно влияет на ____________ ____________ (**совокупный, факторный**) производительность при контроле других социально-экономических характеристик.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупную факторную',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = 'Мы увидели, как налог на товар влияет на ____________ (**цена**) и количество проданного товара и как силы спроса и предложения распределяют бремя налогов между покупателями и продавца­ми.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = 'В отношении КИП такой подход неприемлем, так как в силу масштабности потребляемых и выпускаемых ресурсов и продуктов (услуг) возникает «порочная» круговая зависимость (проект влияет на ____________ (**цена**), с помощью которых исчисляется его эффективность), а попытки ее разрыва при оценке приводят к невозможности однозначно предсказать результаты не только в детерминистском, но и в вероятностном смысле.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на объем выпуска', 
                          title = 'Так что в конце концов увеличение экспорта (или бюджетная экспансия) никак не повлияет ____________ ____________ ____________ (**на, объем, выпуск**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на объем выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = 'Например, экономический спад в промышленно развитых странах может катастрофически повлиять на уровень ____________ (**цена**) на сырье, а значит, и на доходы менее развитых стран.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'исследований', 
                          title = 'Различный характер проблемных областей влияет на структуру ____________ (**исследование**) этих двух дисциплин. Обе, как большинство прогностических наук, состоят из двух аналитических частей: одна изображает «нормальное» поведение системы (для его поддержания), другая — отклонения от этого поведения (для осуществления корректировки).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'исследований',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень', 
                          title = 'Какие факторы влияют на ____________ (**уровень**) сбережений домашнего хозяйства?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства', 
                          title = 'Овермен и др. задаются вопросом о том, как география влияет на структуру ____________ (**производство**) в разрезе локаций, а точнее, насколько локализован тот или иной вид экономической деятельности и насколько высок уровень специализации той или иной локации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'это решение', 
                          title = 'Содержательной стороной потребительского поведения являются процесс принятия решения о покупке и то, какие условия и факторы влияют на ____________ ____________ (**этот, решение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'это решение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

