```{r}
checkdown::check_question(answer = 'в государственном секторе', 
                          title = '#### В 1984 г. общий дефицит ____________ (**в, государственный, сектор**) составил 13,6% ВНП, а дефицит по текущим счетам платежного баланса — 5,2% ВНП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в государственном секторе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Каким образом эта налоговая система изменяет реакцию экономики на изменение ____________ (**государственный, расход**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'по государственным облигациям', 
                          title = '#### Предположим, что процентная ставка ____________ (**по, государственный, облигация**) Соединенного Королевства намного выше, чем по государственным облигациям Японии, и они имеют приблизительно одинаковый срок погашения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по государственным облигациям',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### В какой степени изменение ____________ (**государственный, расход**) увеличивает уровень дохода в моделн, включающей рынок активов?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'органами государственной власти субъектов', 
                          title = '#### В каждой программе перед федеральными органами государственной власти, ____________ (**орган, государственный, власть, субъект**) Федерации, органами местного самоуправления ставится задача выявления и оценки рисков мошенничества и коррупции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'органами государственной власти субъектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственные расходы на', 
                          title = '#### В Российской Федерации в 2014 г. ____________ (**государственный, расход, на**) образование составили 3037,3 млрд руб., или 4,3% от ВВП, а на здравоохранение - 2532,7 млрд руб., или 3,5% от ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственные расходы на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'по государственным облигациям', 
                          title = '#### Если правительство сокращает налоги первого периода без сокращения закупок, то оно входит во второй период с долгом ____________ (**по, государственный, облигация**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по государственным облигациям',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Использование фискальной экспансии в виде увеличения ____________ (**государственный, расход**) не всегда возможно, например когда велик государственный долг страны или региона и их бюджет несколько лет подряд исполняется с большим дефицитом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственного участия в', 
                          title = '#### Зафиксированы планы по полному прекращению ____________ (**государственный, участие, в**) капитале «Роснефти».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственного участия в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственное вмешательство в', 
                          title = '#### Чтобы учесть их влияние, спецификация модели должна быть расширена за счет включения переменных, отражающих ____________ (**государственный, вмешательство, в**) процессы распределения ресурсов и результатов производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственное вмешательство в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственные расходы', 
                          title = '#### Если ____________ (**государственный, расход**) выросли на 100 единиц и величина мультипликатора равна 2, то равновесный доход должен увеличиться на 200 единиц при каждом уровне ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'новой модели государственного управления', 
                          title = '#### Краудсорсинг как составляющая ____________ (**новый, модель, государственный, управление**) регионом эффективна, поскольку отдельно взятый госслужащий не обладает знаниями и навыками для решения комплексных задач, стоящих перед современным государством.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новой модели государственного управления',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличение государственных расходов', 
                          title = '#### Если же рассмотреть стимулирующую налогово-бюджетную политику с другой стороны - как ____________ (**увеличение, государственный, расход**), финансируемых за счет государственной задолженности - то вывод будет тем же.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в государственном секторе', 
                          title = '#### При относительном снижении уровня зарплаты ____________ (**в, государственный, сектор**) коррупция увеличивается, однако для существенного сокращения коррупционных отношений зарплату необходимо значительно увеличивать.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в государственном секторе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансирования дефицита государственного бюджета', 
                          title = '#### Еще одним способом ____________ (**финансирование, дефицит, государственный, бюджет**) является выпуск в обращение (эмиссия) дополнительных денег центральным банком, называемый печатанием денег (printing money), или монетизацией бюджетного дефицита.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансирования дефицита государственного бюджета',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственного регулирования территориального развития', 
                          title = '#### Более того, проекты этих законов разрабатываются разными ведомствами, они слабо увязаны друг с другом в идейном и концептуальном планах, хотя и направлены на совершенствование ____________ (**государственный, регулирование, территориальный, развитие**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственного регулирования территориального развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Если кривая М имеет вид вертикали, то увеличение ____________ (**государственный, расход**) не будет оказывать воздействия на величину равновесного дохода и приведет всего лишь к повышению ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственные расходы', 
                          title = '#### Примерами экзогенных переменных могут служить показатели, определяемые экономической политикой государства (такие, как ____________ (**государственный, расход**) или величина предложения денег), цены на нефть и изменения уровня производительности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственного регулирования территориального развития', 
                          title = '#### Тем не менее уже на начальном этапе работы над Стратегией пространственного развития РФ (разработка ее концепции) появилась надежда, что наконец в системе национального стратегирования России появится программный документ, действительно направленный на модернизацию системы ____________ (**государственный, регулирование, территориальный, развитие**), и в том числе на решение проблемы сокращения чрезмерных региональных неравенств в Российской Федерации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственного регулирования территориального развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'органами государственной власти субъектов', 
                          title = '#### Результативность и эффективность действий региональной и муниципальной власти: назначение и возможности корректной оценки в собственность субъектов РФ федерального имущества, необходимого для осуществления ____________ (**орган, государственный, власть, субъект**) РФ переданных им полномочий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'органами государственной власти субъектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственное вмешательство в', 
                          title = '#### Однако прямое ____________ (**государственный, вмешательство, в**) международные операции порождает множество экономических издержек, включая снижение доступа к иностранным товарам и кредитам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственное вмешательство в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'органов государственной власти субъектов', 
                          title = '#### Такие установки зафиксированы в Стратегии научно-технологического развития Российской Федерации, для реализации которой «необходима консолидация усилий федеральных органов государственной власти, ____________ (**орган, государственный, власть, субъект**) Российской Федерации, научно-образовательного и предпринимательского сообществ, институтов гражданского общества по созданию благоприятных условий для применения достижений науки и технологий в интересах социально-экономического развития России».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'органов государственной власти субъектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственные расходы', 
                          title = '#### При вертикальной кривой М увеличение государственных расходов не может изменить уровень равновесного дохода и только лишь увеличивает уровень равновесной ставки процента. Но если ____________ (**государственный, расход**) повысились, а величина выпуска не изменилась, то должно произойти уравновешивающее сокращение частных расходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'исполнительных органов государственной власти', 
                          title = '#### По данным сводного доклада Минрегионразвития России об оценке эффективности деятельности ____________ (**исполнительный, орган, государственный, власть**) субъектов Федерации за 2009 г., Новосибирская область занимает преимущественно средние позиции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'исполнительных органов государственной власти',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственного участия в', 
                          title = '#### Показано различное влияние инфляции на экономический рост в зависимости от уровня ____________ (**государственный, участие, в**) экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственного участия в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственные расходы', 
                          title = '#### Правительство способно путем изменения таких экономических переменных, как ____________ (**государственный, расход**) (G), налоговые поступления (T) и денежная масса (M) добиваться стабилизации развития национальной экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Другим видом шока является увеличение ____________ (**государственный, расход**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Эта таблица показывает мультипликаторы бюджетной политики для стабильного изменения ____________ (**государственный, расход**) или личных подоходных налогов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Дискреционная стимулирующая налогово-бюджетная политика предполагает рост ____________ (**государственный, расход**) и/или снижение налоговых ставок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственные расходы', 
                          title = '#### Если ____________ (**государственный, расход**) не изменяются, то снижение налогов должно в конце концов быть компенсировано ростом налогов в будущем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственные расходы на', 
                          title = '#### Во всех парламентах время от времени ставится вопрос о необходимости увеличить ____________ (**государственный, расход, на**) образование.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственные расходы на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственного вмешательства в', 
                          title = '#### В статье показано, как изменялась малайзийская экономика, как происходило влияние внешних колебаний на внутреннюю экономическую ситуацию, а также описан процесс ____________ (**государственный, вмешательство, в**) случае возникновения непредвиденных внешних факторов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственного вмешательства в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'полномочий органов государственной власти', 
                          title = '#### В отдельных федеральных законах раскрыто содержание ____________ (**полномочие, орган, государственный, власть**) субъектов РФ, однако полномочия очевидно не равнозначны конкретным задачам, которые ставятся федеральными органами государственной власти перед органами государственной власти субъектов РФ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'полномочий органов государственной власти',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'исполнительных органов государственной власти', 
                          title = '#### Действительно, согласно ч. 2 ст. 26.3 Федерального закона «Об общих принципах организации законодательных (представительных) и ____________ (**исполнительный, орган, государственный, власть**) субъектов Российской Федерации» к полномочиям указанных органов относятся: организация и осуществление межмуниципальных программ и проектов в области охраны окружающей среды и экологической безопасности; дорожная деятельность в отношении автомобильных дорог межмуниципального значения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'исполнительных органов государственной власти',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных закупок товаров', 
                          title = '#### Величина ____________ (**государственный, закупка, товар**) и услуг является политической переменной и поэтому, как правило, экзогенной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных закупок товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов на', 
                          title = '#### В состав выгод провинциального и федерального правительств включались налоговые отчисления, специальные сборы на возмещение ____________ (**государственный, расход, на**) инфраструктуру (surcharges), а также общественные выгоды, исчисляемые на базе теневых цен трудовых ресурсов и иностранной валюты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Бюджетные дефициты США 80-х гг. не были результатом значительного роста ____________ (**государственный, расход**) на капитальные блага, такие как дороги и школы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных закупок товаров', 
                          title = '#### Мультипликатор действует в обе стороны: при росте автономных расходов (в нашем случае ____________ (**государственный, закупка, товар**) и услуг) совокупный доход мультипликативно увеличивается, при уменьшении автономных расходов совокупный доход мультипликативно сокращается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных закупок товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Таким образом, прирост ____________ (**государственный, расход**), сопровождаемый равноценным приростом налоговых поступлений, увеличивает уровень равновесного дохода точно на величину прироста расходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Изменение в фискальной политике часто называют фискальным сжатием, или фискальной консолидацией (увеличение дефицита — вследствие роста ____________ (**государственный, расход**) или вследствие снижения налогов — называется фискальной экспансией).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'федеральной службы государственной статистики', 
                          title = '#### Число заболевших по одному классу болезней определено по статистическим данным Территориального органа ____________ (**федеральный, служба, государственный, статистика**) по Иркутской области за 2008-2010 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'федеральной службы государственной статистики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Кейнсианцы считали, что экономику можно стабилизировать путем увеличения ____________ (**государственный, расход**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственных расходов', 
                          title = '#### Однако сокращение ____________ (**государственный, расход**) на образование приводит к его коммерциализации и повышению доли платного обучения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственного вмешательства во', 
                          title = '#### Свободная торговля предполагает политику минимального ____________ (**государственный, вмешательство, в**) внешнюю торговлю, регулируемую рыночным спросом и предложением, снижая барьеры товарообмена.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственного вмешательства во',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

