```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Необходимо иметь представление о том, какие виды деятельности генерируют основной объем денежных поступлений и оттоков. Анализ движения ____________ (**денежный, средство**) позволяет определить сальдо денежного потока в результате текущей, инвестиционной и финансовой деятельности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Функция совокупного спроса, которая показывает, как инфляция и темп роста ____________ (**денежный, масса**) воздействуют на рост ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Инфляция и реальные запасы ____________ (**денежный, средство**) в Германии в период между I И II мировыми войнами. На данном графике показана динамика инфляции и запасов денежных средств в реальном выражении у населения Германии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Ставки денежно-кредитной политики и ставки ____________ (**денежный, рынок**) в большинстве стран мира следуют за динамикой краткосрочной ставки в США.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежный поток', 
                          title = '#### Именно чистый ____________ (**денежный, поток**) является основой оценки эффективности деятельности предприятия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежный поток',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Термин real money balances на русский язык обычно переводится как реальные денежные остатки. Мы используем другой вариант перевода - запасы ____________ (**денежный, средство**) в реальном выражении, ибо под "остатками" в нашей экономической литературе чаще всего подразумевают остаток средств на счете в банке. Поэтому употребление термина денежные',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Функцией финансового рынка является обеспечение движения ____________ (**денежный, средство**) от собственников (кредиторов) к заемщикам, т. е. перераспределение финансовых ресурсов между субъектами хозяйствования и отраслями экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные средства', 
                          title = '#### Количественная теория денег гласит, что номинальный объем ВНП пропорционален денежной массе, или, что то же самое, спрос на ____________ (**денежный, средство**) в реальном выражении пропорционален реальному объему ВНП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные средства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Изменение объема ____________ (**денежный, масса**) влияет на экономику преимущественно путем изменения процентных ставок, которые в свою очередь воздействуют на совокупный спрос и, следовательно, на ВНП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Вероятно запасы ____________ (**денежный, средство**) в реальном выражении приходят в соответствие с издержками хранения денег на руках постепенно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Рост ____________ (**денежный, масса**) вызывает рост инфляции, а последняя приводит к увеличению ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### К 2019 г. удельный вес в показателях РФ численности населения, производства ВРП и продукции реального сектора макрорегиона сократился на 0,5-0,9%, доли инвестиций и ____________ (**денежный, доход**) населения остались на прежнем уровне.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### Величина прожиточного минимума за рассматриваемый период росла медленнее, чем среднедушевые ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Если уровень безработицы близок к естественному, существует ли риск, что увеличение ____________ (**денежный, масса**) приведет к сокращению безработицы ниже естественного уровня и к росту инфляции?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Взаимные фонды ____________ (**денежный, рынок**) представляют собой фонды, которые вкладывают свои активы в приносящие проценты краткосрочные ценные бумаги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного потока', 
                          title = '#### В нормальной ситуации, когда деятельность компании экономически целесообразна, ожидаемые процентные платежи как для прогнозного, так и для будущего периодов не превышают свободного ____________ (**денежный, поток**) на фирму.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного потока',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных потоков', 
                          title = '#### Накопление финансового запаса позволяет повысить финансовую устойчивость фирмы за счет полной или частичной ликвидации отрицательных ____________ (**денежный, поток**) под воздействием неблагоприятных внешних и внутренних факторов: колебаний спроса, недобросовестности поставщиков и т. п.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### По сравнению с началом кризиса реальные располагаемые ____________ (**денежный, доход**) населения края уменьшились на 4,2%. Удорожание жизни привело к росту численности населения, живущего за чертой бедности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Все показатели оборачиваемости используются для определения скорости движения ____________ (**денежный, средство**) по различным текущим счетам предприятия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### Растет реальная ____________ (**денежный, масса**), что ведет к сдвигу кривой LM вниз.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Кредитно-денежная политика при фиксированном валютном курсе оказывается неэффективной, поскольку попытки изменить величину ____________ (**денежный, масса**) нейтрализуются необходимыми интервенциями на валютном рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Рэнкинг регионов СФО по отношению ____________ (**денежный, доход**) населения к стоимости фиксированного набора потребительских товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Как объяснить взаимосвязь между ростом ____________ (**денежный, масса**) и инфляции, которые наблюдались после 1980 г.?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### От краткосрочной перспективы мы переходим к условно наиболее долгосрочной перспективе, в которой скорость роста ____________ (**денежный, масса**) является и будет являться постоянной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### объемы ВРП прямо зависят от величины освоенных в регионе инвестиций и ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Уменьшение запасов ____________ (**денежный, средство**) в реальном выражении при любом данном объеме производства вызывает снижение k и увеличение V.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### В результате реальная ____________ (**денежный, масса**) возрастает. Процентные ставки будут снижаться, а совокупный спрос и объем выпуска в результате этого возрастать.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Исходным понятием для законодательства о финансовых рынках становится национальное и транснациональное движение ____________ (**денежный, средство**) от инвестора к реципиенту инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Указано распределение городского и сельского населения по величине среднедушевых ____________ (**денежный, доход**) и располагаемых ресурсов в месяц.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежными доходами', 
                          title = '#### Доля населения с ____________ (**денежный, доход**) ниже прожиточного минимума.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежными доходами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### начали снижаться, оно снова увеличилось. Вместе с тем, вразрез с выводами нашего теоретического анализа, это увеличение не было скачкообраз- ным.Вероятно запасы ____________ (**денежный, средство**) в реальном выражении приходят в соответствие с издержками хранения денег на руках постепенно. А может быть населению Германии потребовалось определенное время на то, чтобы',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Есть оценка потоков ____________ (**денежный, средство**) инвестиционного проекта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Потоки ____________ (**денежный, средство**) в экономике регулируются самостоятельно без политических решений по этому вопросу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### В период 2005-2011 гг. в Тюменской области наблюдался рост номинальных среднедушевых ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Изучение условий равновесия на денежном рынке позволяет получить равновесную ставку процента (цена денег) и равновесную величину ____________ (**денежный, масса**). Изменения на денежном рынке прямо связаны с состоянием рынка товаров и услуг. Рынок ресурсов в макроэкономических моделях представлен рынком труда и рынком капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### В третьем разделе отчета -- движение ____________ (**денежный, средство**) в результате финансовой деятельности — зафиксировано, что корпорация выплатила 10 мян долл. своим акционерам в качестве дивидендов в денежной форме и получила заем в размере 94,6 млн долл.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### В 2010 г. возобновилась многолетняя тенденция роста реальных ____________ (**денежный, доход**) населения Алтайского края.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Рост душевых ____________ (**денежный, доход**) населения и пенсий и пособий будет несколько опережать рост заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Распределение населения по размеру среднедушевых ____________ (**денежный, доход**) и располагаемых ресурсов показывает высокую долю среди сельских жителей крайне бедных и малоимущих.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Вы видели, что в краткосрочном периоде снижение номинальной ____________ (**денежный, масса**) ведет к более низкому ВВП и более высокой безработице в течение какого-то времени.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Кредитная система служит мощным фактором концентрации и централизации капитала, способствующим быстрой мобилизации свободных ____________ (**денежный, средство**) и их использованию в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### Теперь увеличивается номинальная ____________ (**денежный, масса**) и соответственно кривая совокупного спроса перемещается вверх и вправо до АР’. Если бы цены были фиксированы, экономика передвинулась бы в точку Е’, точку кейнсианского равновесия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Разница между темпом роста номинальной ____________ (**денежный, масса**) и уровнем инфляции влияет на темп роста ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Сильный экономический спад последовал за решением председателя ФРС Волкера сократить темп прироста ____________ (**денежный, масса**) в 1979 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Потоки ____________ (**денежный, средство**) поступают в последний день периода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в денежной форме', 
                          title = '#### Есть стремление измерить ____________ (**в, денежный, форма**) дефицит рабочей силы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в денежной форме',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Теория человеческого капитала описывает прямые и косвенные вложения ____________ (**денежный, средство**) в образование и профессиональную подготовку работников, что приводит в будущем к более высокой оплате труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### Индекс промышленного производства к 2000 г. составил по краю 53,6%, инвестиции в основной капитал — 91,8%, реальные ____________ (**денежный, доход**) — 96%, реальная заработная плата — 91%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Если темп роста номинальной ____________ (**денежный, масса**) превышает инфляцию, то темп роста реальной денежной массы положительный и темп роста ВВП также.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### Произошла трансформации роли валютного канала ____________ (**денежный, трансмиссия**) в новейшей истории России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Показатель финансового капитала формирует представление об остатке свободных ____________ (**денежный, средство**), на которые могут рассчитывать собственники.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Равновесие переместится из Е в Е’, что приведет к более высокому уровню цен и выпуска. Таким образом, увеличение ____________ (**денежный, масса**) приведет и к более высоким ценам, а не только к более высокому выпуску.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Как в каждой стране высокая инфляция была связана с соответственно высоким ростом номинальной ____________ (**денежный, масса**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в денежной форме', 
                          title = '#### В то же время следует отметить, что российская сторона все же получает определенные средства от инвесторов — регулярные платежи (роялти), которые рассчитываются в процентном отношении от объема добычи минерального сырья или стоимости произведенной продукции и уплачиваются инвестором ____________ (**в, денежный, форма**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в денежной форме',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в денежном выражении', 
                          title = '#### Рабочие получают на 65% меньше заработной платы, чем их предельный продукт ____________ (**в, денежный, выражение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в денежном выражении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Увеличение темпа инфляции ведет к росту номинальной ставки процента, что, в свою очередь, вызывает сокращение запасов ____________ (**денежный, средство**) в реальном выражении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### В краткосрочном периоде увеличение номинальной ____________ (**денежный, масса**) ведет к сдвигу кривой LM вниз до LM ′.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Улучшение экономической ситуации в крае в 1999 г. способствовало повышению ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### В целом за 2010-2013 гг. отток ____________ (**денежный, средство**) из компании составил 156,7 млрд руб.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Если потоки ____________ (**денежный, средство**) выражаются в реальных показателях, то ставка дисконта также должна быть выражена через реальные показатели.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Долгосрочная связь между темпом роста ____________ (**денежный, масса**) и инфляцией в долгосрочном плане не является строго определенной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Выражение обозначает изменение реальных остатков, разницу между темпом прироста ____________ (**денежный, масса**) и темпом инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### Валютный канал ____________ (**денежный, трансмиссия**) носит глобальный характер и подвержен эффектам прямой и обратной связи со стороны внешнего мира. Особенное значение это имеет для стран с формирующимся рынком.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Ожидаемое изменение скорости роста ____________ (**денежный, масса**) вообще никак не влияет на уровень выпуска, а воздействует только на инфляцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Рост уровня цен меньше роста номинальной ____________ (**денежный, масса**), реальное предложение денег растет, понижая реальные процентные ставки и увеличивая совокупное количество товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Изменение скорости роста ____________ (**денежный, масса**) сместит кривую совокупного спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Для анализа используют три вида отчетов: отчет о прибылях и убытках, отчет о движении ____________ (**денежный, средство**) и балансовый отчет. Каждый из этих отчетов, составленных по расчетным данным проекта, характеризует его с разных точек зрения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные потоки', 
                          title = '#### Вывод справедлив только в там случае, если все будущие ____________ (**денежный, поток**) положительны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные потоки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Сокращение ____________ (**денежный, масса**) снижает внутренний уровень цен и повышает номинальный обменный курс на столько же процентов, на сколько сокращается предложение денег в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежном рынке', 
                          title = '#### Изучение условий равновесия на ____________ (**денежный, рынок**) позволяет получить равновесную ставку процента (цена денег) и равновесную величину денежной массы. Изменения на денежном рынке прямо связаны с состоянием рынка товаров и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежном рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Инвестиционная активность является отражением инвестиционной деятельности как процесса вложения ____________ (**денежный, средство**) иидругих инструментов втобъекты предпринимательской деятельности для получения прибыли и/или иного полезного результата.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Отрицательный денежный поток в данном случае означает, что происходит отток ____________ (**денежный, средство**) из компании «Томскнефть» с использованием действующих механизмов корпоративного управления - в основном за счет выплачиваемых акционерам дивидендов, сумма которых в последние три года сопоставима с общим объемом инвестиций за этот же период.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Рост национального дохода ведет к росту спроса на реальные запасы ____________ (**денежный, средство**) точно так же, как он приводит к росту спроса на автомобили.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Изменение темпа роста номинальной ____________ (**денежный, масса**) не влияет на ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### По сравнению с 2000 г. в 2007 г. реальные ____________ (**денежный, доход**) населения и реальная заработная плата выросли в 2,1 раза.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### Видимое различие уровня инфляции отражается в возможностях выбора режима валютного курса странами, а также роли валютного канала ____________ (**денежный, трансмиссия**) в них.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### Отсюда следует простой вывод: при снижении номинальной денежной массы в 1929—1933 гг., почти пропорциональном снижению уровня цен, реальная ____________ (**денежный, масса**) оставалась почти постоянной, устраняя один из механизмов, который мог бы привести к восстановлению экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### В среднесрочном периоде уровень инфляции должен быть равен разнице между темпом роста номинальной ____________ (**денежный, масса**) и нормальным темпом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Центральный банк может объявить целевой диапазон, а не целевую точку — диапазон, внутри которого он намеревается удерживать рост номинальной ____________ (**денежный, масса**) в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Они утверждают, что рост ____________ (**денежный, масса**) неизменно ведет к инфляции и что поддержание умеренного роста денежной массы является единственным способом избежать инфляции в долгосросном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'выражении', 
                          title = '#### За основу средней производительности труда на уровне фирмы экономисты взяли объем продаж в денежном ____________ (**выражение**) за год в расчете на одного «годового» работника.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выражении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных', 
                          title = '#### В целевом варианте прогноза до 2035 г. темпы прироста ВВП в 2021-2025 гг. предполагаются на уровне 4%, среднегодовой прирост реальных ____________ (**денежный**) доходов населения составит 4,5%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### В краткосрочной перспективе изменения скорости роста ____________ (**денежный, масса**) воздействуют как на уровень выпуска, так и на инфляцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### В долгосрочной перспективе устойчивое изменение темпов роста ____________ (**денежный, масса**) ведет к изменению роста инфляции и номинальной процентной ставки в том же направлении и на ту же величину.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### В период 1992-2021 гг. параметры работы валютного канала ____________ (**денежный, трансмиссия**) в России существенно трансформировались.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Если темп роста номинальной ____________ (**денежный, масса**) превышает инфляцию, то темп роста реальной денежной массы положительный и темп роста ВВП также. Если темп роста номинальной денежной массы меньше инфляции, то темп роста реальной денежной массы и темп роста ВВП отрицательные. Другими словами, при данном уровне инфляции стимулирующая монетарная политика (высокие',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Мы рассматривали воздействие увеличения темпа роста ____________ (**денежный, масса**) на ставки процента и инфляцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### На графике показана динамика инфляции и запасов ____________ (**денежный, средство**) в реальном выражении у населения Германии в период с января 1922 по декабрь 1924 г. По мере роста темпа инфляции запасы денег на руках сокращались.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Какое воздействие окажет увеличение номинальной ____________ (**денежный, масса**) на товарный рынок?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Видим отношение среднедушевых ____________ (**денежный, доход**) населения к стоимости фиксированного набора потребительских товаров и услуг (стоимость потребительской корзины).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежными доходами', 
                          title = '#### Доля населения с ____________ (**денежный, доход**) ниже величины прожиточного минимума, установленной в субъекте РФ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежными доходами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### В основе такого результата лежат корректировки на рынке труда: как фирмы, так и рабочие знали, что ____________ (**денежный, масса**) и совокупный спрос возрастут, и соответственно номинальная заработная плата повысится в той же пропорции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Если экономика испытывает рецессию, центральный банк может повысить темп роста номинальной ____________ (**денежный, масса**) выше его среднесрочного значения, с тем чтобы допустить снижение ставки процента и ускорить восстановление ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Увеличение реальной ____________ (**денежный, масса**) вызывает сдвиг кривой LM вниз и вправо, из положения LM1 в положение LM2.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Рост ____________ (**денежный, масса**) является следствием дефицита государственного бюджета.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Если темп роста номинальной ____________ (**денежный, масса**) превышает инфляцию, то темп роста реальной денежной массы положительный и темп роста ВВП также. Если темп роста номинальной денежной массы меньше инфляции, то темп роста реальной денежной массы и темп роста ВВП отрицательные.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Похожая финансовая структура была использована при построении модели для исследования совместного влияния динамики благосостояния фондов, потоков ____________ (**денежный, средство**) и уровня левериджа на волатильность активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Прирост ____________ (**денежный, масса**) вызывает рост общего уровня цен, изменяя их структуру.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Все три зависимости определяют воздействие роста номинальной ____________ (**денежный, масса**) на рост ВВП, безработицу и инфляцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Обратимся к спросу на запасы ____________ (**денежный, средство**) в реальном выражении. Люди держат на руках деньги, потому что деньги являются "ликвидным" активом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### В 2020 году соотношение среднедушевых ____________ (**денежный, доход**) населения с величиной прожиточного минимума по области составило 2,3 раза (14 694,9 рубля), в 2019 году – 2,5 раза (15 274,7 рубля).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### Реальные располагаемые ____________ (**денежный, доход**) населения на товары и услуги в Алтайском крае выросли в 2008-2010 гг. на 36,4%, по России в среднем - на 34,1%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Теперь рассмотрим равновесие ____________ (**денежный, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной', 
                          title = '#### Валютный канал ____________ (**денежный**) трансмиссии в России характеризуется двумя ключевыми этапами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Приносящие проценты вклады размером более 100 000 дол. Сюда не включаются вклады взаимных фондов ____________ (**денежный, рынок**) и взаимных фондов банков (и некоторых других институтов), чтобы предотвратить двойной счет одного и того же актива в денежных агрегатах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### В 2020 году реальные располагаемые ____________ (**денежный, доход**) населения уменьшились на 2,4% по сравнению с 2019 годом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### После корректировки уровня цен на 10% увеличение номинальной ____________ (**денежный, масса**) в итоге не оказало воздействия на объем производства или реальную процентную ставку.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Изменение ____________ (**денежный, масса**) в краткосрочном периоде повлияет на реальные переменные, например выпуск, Еще до того, как цены получат шанс приспособиться.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### В 2008 г. средняя номинальная заработная плата в экономике страны увеличилась по сравнению с предшествующим годом. Однако это не существенно отразилось на условиях воспроизводства человеческого потенциала, так как душевые ____________ (**денежный, доход**) населения ниже и составляют примерно 0,8 от уровня заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### В отчете о движении ____________ (**денежный, средство**) отображаются поступление и расходование денежных средств фирмы за определенный период времени, чем он и отличается от отчета о финансовых результатах, в котором фиксируются все доходы и расходы компании.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Термин real money balances на русский язык обычно переводится как реальные денежные остатки. Мы используем другой вариант перевода - запасы ____________ (**денежный, средство**) в реальном выражении, ибо под "остатками" в нашей экономической литературе чаще всего подразумевают остаток средств на счете в банке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Первоначально более высокий рост номинальной ____________ (**денежный, масса**) ведет к росту ВВП. Проходит некоторое время, прежде чем этот рост денежной массы отразится в инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Экономическая ценность рассчитывается как номинальная оценка будущего притока ____________ (**денежный, средство**) в «настоящих» деньгах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### В целом рецессия ведет к снижению инфляции. При данном росте номинальной ____________ (**денежный, масса**) снижение инфляции ведет к росту реальной денежной массы, снижению номинальной ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежную массу', 
                          title = '#### Рост цен уменьшает реальную ____________ (**денежный, масса**) и ведет к росту ставки процента и уменьшению расходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежную массу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### Нейтральность денег означает, что номинальная ____________ (**денежный, масса**), цены и валютный курс возрастают в одной и той же пропорции, так что реальная денежная масса и относительные цены не изменяются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных единицах', 
                          title = '#### Чтобы найти размер вклада работника в общий доход фирмы, мы должны перевести предельный продукт труда (который измеряется в центнерах яблок) в стоимость предельного продукта (измеряемую в ____________ (**денежный, единица**)).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных единицах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### Целью исследования является определение с учетом релевантного опыта зарубежных стран влияния работы валютного канала ____________ (**денежный, трансмиссия**) на монетарную политику России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Давайте рассмотрим налично-денежную экономику, в которой реальный выпуск и реальная ставка процента имеют фиксированные значения, а темпы роста ____________ (**денежный, масса**) и инфляции постоянны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок', 
                          title = '#### объемы ВРП прямо зависят от величины освоенных в регионе инвестиций и денежных доходов населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### В результате в добывающих отраслях раньше аккумулируются доходы от реализации продукции, идет процесс накопления свободных ____________ (**денежный, средство**), которые могут стать источником инвестиций для других проектов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных', 
                          title = '#### Структура данной модели подходит для изучения совместного влияния на динамику финансового рынка потоков ____________ (**денежный**) средств и поведенческих особенностей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Вы видели, как рост ____________ (**денежный, масса**) ведет в результате снижения ставок процента к росту расходов и ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Компаниям не хватает свободных ____________ (**денежный, средство**) для погашения кредитов, и связано это главным образом с отрицательной динамикой торговли: задержками платежей, падением объемов продаж и снижением спроса на продукцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежную массу', 
                          title = '#### Рост номинальной денежной массы увеличивает реальную ____________ (**денежный, масса**) при каждом уровне цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежную массу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Когда фирма снижает назначаемую ею цену, тем самым она слегка снижает общий уровень цен и, таким образом, увеличивает запасы ____________ (**денежный, средство**) в реальном выражении, что ведет к росту совокупного дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Речь идет о целесообразности вложения ____________ (**денежный, средство**) в те или иные активы и их соотношении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### В целом по РФ реальные ____________ (**денежный, доход**) населения уменьшились на 1,4%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### В этот же период произошло снижение реальных ____________ (**денежный, доход**) населения российского Дальнего Востока и реальной начисленной заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Как мы увидим, изме­нение объема ____________ (**денежный, масса**) приводит к сдвигу кривой совокупного спроса. Сейчас же просто помните о том, что каждая конкретная кривая совокупного спроса изображается для конкретно заданного количества денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Падение реальных ____________ (**денежный, доход**) населения Дальнего Востока произошло за счет опережающих темпов роста розничных цен на товары и услуги по сравнению со среднероссийскими.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'трансмиссии', 
                          title = '#### Обзор исследований показывает, что существенный вклад в изучение валютного канала денежной ____________ (**трансмиссия**) в широком смысле в настоящее время вносит Банк Международных расчетов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Снижение темпа роста номинальной ____________ (**денежный, масса**) ведет к более низкому росту ВВП и более высокой безработице.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежную массу', 
                          title = '#### Но если ВВП не меняется, то уменьшит реальную ____________ (**денежный, масса**) и сдвинет кривую LM вверх.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежную массу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Портфельные инвестиции – это вложения ____________ (**денежный, средство**) с целью извлечения дохода и диверсификации рисков, а не получения права контроля за объектом инвестирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Кривая LM отражает спрос на запасы ____________ (**денежный, средство**) и предложение денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### Среднемесячная номинальная начисленная заработная плата в округе стабильно низкая - 37 807 руб. (в РФ - 43 724 руб.), а среднедушевые ____________ (**денежный, доход**) населения составляют 25 642 руб.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### В целом по РФ реальные денежные доходы населения по сравнению с предыдущим годом снизились на 1,3%. Однако это меньше, чем за аналогичный период 2016 г., когда падение реальных ____________ (**денежный, доход**) было на уровне 5,6%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Нужно достигать жестких целей по инфляции в краткосрочном периоде путем снижения темпов прироста ____________ (**денежный, масса**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Предположим, что такой рост реальной ____________ (**денежный, масса**) ведет к снижению номинальной ставки процента, скажем, с 7% до 6%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежную', 
                          title = '#### Процентные ставки были низкими и денежная экспансия была масштабной, но недостаточной, для того чтобы компенсировать рост спроса на ____________ (**денежный**) массу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежную',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Более высокий рост номинальной ____________ (**денежный, масса**) ведет к увеличению сеньоража.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Результаты показывают, что сокращение ____________ (**денежный, масса**) в США также ведет к рецессии и за границей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### Реальная ____________ (**денежный, масса**) выросла на 2%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Если деньги нейтральны, рост или сокращение ____________ (**денежный, масса**) изменяет уровень цен в той же пропорции, но не оказывает никакого влияния на реальные переменные, такие как выпуск, занятость или реальная ставка процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Международные разногласия в вопросе подходящего темпа роста ____________ (**денежный, масса**) создавали серьезную угрозу существованию системы фиксированных валютных курсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Вызывающий доверие центральный банк — это такой банк, которому верит население; когда банк, обычно через своего председателя, оглашает свое намерение снизить темп роста ____________ (**денежный, масса**) и инфляцию',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Более высокий темп роста ____________ (**денежный, масса**) приводит к более низкой номинальной ставке процента в краткосрочной перспективе и к более высокой номинальной ставке процента в среднесрочной перспективе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Крах был усугублен большой ошибкой в политике, а именно значительным уменьшением номинальной ____________ (**денежный, масса**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Предположим, что неожиданный рост ____________ (**денежный, масса**) увеличивает совокупный спрос и поднимает цены выше ожидаемого уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Изменение ____________ (**денежный, масса**) приводит к изменению ВВП через механизм распределения инвестиционных расходов, которые зависят от динамики процентной ставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'доходами', 
                          title = '#### Доля населения с денежными ____________ (**доход**) ниже величины прожиточного минимума составила 24,2%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доходами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Увеличение скорости роста ____________ (**денежный, масса**) ведет к большей инфляции и росту выпуска, но темп инфляции увеличивается медленнее скорости роста денежной массы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в денежной форме', 
                          title = '#### Если фирма наймет трех человек, то мы обнаружим, что предельный продукт ____________ (**в, денежный, форма**) равен 400 руб., а заработная рабочего -- 300 руб.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в денежной форме',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Долгосрочное отношение между темпом роста ____________ (**денежный, масса**) и инфляцией должно быть приблязительно 1:1, за исключением случаев изменения скорости обращения денег, не связанных с ростом дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Рассмотрим взаимные фонды ____________ (**денежный, рынок**) (money market mutual funds, MMMFs), которые стали популярными в конце 1970х гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Величина взаимных фондов ____________ (**денежный, рынок**) возросла с нуля в ноябре 1982 г. до 320 млрд дол. в марте 1983 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### В некоторых теоретических работах валютный канал ____________ (**денежный, трансмиссия**) определяется как канал международной торговли (international trade-based channel of transmission mechanism).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Регулирование потоков ____________ (**денежный, средство**) составляет основу макроэкономической политики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Составляя предварительные отчеты о финансовых результатах за определенный период, балансы и отчеты о движении ____________ (**денежный, средство**) для своей компании в целом, менеджеры могут контролировать взаимосвязь отдельных планов, и оценивать суммарные потребности фирмы в финансовых средствах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Финансы хозяйствующих субъектов – это система денежных отношений, связанных с формированием и использованием капитала и доходов, денежных фондов в процессе кругооборота ____________ (**денежный, средство**) в виде различных денежных потоков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Уравнение можно использовать для анализа инфляции, т.е. выяснения того, в какой степени она происходит из-за изменений в скорости обращения денег, в какой — из-за темпа роста ____________ (**денежный, масса**) или расширения объема выпуска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Какой темп роста номинальной ____________ (**денежный, масса**) ведет к наибольшему сеньоражу и сколько сеньоража он создает? Это вопросы, которые Филипп Кейган задавал в классической статье о гиперинфляциях, написанной в 1956 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### объем ____________ (**денежный, средство**) субъектов РФ незначителен и составляет 6 % от общей стоимости всех реальных инвестиционных проектов, возникших на основе государственно-частного партнерства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### На основе теории предпочтения ликвидности объясняются равновесие ____________ (**денежный, рынок**) и финансового рынка в целом и последствия изменения этого равновесия вследствие проведения монетарной политики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Основным инструментом для достижения цели по инфляции является ключевая ставка, которая оказывает влияние на формирование ставок ____________ (**денежный, рынок**), что передается в динамику процентных ставок по кредитам и депозитам и других финансовых показателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Кривая LM сдвигается вверх: при данном уровне ВВП уменьшение реальной ____________ (**денежный, масса**) ведет к росту ставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Напомним, что, если спрос на деньги настолько нестабилен, что кривая LM случайным образом двигается туда и сюда, изменение ____________ (**денежный, масса**) с целью сохранения постоянных процентных ставок ведет к более стабильному совокупному спросу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Зависимость количества денег на руках у населения от номинальной ставки процента затрудняет борьбу с инфляцией, так как при прекращении инфляции запасы ____________ (**денежный, средство**) в реальном выражении увеличатся.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Рост номинальной ____________ (**денежный, масса**) увеличивает реальную денежную массу при каждом уровне цен. На рынке активов ставка процента уменьшается, вынуждая людей держать более высокий уровень реальных балансов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Ситуация усугубляется тем, что по итогам 2017 г. отмечалось сокращение реальных ____________ (**денежный, доход**) россиян.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### Одним из индикаторов, характеризующих реальные ____________ (**денежный, доход**) населения, является отношение денежных доходов населения к стоимости фиксированного набора товаров и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Ключевыми параметрами прогнозных расчетов предложены показатели ВРП, инвестиций в основной капитал и ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### В 1995–2015 гг. реальные ____________ (**денежный, доход**) населения увеличились на 224,1%. В номинальном выражении доходы населения РФ в 2000–2015 гг. выросли в 13 раз.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Существенны различия в уровне среднедушевых ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Правительство обязано проводить предсказуемую монетарную политику, поддерживать обоснованный постоянный прирост ____________ (**денежный, масса**) в обращении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Если фактический темп инфляции ниже оптимального, то увеличение ____________ (**денежный, масса**) приведет к росту сеньоража. При повышении темпов инфляции следствием подобной политики будет увеличение инфляции и снижение реального сеньоража.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Как мы показали, долгосрочная нейтральность денег подразумевает, что сокращение номинальной ____________ (**денежный, масса**) на 10% снизит внутренний уровень цен на 10%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Мы получили первую группу результатов: первоначально более низкий темп роста номинальной ____________ (**денежный, масса**) снижает темп роста ВВП и увеличивает безработицу. Увеличение безработицы ведет к снижению инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в денежной форме', 
                          title = '#### Предприятия несут социальную ответственность перед населением региона не только ____________ (**в, денежный, форма**) (непосредственно через выплату заработной платы работникам и всему населению — опосредованно, через налоговый механизм), но также и в безденежной форме через предоставление населению социальных услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в денежной форме',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Основной функцией финансового рынка является перераспределение свободных ____________ (**денежный, средство**) от экономических субъектов, имеющих их избыток, к субъектам с дефицитом денежных средств.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Темп роста номинальной ____________ (**денежный, масса**) должен быть таким, чтобы совокупный спрос и соответственно ВВП росли нормальным темпом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### По официальным данным, реальные располагаемые ____________ (**денежный, доход**) населения области сократились за 2009 г. на 8,4%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Население участвует в формировании централизованных фондов ____________ (**денежный, средство**) посредством уплаты налогов, друтих платежей, носящих обязательный характер.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных', 
                          title = '#### Основной причиной пониженных душевых показателей потребления на территории СФО стали, по-видимому, пониженные темпы роста заработной платы и ____________ (**денежный**) доходов в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### В Новосибирской области за этот период статистика зарегистрировала более высокие темпы роста заработной платы и ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Взаимные фонды ____________ (**денежный, рынок**) могут устанавливать минимальный размер чеков, выписываемых на вклад.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Противоречие может также возникать из-за различий в распределении общей суммы притока ____________ (**денежный, средство**) во времени, даже если два проекта имеют одинаковую величину исходных инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Страхование — система экономических отношений, которые включают совокупность форм и методов формирования целевых фондов ____________ (**денежный, средство**) и их использование на возмЕщение материального и иного ущерба физическому или юридическому лицу за счет средств страховой организации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Величина номинальной ____________ (**денежный, масса**) сезонно проциклична.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массой', 
                          title = '#### Сочетание снижения налогов с манипулированием ____________ (**денежный, масса**) и процентной ставкой позволяет поддерживать стабильное функционирование рыночного механизма.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Опережающий рост цен определил и более низкие темпы роста реальных ____________ (**денежный, доход**) населения, которые за период 1995—2007 гг. выросли в 3,8 раза.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Для восстановления внешнего равновесия Центральный банк вынужден воздействовать на величину ____________ (**денежный, масса**) в обратном направлении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Определите цели вложения ____________ (**денежный, средство**) в ценные бумаги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Кривая AD наклонена вниз, потому что рост уровня цен приводит к снижению объема реальной ____________ (**денежный, масса**), что вызывает сдвиг кривой LM вверх и влево; снижение объема реальной денежной массы приводит к увеличению реальной процентной ставки, что вызывает снижение спроса на товары домашних хозяйств и фирм.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Для предотвращения экономического кризиса необходимо снизить темпы роста ____________ (**денежный, масса**) до 3–4% в год; уменьшить размеры государственного сектора и сократить госрасходы, в том числе и на социальные нужды.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Рост реальных ____________ (**денежный, доход**) превысил программные установки на 1,7%, при этом реальная заработная плата выросла на 7,8%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные средства', 
                          title = '#### В процессе движения фондов у одних товаропроизводителей образуются свободные ____________ (**денежный, средство**) в виде заработной платы, прибыли, амортизационных отчислений, а также доходы населения и госбюджета, в которых нуждаются другие экономические субъекты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные средства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных', 
                          title = '#### Традиционной моделью привлечения ____________ (**денежный**) средств для жилищного строительства в России в постсоветский период является долевое финансирование (на основе договоров долевого участия -- ДДУ).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной', 
                          title = '#### При высокой доле государства в банковской сфере положение банка целиком определяется его возможностью поучаствовать в государственных финансовых потоках. Таким образом, механизм ____________ (**денежный**) трансмиссии в России все более значительно опосредуется государством.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Влияние может быть как прямым (в виде валютной интервенции), так и косвенным (через регулирование объема ____________ (**денежный, масса**) и процентных ставок).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### блюдаем сегодня в Европе или в США, рост номинальной ____________ (**денежный, масса**) ведет к небольшому сокращению реальных кассовых остатков. Таким образом, более высокий рост номинальной денежной массы ведет к увеличению сеньоража. Однако когда темп роста номинальной денежной массы (и, следовательно, инфляции) очень высок, уменьшение реальных кассовых остатков, вызванных',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Необходимо иметь резерв свободных ____________ (**денежный, средство**) для решения неожиданно возникающих инвестиционных задач.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных', 
                          title = '#### Сравнительная динамика роста заработной платы по сибирским субъектам Федерации идентична динамике ____________ (**денежный**) доходов в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Мы объясним, каким образом изменения объема ____________ (**денежный, масса**) воздействуют на процентные ставки, совокупный спрос и экономику в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного', 
                          title = '#### Эффективность отражается величиной чистого ____________ (**денежный**) потока по планируемым периодам (квартал, год): чистая прибыль, плюс амортизационные отчисления (от стоимости введенных основных средств), минус объем инвестиций, в том числе и на потребности в оборотном капитале.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### генерируемые потоки наличных ____________ (**денежный, средство**) в сфере услуг пассажирских автотранспортных перевозок сложно отследить.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Вторая крупнейшая категория активов состоит из взаимных фондов ____________ (**денежный, рынок**) и депозитных счетов. Взаимные фонды денежного рынка представляют собой фонды, которые вкладывают свои активы в приносящие проценты краткосрочные ценные бумаги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Увеличение темпа роста ____________ (**денежный, масса**) смещает кривую совокупного спроса вверх, увеличивая инфляцию и выпуск. Эти измеиения, в свою очередь, вызывают сдвиг вверх кривых предложения и спроса в следующем периоде, что повышает темп инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'средств', 
                          title = '#### Имущественная обеспеченность, в частности обеспеченность собственными автомобилями и жильем, отражает долгосрочное вложение денежных ____________ (**средство**) и, как следствие, уровень реальных доходов населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Финансы всегда имеют денежную форму выражения и отражают отношения посредством реального движения ____________ (**денежный, средство**) и создания специализированных фондов денежных средств.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### В долгосрочном периоде деньги нейтральны; соответственно сокращение ____________ (**денежный, масса**) не окажет никакого влияния на реальный валютный курс, но оно все же вызовет падение уровня цен внутри страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в денежной форме', 
                          title = '#### В этом случае предельный продукт труда ____________ (**в, денежный, форма**) составит 300 руб.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в денежной форме',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### В целом по РФ реальные ____________ (**денежный, доход**) населения по сравнению с предыдущим годом снизились на 1,3%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Скорость роста ____________ (**денежный, масса**) возрастает до более высокого уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Можно ожидать, что спрос на запасы ____________ (**денежный, средство**) в реальном выражении будет зависеть от номинальной ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Вклад заработной платы в повышение ____________ (**денежный, доход**) населения превысил 50,0% и привел к снижению численности работающих бедных.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### К глобальным каналам относится валютный канал ____________ (**денежный, трансмиссия**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### При оценке притока ____________ (**денежный, средство**) по годам может возникнуть проблема в отношении последних лет реализации проекта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Ситуация усугубляется тем, что начиная с 2014 г. отмечается падение реальных ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Поэтому Милтон Фридмен и Анна Шварц доказывали, что за глубину депрессии ответственной была ФРС: она не была напрямую ответственна за снижение номинальной ____________ (**денежный, масса**), но она должна была принять меры, чтобы перекрыть снижение денежного мультипликатора расширением денежной базы в намного большей степени, чем она это сделала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Тем не менее, на данном уровне обсуждения можно увидеть, что объем номинальной ____________ (**денежный, масса**) напрямую связан с уровнем цен, при прочих равных условиях.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Показатель среднедушевых ____________ (**денежный, доход**) имеет определенные дефекты: часть доходов регистрируется не по месту проживания получателя, а по месту выплаты, часть их может быть получена от сделок с вторичными активами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной', 
                          title = '#### Накопленный объем данных позволяет проанализировать изменение работы валютного канала ____________ (**денежный**) трансмиссии в России после перехода к режиму инфляционного таргетирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Рост ____________ (**денежный, масса**) ведет к более низкой ставке процента. Более низкая ставка процента ведет к увеличению инвестиций и — через мультипликатор — к увеличению спроса и ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежном рынке', 
                          title = '#### Представлены последствия изменений на товарном и/или на ____________ (**денежный, рынок**), характеризуемые в краткосрочном периоде изменениями величины реального совокупного выпуска (реального ВВП).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежном рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежный поток', 
                          title = '#### Кроме того, величина чистого денежного потока во многом зависит от платежеспособности покупателей. Если она низка, то и чистый ____________ (**денежный, поток**) самого рентабельного предприятия окажется невелик.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежный поток',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Во втором разделе отображено движение ____________ (**денежный, средство**) в связи с инвестиционной деятельностью, и мы видим, что в течение 2021 г. корпорация GPC затратила 90 млн долл. на приобретение новых заводских.помЕщений и оборудования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Приведите примеры потоков ____________ (**денежный, средство**) по текущей, инвестиционной и финансовой видам деятельности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### На Дальнем Востоке существенно более важное значение в формировании ____________ (**денежный, доход**) населения имеет заработная плата.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Необходимо стремиться к сбалансированию бюджета и поддержанию темпов прироста ____________ (**денежный, масса**) в обращении в соответствии с реальными возможностями увеличения производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'массы', 
                          title = '#### Изменение объема денежной ____________ (**масса**) приведет к расширению объема производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные потоки', 
                          title = '#### Мы разобрались, как фирмы оценивают будущие ____________ (**денежный, поток**) и решают, исходя из полученных цифр, стоит ли им инвестировать в долгосрочные капитальные активы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные потоки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### Таким образом, на основании данных п. 3.1.1 – 3.1.6 диссертации получено несколько выводов о трансформации роли валютного канала ____________ (**денежный, трансмиссия**) в новейшей истории России (таблица 31). В течение всего периода прослеживается либерализация режима валютного курса: от неконвертируемой денежной единицы с 1992 г., узкого',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### В результате снижения ключевой ставки в 2016-2017 гг. проценты на межбанковском рынке уменьшились, а реальная ____________ (**денежный, масса**) во II кв. 2017 г. увеличилась по сравнению с I кв. 2016 г. примерно на 4%, т.е. весьма незначительно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в денежном выражении', 
                          title = '#### За 2013 г. выездной туризм вырос количественно на 24% и ____________ (**в, денежный, выражение**) - на 18%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в денежном выражении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### В начале 1990-х гг. ухудшение системы социальных гарантий и сокращение реальных ____________ (**денежный, доход**) населения Российской Федерации привели к возникновению бедности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Первоначально более высокий рост номинальной ____________ (**денежный, масса**) ведет к росту ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Если рост номинальной ____________ (**денежный, масса**) является более высоким, чем величина, которая максимизирует сеньораж, то этот рост приведет к снижению сеньоража.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### Увеличение номинальной денежной массы полностью нейтрализовано пропорциональным ростом уровня цен. Следовательно, реальная ____________ (**денежный, масса**) не изменилась.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежную массу', 
                          title = '#### В точке Е” и номинальная денежная масса, и уровень цен изменились в одной и той же пропорции, оставив реальную ____________ (**денежный, масса**) и, следовательно, ставку процента и совокупный спрос неизменными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежную массу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных потоков', 
                          title = '#### Для дисконтирования ____________ (**денежный, поток**) по инвестиционным проектам в электроэнергетике, как правило, используется ставка 10%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежном рынке', 
                          title = '#### Монетарная экспансия, обеспечивающая преодоление кризиса, осуществляется посредством неуклонного расширения предложения на ____________ (**денежный, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежном рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные доходы', 
                          title = '#### Реальные ____________ (**денежный, доход**) населения в ценах базового года.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные доходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежными доходами', 
                          title = '#### Доля лиц с ____________ (**денежный, доход**) ниже величины прожиточного минимума после активного периода сокращения (2000-2012 гг.) седьмой год остается больше средней по стране: 15,7% на Дальнем Востоке против 12,6% в целом по РФ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежными доходами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### С другой стороны, если иностранные инвесторы утратят доверие к экономической или политической стабильности, быстрый увод принадлежащих иностранцам ____________ (**денежный, средство**) из страны может привести к болезненному периоду.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежный поток', 
                          title = '#### Для растущей компании типична ситуация, когда свободный ____________ (**денежный, поток**) в течение ряда лет имеет отрицательное значение. С точки зрения собственника, это означает отрицательную текущую доходность.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежный поток',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### В условиях плавающих валютных курсов увеличение ____________ (**денежный, масса**) ведет к росту дохода и обесценению национальной валюты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### 5. Номинальная ставка процента характеризует размеры издержек по хранению денег на руках. Таким образом, можно ожидать, что спрос на запасы ____________ (**денежный, средство**) в реальном выражении будет зависеть от номинальной ставки процента. Зависимость количества денег на руках у населения от номинальной ставки процента затрудняет борьбу с инфляци-',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежными доходами', 
                          title = '#### Наиболее распространенный в Российской Федерации показатель уровня бедности — доля населения с ____________ (**денежный, доход**) ниже величины прожиточного минимума.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежными доходами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### К положительным сдвигам можно отнести высокие темпы прироста среднедушевых ____________ (**денежный, доход**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'средств', 
                          title = '#### Распределение экономического эффекта, получаемого в результате миграции, происходит в форме роста доходов мигрантов, переводов денежных ____________ (**средство**) из-за рубежа на родину.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### В открытой экономике валютный канал ____________ (**денежный, трансмиссия**) закономерно является частью работы глобального механизма денежной трансмиссии и транслирует изменения, происходящие в мировой экономике, в национальную.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Целями вложения ____________ (**денежный, средство**) в ценные бумаги являются: получение дохода, сохранность капитала и его рост, а также расширение сферы влияния, получение доступа к ценным',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Предположим, что спрос на реальные запасы ____________ (**денежный, средство**) зависит скорее от уровня потребления, чем от совокупных расходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в денежном выражении', 
                          title = '#### Предельный продукт фактора ____________ (**в, денежный, выражение**) показывает прирост общего дохода в результате использования Еще одной (дополнительной) единицы переменного фактора L.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в денежном выражении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Так как реальное предложение денег не меняется, темп роста номинальной ____________ (**денежный, масса**) должен равняться темпу роста уровня цен, или уровню инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Наоборот, если безработица упадет ниже 5%, то темп прироста ____________ (**денежный, масса**) может стать ниже 4%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### Если ____________ (**денежный, масса**) растет быстрее, чем цены, то реальные остатки увеличиваются, и если реальная денежная масса растет медленнее цен, то реальные остатки уменьшаются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной', 
                          title = '#### В целом получается, что центральные банки сегодня мыслят иначе, перейдя от категорий роста номинальной ____________ (**денежный**) массы к правилу ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Предпосылка о постоянстве скорости обращения эквивалентна предположению о том, что спрос на реальные запасы ____________ (**денежный, средство**) зависит только от уровня дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежная масса', 
                          title = '#### Вслед за избранием Франклина Делано Рузвельта в 1933 г. произошли изменения в монетарной политике и драматический рост номинальной денежной массы. С 1933 по 1946 г. она выросла на 40%, а реальная ____________ (**денежный, масса**) — на 100%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежная масса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Монетарная теория считает одним из основных средств регулирования экономики изменение ____________ (**денежный, масса**) и процентных ставок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### Сокращение реальных ____________ (**денежный, доход**) населения произошло во всех федеральных округах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Формы хранения денег, такие как срочные вклады, сберегательные вклады, взаимные фонды ____________ (**денежный, рынок**), или же наличность и чековые вклады, имеют с точки зрения дохода одинаковые степени риска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Должно ли небольшое увеличение уровня безработицы вести к небольшому повышению темпов роста ____________ (**денежный, масса**) или политика не должна реагировать до тех пор, пока прирост безработицы не будет значительным, скажем, более 1%?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Увеличение ____________ (**денежный, масса**) приведет к увеличению как уровня выпуска, так и уровня цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Со временем уровень цен повышается, что ведет к сокращению реальной ____________ (**денежный, масса**) до тех пор, пока ВВП не вернется на свой естественный уровень.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных', 
                          title = '#### Никогда нe используйте номинальную процентную ставку при дисконтировании реальных ____________ (**денежный**) потоков или реальную процентную ставку при дисконтировании номинальных денежных потоков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Отчет о движении ____________ (**денежный, средство**) позволяет избежать оценки доходов и расходов исключительно на основе показателей, вошедших в отчеты о финансовых результатах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Воздействие на экономику оказывает изменение объема номинальной ____________ (**денежный, масса**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Рисунок показывает процесс подстройки ВВП и уровня цен в ответ на увеличение номинальной ____________ (**денежный, масса**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### В течение следующих четырех лет монетарная политика направлена на поддержание безработицы на уровне 8%, а не на дальнейшее увеличение безработицы. Темп роста номинальной ____________ (**денежный, масса**) должен быть таким, чтобы совокупный спрос и соответственно ВВП росли нормальным темпом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных потоков', 
                          title = '#### Для дисконтирования ____________ (**денежный, поток**) по инвестиционным проектам в электроэнергетике, как правило, используется процентная ставка в размере 10%',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежные потоки', 
                          title = '#### Сокращать параметры проекта имеет смысл в том случае, если ____________ (**денежный, поток**) в процессе его реализации имели отрицательное значение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежные потоки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Подумайте о последствиях связей между ростом ____________ (**денежный, масса**) и ростом ВВП — со всеми этими вопросами центральный банк сталкивается, принимая решения о том, увеличить ли и на сколько предложение денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### ляет собой отношение между инфляции, и g mt — темп роста номинальной ____________ (**денежный, масса**) в момент време- двумя переменными, то темп роста переменной равен раз-  ни t. Тогда из уравнения (9.6) следует, что',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Чему будет равен общий прирост ____________ (**денежный, масса**) в стране, если при обязательной резервной норме 10% первоначальное увеличение депозитов составило 200 млн. долл.?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных доходов', 
                          title = '#### К положительным сдвигам можно отнести более высокие по сравнению с прожиточным минимумом темпы прироста среднедушевых ____________ (**денежный, доход**) населения, что в условиях низкого уровня инфляции должно обеспечить рост реальных денежных доходов населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных доходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного потока', 
                          title = '#### От прибыли, определяемой разностью между выручкой от продажи продукции и затратами ее производства, следует отличать величину чистого ____________ (**денежный, поток**) (net cash flow), определяемую разностью между денежными поступлениями и платежами предприятия за определенный период времени (месяц, год).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного потока',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Чтобы уравновесить рынок запасов ____________ (**денежный, средство**) в реальном выражении, ставка процента должна возрасти с г± до г2.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Поддержание низкого и стабильного темпа роста ____________ (**денежный, масса**) должно привести к низкой инфляции, стабильному объему выпуска и росту занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной', 
                          title = '#### Особенности работы валютного канала ____________ (**денежный**) трансмиссии в странах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной', 
                          title = '#### Нужно достигать жестких целей по инфляции в краткосрочном периоде путем снижения темпов прироста ____________ (**денежный**) массы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Давайте посмотрим на потоки ____________ (**денежный, средство**) с точки зрения экономических агентов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Из-за жесткости цен кейнсианская модель предсказывает, что увеличение темпа роста ____________ (**денежный, масса**) приведет к более высокой инфляции только после некоторого лага, когда фирмы начинают корректировать свои цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежного рынка', 
                          title = '#### Рост цен на сырье может вызывать падение премии за риск для российской экономики, что, в свою очередь, приводит к падению ставки ____________ (**денежный, рынок**) и некоторому укреплению российской валюты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Объем номинальной ____________ (**денежный, масса**) напрямую связан с уровнем цен, при прочих равных условиях.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'форме', 
                          title = '#### Если предельные издержки на приобретение фактора больше, чем его предельный продукт в денежной ____________ (**форма**), для максимизации прибыли фирме следует уменьшить количество данного фактора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'форме',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Цели прямых инвестиций отличаются от целей портфельных инвестиций, при которых инвесторы обычно и не стремятся оказывать влияние на управление предприятием. Портфельные инвестиции – это вложения ____________ (**денежный, средство**) с целью извлечения дохода и диверсификации рисков, а не получения права контроля над объектом инвестирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### Играет меньшую роль валютный канал ____________ (**денежный, трансмиссия**) в странах с режимом инфляционного таргетирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Неожиданное изменение ____________ (**денежный, масса**) в краткосрочном периоде не является нейтральным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной трансмиссии', 
                          title = '#### Стерилизованные валютные интервенции можно использовать на регулярной основе в режиме таргетирования инфляции, если центральный банк использует их только для нормализации работы валютного канала ____________ (**денежный, трансмиссия**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной трансмиссии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'массы', 
                          title = '#### При низких темпах роста номинальной денежной ____________ (**масса**), таких как мы наблюдаем сегодня в Европе или в США, рост номинальной денежной массы ведет к небольшому сокращению реальных кассовых остатков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Достижение целевого уровня темпа роста ____________ (**денежный, масса**) считается наиболее важной задачей центрального банка.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежный рынок', 
                          title = '#### Кривая равновесия денежного рынка показывает все сочетания ставки процента и уровней дохода, при которых спрос на реальные балансы равен их предложению.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежный рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежной массы', 
                          title = '#### Такой прирост ____________ (**денежный, масса**) вызывает деловую активность в экономике, а выше этого уровня возникает инфляция.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежной массы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'денежных средств', 
                          title = '#### Мировой инвестиционный рынок представляет собой глобальный механизм долгосрочного зарубежного вложения временно свободных ____________ (**денежный, средство**) с целью получения дохода в будущем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'денежных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

