
```{r}
checkdown::check_question(answer = stringr::str_split('цифра 4,84 означает, что; компания в последнем квартале; выплатила акционерам дивиденды в; размере 4,84 доллара на одну акцию', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цифра 4,84 означает, что; компания в последнем квартале; выплатила акционерам дивиденды в; размере 4,84 доллара на одну акцию',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('основная часть доходов; поступает от приватизации,; вторая по величине; статья поступления — дивиденды по акциям', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'основная часть доходов; поступает от приватизации,; вторая по величине; статья поступления — дивиденды по акциям',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('определенный процент от доходной; части фонда направляется на; выплату дивидендов всем жителям; как долевым собственникам на землю и природные ресурсы', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'определенный процент от доходной; части фонда направляется на; выплату дивидендов всем жителям; как долевым собственникам на землю и природные ресурсы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('поскольку фирма планирует; выплачивать 30% своей; чистой прибыли в; качестве дивидендов, акционерный капитал увеличится', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'поскольку фирма планирует; выплачивать 30% своей; чистой прибыли в; качестве дивидендов, акционерный капитал увеличится',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('компания выплатила; акционерам дивиденды; в размере; 3 доллара на одну акцию', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'компания выплатила; акционерам дивиденды; в размере; 3 доллара на одну акцию',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'дивидендов', 
                          title = '#### Люди, покупающие акции, ожидают получить доход в виде ____________ (**дивиденды**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дивидендов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'дивидендов', 
                          title = '#### Рассчитаем темп роста ____________ (**дивиденды**) и затем применим модель дисконтирования дивидендов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дивидендов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'выплату дивидендов', 
                          title = '#### Определенный процент от доходной части фонда направляется на ____________ (**выплата, дивиденд**) всем жителям как долевым собственникам на землю и природные ресурсы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выплату дивидендов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'дивидендов', 
                          title = '#### Домохозяйства получают трудовой доход и процентный доход в виде ____________ (**дивиденды**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дивидендов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'дивиденды по акциям', 
                          title = '#### Основная часть доходов поступает от приватизации, вторая по величине статья поступления — ____________ (**дивиденд, по, акция**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дивиденды по акциям',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```
