```{r}
checkdown::check_question(answer = 'налога на добавленную', 
                          title = '#### Вторая часть Налогового кодекса РФ регулирует порядок уплаты отдельных налогов, например, ____________ (**налог, на, добавить**) стоимость, налога на прибыль, страховых взносов, налога на имущество и т.д.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налога на добавленную',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'удельной добавленной стоимости', 
                          title = '#### Функционирование и механизмы развития производственного кластера с уровнем ____________ (**удельный, добавить, стоимость**) ниже среднего более высоко оценивают системы стандартов (как отечественные, так и международные), а также позитивность влияния крупного бизнеса и благоприятность правовой среды.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'удельной добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'доля добавленной стоимости', 
                          title = '#### ВРП - это более общий показатель, демонстрирующий, какая ____________ (**доля, добавить, стоимость**) тратится на вложения в основные средства, т.е. на накопление капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доля добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокой добавленной стоимостью', 
                          title = '#### В статье обоснованы направления роста доли перерабатывающего сектора Казахстана в общей структуре промышленного производства и выпуска товарной продукции с ____________ (**высокий, добавить, стоимость**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокой добавленной стоимостью',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'добавленной стоимости', 
                          title = '#### Необходимо увеличить в структуре экспорта удельный вес товаров с высокой долей ____________ (**добавить, стоимость**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'структуре валовой добавленной стоимости', 
                          title = '#### Анализ показал, что регионы с высокой долей добычи полезных ископаемых в отраслевой ____________ (**структура, валовой, добавить, стоимость**) занижают положительную корреляцию среднедушевого ВРП с долей городского населения по регионам России по причине более высокого роста экономики при незначительном изменении уровня урбанизации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'структуре валовой добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'долей добавленной стоимости', 
                          title = '#### Существенная часть выбросов СО2 производится предприятиями с невысокой ____________ (**доля, добавить, стоимость**) и объектами ЖКХ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'долей добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стоимостью', 
                          title = '#### Превращение угольной отрасли из отрасли, добывающей сырье, в отрасль, производящую инновационную продукцию означает организацию в Кемеровской области предприятий по производству из угля (и метана угольных пластов) продукции с высокой добавленной ____________ (**стоимость**) и последующее перепрофилирование региона из центра добычи угля в центр переработки традиционных углеводородов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стоимостью',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'доли добавленной стоимости', 
                          title = '#### В методиках Инвестиционного фонда предлагается рассчитывать косвенные эффекты при помощи расчета ____________ (**доля, добавить, стоимость**), произведенной благодаря реализации проекта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доли добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'доля добавленной стоимости', 
                          title = '#### В индикаторах второй группы влиянию региональных удорожаний подвержены и числитель, и знаменатель (доля инвестиций в ВРП, ____________ (**доля, добавить, стоимость**) в выпуске и др.), и их совместное влияние на уровень индикатора проявляется слабее.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доля добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'создания добавленной стоимости', 
                          title = '#### Было показано, что цепочка создания ценности в компании является элементом отраслевой системы ____________ (**создание, добавить, стоимость**) (отраслевой бизнес-системы) и внутри этой системы возможна «миграция ценностей» от одного участника к другому.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'создания добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокой долей добавленной стоимости', 
                          title = '#### Китайский лесной экспорт включает в себя преимущественно товары с ____________ (**высокий, доля, добавить, стоимость**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокой долей добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'долей добавленной стоимости', 
                          title = '#### Рассмотрим агрегированную отраслевую структуру промышленности, выделив три группы отраслей: отрасли с высокой ____________ (**доля, добавить, стоимость**) (пищевая, легкая, химическая и нефтехимическая промышленность, машиностроение, промышленность строительных материалов), добывающие отрасли (топливная, лесная промышленность, черная и цветная металлургия), а также электроэнергетику.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'долей добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'структуре валовой добавленной стоимости', 
                          title = '#### На территории этих регионов не развит промышленный сектор, в ____________ (**структура, валовой, добавить, стоимость**) значительная доля приходится на государственное управление, образование и здравоохранение, которые финансируются из бюджета.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'структуре валовой добавленной стоимости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

