```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Переезды скорее всего обусловлены поиском лучшей работы, более высокой ____________ (**заработный, плата**), более комфортных условий жизни, лучшего доступа к социальной инфраструктуре, возможностей получить образование.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### Часто искать подрядчиков для аутсорсинга транснациональные корпорации стремятся не в развитых странах, а в развивающихся, где имеются хорошо подготовленные специалисты, готовые с большой отдачей работать за невысокую ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### Понятие средней квалификации имеет различные определения: может ассоциироваться с работниками, получающими среднюю ____________ (**заработный, плата**), но чаще – с полученным образованием.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Можно увидеть, что эластичность фонда ____________ (**заработный, плата**) регионов по основным фондам регионов примерно одинакова для всех групп регионов, хотя наибольшей величины она достигает в европейской части России, и что исключение из расчета мегаполисов несколько уменьшает величину этого коэффициента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### В модели MPS, например, заработная плата реагирует только на текущую и прошлую инфляцию и на текущую безработицу. Но если предположить, что агенты, устанавливающие ____________ (**заработный, плата**), имеют рациональные ожидания, подстройка произойдет гораздо быстрее.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Это приводит к увеличению абсолютного размера оплаты труда в республике, но если сопоставить размер ____________ (**заработный, плата**) и прожиточного минимума в Якутии, то получится примерно средний по стране показатель, а это говорит о достаточно высокой стоимости жизни в республике, что обусловлено во многом издержками жизни в экстремальных природных условиях.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### По своему номинальному значению минимальная ____________ (**заработный, плата**) неуклонно росла в течение последних 60 лет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### Если рассматривать данный показатель в региональном разрезе, то в 2009 г. он достигал максимума в следующих субъектах Федерации: Республика Тыва — 96 %, Республика Ингушетия — 85 % и Республика Алтай — 81 %, т. е. в экономически слаборазвитых регионах, где среднемесячная ____________ (**заработный, плата**) составляет менее 70 % от средней заработной платы по стране.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Примером могут служить действия профсоюзов, члены которых в целом получают значительно больше минимума ____________ (**заработный, плата**), в поддержку повышения минимального уровня заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Условием выживания части отечественных предприятий (в разных регионах различного количества) является не только предельно низкий уровень ____________ (**заработный, плата**), но и несвоевременность выплат.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Найдя подобные точки для разных ставок ____________ (**заработный, плата**), мы получим кривую спроса на труд монополиста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### В этом разделе мы расскажем, как теория эффективной ____________ (**заработный, плата**) (efficiency wage theory) объясняет безработицу и дискриминацию в области заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Постоянный уровень реальной ____________ (**заработный, плата**) является допустимой аппроксимацией действительного характера изменений заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### Эффект дохода возникает из-за того, что более высокая ____________ (**заработный, плата**) работников увеличивает их покупательную способность.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платой', 
                          title = '#### Мы показываем кривую Филлипса как взаимосвязь между ____________ (**заработный, плата**) текущего периода, заработной платой прошлого периода и фактическим уровнем занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Все внутренние затраты фирмы (на выплату ____________ (**заработный, плата**), амортизацию, аренду капитала, аренду помещения и др.), а также прибыль фирмы включаются в добавленную стоимость.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Другим основанием для критики является тот факт, что минимум ____________ (**заработный, плата**) мало влияет на снижение уровня бедности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### даемого уровня инфляции, π te , и от уровня безработи- цы, u t . Он также зависит от надбавки µ, от факторов, влияющих на установление ____________ (**заработный, плата**) z, и от воздействия уровня безработицы на заработную плату 187Инфляция,',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Действительно, имеется широкое разнообразие программ, включая положения “специально для лета”, которые предусматривают снижение минимальной ____________ (**заработный, плата**) в летние месяцы на 25% с целью уменьшения влияния минимальной заработной платы на подростковую безработицу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной плате', 
                          title = '#### Для дарвинисткой модели характерны доминирование частных предприятий, стремящихся максимизировать краткосрочные прибыли для инвесторов, низкий уровень профсоюзного движения, децентрализованные переговоры по ____________ (**заработный, плата**), ограниченное трудовое законодательство.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной плате',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### < Уравнение (13.6) показывает, что при данном уровне безработицы ре- альная заработная плата, определяемая отношением установления ____________ (**заработный, плата**), также выше на 5%: кривая установления заработной платы сдвигается вверх. < Заметим, что при исходном уровне безработицы, u n , обе кривые сдви-',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Основная часть населения занята в сельском хозяйстве, для которого традиционно характерен низкий уровень ____________ (**заработный, плата**) по сравнению с другими отраслями».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### В настоящее время преградой на пути развития рынка явился спрос. На него наталкивается предложение. Спрос должен формировать предложение. Но он не соответствует возможностям предложения. В значительной мере это происходит от низкой ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Эффект уровня оценивает те различия в заработной плате, которые могут быть обусловлены наличием в регионах более высокой или более низкой ____________ (**заработный, плата**) в отдельных кластерах, чем национальная средняя заработная плата для этих кластеров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### Для некоторых рабочих, профессия которых больше уже не требуется в экономике, структурные сдвиги могут на самом деле означать безработицу или более низкую ____________ (**заработный, плата**), или и то, и и другое.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Означает ли это в таком случае, что досуг является «товаром Гиффена»? Ответ должен быть отрицательным, так как в случае спроса на досуг увеличение цены (т. е. повышение ____________ (**заработный, плата**)) применимо не только к тому, что покупает покупатель, но и к тому, что он продает, т. е. к его труду.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Инфляция имеет и социальные последствия, она ведет к перераспределению национального дохода, является как бы сверхналогом на население, что обусловливает отставание темпов роста номинальной, а также реальной ____________ (**заработный, плата**) от резко возрастающих цен на товары и услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Поскольку в структуре затрат доля ____________ (**заработный, плата**) увеличилась почти до 60%, вызывает тревогу «консервация» доли капитальных затрат, связанных с приборным обеспечением центров коллективного пользования и созданием уникальных установок, без чего невозможны развитие научных кадров и получение результатов мирового уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Профсоюзы не только способствуют росту ____________ (**заработный, плата**), но и укрепляют позиции рабочих в ходе переговоров по многим другим вопросам, таким как продолжительность рабочего дня и условия труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### рах, зависит от ожидаемого уровня цен, P e , уровня безработицы, u, и парамет-. ра z, отражающего влияние всех остальных факторов, которые могут воздей- ствовать на установление ____________ (**заработный, плата**), — от пособий по безработице до форм коллективных договоров. n Цена P, устанавливаемая фирмой (соответственно уровень цен), равна',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### При любой другой величине ____________ (**заработный, плата**), отличной от E , равновесие на рынке труда нарушается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Без индексации ____________ (**заработный, плата**) более низкая безработица ведет к повышению заработной платы, что, в свою очередь, повышает цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Bмеет место отрицательная взаимосвязь между темпами роста и заработной платой, поскольку более низкий уровень ____________ (**заработный, плата**) способствует ускоренному накоплению капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### Кривая долгосрочного совокупного предложения основана на допущении о том, что номинальная ____________ (**заработный, плата**) является фиксированной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платой', 
                          title = '#### Давайте посмотрим, как экономические издержки отличаются от бухгалтерских в случае с ____________ (**заработный, плата**) и экономической амортизацией благодаря альтернативным издержкам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### В настоящее время объем среднедушевого ВРП по субъектам Федерации различается в 67 раз, а средняя ____________ (**заработный, плата**) - в 6 раз.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### С ростом затрат на производство на Тайване многие из них начали переносить свое производство в страны с более низким уровнем ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Рост безработицы ведет к снижению ____________ (**заработный, плата**) ниже стоимости рабочей силы, которая делает невыгодным применение машин.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### При увеличении среднемесячной ____________ (**заработный, плата**) в среднем по стране на 13,2% (до 21 тыс. руб.) в ММО рост составил всего 9,3% (до 17,6 тыс. руб.).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Сколько работников будет нанимать фирма, если существующая ставка ____________ (**заработный, плата**) равна 27,95 дол.?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Особенно интересные возможности обещает теория эффективной ____________ (**заработный, плата**), которая утверждает, что многие фирмы могут платить заработную плату выше равновесного уровня, чтобы добиться лояльности со стороны рабочей силы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### Представители других национальных меньшинств нередко вынуждены соглашаться на более низкую ____________ (**заработный, плата**) за одну и ту же работу, чем их белые коллеги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### При построении кривой, предложения труда для какого-то конкретного работника мы просто определяем, как будет меняться оптимальное количество предлагаемого им труда при изменении ставок ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### В экономике США индексация ____________ (**заработный, плата**) не является ни распространенной, ни полной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### При выработке мер экономической политики следует отказаться от решений, вызывающих рост издержек (например, повышение ____________ (**заработный, плата**) бюджетникам).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Очевидна зависимость трансфертов от ____________ (**заработный, плата**), надбавок к ней в северных и восточных регионах, от демографической структуры населения и срока выхода на пенсию (который в северных и восточных регионах наступает в среднем раньше).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### В период низкого уровня производства и высокого уровня безработицы, к примеру, ____________ (**заработный, плата**) рабочих должна сократиться, что приведет к снижению издержек производства и увеличению объема предлагаемой продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной плате', 
                          title = '#### Безработица, возникающая в результате поиска работы, заметно отличается от той, которая вызывается законами о минимальной ____________ (**заработный, плата**), деятельностью профсоюзов и эффективной оплатой труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной плате',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Со времени принятия в 1938 г. Закона о справедливых условиях труда в Соединенных Штатах существует федеральный минимум ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платой', 
                          title = '#### Дифференциация заработной платы — разница между ____________ (**заработный, плата**), получаемой одним работником или группой работников, и заработной платой, получаемой другим работником.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### В современной кривой Филлипса темпы прироста номинальной ____________ (**заработный, плата**) заменены на темпы инфляции. Это различие не имеет принципиального значения, так как увеличение заработной платы и рост цен тесно связаны друг с другом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### По теории эффективной ____________ (**заработный, плата**), причина негибкости заработной платы состоит в том, что фирмы несут потери в производительности, если идут на сокращение заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### Ряд стран сократил системы выплат по безработице, уменьшил или ликвидировал минимальную ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Крупнейшая категория дохода состоит главным образом из ____________ (**заработный, плата**) и жалованья, которые выплачиваются предпринимательским сектором и государством за труд.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Расчетный фонд ____________ (**заработный, плата**) был получен как произведение среднемесячной номинальной начисленной заработной платы работников организаций за 12 месяцев и среднесписочной численности работников организаций за вычетом подоходного налога, плюс поступления в бюджеты региональных фондов пенсионного обеспечения, занятости и медицинского страхования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### рынка рабочей силы. В период с 1975 по 1980 г. на рынке бейсбольных игроков устано- вилось новое равновесие, Если до 1975 г. расходы на контракты с игроками составляли 25% всех издержек команд, то к 1980 г. общий фонд ____________ (**заработный, плата**) игроков вырос по 40%. Кроме того; срелняя заработная плата игроков удвоилась в реальном выраже-',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Ясно, что рабочие, озабоченные величиной реальной ____________ (**заработный, плата**), хотят, чтобы номинальная зарплата полностью учитывала инфляцию, которую они ожидают в период между моментом установления уровня заработной платы и моментом ее фактической выплаты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Когда рост ____________ (**заработный, плата**) превысит рост производительности, т. е. произойдет завышенная оценка фактора производства, тогда мы говорим об инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Рассматривается также гипотеза о единой ставке номинальной ____________ (**заработный, плата**) в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### В конечном счете, все эти выплаты получают потребители в форме ____________ (**заработный, плата**) рабочих и служащих, дивидендов или процентных выплат.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### С помощью каких способов профсоюзы могут понизить эластичность спроса на труд, чтобы минимизировать отрицательные эффекты при повышении ____________ (**заработный, плата**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Каждый работник при определении предложения услуг труда исходит из максимизации своего удовлетворения от комбинации работа-досуг при ограничении, налагаемом действующей ставкой ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Работники становятся менее требовательными в отношении ____________ (**заработный, плата**) только в условиях высокой безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Взносы по социальному страхованию, которые преимущественно существуют в форме налогов, взимаемых с ____________ (**заработный, плата**), считаются частью федерального бюджета.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Выигрыш в лотерею не повлиял на величину текущего вознаграждения за труд — реальная ставка ____________ (**заработный, плата**) Эйса как была, так и осталась $35 в час, — поэтому здесь не может проявиться эффект замещения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### Существует также мнение, что средний получатель заработной платы склонен питать некоторые иллюзии, когда одновременно возрастают и номинальная ____________ (**заработный, плата**), и уровень цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### В сущности, повышение номинальной ____________ (**заработный, плата**), вызванное повышением уровня цен, заставляет работников считать, что возросла и реальная заработная плата.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### Безработные захотят работать за ____________ (**заработный, плата**) ниже, чем та, которую получают занятые.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Согласно выдвинутому им тезису, темпы инфляции, вызываемой ростом ____________ (**заработный, плата**), находятся в тесной взаимосвязи с уровнем безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Эффект дохода уменьшает величину предложения труда, когда рост ставки реальной ____________ (**заработный, плата**) делает работника богаче.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### В чем состоит суть дискуссии о необходимости установления государством минимального размера ____________ (**заработный, плата**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платой', 
                          title = '#### Коэффициент замещения показывает расчётный размер гипотетической пенсии работника со средней ____________ (**заработный, плата**) в течение первого года после назначения пенсии в сравнении с заработком перед пенсией в базовом случае (т.е. с 40-летней карьерой и выходом на пенсию в официальном пенсионном возрасте).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной плате', 
                          title = '#### Объясните, почему максимизирующий прибыль уровень занятости для фирмы обеспечивается, когда предельный доход продукта труда равен номинальной ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной плате',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платой', 
                          title = '#### Переменные национального уровня агрегируются по региональным данным СВР, а не берутся из национальной базы, чтобы гарантировать, что заработная плата и эффекты уровня действительно отражают различие между средней ____________ (**заработный, плата**) в регионах и национальной средней заработной платой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### Вдобавок эти рабочие места должны генерировать и достаточно высокую добавленную стоимость, что позволит повысить ____________ (**заработный, плата**) и реальные доходы населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### За последние полвека рост ____________ (**заработный, плата**) в США стагнировал, неравенство в заработной плате росло, а уровень участия в рабочей силе мужчин прайм-возраста неуклонно снижался.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Это наблюдение не согласуется ни с моделью жесткой ____________ (**заработный, плата**), ни с моделью неверных представлений рабочих.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Другими словами, жесткость ____________ (**заработный, плата**) означает, что при низком уровне цен на товары производство становится менее выгодным, что побуждает фирмы к снижению объема предлагаемых товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Принцип сравнения набора кластеров с относительным уровнем ____________ (**заработный, плата**) подобен концепции анализа «сдвиг-доля», который был первоначально предложен Данном и часто применяется в региональных исследованиях.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### В соответствии с моделью предложения труда выбор между ситуацией, когда человек не работает совсем, и ситуацией, когда определенное число часов он отдает работе за ____________ (**заработный, плата**), определяется ставкой заработной платы, нетрудовым доходом и индивидуальными предпочтениями между трудом и досугом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Подход О.У. Филлипса (как и неоклассиков) отличался от подхода Кейнса с предпосылкой об экзогенном характере движения ____________ (**заработный, плата**): темп инфляции, вызванной ростом заработной платы, в них определялся эндогенно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Пакет компенсации за труд, предлагаемый монопсонистом и состоящий из ____________ (**заработный, плата**), средств на охрану труда и прочих дополнительных льгот, менее ценен, чем соответствующий пакет при конкуренции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Этот эффект безработицы может оказывать сдерживающее воздействие на требования профсоюзов по повышению ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Эта система представляет собой совокупность положений, с помощью которых определяется размер ____________ (**заработный, плата**) различных категорий работников.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной плате', 
                          title = '#### Существует общее мнение, что основным фактором роста заработной платы высококвалифицированных работников по отношению к ____________ (**заработный, плата**) низкоквалифицированных работников является постоянный рост спроса на высококвалифицированный персонал по отношению к спросу на низкоквалифицированный.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной плате',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной плате', 
                          title = '#### Для професиональной переподготовки характерны сильные профсоюзы, пользующиеся в основном монополией на представительство, централизованные переговоры по ____________ (**заработный, плата**), развитая трудовая регламентация, составляемая на основе коллективных переговоров и законодательства, высокий уровень пособий по безработице, активная политика занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной плате',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработную плату', 
                          title = '#### Государство устанавливает минимальную ____________ (**заработный, плата**) с тем, чтобы соблюдались интересы низкооплачиваемых категорий работников.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработную плату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Для оценки уровня жизни населения субъектов РФ, разработки и реализации региональных социальных программ, планирования темпов роста ____________ (**заработный, плата**), пенсий, социальных пособий, а также составления бюджетов используют понятия минимального потребительского бюджета (МПБ) и бюджета прожиточного минимума.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### Большое количество доказательств свидетельствует о том, что реальная ____________ (**заработный, плата**) является умеренно проциклическим показателем, хотя некоторые исследователи не согласны с этим утверждением.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной плате', 
                          title = '#### Любой фактор, который увеличивает предложение труда при данной текущей реальной ____________ (**заработный, плата**), сдвигает кривую предложения труда вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной плате',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Социальный эффект связан с ростом производительности труда на 16% по сравнению с 2009 г. и ростом среднемесячной ____________ (**заработный, плата**) работников на 6,8%, причем среднесписочная численность работников в 2010 г. снизилась на 1,45%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Монополист будет увеличивать занятость до тех пор, пока предельный продукт труда - в данном случае единственного используемого им переменного фактора - не сравняется с конкурентной ставкой ____________ (**заработный, плата**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### В течение этого периода подстройки работники продолжают требовать повышения ____________ (**заработный, плата**), что уже не соответствует новым, более низким темпам роста производительности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Наиболее примечательным в этой таблице является весьма высокая доля ____________ (**заработный, плата**) наемным работникам в национальном доходе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработной платы', 
                          title = '#### Тенденция к снижению ____________ (**заработный, плата**) складывается как со стороны предложения труда, так и со стороны спроса на труд.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заработная плата', 
                          title = '#### За период с 2009 по 2013 г. среднемесячная номинальная начисленная ____________ (**заработный, плата**) в Пермском крае увеличилась с 15227,6 до 24715,5 руб., или на 62,3%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заработная плата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

