
```{r}
checkdown::check_question(answer = stringr::str_split('во; многом; зависит; от', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'во; многом; зависит; от',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('зависит; от; того,; что', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'зависит; от; того,; что',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('в; значительной; степени; зависит', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; значительной; степени; зависит',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('зависит; от; ставки; ', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'зависит; от; ставки; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('напрямую; зависит; от; ', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'напрямую; зависит; от; ',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Указанные два способа определения факторонасыщенности позволяют выявить предложение и спрос не только на факторы производства, но и непосредственно на товары, которые производятся с их участием, так как спрос на факторы производства зависит от ____________ (**спрос**) на конечные товары. Фактороинтенсивность – показатель, дающий представление об относительных затратах факторов на производство единицы какого-либо товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'общий уровень цен', 
                          title = '#### Теперь мы располагаем элементами теории, которая позволяет определить, от чего зависит ____________ ____________ ____________ (**общий, уровень, цена**) в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'общий уровень цен',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'размеров', 
                          title = '#### Изъятие вкладов в чрезмерных масштабах вследствие паники вкладчиков сказалось негативно на работе банков. Влияние этого фактора на устойчивость банка не зависит от ____________ (**размер**) банка и не знает границ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'размеров',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'сбережений', 
                          title = '#### Экономика, где есть технический прогресс, имеет положительный темп роста ВВП на одного работника даже в долгосрочном периоде. Этот долгосрочный темп роста не зависит от нормы ____________ (**сбережение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сбережений',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'состояния', 
                          title = '#### Исходя из этого, следует подчеркнуть важность модернизации и диверсификации экономики и необходимость ее интенсивного развития, что во многом зависит от ____________ (**состояние**) основных средств предприятий и производственного сектора в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'состояния',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```
