```{r}
checkdown::check_question(answer = 'инфляции', 
                          title = '#### Продажа на открытом рынке государственных ценных бумаг, повышение учетной ставки - это политика "дорогих" денег. Она проводится в период ____________ (**инфляция**) в целях сокращения совокупного спроса. Для этого ЦБ уменьшает предложение денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инфляции на шоки', 
                          title = '#### Мы обнаружили некоторую корреляцию между реакциями региональной ____________ (**инфляции, на, шок**) ДКП и валютного курса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляции на шоки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инфляции на шоки', 
                          title = '#### Величина регионального отклика ____________ (**инфляции, на, шоки**) ДКП сопоставляется с величиной регионального отклика инфляции на общие шоки курса иностранной валюты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляции на шоки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокие темпы инфляции', 
                          title = '#### Принимая во внимание чрезвычайно ____________ (**высокие, темпы, инфляции**) в России, хранение активов Фонда в рублевой валюте должно быть существенно ограничено.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокие темпы инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоких темпов инфляции', 
                          title = '#### Однако следует иметь в виду, что эта формула справедлива лишь для низких темпов инфляции (до 10%), а для ____________ (**высокие, темпы, инфляции**) необходимо использовать другую формулу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоких темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоких темпов инфляции', 
                          title = '#### Однако субъекты экономики ожидают ____________ (**высокие, темпы, инфляции**) как раз потому, что текущая и перспективная денежно-кредитная и финансово-бюджетная политика правительства подтверждает их оценки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоких темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпов инфляции в', 
                          title = '#### Инфляционные ожидания - это оценка субъектами рынка изменения ____________ (**темп, инфляции, в**) будущем периоде. Можно сказать, что инфляционные ожидания управляют ценами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпов инфляции в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоких темпов инфляции', 
                          title = '#### Метод срока окупаемости успешно используется для экспресс-анализа проектов в условиях ____________ (**высокие, темпы, инфляции**), политический нестабильности или при дефиците ликвидности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоких темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'целей по инфляции', 
                          title = '#### Введенное в России в 2017 г. бюджетное правило помогает Банку России с большей эффективностью достигать ____________ (**целей, по, инфляции**) и способствует снижению долгосрочных процентных ставок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'целей по инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'целей по инфляции', 
                          title = '#### Удается ли обеспечить достижение ____________ (**целей, по, инфляции**)? Должны ли центробанки использовать инструменты денежной политики для решения задач финансовой стабильности?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'целей по инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инфляции', 
                          title = '#### Чем меныше покупательная способность денег, тем меньшее количество наличных денег хотят держать люди на руках. Это связано с тем, что люди, которые хранят наличные деньги, в период ____________ (**инфляция**) платят инфляционный налог.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпов инфляции', 
                          title = '#### Широко распрострамено мнение о том, что повышение обменного курса доллара за период до 1985 г. сыграло важную роль в замедлении ____________ (**темп, инфляции**) в США в начале 80-х гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инфляции', 
                          title = '#### Экономические решения основываются на относительных ценах, однако в период ____________ (**инфляция**) изменение относительных цен не отражает действительного различия в эффективности производства разных видов товаров, а лишь разницу в скорости изменения цен на товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпов инфляции', 
                          title = '#### Данное уравнение показывает, что изменение номинального обменного курса валют двух стран равно сумме изменений реального обменного курса и разницы ____________ (**темп, инфляции**) в этих странах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'целей по инфляции', 
                          title = '#### По-прежнему дискуссионной представляется политика Банка России в части сохранения высоких процентных ставок для достижения, как декларируется, ____________ (**целей, по, инфляции**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'целей по инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инфляции на шоки', 
                          title = '#### Авторы приводят два возможных объяснения. Первое заключается в том, что слабее стала реакция ____________ (**инфляции, на, шок**) совокупного спроса при заданных ожиданиях. Еще одно возможное объяснение заключается в том, что сами ожидания стали реагировать слабее на фундаментальные факторы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляции на шоки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоких темпов инфляции', 
                          title = '#### Сторонники точки зрения альтернативной «теории рациональных ожида­ний» полагают, что инфляция — процесс весьма инерционный. Они считают, что если фирмы и рабочие ожидают ____________ (**высокие, темпы, инфляции**), при заключе­нии сделок они ориентируются на свою оценку перспектив экономического положения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоких темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпов инфляции', 
                          title = '#### Темпы инфляции в США находятся на среднем уровне по сравнению с прочими промышленно развитыми странами и гораздо ниже ____________ (**темп, инфляции**) в некоторых других странах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпов инфляции', 
                          title = '#### На рисунке приведены графики изменения ____________ (**темп, инфляции**) в США за пери­од с 1965 по 1995 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в уровнях инфляции', 
                          title = '#### Большие различия ____________ (**уровень, инфляции, в**) среди стран практически всегда являются результатом значительных различий в темпах роста количества денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в уровнях инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпов инфляции', 
                          title = '#### Чем большим доверием пользуется политика, направленная на замедление ____________ (**темп, инфляции**) в экономике, тем больший успех эта политика будет иметь.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в уровнях инфляции', 
                          title = '#### В основе движения обменных курсов лежат в первую очередь фундаментальные соотношения, устанавливающие взаимосвязь между различиями ____________ (**уровень, инфляции, в**) и процентных ставок в разных странах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в уровнях инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инфляции на шоки', 
                          title = '#### Изменение режима влияет на реакцию ____________ (**инфляции, на, шок**) предложения и обменного курса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляции на шоки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в уровнях инфляции', 
                          title = '#### Скользящее фиксирование предполагает, что реальный валютный курс К = РИ(Р/е) остается неизменным, поскольку обесценение компенсирует различие ____________ (**уровень, инфляции, в**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в уровнях инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоких темпов инфляции', 
                          title = '#### Значит, что сбалансированность бюджета и жесткая кредитно-денежная политика сами по себе недостаточны для сдерживания ____________ (**высокие, темпы, инфляции**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоких темпов инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'целей по инфляции', 
                          title = '#### Всего два десятилетия назад в данной научной статье исследовались издержки от публикации центральным банком ____________ (**целей, по, инфляции**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'целей по инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'целей по инфляции', 
                          title = '#### Как показывают расчеты, инфляция в России в последние 15 лет формируется в основном за счет немонетарных факторов, а рост процентных ставок подавляет деловую активность. Это снижает предложение товаров и услуг, что содействует росту инфляции. Через жесткую монетарную политику ЦБ РФ добился ____________ (**цели, по, инфляции**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'целей по инфляции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпы инфляции в', 
                          title = '#### Большинство исследователей приходят к выводу, что в последние годы возросло влияние глобализации и внешних факторов на ____________ (**темп, инфляции, в**) отдельно взятых странах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпы инфляции в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

