```{r}
checkdown::check_question(answer = 'инвестиционный', 
                          title = '#### После пандемии ____________ (**инвестиционный**) рынок начал восстанавливаться.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной деятельности', 
                          title = '#### Следует минимизировать риски ____________ (**инвестиционный, деятельность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной деятельности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные', 
                          title = '#### Компании закрывают ____________ (**инвестиционный**) проекты в ожидании спада экономической активности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные', 
                          title = '#### Анализ инвестиционной программы выявил высокие ____________ (**инвестиционный**) риски в первые пять лет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной деятельности', 
                          title = '#### Изменилась ставка налогообложения доходов, полученных от ____________ (**инвестиционный, деятельность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной деятельности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционными стратегиями', 
                          title = '#### Люди следуют за популярными ____________ (**инвестиционные, стратегии**), обещающими быструю возможность разбогатеть.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционными стратегиями',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных', 
                          title = '#### Инвесторы чаще проверяли стоимость своих ____________ (**инвестиционный**) портфелей на растущих рынках, чем на стабильных или падающих.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных фондов', 
                          title = '#### Центральный банк подготовил обзор ключевых показателей паевых и акционерных ____________ (**инвестиционный, фонд**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных фондов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных потоков', 
                          title = '#### Ресурсы предопределяют не только структуру российской внешней торговли, но и структуру ____________ (**инвестиционный, поток**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Повышение уровня неопределенности в экономике становится причиной отказа от новых ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных потоков', 
                          title = '#### Экологическая повестка повлечет перераспределение ____________ (**инвестиционный, поток**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной деятельности', 
                          title = '#### Порядок осуществления ____________ (**инвестиционный, деятельность**) в стране, порядок привлечения отечественных и иностранных инвестиций определяет специальное инвестиционное законодательство.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной деятельности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных фондов', 
                          title = '#### В кризисный период фактические оттоки среди открытых паевых ____________ (**инвестиционный, фонд**) не превышали 5% от стоимости их чистых активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных фондов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной деятельности', 
                          title = '#### Государственное регулирование ____________ (**инвестиционный, деятельность**) – это воздействие государства на инвестиционные отношения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной деятельности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционный', 
                          title = '#### ____________ (**инвестиционный**) налоговый кредит представляет собой разновидность отсроченных налоговых платежей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционными портфелями', 
                          title = '#### Около половины инвесторов на рынке обладают ____________ (**инвестиционный, портфель**) среднего размера.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционными портфелями',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной политики', 
                          title = '#### К формированию и реализации ____________ (**инвестиционный, политика**) акционерам и менеджменту компании стоит подходить максимально ответственно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной политики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной привлекательности', 
                          title = '#### Мотивом повышения ____________ (**инвестиционный, привлекательность**) является устойчивый рост дивидендных выплат российских компаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной привлекательности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных товаров', 
                          title = '#### Нередко под инвестиционным рынком понимают только рынок ____________ (**инвестиционный, товар**) и инвестиционных услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Банк может потребовать независимую оценку ____________ (**инвестиционный, проект**) для подтверждения их прибыльности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных потоков', 
                          title = '#### Государственная программа способствует росту торговых и ____________ (**инвестиционный, поток**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Существует модель оптимизации портфеля ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### В компании допущены ошибки при оценке эффективности ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного рынка', 
                          title = '#### Основной тенденцией мирового ____________ (**инвестиционный, рынок**) является сильный интерес инвесторов к развивающимся рынкам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Отдельные международные финансовые организации специализируются на финансировании ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционную привлекательность', 
                          title = '#### Ужесточение политики Федеральной резервной системы снижает ____________ (**инвестиционный, привлекательность**) развивающихся рынков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционную привлекательность',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционный климат', 
                          title = '#### Хотя санкции были сняты, ____________ (**инвестиционный, климат**) в стране оставался достаточно плохим.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционный климат',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционный', 
                          title = '#### Несмотря на благоприятный ____________ (**инвестиционный**) климат, в период кризиса все-таки произошел отток инвестиций из региона.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной деятельности', 
                          title = '#### Инвесторы, заказчики, подрядчики, пользователи объектов капитальных вложений являются субъектами ____________ (**инвестиционный, деятельность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной деятельности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной стратегией', 
                          title = '#### Розничные инвесторы могут держать актив или выходить из него по причинам, никак не связанным с ____________ (**инвестиционные, стратегии**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной стратегией',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционный фонд', 
                          title = '#### Вкладчики готовы вложить в ____________ (**инвестиционный, фонд**) $400 млн.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционный фонд',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной политики', 
                          title = '#### Необходимо поддерживать эффективность налоговой, бюджетной и ____________ (**инвестиционный, политика**): всегда есть желание закрыть проблемы деньгами, а не заниматься налоговыми стимулами, повышением эффективности госрасходов и инвестиционным климатом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной политики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционном рынке', 
                          title = '#### Марк Мобиус известен на ____________ (**инвестиционный, рынок**) как первоклассный аналитик, способный отыскивать компании с большим потенциалом роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционном рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных решений', 
                          title = '#### Не стоит рассчитывать на интуицию в принятии ____________ (**инвестиционное, решение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных решений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционный', 
                          title = '#### У инвестора пропадает стимул к увеличению инвестиций, и ____________ (**инвестиционный**) спрос снижается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных', 
                          title = '#### На схеме представлены источники финансирования ____________ (**инвестиционный**) проектов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной привлекательности', 
                          title = '#### Активы сопоставлены по ____________ (**инвестиционный, привлекательность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной привлекательности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного', 
                          title = '#### Процесс анализа рисков ____________ (**инвестиционный**) проекта во многом определяется экспертом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных фондов', 
                          title = '#### Компания получила лицензию на деятельность альтернативных ____________ (**инвестиционный, фонд**) в стране.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных фондов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционному налоговому кредиту', 
                          title = '#### У российских предприятий есть доступ к ____________ (**инвестиционный, налоговый, кредит**) по налогу на прибыль, по региональным и местным налогам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционному налоговому кредиту',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной деятельности', 
                          title = '#### Какие финансовые инструменты используются при прямых методах государственного регулирования ____________ (**инвестиционный, деятельность**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной деятельности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Мировой финансовый кризис существенно повлиял на возможности реализации крупных ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционным рискам', 
                          title = '#### Устойчивость к ____________ (**инвестиционный, риск**) может меняться в зависимости от рыночных условий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционным рискам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные стратегии', 
                          title = '#### Личные характеристики человека могут влиять на ____________ (**инвестиционные, стратегии**), особенно склонность к риску.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные стратегии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные товары', 
                          title = '#### Фирмы приобретают ____________ (**инвестиционный, товар**) и сдают их в аренду.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные товары', 
                          title = '#### Произойдет рост цен на ____________ (**инвестиционный, товар**) относительно цен на труд (заработных плат, доходов).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной привлекательности', 
                          title = '#### Рейтинговая оценка ____________ (**инвестиционный, привлекательность**) региона присваивается по специальной шкале.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной привлекательности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Дружественные страны договорились о реализации крупных ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной', 
                          title = '#### На практике оценка ____________ (**инвестиционный**) привлекательности часто сводится к анализу финансового состояния объектов инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного', 
                          title = '#### В секторах производственного и ____________ (**инвестиционный**) спроса наблюдалось сокращение прибыли по сравнению с отраслями потребительского спроса и торговли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного проекта', 
                          title = '#### Были получены значения показателей, подтверждающие эффективность ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного проекта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционным проектам', 
                          title = '#### Крупным ____________ (**инвестиционный, проект**) предоставят налоговые льготы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционным проектам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### В результате реализации ____________ (**инвестиционный, проект**) произойдет частичное импортозамещение технологий и производств.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной политики', 
                          title = '#### На схеме города распределены по наличию ____________ (**инвестиционный, политика**) и инвестиционного паспорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной политики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной привлекательности', 
                          title = '#### Высокий уровень ____________ (**инвестиционный, привлекательность**) региона снижает инвестиционный риск.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной привлекательности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной', 
                          title = '#### Заметную роль в поддержании ____________ (**инвестиционный**) активности в области начинают играть инвестиции в жилищное строительство.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного спроса', 
                          title = '#### Восстановление потребительского и ____________ (**инвестиционный, спрос**) займет определенное время.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные портфели', 
                          title = '#### Ученые изучили ____________ (**инвестиционный, портфель**) более 100 европейских банков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные портфели',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной поддержки', 
                          title = '#### В правительстве разрабатываются направления финансово-кредитной и ____________ (**инвестиционный, поддержка**) предпринимательства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной поддержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной активности', 
                          title = '#### Высокий уровень тарифов на продукцию и услуги естественных монополий влекут за собой низкий уровень ____________ (**инвестиционный, активность**) в реальном секторе экономики, несмотря на снижение темпов инфляции и процентных ставок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной активности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной привлекательности', 
                          title = '#### Дана оценка ____________ (**инвестиционный, привлекательность**) регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной привлекательности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные проекты', 
                          title = '#### Обычно ____________ (**инвестиционный, проект**) долгосрочны, а вкладчики ценят краткосрочную ликвидность, то есть возможность при необходимости изъять свои сбережения для немедленного потребления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные проекты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционным', 
                          title = '#### Траст, чьи паи торгуются на фондовой бирже по рыночным ценам, называется паевым ____________ (**инвестиционный**) фондом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционным',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной активности', 
                          title = '#### Результаты анализа показывают низкую корреляцию ____________ (**инвестиционный, активность**) и совокупной факторной продуктивности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной активности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного климата', 
                          title = '#### Благодаря изменениям в законодательстве ожидается улучшение ____________ (**инвестиционный, климат**) и появление новых рабочих мест, а соответственно, и рост качества жизни населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного климата',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной', 
                          title = '#### Фискальная политика не обеспечила стимулы для ____________ (**инвестиционный**) активности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного', 
                          title = '#### Региональные органы власти прилагают больше усилий к улучшению ____________ (**инвестиционный**) климата, чем несколько лет назад.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного налогового кредита', 
                          title = '#### Рост ожидаемого выпуска, уменьшение ставки процента или увеличение ____________ (**инвестиционный, налоговый, кредит**) увеличивают объем инвестирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного налогового кредита',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной активности', 
                          title = '#### Повысился рост ____________ (**инвестиционный, активность**) в сфере услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной активности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционным', 
                          title = '#### Вероятность не получить прибыль от вложенных денег называется ____________ (**инвестиционный**) риском.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционным',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Дисконтирование и современная стоимость чаще всего применяются при оценке ____________ (**инвестиционный, проект**), при расчетах экономической эффективности капиталовложений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Ставка процента измеряет стоимость финансирования ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных стратегий', 
                          title = '#### Для других отраслей влияние ____________ (**инвестиционные, стратегии**) на уровень инвестиций не наблюдается, либо статистически не значимо (на 5-10% уровне).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных стратегий',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Будет обеспечена государственная поддержка крупных ____________ (**инвестиционный, проект**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных решений', 
                          title = '#### Различные предубеждения влияют на учестников торгов при принятии ____________ (**инвестиционное, решение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных решений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной политики', 
                          title = '#### Предложен комплекс мер государственной ____________ (**инвестиционный, политика**), предусматривающих приоритет инновационных инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной политики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной привлекательности', 
                          title = '#### Агентство ежегодно составляет рейтинг ____________ (**инвестиционный, привлекательность**) регионов России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной привлекательности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных проектов', 
                          title = '#### Финансово-экономическая оценка ____________ (**инвестиционный, проект**) занимает важное место в процессе обоснования и выбора возможных вариантов вложения денежных средств в реальный сектор экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных проектов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционная', 
                          title = '#### Росту цен также способствует ____________ (**инвестиционный**) привлекательность жилья.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционную', 
                          title = '#### Проанализированы показатели, отражающие эффективность и ____________ (**инвестиционный**) политику компаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционную',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционный климат', 
                          title = '#### Индексы, отвечающие за ____________ (**инвестиционный, климат**) и инновационную инфраструктуру, продолжили снижаться.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционный климат',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной политики', 
                          title = '#### Эффективность государственной ____________ (**инвестиционный, политика**) зависит не только от общего объема инвестиций, а от того, в какие именно отрасли будут направлены инвестиционные потоки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной политики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные', 
                          title = '#### Можно сказать, что ____________ (**инвестиционные**) ресурсы формировались и использовались не эффективно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных', 
                          title = '#### Геополитика находится в центре внимания при принятии ____________ (**инвестиционное**) решений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного', 
                          title = '#### При действии ____________ (**инвестиционный**) налогового кредита происходит перераспределение налогового бремени инвестора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных товаров', 
                          title = '#### Американские покупатели потребительских и ____________ (**инвестиционный, товар**) переключат свой спрос с британских товаров на американские, что также ограничит спрос на фунты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной деятельности', 
                          title = '#### При разработке инвестиционных проектов важно внимательно изучать действующие редакции нормативных актов, которые устанавливают основы государственного регулирования ____________ (**инвестиционный, деятельность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной деятельности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного портфеля', 
                          title = '#### Не существует единой стратегии формирования ____________ (**инвестиционный, портфель**), которая подходила бы абсолютно всем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного портфеля',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного', 
                          title = '#### Инвестиционная политика, проводимая государством, направлена на создание благоприятного ____________ (**инвестиционный**) климата в стране.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционных расходов', 
                          title = '#### Причина макроэкономической нестабильности кроется в колебаниях ____________ (**инвестиционные, расходы**) и происходящих время от времени спадах совокупного предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной', 
                          title = '#### Деньги поступают от операционной (производственной) деятельности, от ____________ (**инвестиционный**) деятельности и от финансовой деятельности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной', 
                          title = '#### активизация ____________ (**инвестиционный**) деятельности – залог экономического роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционные расходы', 
                          title = '#### Более низкая процентная ставка увеличивает и потребительские расходы (потому что сокращается сбережение), и ____________ (**инвестиционные, расходы**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционной', 
                          title = '#### В 1990-е гг. на развитых рынках был проведен ряд исследований зависимости доходности акций и ____________ (**инвестиционный**) активности компаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

