```{r}
checkdown::check_question(answer = 'разнообразия', 
                          title = '#### Причинами расхождений помимо разных методов анализа данных могут выступать различные характеристики принадлежности, используемые для оценки ____________ (**разнообразие**): национальность, религия, страна происхождения, профессиональные задачи в процессе производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'разнообразия',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'практике', 
                          title = '#### Рассмотренная зависимость широко используется в ____________ (**практика**) ценообразования для финансовых активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'практике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'строительных', 
                          title = '#### Хвойная древесина, в основном из России и Новой Зеландии, в большинстве случаев используется в качестве ____________ (**строительный**) материалов и, таким образом, почти полностью предназначается для внутреннего конечного использования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'строительных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'оценки', 
                          title = '#### Данный показатель выбран в качестве целевого при мониторинге выполнения указов Президента РФ, он отслеживается Росстатом, используется для ____________ (**оценка**) результатов развития конкретных регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'продукции', 
                          title = '#### Общественные экономические ресурсы используются для производства ____________ (**продукция**) монополии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменения', 
                          title = '#### Индекс деловой активности рассчитывается по результатам опроса менеджеров по закупкам и используется для оценки ____________ (**изменение**) экономической активности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'политику', 
                          title = '#### Для увеличения объемов вложений и активизации инвестиционного процесса государство может использовать ____________ (**политика**) стимулирования инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'политику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'источника', 
                          title = '#### Дополнительный выпуск денежных знаков помимо оплаты государственного долга используется в качестве ____________ (**источник**) доходов (сеньораж).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'источника',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'вводных', 
                          title = '#### Практические результаты работы могут быть использованы в качестве ____________ (**вводный**) данных для построения системы дифференцированного регулирования банковской системы, нацеленной на сохранение и укрепление позиций региональных банков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'вводных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'показателя', 
                          title = '#### Приведенные примеры отражают нечастые случаи противоречия данных реальности, и ВВП можно использовать в качестве ____________ (**показатель**) общественно-экономического развития, но всегда помнить о большой степени неточности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'показателя',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'разработке', 
                          title = '#### Разработаны методология и модельный аппарат построения долгосрочных программ развития проблемных регионов ресурсного типа, методы оценки интегрального эффекта их реализации в рыночных условиях хозяйствования, которые были использованы при ____________ (**разработка**) программ ряда регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'разработке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обслуживания', 
                          title = '#### На основе анализа источников был сформирован набор показателей, которые разные авторы предлагают использовать для оценки ____________ (**обслуживание**) клиентов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обслуживания',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономических', 
                          title = '#### Капитал (capital) — ресурсы длительного пользования, используемые для производства ____________ (**экономический**) благ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономических',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'качестве', 
                          title = '#### Термин «нарратив» часто используется в ____________ (**качество**) «истории», какой-то последовательности событий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'качестве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'деятельности', 
                          title = '#### Уровень принятия решения, на котором целесообразно использование показателя: в соответствии с уровнями иерархии управления деятельностью компании показатели могут использоваться для оценки ____________ (**деятельность**) на стратегическом, тактическом и операционном уровне.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'деятельности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'оценки', 
                          title = '#### Данные ряды, используемые для ____________ (**оценка**) моделей, включают 618 наблюдений (рабочих дней) с 6 ноября 2014 г. по 20 апреля 2017 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'странам', 
                          title = '#### В работе используются данные по ____________ (**страна**), а основное внимание уделяется странам с формирующимися рынками.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'странам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'оценки', 
                          title = '#### Ромер доказывала, что методы, используемые для ____________ (**оценка**) исторических данных, обычно преувеличивали величину более ранних циклических колебаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эффективности', 
                          title = '#### Согласно Xia and Wu (2016), теневая ставка может использоваться для оценки ____________ (**эффективность**) ДКП, когда наблюдаемая ставка приближается к нулевой отметке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффективности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'модели', 
                          title = '#### Полученные наборы данных используются для оценки ____________ (**модель**) логистической регрессии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'модели',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства', 
                          title = '#### Факторов, которые используются для ____________ (**производство**) продукта, очень много.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития страны', 
                          title = '#### Во Франции в 2008 г. была создана Комиссия по измерению эффективности экономики и социального прогресса, по итогам работы которой было предложено использовать для оценки ____________ ____________ (**развитие, страна**) такие параметры, как счастье и доступность услуг здравоохранения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития страны',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'корпоративной', 
                          title = '#### Полученные на основе досчета характеристики используются для оценки ____________ (**корпоративный**), региональной и социальной эффективности проектов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'корпоративной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'анализе', 
                          title = '#### Сравнительная статистика широко используется в микро- и в макроэкономическом ____________ (**анализ**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'анализе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства', 
                          title = '#### Функция производственная — зависимость между количеством используемых факторов ____________ (**производство**) и максимально возможным выпуском продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'анализа', 
                          title = '#### С помощью технологии обработки открытых вопросов анкет можно разрабатывать типологии, которые используются для ____________ (**анализ**) структур пространственного развития туристского кластера.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'анализа',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'выработке', 
                          title = '#### Для анализа динамики производительности и заработной платы использованы данные по ____________ (**выработка**) ВДС на одного занятого, скорректированные на величину ФНТУ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выработке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'теневой экономике', 
                          title = '#### Наличные деньги также широко используются в ____________ ____________ (**теневой, экономика**), как для осуществления нелегальных операций, так и для укрывания легальных операций от налогообложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теневой экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'понимания', 
                          title = '#### Мы не только продемонстрируем, как анализ спроса и предложения можно использовать для ____________ (**понимание**) и оценки подобной политики, но и посмотрим, как отклонения от конкурентного рыночного равновесия ведут к эффективности издержек.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'понимания',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'продажу', 
                          title = '#### Отмечалось, что государство может использовать ____________ (**продажа**) своих облигаций для финансирования дефицита госбюджета.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'продажу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'восьми', 
                          title = '#### Для оценивания параметров этого уравнения использованы данные по ____________ (**восемь**) дальневосточным субъектам Российской Федерации в разрезе основных отраслей за период 1991-2005 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'восьми',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ресурсов', 
                          title = '#### Источник привлечения средств отражает эффективность использования финансовых ____________ (**ресурс**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ресурсов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'средства', 
                          title = '#### Деньги включают в себя активы, которые могут быть использованы в качестве ____________ (**средство**) платежа, такие как наличность и остатки на текущих счетах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'средства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'оценки', 
                          title = '#### Учитывалось, что показатели, используемые для ____________ (**оценка**) МВР, должны быть представлены в государственной статистике и ведомственной отчетности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объясняемой', 
                          title = '#### Способ использует в качестве ____________ (**объяснять**) переменной при проведении темпорального дезагрегирования близкую по смыслу и значениям альтернативную переменную с наблюдаемыми как низко, так и высокочастотными данными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объясняемой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'административные меры', 
                          title = '#### На российском рынке наиболее часто используются ____________ ____________ (**административный, мера**) и антимонопольное законодательство.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'административные меры',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства', 
                          title = '#### Совокупному выпуску соответствует доход, получаемый владельцами факторов производства - труда, капитала и земли, которые используются для ____________ (**производство**) выпуска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'измерения', 
                          title = '#### Поскольку значение реального ВВП не подвержено влиянию ценовых колебаний, его можно использовать для ____________ (**измерение**) роста производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'измерения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'торговых', 
                          title = '#### Кратное выручки часто используется для оценки ____________ (**торговый**) и консалтинговых компаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'торговых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ресурса', 
                          title = '#### Промежуточный продукт в каждый период производится монополистом, который использует в качестве ____________ (**ресурс**) единицу конечного выпуска на единицу промежуточного.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ресурса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'альтернативы', 
                          title = '#### Предложенное Шеллингом решение сводится к попытке устранить проблему, используя в качестве ____________ (**альтернатива**) приемлемый материальный стимул.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'альтернативы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в литературе', 
                          title = '#### Решить проблему сверхпараметризации в VAR-моделях можно было несколькими способами, которые наиболее часто используются ____________ ____________ (**в, литература**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в литературе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'синонимов', 
                          title = '#### В данной статье понятия «счастье», «субъективные оценки благосостояния» и «удовлетворенность жизнью» используются в качестве ____________ (**синоним**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'синонимов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'досуг', 
                          title = '#### Для обозначения деятельности вне работы (такой, как прием пищи, сон, работа в саду, проведение времени с семьей и друзьями) экономисты используют термин ____________ (**досуг**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'досуг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'оценки', 
                          title = '#### Рассмотрим показатели, которые часто используются для ____________ (**оценка**) и сопоставления портфелей инвестиционных (финансовых) активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оценки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'бенчмарка', 
                          title = '#### Даже самые крупные и наиболее ликвидные выпуски не настолько ликвидны, чтобы использоваться в качестве ____________ (**бенчмарка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'бенчмарка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'трудности текста', 
                          title = '#### Тулдава (1975) предлагает свою формулу удобочитаемости и высказывает идею использовать для оценки ____________ ____________ (**трудность, текст**) дополнительный предиктор – количество многозначных слов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'трудности текста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'оптимальности', 
                          title = '#### Показатели налоговой квоты, чистой прибыли, налогового бремени могут использоваться для оценки ____________ (**оптимальность**) выбора систем налогообложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оптимальности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'капитала', 
                          title = '#### Под физическим капиталом, или просто капиталом, мы понимаем оборудование, здания и сооружения, используемые для производства ____________ (**капитал**) — товаров и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'капитала',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'другого', 
                          title = '#### Среди предпосылок теоремы Столпера-Самуэльсона значатся: 1) торговля является свободной — государства воздерживаются от установления тарифов и других торговых ограничений; 2) ни один из товаров не используется для производства ____________ (**другой**); 3) количество (предложение) факторов не может быть изменено.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'другого',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'бакалаврских', 
                          title = '#### Материалы диссертации использованы при разработке ____________ (**бакалаврский**) курсов экономического факультета МГУ имени М.В. Ломоносова «Модели экономического роста» и «Методы оптимальных решений» и в настоящее время применяются в их преподавании.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'бакалаврских',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных', 
                          title = '#### На современном этапе институт жалоб активно используется в ____________ (**социальный**) государствах и включает легальные формы общественного протеста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конкурентной продукции', 
                          title = '#### Фермеры получают ценовую поддержку только там, где земля постоянно используется для производства ____________ ____________ (**конкурентный, продукция**), например пшеницы или кукурузы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конкурентной продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'въезда', 
                          title = '#### Термин «открытый порт» применяется для обозначения морских портов, аэропортов, станций и сухопутных мест пересечения государственной границы гражданами, товарами или транспортными средствами, которые используются для ____________ (**въезд**) в страну или выезда из страны (Государственные Положения функционирования открытых портов от 18.09.1985, принятые Госсоветом).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'въезда',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промежуточной', 
                          title = '#### Дж. Кейнс, по имени которого получил название данный эффект, дал ему объяснение, используя в качестве ____________ (**промежуточный**) переменной ставку процента по кредитам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промежуточной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'физики', 
                          title = '#### Некоторые экономисты используют термин «гистерезис», заимствованный из ____________ (**физик**), для описания поведения европейской безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'физики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

