```{r}
checkdown::check_question(answer = 'мировой финансовой системы', 
                          title = 'В итоговом коммюнике говорится о необходимости обеспечить прозрачность ____________ (**мировой, финансовый, система**), а также установить жесткий контроль над работой мировых финансовых организаций, таких как Всемирный банк и Международный валютный фонд.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировых финансовых рынков', 
                          title = 'Наиболее известные инвестиционные дома являются активными участниками ____________ (**мировой, финансовый, рынок**), господствуя, в частности, на рынках еврооблигаций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировых финансовых рынков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировых рынках', 
                          title = 'Если несколько стран вывозят один и тот же товар и каждая из них принимает меры к увеличению экспорта, то предложение этого товара ____________ (**на, мировой, рынок**) может превышать спрос и понижать экспортные цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировых цен на', 
                          title = 'Наличие данной тенденции обусловлено сокращением потребления рыбной продукции на внутреннем рынке вследствие появления в структуре пищевого рациона населения страны большого ассортимента «легких в приготовлении» мясных продуктов, а также повышения ____________ (**мировой, цена, на**) морепродукты, инициированного увеличением объемов потребления рыбы и морепродуктов в Китае, Европе и США.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировых цен на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития мировой экономики', 
                          title = 'Российская модель управления пространственным развитием не отражает современных тенденций ____________ (**развитие, мировой, экономика**), основанных на усилении конкуренции на всех уровнях управления -предпринимательском, региональном, муниципальном, а также конкуренции между странами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития мировой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой валютной системы', 
                          title = 'Выдвигаются и более смелые идеи о создании единой ____________ (**мировой, валютный, система**) и мирового центрального банка.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой валютной системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой финансовый рынок', 
                          title = 'Финансовый капитал может без ограничений пе ремещаться с внутреннего на ____________ (**мировой, финансовый, рынок**), и наоборот.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовый рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировые рынки', 
                          title = 'Научные открытия, передовые технологии позволили вывести (и продолжают выводить) ____________ (**на, мировой, рынок**) новые природные ресурсы и их заменители, а также вызывают изменение структуры спроса на сырье, материалы, полуфабрикаты, комплектующие и другие товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировые рынки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировой арене', 
                          title = 'Международное образование в таком контексте видится инструментом интеграции в мировое научное и образовательное сообщество, работает на повышение престижа страны ____________ (**на, мировой, арена**) и на формирование национальных элит, способствует накоплению человеческого капитала, который, в свою очередь, гарантирует государствам развитие «экономики знаний» в долгосрочной перспективе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировой арене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста мировой экономики', 
                          title = 'Среднегодовые темпы ____________ (**рост, мировой, экономика**) оцениваются на уровне 3,7-3,8%, т.е. для достижения поставленных целей темпы роста российской экономики должны составлять как минимум 3,9-4%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста мировой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировые рынки', 
                          title = 'В связи с этим строительство заводов по сжижению газа на Сахалине, а в перспективе и на Кольском полуострове является не только технологическим прорывом для России, но и важнейшим шагом в диверсификации поставок ____________ (**на, мировой, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировые рынки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в мировой экономике', 
                          title = 'Помимо технологического развития важно учитывать и масштабы страны, так как это говорит о ее влиятельности ____________ (**в, мировой, экономика**) и научном сообществе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в мировой экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стороны мирового товарного рынка', 
                          title = 'В торговую компоненту валютного канала включается то, как изменение условий со ____________ (**сторона, мировой, товарный, рынок**) отражается на изменении курса валюты и показателя чистого экспорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стороны мирового товарного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой финансовый кризис', 
                          title = 'Эти институты, так же как и Всемирная торговая организация, полагаясь в основном на Вашингтонский консенсус, не смогли достигнуть в существенном плане поставленных перед ними целей по улучшению уровня жизни основной массы населения планеты даже в развитом мире и тем более стабилизировать глобальную экономику, чему свидетельством является развивающийся ____________ (**мировой, финансовый, кризис**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовый кризис',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в мировой торговле', 
                          title = 'Особую группу оптовых банков составляют акцептные дома, предоставлякицие акцентные кредиты во внешней и внутренней торговле, однако ____________ (**в, мировой, торговля**) в последнее время такие кредиты используются редко.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в мировой торговле',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировые рынки', 
                          title = 'Структурная перестройка экономики Якутии предполагается в первую очередь за счет ускоренного роста отраслей топливно-энергетического комплекса, ориентированных ____________ (**на, мировой, рынок**) нефти и газа (в том числе за счет освоения и выхода на проектную мощность Талаканского нефтегазоконденсатного и Чаяндинского газоконденсатного месторождений).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировые рынки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировых рынках', 
                          title = 'Проведенные обследования показывают, что 8% продукции, появившейся в конце 70-х годов ____________ (**на, мировой, рынок**), являлось принципиально новой по своим свойствам и 12% — новой по технологии изготовления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в мировой практике', 
                          title = 'Поэтому объективному и долговременному разграничению доходов между бюджетами всех уровней способствовало бы сочетание двух применяемых ____________ (**в, мировой, практика**) способов. Первый сводится к четкому разделению конкретных налогов на федеральные, региональные и местные. Второй способ предусматривает установление местных надбавок к действующим федеральным и региональным налогам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в мировой практике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мирового экономического кризиса', 
                          title = 'Во время ____________ (**мировой, экономический, кризис**) 1929–1933 гг. Германия, Франция и ряд других стран отказались в дальнейшем оплачивать свои долги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мирового экономического кризиса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой ставке процента', 
                          title = 'При неизменной ____________ (**мировой, ставка, процент**) инвестиции остаются на том же уровне.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой ставке процента',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировой рынок', 
                          title = 'В прошлом внешние инвестиции в накопление благородных металлов (денег) имели принципиальное значение для стран, лишенных возможности поставлять эти металлы (деньги) ____________ (**на, мировой, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировой рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в мировое хозяйство', 
                          title = 'Началом «большого подъема» Н. Кондратьев считал массовое внедрение в производство новых технологий, вовлечение новых стран ____________ (**в, мировой, хозяйство**), изменение объемов добычи золота.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в мировое хозяйство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой ставки процента', 
                          title = 'Объем инвестиций зависит от реальной ____________ (**мировой, ставка, процент**): высокие ставки процента делают некоторые инвестиционные проекты неприбыльными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой ставки процента',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировых цен на', 
                          title = 'Ханты-Мансийский и Ямало-Ненецкий автономные округа обеспечивают высокую производительность рабочих мест за счет конъюнктуры ____________ (**мировой, цена, на**) нефть и газ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировых цен на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировой арене', 
                          title = 'Благодаря значительным ресурсам возрастает политический вес государства ____________ (**на, мировой, арена**), появляется реальная возможность устанавливать свои правила игры на газовом рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировой арене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировые цены на', 
                          title = 'Важную роль в ухудшении ситуации в добывающих отраслях сыграло падение мировых цен на ряд сырьевых товаров, являющихся важными статьями экспорта ДРК. Так, ____________ (**мировой, цена, на**) медь и олово в 1990—1998 гг. были в среднем соответственно на 30% и 77% ниже уровня цен 1980 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировые цены на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировая цена на', 
                          title = 'Средняя ____________ (**мировой, цена, на**) продовольствие временно поднялась в начале 1970-х гг., но с тех пор неуклонно понижалась.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая цена на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировых рынках', 
                          title = 'Сдвиги в производственной базе и структуре спроса ____________ (**на, мировой, рынок**) вызвали значительные изменения в структуре экспорта и импорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падение мировых цен', 
                          title = 'Кризис 2014-2015 гг. отличался динамикой и структурными пропорциями от предыдущего кризиса, поскольку ____________ (**падение, мировой, цена**) на энергоресурсы наложилось на кардинальное изменение внешних условий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падение мировых цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой финансовый кризис', 
                          title = 'Вопреки распространенному мнению, не ____________ (**мировой, финансовый, кризис**) привел к падению строительной отрасли в России, а сложившаяся модель удовлетворения жилищного спроса исчерпала себя и вызвала кризисные процессы на российском жилищном рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовый кризис',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мирового товарного рынка', 
                          title = 'В торговую компоненту валютного канала включается то, как изменение условий со стороны ____________ (**мировой, товарный, рынок**) отражается на изменении курса валюты и показателя чистого экспорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мирового товарного рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития мировой экономики', 
                          title = 'Крайне важно рассмотреть объективную природу современных конъюнктурных колебаний для того, чтобы понять логику ____________ (**развитие, мировой, экономика**) после азиатского финансового кризиса 1997-1998 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития мировой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в мировую экономику', 
                          title = 'Стратегический план может быть ориентирован на достижение следующих трех стратегических целей: создание благоприятного климата для бизнеса; интеграция ____________ (**в, мировой, экономика**); улучшение социальной среды.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в мировую экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой финансовой системы', 
                          title = 'Отсутствовали, таким образом, органы постоянного мониторинга за развитием ____________ (**мировой, финансовый, система**), вырабатывающие принципы ее функциопирования и оказывающие финансовую помощь отдельным странам для решения их экономических проблем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой финансовой системе', 
                          title = 'Существующий порядок в ____________ (**мировой, финансовый, система**) отвечает интересам стран, финансовые институты которых занимают в ней ведущее положение и могут получать выгоды за счет слабейших.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовой системе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в мировом производстве', 
                          title = 'Асимметричная зависимость развивающихся стран от Запада выступает следствием структуры их производительных сил, что создает противоречивые тенденции ____________ (**в, мировой, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в мировом производстве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой финансовой системе', 
                          title = 'Существующий порядок в ____________ (**мировой, финансовый, система**) отвечает интересам стран, финансовые институты которых занимают в ней ведущее положение и могут получать выгоды за счет слабейших, нанося им ущерб.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовой системе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировой рынок', 
                          title = 'Как эти квоты подействовали ____________ (**на, мировой, рынок**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировой рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировая цена на', 
                          title = 'Но что происходит в случае, когда экономика США открыта для торговли и ____________ (**мировой, цена, на**) алюминий выше или ниже внутренней цены в долларах?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая цена на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой финансовый рынок', 
                          title = 'Если для крупных предприятий альтернативой могло бы стать возобновление доступа на ____________ (**мировой, финансовый, рынок**), то среднему бизнесу приходится уповать только на российские деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовый рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой ставки процента', 
                          title = 'Наша открытая экономика столь мала, что почти не оказывает воздействия на величину ____________ (**мировой, ставка, процент**), так как ее инвестиции и сбережения - лишь незначительная часть мировых сбережений и мировых инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой ставки процента',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировых рынках', 
                          title = 'Экономический рост 1999-2006 гг. был на три четверти обусловлен благоприятной конъюнктурой ____________ (**на, мировой, рынок**) топлива и сырья.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой ставке процента', 
                          title = 'В малой открытой экономике реальная ставка процента равна реальной ____________ (**мировой, ставка, процент**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой ставке процента',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировом рынке', 
                          title = 'В развивающихся странах появились новые моменты в развитии внешнеэкономических связей, определяемые неблагоприятной для них ситуацией ____________ (**на, мировой, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировом рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировой рынок', 
                          title = 'На самом же деле правительство опасалось того, что производители, получив право выхода ____________ (**на, мировой, рынок**), почувствуют свою независимость от государства и вновь начнут бороться против власти.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировой рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мирового финансового кризиса', 
                          title = 'Из общего числа опрошенных руководителей малых и средних предприятий (3365) провинции Чжэцзян 157 чел. считают, что их предприятия не подверглись влиянию ____________ (**мировой, финансовый, кризис**), 2280 - полагают его влияние несущественным, 916 - признают сильное влияние кризиса на свои предприятия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мирового финансового кризиса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мирового спроса на', 
                          title = 'Вследствие вялости ____________ (**мировой, спрос, на**) товары и услуги и ужесточения кредитной политики банков объемы экспорта из стран БРИКС существенно снизились.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мирового спроса на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой валютной системы', 
                          title = 'Вследствие этих процессов система погашения обязательств по международным (внешним) долгам государств находится в стадии реформирования, а ее организационные структуры переживают этап трансформации, вызванный дестабилизацией ____________ (**мировой, валютный, система**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой валютной системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в мировое хозяйство', 
                          title = 'Важной сферой преобразований экономики России являются международные валютные отношения, поскольку взят курс на интеграцию ____________ (**в, мировой, хозяйство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в мировое хозяйство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста мировой экономики', 
                          title = 'Опережающее увеличение объема денежных потоков и накопленных финансовых активов по сравнению с темпами ____________ (**рост, мировой, экономика**) стало характерной чертой развития современной мировой валютно-финансовой системы на протяжении нескольких десятилетий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста мировой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

