```{r}
checkdown::check_question(answer = 'национальный', 
                          title = '#### Сегодня термин «валовой ____________ (**национальный**) продукт» (ВНП) принят во всем мире, но в начале 20 века он игнорировался.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального дохода', 
                          title = '#### Модель определяет норму роста инвестиций, обеспечивающую необходимое увеличение ____________ (**национальный, доход**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальных сбережений', 
                          title = '#### Желаемые национальные сбережения определяются как уровень ____________ (**национальный, сбережение**), который достигается, когда совокупное предложение в стране находится на желаемом уровне.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальных сбережений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального богатства', 
                          title = '#### Ощущение несправедливого распределения ____________ (**национальный, богатство**) способствовало росту популизма.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального богатства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальную экономику', 
                          title = '#### Государственные сбережения вкладываются в ____________ (**национальный, экономика**) и становятся дополнительным источником инвестиций для предприятий реального сектора национальной экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальную экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального', 
                          title = '#### При расчете индекса человеческого развития (ИЧР) суммируется влияние трех основных компонент: индекса ожидаемой продолжительности жизни, индекса образования, индекса валового ____________ (**национальный**) дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальных', 
                          title = '#### В каждой отдельно взятой стране валовой внутренний продукт подсчитывается на основе системы ____________ (**национальный**) счетов, которая построена на концепции производительного характера всех видов деятельности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной валюты', 
                          title = '#### Фиксируются систематические интервенции центральных банков в Латинской Америке для предотвращения укрепления курса ____________ (**национальный, валюта**) после глобального финансового кризиса 2008–2009 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной валюты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Уровень цен и валютного курса является лишь одной из характеристик конкурентоспособности ____________ (**национальный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'системе национальных счетов', 
                          title = '#### Работа по дому точно так же становится субститутом рабочих часов, но, в отличие от рыночного производства, она не учитывается в ____________ (**система, национальный, счет**), то есть в ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'системе национальных счетов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальную', 
                          title = '#### Даже незначительное повышение процентных ставок приводит к неограниченному притоку капитала, давлению на ____________ (**национальный**) валюту в сторону ее удорожания.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальную',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной безопасности', 
                          title = '#### Закон был принят для повышения экономической самодостаточности страны и ее ____________ (**национальный, безопасность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной безопасности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального', 
                          title = '#### Основные методы мобилизации ____________ (**национальный**) дохода в процессе его перераспределения при формировании фондов — специальные налоги и сборы, средства из бюджета и займы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального производства', 
                          title = '#### Что определяет реальный объем ____________ (**национальный, производство**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на национальном уровне', 
                          title = '#### Разница в регулировании криптовалют ____________ (**на, национальный, уровень**) снижает эффективность регуляторных мер: ужесточение законодательства в одной стране приводит к перетоку операций в более дружественные страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на национальном уровне',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной безопасности', 
                          title = '#### Многие страны ограничивают прямые иностранные инвестиции под предлогом обеспечения ____________ (**национальный, безопасность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной безопасности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной валюты', 
                          title = '#### Управление курсом ____________ (**национальный, валюта**) используется разными странами в надежде стимулировать рост экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной валюты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фонда национального благосостояния', 
                          title = '#### Объем ____________ (**фонд, национальный, благосостояние**) за месяц сократился на 7%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фонда национального благосостояния',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной валюты', 
                          title = '#### Доллар – это показатель обменного курса ____________ (**национальный, валюта**) и ее покупательной способности по отношению к импортным товарам и услугам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной валюты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальном', 
                          title = '#### Заказанный по интернету товар могут доставить из любого города, поэтому потребитель привык, что цены должны быть везде одинаковыми. Это выравнивает цены на ____________ (**национальный**) уровне и делает их намного менее чувствительными к локальным шокам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальном',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальный', 
                          title = '#### В Греции, Португалии ____________ (**национальный**) доход на душу населения не превышает 70% среднего показателя для всех стран Евросоюза.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального дохода', 
                          title = '#### Мы можем с уверенностью говорить о том, что инвестированные государством 100 млн дол. в конечном итоге вызвали прирост ____________ (**национальный, доход**) на 200 млн дол.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Государство может пойти и на большую открытость ____________ (**национальный, экономика**) по отношению к мировому рынку, снизив таможенные пошлины и создав конкуренцию национальным производителям.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономике', 
                          title = '#### Распределение между городским и сельским населением и доля сельского хозяйства в ____________ (**национальный, экономика**) влияют на масштабы теневой экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальных', 
                          title = '#### Рост бюджетного дефицита сдвигает кривую желаемых ____________ (**национальный**) сбережений влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальную', 
                          title = '#### Очень важно учитывать последствия иностранного влияния на ____________ (**национальный**) экономику, так как довольно малый объем инвестиций в страну может вызвать серьезные изменения в структуре ее экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальную',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального дохода', 
                          title = '#### Инфляция нарушает распределение ____________ (**национальный, доход**) между трудом и капиталом в пользу капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального производства', 
                          title = '#### Динамика инвестиций является фактором, влияющим в будущем на объем ____________ (**национальный, производство**), уровень занятости и потребления населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальную денежную единицу', 
                          title = '#### В хозяйственном обороте современной Франции банкноты и монеты евро заменили ____________ (**национальный, денежный, единица**) – французский франк.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальную денежную единицу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальное', 
                          title = '#### Все ключевые макроэкономические показатели, которые мы рассмотрели (ВВП, составные части доходов и расходов, ____________ (**национальный**) богатство и сбережения), измерялись по их текущей рыночной стоимости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальное',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной валюты', 
                          title = '#### Центральные банки стремятся свести к минимуму колебания валютных курсов, поскольку обесценение ____________ (**национальный, валюта**) приводит к росту ожидаемой и фактической инфляции выше целевого показателя.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной валюты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Выявлены закономерности развития ____________ (**национальный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальный', 
                          title = '#### Под теневой экономикой понимается экономическая деятельность, которая не учитывается официальной статистикой и не включается в валовой ____________ (**национальный**) продукт. В международной практике нелегальную экономическую деятельность называют shadow economy (теневая экономика).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной безопасности', 
                          title = '#### Иностранные прямые капиталовложения ограничиваются только исходя из интересов ____________ (**национальный, безопасность**) в ряде отраслей добывающей и обрабатывающей промышленности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной безопасности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной', 
                          title = '#### Наука и высшее образование играют большую роль в обеспечении ____________ (**национальный**) безопасности страны .',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной валюты', 
                          title = '#### Под валютным кризисом подразумевается существенный рост спроса на иностранную валюту, следствием которого выступают увеличение обменного курса ____________ (**национальный, валюта**), рост валютных интервенций, рост процентных ставок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной валюты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Когда экономика устойчиво растет, тогда улучшается ситуация в большинстве отраслей ____________ (**национальный, экономика**), увеличивается благосостояние и работников этих отраслей, и собственников капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальные сбережения', 
                          title = '#### Помимо влияния на ____________ (**национальный, сбережение**) и внутренние инвестиции, реаль­ная процентная ставка оказывает воздействие и на величину чистых иностранных инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальные сбережения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальных', 
                          title = '#### Рост инфляционных ожиданий в Европе и Центральной Азии был связан с повышением цен на продукты и на энергоресурсы, обесценением ____________ (**национальный**) валют и политической нестабильностью.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Экономическая безопасность— состояние защищенности ____________ (**национальный, экономика**) от внешних и внутренних угроз, при котором обеспечивается экономический суверенитет страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального', 
                          title = '#### Человеческий капитал обеспечивает около двух третей ____________ (**национальный**) богатства в мире.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на национальном уровне', 
                          title = '#### В странах Азии увеличивается неравенство ____________ (**на, национальный, уровень**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на национальном уровне',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной', 
                          title = '#### Установление курса ____________ (**национальный**) денежной единицы в иностранной валюте в данный момент называется валютной котировкой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Созданы условия для распространения достижений научно-технического прогресса на большинство отраслей ____________ (**национальный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальные сбережения', 
                          title = '#### Чтобы нейтрализовать отрицательное воздействие социального страхования на ____________ (**национальный, сбережение**), многие экономисты предлагают реформировать всю эту систему.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальные сбережения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальных сбережений', 
                          title = '#### Чистый экспорт равен чистым иностранным инвестициям, которые равняются раз­ности ____________ (**национальный, сбережение**) и внутренних инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальных сбережений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной валюты', 
                          title = '#### обесценение ____________ (**национальный, валюта**) может повысить конкурентоспособность экспортных товаров страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной валюты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной', 
                          title = '#### На уровне ____________ (**национальный**) экономики важно учитывать региональное распределение производства и конечного потребления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальных сбережений', 
                          title = '#### Что происходит с реальным обменным курсом если правительство снижает уровень ____________ (**национальный, сбережение**) за счет увеличения государственных закупок?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальных сбережений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'система национальных счетов', 
                          title = '#### Для анализа экономической деятельности государств применяется ____________ (**система, национальный, счет**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'система национальных счетов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальный', 
                          title = '#### Чистый ____________ (**национальный**) продукт - сумма конечных товаров и услуг, произведенных и приобретенных нацией за определенный период (за год) за вычетом той части инвестиций, которая пошла на замену устаревшего и износившегося оборудования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального', 
                          title = '#### счета ____________ (**национальный**) дохода являются логическим отражением структуры экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальная', 
                          title = '#### Приоритетными направлениями в развитии страны считаются ____________ (**национальный**) безопасность, ускоренное импортозамещение в технологической сфере, борьба с неравенством путем перераспределения ресурсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фонды национального благосостояния', 
                          title = '#### Центральные банки и суверенные ____________ (**фонд, национальный, благосостояние**) хранят свои международные резервы и активы в международных валютах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фонды национального благосостояния',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Внешние факторы экономического роста обусловлены статусом ____________ (**национальный, экономика**) на мировом рынке и внешнеэкономической ситуацией.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальные сбережения', 
                          title = '#### Равновесная реальная процентная ставка в закрытой экономике в данном случае составила бы 4%, а ____________ (**национальный, сбережение**) и инвестиции — $3 млрд.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальные сбережения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальных сбережений', 
                          title = '#### Потребители реагируют на снижение налогов увеличением потребления, и возникающий в результате снижения налогов дефицит будет уменьшать уровень ____________ (**национальный, сбережение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальных сбережений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной', 
                          title = '#### Страны используют «манипулирование» курсом ____________ (**национальный**) валюты или сглаживание его краткосрочных колебаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального', 
                          title = '#### Какие основные принципы распределения и перераспределения ____________ (**национальный**) дохода?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национального дохода', 
                          title = '#### Рассчитайте долю прироста ____________ (**национальный, доход**) страны за счет повышения производительности труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национального дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'системе национальных счетов', 
                          title = '#### Наше внимание будет сосредоточено не на функцио­yировании финансовых рынков, а на количественной оценке их параметров, то есть на ____________ (**система, национальный, счет**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'системе национальных счетов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'счета национального дохода', 
                          title = '#### Но ____________ (**счет, национальный, доход**) полезны также тем, что они обеспечивают нас концептуальной схемой для описания связей между тремя ключевыми макроэкономическими переменными — выпуском, доходами и расходами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'счета национального дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальные', 
                          title = '#### В состоянии равновесия желаемые инвестиции (спрос на сбережения) и желаемые ____________ (**национальный**) сбережения (предложение сбережений) должны быть равны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'валового национального продукта', 
                          title = '#### Легкая промышленность занимает одно из важных мест в производстве ____________ (**валовой, национальный, продукт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'валового национального продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной безопасности', 
                          title = '#### Никто не ставит под сомнение важность расхо­дов на обеспечение ____________ (**национальный, безопасность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной безопасности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной', 
                          title = '#### Шведский индекс потребительского доверия связан с динамикой потребления в ____________ (**национальный**) экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

