```{r}
checkdown::check_question(answer = 'налоговой нагрузки на', 
                          title = '#### Первое направление налоговой политики связано с уровнем и со структурой ____________ (**налоговый, нагрузка, на**) бизнес.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговой нагрузки на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного налогового кредита', 
                          title = '#### Предоставление ____________ (**инвестиционный, налоговый, кредит**) осуществляется на основании заявления организации и документации, подтверждающей основания для предоставления кредита.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного налогового кредита',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем налоговых поступлений', 
                          title = '#### Свертывание объемов производства работающих на экспорт товаропроизводителей и их доходов вызовет сокращение занятости и, как следствие, меньший ____________ (**объем, налоговый, поступление**) в бюджеты всех уровней.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем налоговых поступлений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в налоговом законодательстве', 
                          title = '#### В качестве изменений ____________ (**в, налоговый, законодательство**) в Китае следует отметить рост коэффициента квалифицированной рабочей силы на 14% и объема расходов на НИОКР.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в налоговом законодательстве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень налоговой нагрузки', 
                          title = '#### Экспортной составляющей экономики региона объясняются различия в уровне налоговой нагрузки в Красноярском крае (доля экспорта в ВРП в среднем за исследуемый период составила 33,4%) и Томской области (доля экспорта в ВРП - 8,7%), а также низкий ____________ (**уровень, налоговый, нагрузка**) в Республике Хакасии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень налоговой нагрузки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижения налоговой нагрузки', 
                          title = '#### Ожидается, что в перспективе наибольшего ____________ (**снижение, налоговый, нагрузка**) потребуют проекты, реализуемые на арктическом шельфе (вариант «Шельф»).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижения налоговой нагрузки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговые льготы в', 
                          title = '#### Для предприятий, работающих на территории Z-парк, предусмотрены: ____________ (**налоговый, льгота, в**) виде снижения налоговой ставки до 15%; налоговые вычеты по расходам до 50%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговые льготы в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговой нагрузки на', 
                          title = '#### Частичное уменьшение ____________ (**налоговый, нагрузка, на**) предприятие следует рассматривать как вклад государства (в рамках государственно-частного партнерства) в реализацию инновационно-инвестиционных проектов на промышленных предприятиях.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговой нагрузки на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговый кредит на', 
                          title = '#### Следует отметить, что вышеперечисленные налоговые льготы не уникальны, так как распространены и множество других налоговых льгот в сфере НИОКР, при применении которых общий ____________ (**налоговый, кредит, на**) проведение научных исследований не применяется.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговый кредит на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предоставление налоговых льгот', 
                          title = '#### Таким образом, ____________ (**предоставление, налоговый, льгота**) для участников строительной индустрии, позволило в короткие сроки обеспечить формирование и развитие столицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предоставление налоговых льгот',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиционного налогового кредита', 
                          title = '#### В Томской, Омской, Кемеровской областях, Красноярском и Забайкальского краях и Республике Бурятии приняты нормативные правовые акты, определяющие условия предоставления ____________ (**инвестиционный, налоговый, кредит**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиционного налогового кредита',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговые льготы в', 
                          title = '#### Подразумевается, что ____________ (**налоговый, льгота, в**) России, например, перенос убытков на будущие налоговые льготы, применяются в результате модернизации производства, приобретения нового высокотехнологичного оборудования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговые льготы в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в налоговых поступлениях', 
                          title = '#### Изменения ____________ (**в, налоговый, поступление**) и государственных расходах происходят автоматически.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в налоговых поступлениях',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговые поступления', 
                          title = '#### Разумеется, правительство использует эти____________ (**налоговый, поступление**) в 12,5 млн дол. на производство общественных товаров и услуг соответствующей стоимости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговые поступления',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговый кредит на', 
                          title = '#### Отрицательный подоходный налог напоминает ____________ (**налоговый, кредит, на**) заработанный доход, который позволяет работающим членам бедных семей получать возмещение подоходного налога, превышающее уплаченные в течение года налоги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговый кредит на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговых доходов в', 
                          title = '#### Потоки денежных средств в контуре «региональный актив - федеральный бюджет - региональные бюджеты» отражают локализацию ____________ (**налоговый, доход, в**) регионе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговых доходов в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговых поступлений от', 
                          title = '#### До этого времени около 35% доходной части консолидированного бюджета Омской области формировалось за счет ____________ (**налоговый, поступление, от**) «Сибнефти», соответственно, бюджет региона недополучил в 2006 г. более 8 млрд руб.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговых поступлений от',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговые льготы в', 
                          title = '#### По оценке экспертов РСПП, ключевая причина низкого спроса со стороны предприятий на ____________ (**налоговый, льгота, в**) инновационной деятельности - несоответствие условиям применения налоговых льгот.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговые льготы в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'федеральной налоговой службы', 
                          title = '#### Исправлением «некондиционной» (неполной) информации путем обхода каждого потенциального плательщика должны были заняться сотрудники администраций муниципальных органов власти при поддержке ____________ (**федеральный, налоговый, служба**) и Росреестра.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'федеральной налоговой службы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'распределение налогового бремени', 
                          title = '#### На положительное отношение граждан и предприятий к местным властям влияет ____________ (**распределение, налоговый, бремя**) между местным населением и деловым сектором, хотя боязнь загрязнения окружающей среды часто заставляет местные власти выступать против создания новых промышленных предприятий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'распределение налогового бремени',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижение налоговой нагрузки', 
                          title = '#### Некоторые источники утверждают, что налоговые льготы способствуют уязвимости экономики, так как ____________ (**снижение, налоговый, нагрузка**) для бизнеса может вызвать значительный рост государственных заимствований для обслуживания текущих обязательств в ближайшие годы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение налоговой нагрузки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'специальных налоговых режимов', 
                          title = '#### В.Г. Басарева группы предлагают сохранить все виды ____________ (**специальный, налоговый, режим**) для субъектов малого бизнеса: «Целесообразно сохранить все виды специальных налоговых режимов для субъектов малого и среднего предпринимательства. Это не только позволит сохранить налоговые поступления от этой категории бизнеса, но и сохранит лояльность предпринимательского сообщества к власти и будет способствовать укреплению традиций легальности в российском бизнесе».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'специальных налоговых режимов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговых льгот в', 
                          title = '#### Следующим весьма распространенным видом ____________ (**налоговый, льгота, в**) Казахстане являются налоговые освобождения, которые в основном распространяются на налог на прибыль.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговых льгот в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговые льготы для', 
                          title = '#### Предложены ____________ (**налоговый, льгота, для**) производителей цифрового оборудования из РФ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговые льготы для',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижения налоговых ставок', 
                          title = '#### Если говорить о стимулах к труду, то исследования свидетельствуют: в результате ____________ (**снижение, налоговый, ставка**) одни люди работают больше, а другие — меньше.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижения налоговых ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в налоговых поступлениях', 
                          title = '#### Доля налоговой задолженности ____________ (**в, налоговый, поступление**) в Томской области (3,8%) почти в 22 раза ниже, чем в Забайкальском крае (85,6%).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в налоговых поступлениях',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'часть налогового бремени', 
                          title = '#### Группы, которые держат под контролем цены на предлагаемые ими услуги, имеют возможность переложить ____________ (**часть, налоговый, бремя**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'часть налогового бремени',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговых поступлений в', 
                          title = '#### Несмотря на существенное сокращение объема промышленного производства с начала рыночных реформ, сегодня город располагает значительным промышленным потенциалом, составляющим весомую долю в общероссийском производстве, обеспечивающим стабильную занятость и являющимся источником ____________ (**налоговый, поступление, в**) городской бюджет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговых поступлений в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная налоговая ставка', 
                          title = '#### Так как ____________ (**предельный, налоговый, ставка**) по мере увеличения дохода возрастает, высокообеспеченные семьи выплачивают правительству значительную часть дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная налоговая ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговой системы в', 
                          title = '#### Принятый в конце 1991 г. Федеральный закон «Об основах ____________ (**налоговый, система, в**) Российской Федерации» предусматривал 23 местных налога, перечень которых был закрытым.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговой системы в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'часть налогового бремени', 
                          title = '#### Несмотря на то, что весь налог вносится в госбюджет продавцами, ____________ (**часть, налоговый, бремя**) ложится на покупателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'часть налогового бремени',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предоставление налоговых льгот', 
                          title = '#### Для снижения налоговой нагрузки также целесообразно практиковать финансовое стимулирование экоинновационных процессов (зачеты экологических платежей в размере осуществленных природоохранных затрат, ____________ (**предоставление, налоговый, льгота**) и каникул, дифференциация налоговых ставок и их проциклический характер) при внедрении наилучших существующих технологий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предоставление налоговых льгот',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'проявления региональной налоговой политики', 
                          title = '#### Можно предположить, что это ____________ (**проявление, региональный, налоговый, политика**) в сфере налогового контроля, которая в отличие от региональной налоговой политики в сфере налогового регулирования не декларируется и законодательно не оформляется.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'проявления региональной налоговой политики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предоставления налоговых льгот', 
                          title = '#### Охарактеризуем региональную налоговую политику субъектов СФО в сфере налогового регулирования через сравнительный анализ эффективности ____________ (**предоставление, налоговый, льгота**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предоставления налоговых льгот',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговых платежей в', 
                          title = '#### Показатели вклада отражают долю вкладов, поступающих в федеральный бюджет за счет ____________ (**налоговый, платеж, в**) регионе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговых платежей в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижение налоговых ставок', 
                          title = '#### Рост ставок налога на прибыль корпораций смещают кривую спроса на капитал вниз-влево, так как ослабляются стимулы к инвестированию. И, наоборот, ____________ (**снижение, налоговый, ставка**) и введение налоговых льгот сместят кривую спроса на капитал в правостороннем направлении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение налоговых ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня налоговой нагрузки', 
                          title = '#### Определенную роль в дифференциации ____________ (**уровень, налоговый, нагрузка**) играет отраслевая специфика субъектов, и в первую очередь внешнеэкономическая деятельность налогоплательщиков, функционирующих на территории того или иного субъекта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня налоговой нагрузки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговых льгот в', 
                          title = '#### Следует отметить существенные отличия применения ____________ (**налоговый, льгота, в**) России и зарубежных странах, в США, например, и по смыслу, и по условиям применения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговых льгот в',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налоговых льгот для', 
                          title = '#### В этом случае предполагается законодательное установление таких ____________ (**налоговый, льгота, для**) инвесторов — держателей внешнего долга, которые побудили бы их к инвестициям.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налоговых льгот для',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижение налоговой нагрузки', 
                          title = '#### Намечались общее ____________ (**снижение, налоговый, нагрузка**) на экономику и концентрация дефицита бюджетной системы и государственного долга на федеральном уровне, что также способствовало бы самостоятельности регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение налоговой нагрузки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'налогового бремени на', 
                          title = '#### Экономисты сводят многие налоговые льготы, оказывающие воздействие на величину инвестиций, в единый измеритель ____________ (**налоговый, бремя, на**) капитал, называемый эффективной налоговой ставкой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'налогового бремени на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

