```{r}
checkdown::check_question(answer = 'ожидаемая; продолжительность; жизни; населения', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; продолжительность; жизни; населения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ожидаемая; норма; чистой; прибыли', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; норма; чистой; прибыли',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ожидаемая; реальная; процентная; ставка', 
                          title = '#### Поставьте слова в правильном порядке:',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая; реальная; процентная; ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

