```{r}
checkdown::check_question(answer = 'камеру', 
                          title = '#### Подобная стратегия также используется при торговле камерами «Polaroid» (вы платите за ____________ (**камера**), позволяющую вам продуктивно использовать пленку, которую вы покупаете целыми упаковками).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'камеру',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товар', 
                          title = '#### Потре­бительский излишек — сумма, которую потребители готовы заплатить за ____________ (**товара**) за вычетом суммы, которую они действительно платят.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товар',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'него', 
                          title = '#### Базисная, фундаментальная стоимость актива (asset’s fundamental value) определяется как цена, которую должны заплатить за ____________ (**он**) хорошо осведомленные инвесторы на рынке, где действуют законы свободной конкуренции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'него',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фактор производства', 
                          title = '#### Экономическая рента — это та сумма, которую фирмы готовы заплатить за ____________ ____________ (**фактор, производство**), за вычетом минимальной суммы, необходимой для его покупки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактор производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'страховку', 
                          title = '#### Страхование предполагает выплату страхового взноса, или премии (цены, которую вы платите за ____________ (**страховка**)) с целью избежать убытков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'страховку',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

