```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'В 4 раза увеличился объем производства тяжелой и добывающей промышленности, в 1,9 раза увеличилось производство потребительских товаров. Существенную долю общего ____________ (**объем, производство**) составляли экспортные поставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы производства', 
                          title = 'В долговременном периоде, по определению, все ____________ (**фактор, производство**) являются переменными. Краткосрочный период, напротив, определяется как промежуток времени, в течение которого один или более факторов производства невозможно изменить.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Излишек производителя определяет сумма общей прибыли производителей и рентных доходов от ____________ (**фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширения производства', 
                          title = 'Товарное производство застывает в своем развитии, поскольку исчезают стимулы для ____________ (**расширение, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширения производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внутреннего производства', 
                          title = 'В то же время спрос на товары ____________ (**внутренний, производство**), наряду с расходами резидентов, теперь включает в себя и экспорт, т.е. внешний спрос.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутреннего производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Постройте по этим точкам кривую продуктовой трансформации (границу ____________ (**производственный, возможность**)).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Хотя снижение ____________ (**объем, производство**), что вполне понятно, уменьшает величину предложения товаров, оно также уменьшает и величину спроса на товары. Причиной этого является то, что снижение объема производства означает также и снижение величины доходов, которое приводит к падению величины желаемого потребления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производством и потреблением', 
                          title = 'Рыночный капитализм нестабилен в своей основе и не существует никакого автоматического механизма, который мог бы обеспечивать занятость и равновесие между ____________ (**производство, и, потребление**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производством и потреблением',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'имеет место убывающая отдача от масштаба в производстве обоих благ; б) если нарушается допущение об однородности факторов (например, один из ____________ (**фактор, производство**) имеет убывающую производительность в производстве какого-либо блага); в) при допущении об однородности факторов и посто-',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторами производства', 
                          title = 'В этой модели уровень дохода определяется используемыми ____________ (**фактор, производство**) и применяемой технологией, а распределение дохода между домашними хозяйствами определяется величиной предельных продуктов факторов производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторами производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в структуре производства', 
                          title = 'По мере из­менений ____________ (**в, структура, производство**) в одних компаниях создавались рабочие места, а в других они сокращались. Результатом этих процессов стал рост производитель­ности труда и повышение уровня жизни населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в структуре производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства продукции', 
                          title = 'Предприятие зависит от поставок изделий, необходимых для ____________ (**производство, продукция**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы производства', 
                          title = 'Спрос на ____________ (**фактор, производство**) является исходным спросом. То есть спрос фирмы на факторы производства исходит из решения об объеме производства третьего товара, который предполагается поставлять на некий ры­нок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Выгоды изначально оцениваются в рыночных ценах выпускаемой в рамках проекта продукции, затраты - в рыночных ценах используемых ____________ (**фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне производства', 
                          title = 'Минимум на этой кривой наблюдается при ____________ (**уровень, производство**) Q0.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'Транспортные средства 8,6 8,2 12,6 Источник: UNCTAD handbook of statistics. 2000; Industrial development global report. В результате увеличилась доля средств производства в общем объеме продукции обрабатывающей промышленности, отмечалось увеличение доли развивающихся стран в мировом производстве средств производства. Наибольшие сдвиги произошли в выпуске базовых и промежуточных товаров. Так, выпуск черных металлов достиг 17%, промышленных химикатов — 13,3%, резины — 17,9%, продуктов нефтепереработки — порядка 40%. Однако в 90-е годы не отмечалось заметного перелива капитала в отрасли, производящие орудия труда. Доля машин (неэлектрические и электрические машины) в мировом производстве соответствующей продукции осталась на прежнем уровне. Исключение составило производство транспортных средств (табл. 28.2). Не только внутренние, но и внешние факторы содействовали индустриальному развитию. В последние десятилетия отмечался процесс перемЕщения из западных стран в развивающиеся трудоинтенсивных производств, химических базовых продуктов с последующим их экспортом. Это было обусловлено стремлением ТНК западных стран повысить конкурентоспособность своей продукции за счет дешевой рабочей силы, снизить отрицательное воздействие ряда производств на окружающую среду в своих странах.', 
                          title = 'Увеличилась доля средств производства в общем объеме продукции обрабатывающей промышленности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'Транспортные средства 8,6 8,2 12,6 Источник: UNCTAD handbook of statistics. 2000; Industrial development global report. В результате увеличилась доля средств производства в общем объеме продукции обрабатывающей промышленности, отмечалось увеличение доли развивающихся стран в мировом производстве средств производства. Наибольшие сдвиги произошли в выпуске базовых и промежуточных товаров. Так, выпуск черных металлов достиг 17%, промышленных химикатов — 13,3%, резины — 17,9%, продуктов нефтепереработки — порядка 40%. Однако в 90-е годы не отмечалось заметного перелива капитала в отрасли, производящие орудия труда. Доля машин (неэлектрические и электрические машины) в мировом производстве соответствующей продукции осталась на прежнем уровне. Исключение составило производство транспортных средств (табл. 28.2). Не только внутренние, но и внешние факторы содействовали индустриальному развитию. В последние десятилетия отмечался процесс перемЕщения из западных стран в развивающиеся трудоинтенсивных производств, химических базовых продуктов с последующим их экспортом. Это было обусловлено стремлением ТНК западных стран повысить конкурентоспособность своей продукции за счет дешевой рабочей силы, снизить отрицательное воздействие ряда производств на окружающую среду в своих странах.',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'Машиностроение занимает ведущее положение в структуре ____________ (**промышленный, производство**). На него приходится около 50% занятых в сфере промышленного производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фактора производства', 
                          title = 'Если фирма покупает какой-то вид ресурса, который не покупают другие фирмы, она, вероятнее всего, является монопсонистом на рынке данного ____________ (**фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактора производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'Устанавливаются цены на уровне предельных ____________ (**издержка, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень производства', 
                          title = 'Изменение фискальной политики увеличивает совокупный спрос на товары и ____________ (**уровень, производство**) при полной занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эффективности производства', 
                          title = 'Вливаются инвестиции в повышение ____________ (**эффективность, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффективности производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в производстве которых', 
                          title = 'Поскольку спрос на факторы производства является производным от спроса на блага, ____________ (**в, производство, который**) он используется, спрос на факторы и их цены зависят и от стро­ения рынка факторов, и от строения рынка благ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в производстве которых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Использование трудовых ресурсов (и капитала) в проекте сопряжено с определенными альтернативными затратами (opportunity costs) вследствие наличия иных, более эффективных способов использования ____________ (**фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Кривая LM наклонена вверх, потому что увеличение ____________ (**объем, производство**) вызывает увеличение спроса на деньги, приводя к росту реальной процентной ставки, необходимой для обеспечения равновесия на рынке активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривую производственных возможностей', 
                          title = 'Построим ____________ (**кривая, производственный, возможность**) двух государств.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривую производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Затраты труда прямо связаны с издержками производства фирмы: чем меньше количество затраченных часов, тем меньше предельные и средние ____________ (**издержка, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объеме производства', 
                          title = 'Работники также могут достаточно быстро решить - оставить прежнюю работу или наняться на какую-то другую новую. Поэтому изменения в ____________ (**объем, производство**) год от года могут часто следовать за изменениями занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объеме производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'Объем ____________ (**промышленный, производство**) в физическом выражении удвоился, несмотря на негативные для экономики процессы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'Прежде всего выясним, какой ____________ (**объем, производство**) может быть с меньшими затратами произведен одной фирмой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Может ли средняя производительность труда падать при увеличении общего ____________ (**объем, производство**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривая производственных возможностей', 
                          title = 'Таким образом, когда растет предложение ресурсов или совершенствуются технологии и техника, ____________ (**кривая, производственный, возможность**) смещается вверх и вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'затраты на производство', 
                          title = 'Если цена выше уровня средних издержек, т. е. компенсируются все ____________ (**затрата, на, производство**) и обеспечивается получение нормальной прибыли, предприниматель получает прибыль.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'затраты на производство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производстве товара', 
                          title = 'Фирма использует в ____________ (**производство, товар**) капитал (К) и труд (L).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производстве товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обрабатывающих производств', 
                          title = 'В целом доля ____________ (**обрабатывать, производство**) в структуре ВРП сократилась даже по сравнению с 2009 г. и составила 29,5%, но при этом доля производств по добыче полезных ископаемых выросла более чем в 2 раза.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обрабатывающих производств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства единицы продукции', 
                          title = 'Технология изготовления продукции такова, что фирма использует в производстве 3 единицы ресурса А и 1 единицу ресурса В для ____________ (**производство, единица, продукция**). Стоимость единицы ресурса А — 1 долл., а единицы ресурса В — 2 долл.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства единицы продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Долгосрочные средние ____________ (**издержка, производство**) остаются неизменными: при любом уровне производства они равны $10 на единицу продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства продукции', 
                          title = 'Увеличение ____________ (**производство, продукция**) в этом случае определяется двумя факторами: приращением труда и приращением капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'используемые в производстве', 
                          title = 'Экстенсивный рост происходит за счет увеличения количества ресурсов, используемых в производстве.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'используемые в производстве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рост производства', 
                          title = 'Попавшие в долговой кризис страны в целях выравнивания платежного баланса сократили импорт, что вызвало ряд взаимосвязанных неблагоприятных последствий. Сокращение ввоза средств производства, сырья и материалов повлекло за собой снижение нормы накопления, а это сдерживало ____________ (**рост, производство**) и экспорта. В итоге из-за снижения темпов роста экономики кризисные страны оказались отброшенными на десять лет по уровню экономического развития.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек на производство', 
                          title = 'Предельная норма трансформации в любой точке кривой предела производственных возможностей равно соотношению предельных ____________ (**издержка, на, производство**) одежды  и предельных издержек на производство продуктов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек на производство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'необходимых для производства', 
                          title = 'В этой главе мы поговорим о рынках факторов производства (factor markets): труда, сырья и других ____________ (**необходимый, для, производство**) ресурсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'необходимых для производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ростом производства', 
                          title = 'Рост спроса ведет к немедленному росту производства, рост дохода, связанный с ____________ (**рост, производство**), ведет к немедленному росту спроса, и т.д.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ростом производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Когда и рынки продукции, и рынки ____________ (**фактор, производство**) являются совершенно конкурентными, ресурсы используются эффективно, поскольку разность общих доходов и общих издержек максимальна.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'индекс промышленного производства', 
                          title = 'Индекс выпуска товаров и услуг в январе 2009 г. по сравнению с январем 2008 г. составил 87,5%, ____________ (**индекс, промышленный, производство**) — 84%, грузооборот транспорта — 85,3%, внешнеторговый оборот — 82,7%, причем экспорт сократился гораздо сильнее, чем импорт (73,9% для экспорта против 96,4% для импорта).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекс промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ресурсов для производства', 
                          title = 'Ценовая поддержка привела к избыточному выделению ____________ (**ресурс, для, производство**) сахара менее эффективными американскими производителями.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ресурсов для производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста производства', 
                          title = 'До середины 70-х годов темпы ____________ (**рост, производство**) продовольствия отставали от темпов роста населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривой производственных возможностей', 
                          title = 'Что происходит с ____________ (**кривая, производственный, возможность**), если растет количество ресурсов, находящихся в распоряжении общества?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривой производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширения производства', 
                          title = 'Фирмы испытывают потребность в дополнительных средствах для ____________ (**расширение, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширения производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширению производства', 
                          title = 'Желание получить прибавочную стоимость создает тенденцию к ____________ (**расширение, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширению производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производство товаров', 
                          title = 'Учитывается бщий объем расходов на ____________ (**производство, товар**) и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производство товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Рост уровня сбережений увеличивает темпы роста ____________ (**объем, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширение производства', 
                          title = 'Часть продукта поступает в личное потребление, часть – на накопление, часть – на ____________ (**расширение, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширение производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фактор производства', 
                          title = 'Если маржиналисты признают предпринимательскую деятельность как ____________ (**фактор, производство**), то марксисты отрицают ее.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактор производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фактора производства', 
                          title = 'Определите максимально возможный выпуск продукции на единицу данного ____________ (**фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактора производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Фирма может изменять структуру вводимых ____________ (**фактор, производство**) в связи с технологическими нововведениями или изменениями в ценах на вводимые факторы производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'необходимые для производства', 
                          title = 'Предположим, что факторы, ____________ (**необходимый, для, производство**) 1 единицы продовольствия, стоят $160. Предельные издержки продовольствия составят тогда $160, а предельные издержки производства одежды будут равны лишь $80.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'необходимые для производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спад производства', 
                          title = 'Среднегодовые темпы прироста ВВП приближались к 3% и превосходили подобный показатель всех развитых стран в целом. Рост отличался устойчивостью, хозяйство пережило один ____________ (**спад, производство**) в 1991 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спад производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'В результате в 2017-2020 гг. длительная тенденция сокращения объема ____________ (**промышленный, производство**) сменилась его ростом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производство товаров', 
                          title = 'Чем больше мы тратим на национальную оборону, чтобы надежно за­щитить наши границы, тем меньше ресур­сов мы направляем на ____________ (**производство, товар**) и повышение уровня жизни.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производство товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширения производства', 
                          title = 'На рисункетраектория ____________ (**расширение, производство**) демонстрирует комбинации труда и капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширения производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Кривая рыночного предложения товара, продаваемого на конкурентном рынке, обычно направлена в правый верхний угол, так как предельные ____________ (**издержка, производство**) товара, как правило, возрастают.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'затраты на производство', 
                          title = 'Субсидия может быть предоставлена производителю на проведение технологических работ, приобретение нового основного технологического оборудования, что снижает ____________ (**затрата, на, производство**) инновационной продукции и стоимость продукции для потребителя.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'затраты на производство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня производства', 
                          title = 'Характерной чертой изменения структуры обрабатывающих производств в условиях низких темпов роста экономики является снижение технологического ____________ (**уровень, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Заметьте, что кривая границы ____________ (**производственный, возможность**) вы­гнута наружу. Ее форма означает, что издержки упущенных возможностей про­изводства автомобилей зависят от уровня производства каждого товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'При любом уровне ВВП выше равновесного реальный ____________ (**объем, производство**) будет превышать совокупные расходы, что приведет к незапланированным инвестициям в товарные запасы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Что показывает кривая ____________ (**производственный, возможность**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'используемые для производства', 
                          title = 'Зная функцию издержек подразделения, руководство автомобильной компании может определить оптимальную трансфертную цену  на двигатели, ____________ (**использовать, для, производство**) автомобилей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'используемые для производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производством и потреблением', 
                          title = 'Анализ связей между ____________ (**производство, и, потребление**) показывает уровень развития товарных форм хозяйств, влияние внутреннего и международного разделения труда на распределение доходов, на сферу личного и производственного потребления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производством и потреблением',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Неблагоприятный шок предложения оказывает прямое воздействие на снижение ____________ (**объем, производство**), уменьшая выпуск продукции, которая могла бы быть произведена при любых фиксированных значениях капитала и труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в производстве которых', 
                          title = 'Страна должна специализироваться на производстве тех товаров, которые она может производить с наименьшими издержками по сравнению с другими странами, и торговать ими в обмен на товары, эффективность ____________ (**в, производство, который**) принадлежит другой стране.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в производстве которых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кает депрессионный риск, вызванный экономическим спадом и депрессией. В этом случае больше всего страдают отрасли, вы- пускающие средства производства и товары длительного поль- зования. Но в то же время этот период оптимален для начала инвестиций, так как стоимость заимствованных средств быва-', 
                          title = 'Больше всего страдают отрасли, выпускающие средства производства и товары длительного пользования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кает депрессионный риск, вызванный экономическим спадом и депрессией. В этом случае больше всего страдают отрасли, вы- пускающие средства производства и товары длительного поль- зования. Но в то же время этот период оптимален для начала инвестиций, так как стоимость заимствованных средств быва-',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производстве продукции', 
                          title = 'Главенствующую роль в ____________ (**производство, продукция**) играют крупные сельскохозяйственные организации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производстве продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Функция производственная — зависимость между количеством используемых ____________ (**фактор, производство**) и максимально возможным выпуском продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объемах производства', 
                          title = 'Изменения в ____________ (**объем, производство**), вызванные ухудшением условий торговли, зависят от структуры издержек той или иной отрасли и от изменений во внутреннем спросе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объемах производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обрабатывающих производств', 
                          title = 'Компания концентрируется на развитии ____________ (**обрабатывать, производство**) и увеличении инвестиционной активности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обрабатывающих производств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фактор производства', 
                          title = 'Труд как ____________ (**фактор, производство**) – любые умственные и физические усилия, прилагаемые людьми в процессе хозяйственной деятельности. Ценой труда выступает заработная плата.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактор производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня производства', 
                          title = 'Придется увеличить объем производства, что показано горизонтальными стрелками, направленными вправо от ____________ (**уровень, производство**) в 250 единиц.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'Инфляция замедлилась и при этом снизилась чувствительность инфляции к динамике бизнес-цикла (кривая Филлипса стала более пологой). В числе таких факторов авторы указывают глобализацию (снижение ____________ (**издержка, производство**) и торговли повлияло на уровень инфляции, и на усиление глобальной конкуренции, что в свою очередь повлияло на возможности компаний повышать цены в бизнес-цикле).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'И точка Е, лежащая вне прежних границ области ____________ (**производственный, возможность**) фирмы, окажется теперь достижимой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы производства', 
                          title = 'Рассмотрим сначала, какой вклад ____________ (**фактор, производство**) вносят в увеличение выпуска продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'Рис. 1.1 позволяет получить более четкое представление о трех взаимосвязанных понятиях - ограниченности ресурсов, выборе и затратах, как они интерпретируются в экономике. Возьмем точку F внутри области производственных возможностей. Очевидно, что она означает такую комбинацию средств производства и предметов потребления, которая существенно меньше, чем могло бы производиться при полном и эффективном использовании всех ресурсов. Выбрав такую точку, мы смирились бы либо с наличием неиспользованных ресурсов (например, с безработицей), либо с низкой эффективностью их использования (например, с большими потерями, в том числе и рабочего времени). Наоборот, точка Е характеризует такой выпуск продукции, который недостижим при полном использовании наличных ресурсов и существующей технологии. Таким образом, кривая ABCD, т.е. граница области производственных возможностей, характеризует одновременно и возможный, и желательный выпуск продукции. Именно из точек, лежащих на этой кривой и представляющих различные возможные сочетания выпуска средств производства и предметов потребления, мы и должны (в силу гипотезы о рациональном поведении) выбрать ту, которая для нас наиболее предпочтительна.', 
                          title = 'Возьмем точку F внутри области производственных возможностей. Очевидно, что она означает такую комбинацию средств производства и предметов потребления, которая существенно меньше, чем могло бы производиться при полном и эффективном использовании всех ресурсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'Рис. 1.1 позволяет получить более четкое представление о трех взаимосвязанных понятиях - ограниченности ресурсов, выборе и затратах, как они интерпретируются в экономике. Возьмем точку F внутри области производственных возможностей. Очевидно, что она означает такую комбинацию средств производства и предметов потребления, которая существенно меньше, чем могло бы производиться при полном и эффективном использовании всех ресурсов. Выбрав такую точку, мы смирились бы либо с наличием неиспользованных ресурсов (например, с безработицей), либо с низкой эффективностью их использования (например, с большими потерями, в том числе и рабочего времени). Наоборот, точка Е характеризует такой выпуск продукции, который недостижим при полном использовании наличных ресурсов и существующей технологии. Таким образом, кривая ABCD, т.е. граница области производственных возможностей, характеризует одновременно и возможный, и желательный выпуск продукции. Именно из точек, лежащих на этой кривой и представляющих различные возможные сочетания выпуска средств производства и предметов потребления, мы и должны (в силу гипотезы о рациональном поведении) выбрать ту, которая для нас наиболее предпочтительна.',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Требования к производству продукции оказывают значительное влияние на отрасль, но их изменение позволит снизить ____________ (**издержка, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'необходимых для производства', 
                          title = 'Напомним, что изокванта — это кривая, представляющая множество всех комбинаций факторов производства, ____________ (**необходимый, для, производство**) определенного объема выпуска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'необходимых для производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'Налог на ____________ (**объем, производство**) смещает кривую предельных издержек вверх на величину налога. Фирма будет снижать свой объем производства до точки, в которой сумма предельных издержек и налога сравняется с ценой товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'Совет директоров принимает решение, которое определяет источник покрытия ____________ (**издержка, производство**) и обращения и обеспечения стабильности поступления доходов в течение периода эксплуатации объекта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объеме производства', 
                          title = 'Кривые MR и МС пересекаются как при ____________ (**объем, производство**), равном q 0 , так и при q*. Однако при q 0 прибыль явно не максимальна.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объеме производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста производства', 
                          title = 'Хотя большая величина капитала и позволяет достичь большего объема производства, однако темпы ____________ (**рост, производство**) снижаются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Обычно границы ____________ (**производственный, возможность**) “выпуклы наружу”.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Многие производственные функции имеют свойство постоянной отдачи от масштаба. Если производственная функция обладает этим свойством, то при одновременном изменении всех ____________ (**фактор, производство**) на одну и ту же величину она сама изменяется на ту же величину.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'В свою очередь, повышение цен ____________ (**фактор, производство**) может привести к смЕщению вверх кривых предельных издержек фирм.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'В результате повышение рыночной цены побуждает фирмы, уже действующие на рынке, увеличить ____________ (**объем, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объемом производства', 
                          title = 'На рисунке мы показали взаимосвязь между ____________ (**объем, производство**) и величиной капитала на базе производственной функции для США в 2001 г., оставляя постоянным количество труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объемом производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Для короткого периода важное значение имеет деление затрат на постоянные, не зависящие от ____________ (**объем, производство**), и перемен­ные, изменяющиеся при изменении размеров выпуска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объемом производства', 
                          title = 'Постройте график взаимосвязи между ____________ (**объем, производство**) и величиной труда при постоянном значении капитала на его сегодняшнем уровне.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объемом производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'индекс промышленного производства', 
                          title = 'Экономическое развитие края характеризовалось достаточно высокими темпами прироста производства товаров и услуг. За этот период валовой региональный продукт увеличился на 48,2% (Россия — на 60,4%, ДФО — на 52,7%), ____________ (**индекс, промышленный, производство**) — на 34,4% (Россия — на 43,7%, ДФО — на 51,1%), инвестиции в основной капитал увеличились в 2,2 раза (Россия — в 2,2 раза, ДФО — в 3 раза).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекс промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Фактически наклон границы ____________ (**производственный, возможность**) выражает отношение предельных издержек производства одного товара к предельным издержкам производства другого товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства товаров', 
                          title = 'Стоимость изношенного в процессе ____________ (**производство, товар**) и услуг оборудования и зданий учитывается в величине инвестиционных расходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне производства', 
                          title = 'Максимальное значение на кривой MP в верхней части рисунка соответствует L = Ll и что минимальное значение на кривой МС в нижней части рисунка имеет место при ____________ (**уровень, производство**) Qr, который соответствует L — Lv.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы производства', 
                          title = 'Когда цена растет, все фирмы в отрасли расширяют свое производство. Дополнительный выпуск увеличивает спрос на ____________ (**фактор, производство**) и может привести к установлению более высоких цен на них.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обрабатывающих производств', 
                          title = 'С другой стороны, доля ____________ (**обрабатывать, производство**) за этот период уменьшилась.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обрабатывающих производств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'Приросты объемов ____________ (**промышленный, производство**) ушли в отрицательную зону.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Производительиость — это показатель среднего реального ____________ (**объем, производство**), или реальный объем производства в расчете на единину затрат.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обрабатывающих производствах', 
                          title = 'Больше всего опасений вызывают данные по промышленному производству, темпы роста которого замедлились с 6,3% в 2011 г. до 4,9% в 2012 г. При этом прирост выпуска продукции в ____________ (**обрабатывать, производство**) сжался с 11,8% до 5,6%, а в добывающих отраслях замедлился с 3,4% до 2,5%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обрабатывающих производствах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Мы будем разбирать выбор комбинации ____________ (**фактор, производство**), сводящей к минимуму издержки фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Если не принимать во внимание стоимость факторов производства, то совокупные ____________ (**издержка, производство**) конечного подразделения равны К(О).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эффективность производства', 
                          title = '____________ (**эффективность, производство**) - отношение между затратами ограниченных ресурсов и произведенным объемом товаров или услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффективность производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства товаров', 
                          title = 'Всякое предприятие соединяет под своим управлением факторы производства - капитал, землю и труд, которые оно использует для ____________ (**производство, товар**) и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'В экономической теории проблема распределения и образования факторных доходов всегда вызывала огромный интерес. То, что для владельцев ____________ (**фактор, производство**) составляло доход, для покупателей этих факторов становится издержками.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'Несколько увеличилась доля экспорта в объеме ____________ (**промышленный, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'используются для производства', 
                          title = 'Общественные экономические ресурсы ____________ (**использовать, для, производство**) продукции монополии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'используются для производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства товаров', 
                          title = 'Точки на границе производственных возможностей и отражают эффек­тивный уровень производства. Если объем ____________ (**производство, товар**) находится в точке А, экономика уже не имеет возможности увеличить производство одного товара без снижения производства другого.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'управление должны быть единым целым в рамках фирмы, она должна располагаться на одной площадке, используемые ей экономические ресурсы должны быть исключительно материальными и иметь предельно простую природу. Таким образом, рассматриваемое пространство является скорее технологическим, нежели экономическим. Количество квадратных метров, необходимых для строительства и работы фирмы, несомненно является функцией от ее размера, но эффект масштаба не может реализовываться бесконечно; поэтому конечными определяющими факторами оказываются технологические особенности, такие как природа материалов, которые необходимо хранить и перерабатывать; используемые машины и оборудование; пространство, необходимое для подготовки и осуществления работ. При соблюдении этих условий для данной единицы промышленного производства могут быть найдены оптимальные технологические параметры пространства. Как только мы отменяем упрощения, принятые для облегчения задачи, мы оказываемся неспособны определить местоположение фирмы в обычном пространстве. Фирма зачастую состоит из организаций, распределенных в пространстве, между которыми образуются разные по своей интенсивности связи. Одна организация при этом может состоять из частей, не являющихся непрерывными. Средства производства включают оборудование и материалы, но также и электроэнергию и деньги на банковских счетах. Однако все эти сложности локализации нас не интересуют, главным является понимание того, что экономический анализ этой локализации или связанный с ней основан на серьезных иллюзиях, скрывающих суть экономического пространства, предложенного нами. Фирма, прежде всего, действует в пространстве, определяемом планом. Этот план представляет собой набор связей между фирмой и, с одной стороны, поставщиками средств производства (сырье, труд, энергия, капитал), а с другой стороны, потребителями продукта (как промежуточного, так и конечного). Экономическое расстояние в денежном выражении, то есть в терминах цен и затрат, определяется факторами вне этого плана; оно зависит от структуры и организации плана фирмы и структуры и организации планов групп, связанных с фирмой. То есть такое экономическое пространство не только не поддается картографированию, но и не может быть представлено даже единым перечнем характеристик. Грубое представление этого пространства может быть получено для некоего временного промежутка путем построения альтернативных перечней характеристик, в рамках множества возможных комбинаций. Глава фирмы, в некоторой степени, способен самостоятельно определять экономические расстояния фирмы на период. Однако в случае расширения [производства] план на один период включает не только величины для следующего периода. План развития сам по себе огра- 83 ПЭ2', 
                          title = 'Фирма, прежде всего, действует в пространстве, определяемом планом. Этот план представляет собой набор связей между фирмой и поставщиками средств производства (сырье, труд, энергия, капитал), а с другой стороны, потребителями продукта (как промежуточного, так и конечного).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'управление должны быть единым целым в рамках фирмы, она должна располагаться на одной площадке, используемые ей экономические ресурсы должны быть исключительно материальными и иметь предельно простую природу. Таким образом, рассматриваемое пространство является скорее технологическим, нежели экономическим. Количество квадратных метров, необходимых для строительства и работы фирмы, несомненно является функцией от ее размера, но эффект масштаба не может реализовываться бесконечно; поэтому конечными определяющими факторами оказываются технологические особенности, такие как природа материалов, которые необходимо хранить и перерабатывать; используемые машины и оборудование; пространство, необходимое для подготовки и осуществления работ. При соблюдении этих условий для данной единицы промышленного производства могут быть найдены оптимальные технологические параметры пространства. Как только мы отменяем упрощения, принятые для облегчения задачи, мы оказываемся неспособны определить местоположение фирмы в обычном пространстве. Фирма зачастую состоит из организаций, распределенных в пространстве, между которыми образуются разные по своей интенсивности связи. Одна организация при этом может состоять из частей, не являющихся непрерывными. Средства производства включают оборудование и материалы, но также и электроэнергию и деньги на банковских счетах. Однако все эти сложности локализации нас не интересуют, главным является понимание того, что экономический анализ этой локализации или связанный с ней основан на серьезных иллюзиях, скрывающих суть экономического пространства, предложенного нами. Фирма, прежде всего, действует в пространстве, определяемом планом. Этот план представляет собой набор связей между фирмой и, с одной стороны, поставщиками средств производства (сырье, труд, энергия, капитал), а с другой стороны, потребителями продукта (как промежуточного, так и конечного). Экономическое расстояние в денежном выражении, то есть в терминах цен и затрат, определяется факторами вне этого плана; оно зависит от структуры и организации плана фирмы и структуры и организации планов групп, связанных с фирмой. То есть такое экономическое пространство не только не поддается картографированию, но и не может быть представлено даже единым перечнем характеристик. Грубое представление этого пространства может быть получено для некоего временного промежутка путем построения альтернативных перечней характеристик, в рамках множества возможных комбинаций. Глава фирмы, в некоторой степени, способен самостоятельно определять экономические расстояния фирмы на период. Однако в случае расширения [производства] план на один период включает не только величины для следующего периода. План развития сам по себе огра- 83 ПЭ2',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'Какое воздействие оказывает политика жесткой реальной заработной платы на фактический ____________ (**объем, производство**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня производства', 
                          title = 'Для каждого ____________ (**уровень, производство**) в верхней части рисунка мы можем найти соответствующую равновесную реальную ставку процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Капиталистические ____________ (**издержка, производство**) товара состоят из затрат постоянного и переменного капитала, т.е. из расходов на средства производства и на заработную плату рабочим.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Если новая техника, новые технологические процессы будут внедряться одновременно и примерно в равной мере во всех отраслях, то граница ____________ (**производственный, возможность**) сдвинется из положения AD в положение AiDi.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Все комбинации ____________ (**фактор, производство**), представленные на изокванте, являются технологически эффективными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'При этом точка "планового" равновесия Р должна пе­реместиться в точку "рыночного" равновесия М, которое опреде­ляется как точка касания кривой ____________ (**производственный, возможность**) с кривой социальных предпочтений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производство единицы продукции', 
                          title = 'Увеличение субсидий  обусловливает уменьшение издержек фирм на ____________ (**производство, единица, продукция**) и ведет к росту совокупного предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производство единицы продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Выбор базисного года может иметь важное значение при расчете роста реального ____________ (**объем, производство**), на который оказывает воздействие изменение уровня цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'Все показатели ориентированы на снижение ____________ (**издержка, производство**) продукции (работ, услуг).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства единицы продукции', 
                          title = 'Правая часть уравнения представляет издержки производства допол-нительной единицы продукции (ставка заработной платы, умноженная на затраты труда, необходимые для ____________ (**производство, единица, продукция**)), т. е. предельные издержки производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства единицы продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторами производства', 
                          title = 'Предполагается, что домохозяйства владеют всеми ____________ (**фактор, производство**) в экономике (капитал и труд в нашей модели). Они могут покупать и продавать государственные облигации, приносящие номинальную безрисковую процентную ставку.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторами производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производство продукции', 
                          title = 'Увеличение издержек фирм на ____________ (**производство, продукция**) вызывает сдвиг и кривой краткосрочного, и кривой долгосрочного совокупного предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производство продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объемов производства', 
                          title = 'Необходимо осознавать, что неизбежное следствие жесткой монетарной политики, направленной на снижение темпов инфляции, — повышение уровня безработи­цы и сокращение ____________ (**объем, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объемов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объеме производства', 
                          title = 'Изменения в ____________ (**объем, производство**) ведут к изменениям в доходе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объеме производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'Видно изменение ____________ (**издержка, производство**) на единицу продукции под воздействием определенных факторов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства и потребления', 
                          title = 'Следует формировать оптимальную территориальную структуру ____________ (**производство, и, потребление**) энергии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства и потребления',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эффективности производства', 
                          title = 'Глобализация рынков способствует высокому уровню ____________ (**эффективность, производство**) и обращения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффективности производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эффективности производства', 
                          title = 'Следует сформировать план повышения ____________ (**эффективность, производство**), который учитывает нововведения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эффективности производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'Неразрешенный своевременно структурный кризис советской экономики (утяжеленная структура производства, противоречия между производством средств производства и производством предметов потребления, повышенная ре- сурсоемкость производства, усиление проблемы дефицита и т.п.) в итоге транс- формировался в кризис всей социально-экономической системы советской эконо-', 
                          title = 'Неразрешенный своевременно структурный кризис советской экономики (утяжеленная структура производства, противоречия между производством средств производства и производством предметов потребления, повышенная ресурсоемкость производства, усиление проблемы дефицита и т.п.) в итоге трансформировался в кризис всей социально-экономической системы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'Неразрешенный своевременно структурный кризис советской экономики (утяжеленная структура производства, противоречия между производством средств производства и производством предметов потребления, повышенная ре- сурсоемкость производства, усиление проблемы дефицита и т.п.) в итоге транс- формировался в кризис всей социально-экономической системы советской эконо-',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста производства', 
                          title = 'Новосибирская область достигла высоких темпов ____________ (**рост, производство**) и потребления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'которая базировалась на принципе вынужденных сбережений средств населения через искусственно созданные ограничения потребления, когда государство перенаправляло большие ресурсы в пользу сектора производства средств производства. Поэтому СССР, отставая по доле инвестиций в ВВП только от Японии, имел сравнительно невысокий сред- недушевой ВВП [Schroeder, 1985. P. 60–64].', 
                          title = 'Государство перенаправляло большие ресурсы в пользу сектора производства средств производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'которая базировалась на принципе вынужденных сбережений средств населения через искусственно созданные ограничения потребления, когда государство перенаправляло большие ресурсы в пользу сектора производства средств производства. Поэтому СССР, отставая по доле инвестиций в ВВП только от Японии, имел сравнительно невысокий сред- недушевой ВВП [Schroeder, 1985. P. 60–64].',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фактора производства', 
                          title = 'Рента — это доход не только от ____________ (**фактор, производство**) “земля”, но и от любого другого фактора, предложение которого неэластично.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактора производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'Более высокая производительность непосредственно увеличивает ____________ (**объем, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'используется для производства', 
                          title = 'Сталь ____________ (**использовать, для, производство**) значительного числа товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'используется для производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Экономика находится на кривой ____________ (**производственный, возможность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'На изменение структуры ____________ (**промышленный, производство**) повлияли существенные сдвиги в спросе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста производства', 
                          title = 'Все, что мы скажем о темпах ____________ (**рост, производство**) или потребления на одного работника, будет справедливо и для производства и потребления на душу населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'Задача фирмы – найти оптимальный ____________ (**объем, производство**), при котором получит максимальную прибыль или минимальные убытки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширение производства', 
                          title = 'Сбережения делаются как фирмами, так и домашними хозяйствами. Фирмы сберегают на ____________ (**расширение, производство**) и увеличение прибыли. Домашние хозяйства сберегают по ряду причин: обеспечение старости, передачи состояния детям.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширение производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня производства', 
                          title = 'Есть несколько других показателей ____________ (**уровень, производство**) и дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Средние совокупные издержки представляют собой совокупные издержки, деленные на объем выпуска. Таким образом, средние совокупные ____________ (**издержка, производство**) при объеме выпуска в 5 единиц составляют 36 долл.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Графически экономический рост производства продовольственных (С) и непродовольственных (Q) товаров изображается смЕщением кривой ____________ (**производственный, возможность**) вправо от АВ к СD.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержкам производства', 
                          title = 'Таким образом, прибыль максимальна, когда предельный доход фирмы равен предельным ____________ (**издержка, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержкам производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'В результате в период 2003—2008 гг. прирост банковских активов составил 73%, в то время как прирост ____________ (**промышленный, производство**) только 5,7% .',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Если повышение инвестиций ведет к обновлению основного капитала и увеличению производительности ____________ (**фактор, производство**), то оно свидетельствует о повышении качества роста в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Построим кривые ____________ (**производственный, возможность**) Петра и Андрея при первоначальных технологиях. На этой основе построим общую кривую производственных возможностей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'затратами на производство', 
                          title = 'Обязательное условие для получения прибыли — превышение выручки от реализации продукции (вылолнения работ, оказания услуг) над ____________ (**затрата, на, производство**) и реализацию продукции (выполнение работ, оказание услуг).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'затратами на производство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Результаты экономической деятельности могут находиться на гра­нице ____________ (**производственный, возможность**) или внутри кривой, но никак не за ее пределами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'Были разрушены экономические основы российского города: объем ____________ (**промышленный, производство**) по сравнению с 1913 г. упал в 7 раз.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Экономическая прибыль должна быть равна нулю, т. е. после оплаты услуг ____________ (**фактор, производство**) в распоряжении собственников не остается денежных средств.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторам производства', 
                          title = 'Меняются требования к ____________ (**фактор, производство**), повышаются требования к квалификации и качеству труда – работник превращается в управляющего системой машин.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторам производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'Цены остаются постоянными в краткосрочном периоде, а фирмы предлагают такой ____________ (**объем, производство**) товаров, на которые предъявляется спрос при этом фиксированном уровне цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ростом производства', 
                          title = 'Потребительский спрос возрастает вместе с ____________ (**рост, производство**): любое увеличение выпуска ведет к дальнейшему росту спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ростом производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширению производства', 
                          title = 'Резкое удешевление продукции расширяло рынки сбыта, дешевые товары легко вытесняли более дорогие изделия других стран. В конкурентной борьбе побеждали те, на чьих предприятиях производилось большее количество товаров с меньшей индивидуальной стоимостью, а это вело к ____________ (**расширение, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширению производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Средние общие ____________ (**издержка, производство**) на уровне 5 штук равняются $36.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обрабатывающих производств', 
                          title = 'На графике изображена доля ____________ (**обрабатывать, производство**) в ВРП по типам регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обрабатывающих производств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Изокоста представляет собой все возможные сочетания труда и капитала, которые имеют одну и ту же суммарную стоимость, т.е. все сочетания двух ____________ (**фактор, производство**) с равными совокупными издержками.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объемов производства', 
                          title = 'Стабилизация ситуации в экономике страны в целом и сельском хозяйстве в частности сопровождалась снижением ____________ (**объем, производство**) в хозяйствах населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объемов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'В результате международной миграции за рубеж перемещается товар особого свойства — рабочая сила. Принципиальное ее отличие от других ____________ (**фактор, производство**) заключается в том, что она сама является фактором производства других факторов, создателем прибавочной стоимости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внутреннего производства', 
                          title = 'По мере роста дохода внутренний спрос на товары ____________ (**внутренний, производство**) увеличивается в меньшей степени, чем общий внутренний спрос.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутреннего производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства продукции', 
                          title = 'В то же время переход к учету экологических параметров технологий, используемых для ____________ (**производство, продукция**), являются одним из важных направлений усиления международной конкуренции. Экологическое инновационное развитие позволяет не только последовательно сокращать масштабы негативного антропогенного воздействия на окружающую природную среду, но и приносить выгоду экологически ответственному бизнесу (что требует установления со 192',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства товаров', 
                          title = 'Учитываются природные ресурсы, которые могут быть использованы для ____________ (**производство, товар**) и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторами производства', 
                          title = 'Ранее мы рассматривали, главным образом, два фактора - труд и капитал - при создании продукции фирмой. Теперь двумя ____________ (**фактор, производство**) в нашей модели ценообразования будут земля и труд.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторами производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'индекса промышленного производства', 
                          title = 'Это подтверждается и динамикой ____________ (**индекс, промышленный, производство**): в 2013 г. по сравнению с 2012 г. он составил 100,1%, в июне 2013 г. по сравнению с июнем 2012 г. — 100,1%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекса промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'Для того чтобы определить, как связаны между собой рост запасов капитала, рабочей силы и улучшение технологии и как они воздействуют на ____________ (**объем, производство**), мы используем модель Солоу. Сначала мы проанализируем, как спрос и . предложение товаров определяют параметры процесса накопления капитала. Для',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Кривая средних издержек в долгосрочном периоде вначале отражает экономию от масштаба, но при увеличении ____________ (**объем, производство**) имеют место потери от масштаба.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производство и потребление', 
                          title = 'Запрет на ____________ (**производство, и, потребление**) данного товара равносилен повышению цены до уровня, соответствующего точке А на вертикальной оси. При такой высокой цене объем спроса и объем продажи сокращаются до нуля.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производство и потребление',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы производства', 
                          title = 'Изменения объема производства вызывают изменения цен на вводимые ____________ (**фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства товара', 
                          title = 'Частные предельные издержки ____________ (**производство, товар**) повышаются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'При увеличении денежной массы происходит рост стоимости корпоративных ценных бумаг и, как следствие, через увеличение стоимости активов и инвестиций растут совокупный спрос и ____________ (**объем, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Кривая ABCD, называемая границей области ____________ (**производственный, возможность**), показывает максимально возможные объемы производства предметов потребления и средств производства при полном использовании всех имеющихся ресурсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширением производства', 
                          title = 'Рассмотрим издержки производства, связанные с ____________ (**расширение, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширением производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'Обычно известны источники роста ____________ (**промышленный, производство**) в регионе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Мы можем оказаться на границе ____________ (**производственный, возможность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'Создание ЕВР означало формирование однородного пространства с равными условиями конкуренции, что должно усилить стремление западно-европейских компаний к снижению ____________ (**издержка, производство**) за счет экономии на масштабах производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'используемых в производстве', 
                          title = 'Как правило, соответствующий успех международных и национальных видов деятельности определяется главным образом продуктивностью (efficiency) постоянных и переменных ресурсов, ____________ (**использовать, в, производство**), в то время как местные и региональные виды деятельности, напротив, как кажется, больше зависят от эффективности их маркетинговых сетей (marketing networks).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'используемых в производстве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'используемых в производстве', 
                          title = 'Эффективность ____________ (**использовать, в, производство**) ресурсов до­стигается тогда, когда средние затраты длительного периода минимальны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'используемых в производстве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторов производства', 
                          title = 'Все теории гибкого акселератора имеют один значительный недостаток: они не учитывают цены ____________ (**фактор, производство**) и цену инвестиционных товаров, а поэтому не способны оценить влияние ценовых факторов, в том числе цены предложения капитала на инвестиции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Нарисуйте кривую ____________ (**производственный, возможность**) Кокабаны, если ее население равно 1 млн. человек.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внутреннего производства', 
                          title = 'Иностранные товары отличаются от товаров ____________ (**внутренний, производство**), поэтому мы не можем просто вычесть объем импорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутреннего производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки на производство', 
                          title = 'Если средние ____________ (**издержка, на, производство**) 1 кВт/ч энергии составляют 10 центов, то, значит, предельные издержки на обслуживание потребителей во внепиковые часы должны быть меньше 10 центов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки на производство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'По мере роста размеров предприятия вступает в действие ряд факторов, ведущих к снижению средних ____________ (**издержка, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'Массовое производство ведет к снижению ____________ (**издержка, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Кривые издержек фирмы постоянно растут вместе с увеличением ____________ (**объем, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривая производственных возможностей', 
                          title = 'Как выглядит ____________ (**кривая, производственный, возможность**) одновременного труда двух работников в течение 8 ч?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'Небольшие технологические улучшения в производственном процессе могут создать заметное конкурентное преимущество. Если фирма может даже немного снизить ____________ (**издержка, производство**), она может снизить цену и захватить дополнительную долю рынка.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'Заметим, что объем производства потребительских товаров в точке Е превышает весь возможный объем их выпуска при полном, стопроцентном использовании на эти цели всех ресурсов при прежней границе ____________ (**производственный, возможность**) (точка Е лежит правее точки D).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленного производства', 
                          title = 'Доля обрабатывающей промышленности в общем объеме ____________ (**промышленный, производство**) снизилась.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленного производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержками производства', 
                          title = 'Видна зависимость между ____________ (**издержка, производство**) и объемом выпуска данной фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержками производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Уровень цен зависит от ____________ (**объем, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержкам производства', 
                          title = 'Чтобы определить эффективный уровень предоставления общественного блага, мы должны затем приравнять сумму этих предельных выгод к предельным ____________ (**издержка, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержкам производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема производства', 
                          title = 'Можно добиться снижения темпов инфляции, но только ценой роста уровня безработицы и Еще большего сокращения ____________ (**объем, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фактора производства', 
                          title = 'Равенство (7.1) показывает, что в краткосрочном периоде предельные из держки равны стоимости переменного ____________ (**фактор, производство**), деленной на предельный продукт этого фактора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фактора производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержек производства', 
                          title = 'Начертите график предельных ____________ (**издержка, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержек производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объемах производства', 
                          title = 'Уравнение показывает, что предельный продукт труда есть разница в ____________ (**объем, производство**) при использовании L +1 и при использовании L единиц труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объемах производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства продукции', 
                          title = 'Это уравнение применяется при определении объема ____________ (**производство, продукция**) с максимапьной прибылью.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства продукции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня производства', 
                          title = 'Увеличение совокупного спроса вытолкнуло экономику этих стран за пределы ____________ (**уровень, производство**) при полной занятости, вызвав инфляцию спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесие в производстве', 
                          title = 'Как достигается ____________ (**равновесие, в, производство**) и потреблении?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесие в производстве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторам производства', 
                          title = 'Маржиналистская классификация к ____________ (**фактор, производство**) относит землю, труд, капитал, предпринимательскую способность и информацию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторам производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внедрения в производство', 
                          title = 'Л.И. Брежнев выразил недовольство развитием народного хозяйства в ракурсе ____________ (**внедрение, в, производство**) новой продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внедрения в производство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производства товара', 
                          title = 'То, чего стоит товар капиталистам, измеряется затратой капитала, то, чего товар стоит обществу – затратой труда. Поэтому капиталистические издержки ____________ (**производство, товар**) меньше его стоимости, или действительных издержек производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производства товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'промышленном производстве', 
                          title = 'Резко снизилось число работников, занятых в качестве домашней прислуги, в ____________ (**промышленный, производство**) и в сельско-хозяйственном секторе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'промышленном производстве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расширения производства', 
                          title = 'Для каждого уровня выпуска фирма использует вдвое больше труда по сравнению с капиталом. Следовательно, траектория ____________ (**расширение, производство**) — это прямая линия с наклоном, равным ΔK/ΔL = (50–25)/(100–50) = 1/2.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расширения производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень производства', 
                          title = 'При уровне занятости, равном N , величина совокупного объема производства, предлагаемого фирмами, — это ____________ (**уровень, производство**) при полной занятости Y.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'издержки производства', 
                          title = 'В точке О F предельные ____________ (**издержка, производство**) продовольствия очень низки (значительная часть объема производства изготавливается с очень небольшими затратами факторов).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'издержки производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'В России необходимо затратить 50 ч на производство каждого автомобиля и 20 ч – на каждую антенну. Во Франции и на автомобиль, и на спутниковую антенну требуется по 30 ч. Покажите графически границу ____________ (**производственный, возможность**) при одновременном производстве двух товаров отдельно для России и Франции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня производства', 
                          title = 'Устанавливаются основные цели экономической стратегии, повышение технологического ____________ (**уровень, производство**) и обеспечение его эффективности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей', 
                          title = 'При движении вниз по кривой предела ____________ (**производственный, возможность**) мы отказываемся от еды в пользу дополнительной одежды.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обрабатывающих производств', 
                          title = 'Пространственная концентрация ____________ (**обрабатывать, производство**) и трудовых ресурсов соответствующей квалификации растет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обрабатывающих производств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы производства', 
                          title = 'Длительный период в отличие от короткого характеризуется тем, что в течение его все ____________ (**фактор, производство**) являются переменными. В длительном периоде предприятие может изменять не только объем применяемых трудовых и материальных ресурсов, но и изменить величину производственной мощности. Важно понять, что предприятие всегда функционирует в условиях короткого периода, но планирует свое развитие на длительный период.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = 'Реальный ____________ (**объем, производство**) сократится, а безработица возрастет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'необходимые для производства', 
                          title = 'Фирмы столкнулись с тем, что им приходится покупать товары, ____________ (**необходимый, для, производство**), по возросшим ценам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'необходимые для производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'затрат на производство', 
                          title = 'Основу цены туристских продуктов (услуг) составляет их себестоимость. Она складывается преимущественно из ____________ (**затрата, на, производство**), доля которых в цене колеблется от 50 до 75% прибыли, а также из комиссии посредников, продвигающих турпродукт на рынок, и налога на добавленную стоимость, рассчитываемого по ставке 18%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'затрат на производство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производстве товаров', 
                          title = 'Национальный доход (national income) — в США это доход, который создается в ____________ (**производство, товар**) и услуг резидентами США.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производстве товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

