```{r}
checkdown::check_question(answer = 'невозможности', 
                          title = '#### Обычно, не дожидаясь наступления критической точки, центральный банк принимает решение о ____________ (**невозможность**) дельнейшего поддержания валютнсго курса и девальвирует свою валюту.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'невозможности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заключении', 
                          title = '#### Согласован с общиной раздел земельного участка, принято решение о ____________ (**заключение**) соглашения о возмещении убытков, о привлечении членов общины к подрядным работам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заключении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внешние эффекты', 
                          title = '#### При определении объемов производства, потребления, продаж или покупок участники рыночных сделок ориентируются лишь на свои частные интересы и не принимают во внимание ____________ ____________ (**внешний, эффект**), как отрицательные, так и положительные.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внешние эффекты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'превышении', 
                          title = '#### Регулирующим субфедеральным органам было предоставлено право самостоятельно принимать решения о ____________ (**превышение**) предельных размеров тарифов на электрическую энергию, если это обусловлено объемом инвестиционных программ энергокомпаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'превышении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'создании', 
                          title = '#### В 1898 году было пересмотрено соглашение о создании сообщества и принято решение о ____________ (**создание**) общего рынка и общего экономического пространства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'создании',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'страховании', 
                          title = '#### В 1968 г. для предоставления доступного страхования от наводнений в том числе, в зонах с повышенным риском опасности наводнений, Конгрессом США был принят закон о ____________ (**страхование**) от наводнений (National Flood Insurance Act) и была создана Национальная программа страхования наводнений (NFIP).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'страховании',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объеме', 
                          title = '#### Как конкурентная фирма принимает решение об ____________ (**объем**) рыночного предложения?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объеме',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обстоятельства', 
                          title = '#### Эта модель исходит из того, что решения людей о потреблении и сбережении в данном году являются результатом планирования, которое принимает во внимание ____________ (**обстоятельство**), уже ставшие фактом и прогнозируемые на предстоящее будущее, или обстоятельства всего жизненного цикла домохозяйства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обстоятельства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'проведении', 
                          title = '#### Автор сообщения принимает участие в ____________ (**проведение**) данных обзоров как эксперт от России в течение последних десяти лет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'проведении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ситуацию', 
                          title = '#### При анализе реальных величин, таких как объем производства и реальная ставка процента, можно не принимать во внимание ____________ (**ситуация**), складывающуюся на рынке денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ситуацию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'взаимосвязь', 
                          title = '#### Как правило, исследования, в которых анализируются количественные данные о деятельности полиции, судов и тюрем в разных странах, не принимают во внимание их ____________ (**взаимосвязь**) с показателями, характеризующими другие сферы общества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'взаимосвязь',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'другой важнейший фактор', 
                          title = '#### Совершенно не принимается во внимание ____________ ____________ ____________ (**другой, важный, фактор**), вызвавший явление неплатежей, а именно отсутствие адекватной платежной системы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'другой важнейший фактор',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'действия по предотвращению', 
                          title = '#### Смысл названия концепции становится понятен, если принимать во внимание, что все ____________ (**действие, по, предотвращение**) или снижению рисков, предпринятые в соответствии с этой концепцией, остаются неизменными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'действия по предотвращению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факт', 
                          title = '#### Цель собственника состоит в том, чтобы максимизировать ожидаемую прибыль, учитывая неопределенность результатов и принимая во внимание тот ____________ (**факт**), что поведение ремонтного рабочего невозможно проконтролировать.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'нынешний', 
                          title = '#### Для каждой отрасли необходимо принимать во внимание ____________ (**нынешний**) и вероятный в будущем размер железнодорожных тарифов и водных фрахтов и не повторить ошибки Вебера, который не учитывает особенностей железнодорожной тарификации, делающей стоимость провозки грузов пропорциональной не только весу, но и размеру специфических для данного груза тарифных ставок».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'нынешний',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'существующую систему', 
                          title = '#### Результаты этих исследований показали, что для использования методики расчета истинных сбережений на уровне российских регионов ее следует модифицировать, принимая во внимание ____________ ____________ (**существовать, система**) статистического учета, а также подтвердили возможность применения данного показателя для оценки устойчивости развития территориальных социо-эколого-экономических систем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'существующую систему',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внимание', 
                          title = '#### Однако необходимо принимать во ____________ (**внимание**) закон убывающей предельной полезности, в соответствии с которым для увеличения продолжительности жизни населения будет требоваться все больше ресурсов, направляемых в том числе на развитие социальной инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внимание',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестировании', 
                          title = '#### Предприниматели, принимая решение об ____________ (**инвестирование**), учитывают ожидаемую норму дохода на капиталовложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестировании',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'действия', 
                          title = '#### У всех компаний были одинаковые условия в отношении спроса и затрат, и каждая из фирм должна была принять решение относительно цены на этот товар, принимая во внимание ____________ (**действие**) конкурентов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'действия',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'решить проблему', 
                          title = '#### С развитием электронно-вычислительной техники в середине 70-х гг. была предпринята попытка ____________ ____________ (**решить, проблема**) переработки огромного массива информации с помощью внедрения ЭВМ в планирование на различных уровнях.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'решить проблему',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'о ежегодном', 
                          title = '#### Во время визита С. Миронова в КНР в августе 2003 г. было принято решение ____________ ____________ (**о, ежегодной**) проведении конференции для регулярного диалога между двумя странами по вопросам приграничного и межрегионального сотрудничества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'о ежегодном',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'продаже', 
                          title = '#### Универсальный магазин принимает решение о ____________ (**продажа**) детской мебели.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'продаже',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'при принятии', 
                          title = '#### Даже среди ведущих западных стран отсутствует «совершенная симметрия», так как на долю США приходится 45% ВВП «семерки», и средние показатели, которые принимаются во внимание ____________ ____________ (**при, принятие**) совместных решений, в значительной степени определяются уровнем и масштабом развития американской экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при принятии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'Психологический доход', 
                          title = '#### Точно так же не принимается во внимание так называемый «____________ (**психологический, доход**)» — то удовлетворение, которое люди получают от своей работы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'Психологический доход',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стратегические приоритеты', 
                          title = '#### При этом, безусловно, должны приниматься во внимание ____________ ____________ (**стратегический, приоритет**) - как в рамках реализации конкретного стратегического решения, так и при сопоставлении нескольких стратегических решений, которые конкурируют между собой за масштаб использования государственных финансовых ресурсов и институциональных условий для поддержки их реализации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стратегические приоритеты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'прогнозировании', 
                          title = '#### Кроме того, результаты полученных исследований должны приниматься во внимание при ____________ (**прогнозирование**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'прогнозировании',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'риск убытков', 
                          title = '#### Если все владельцы автомобилей будут обязаны застраховаться от несчастного случая, то в конечном итоге они и будут принимать на себя весь ____________ (**риск, убыток**) автомобильных аварий, выплачивая более высокие страховые взносы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'риск убытков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'профилактике', 
                          title = '#### Мировой опыт свидетельствует, что даже в условиях достаточно стабильного экономического роста необходимо принимать меры по ____________ (**профилактика**) рисков, угрожающих развитию экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'профилактике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'способа распоряжения', 
                          title = '#### Процесс, в ходе которого домохозяйства принимают решенияотносительно ____________ (**способ, распоряжение**) накопленными ими сбережениями, носит название личного инвестирования или распределения денежных средств между различными видами активов (asset allocation).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'способа распоряжения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем производства', 
                          title = '#### Смысл модели Курно состоит в том, что каждая фирма принимает ____________ ____________ (**объем, производство**) своего конкурента за фиксированную величину, а затем решает, какое количество товара производить ей самой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'действия', 
                          title = '#### Поскольку фирма будет действовать наилучшим образом, принимая во внимание ____________ (**действие**) своих конкурентов, естественно предположить, что и сами конкуренты будут поступать как можно лучшим образом, принимая во внимание поведение нашей фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'действия',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внимание', 
                          title = '#### При этом, правда, необходимо принимать во ____________ (**внимание**) тот факт, что на уровне федеральных округов специфика заполнения статистических форм такова, что иностранные инвестиции могут фиксироваться в составе показателей деятельности холдинга.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внимание',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансировании', 
                          title = '#### Несмотря на то что за счет финансирования Банком развития Монголии выполнено 86,6% земляных работ, в 2015 г. строительство было приостановлено, а в 2018 г. правительство страны приняло решение о ____________ (**финансирование**) этой дороги за счет прибыли государственной компании «Эрдэнэс Таван-Толгой», что сыграло важную роль в продолжении ее строительства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансировании',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'дивидендные', 
                          title = '#### Для акций стандартным показателем заработанной текущей доходности выступает показатель TSR, хотя часто аналитики не принимают во внимание ____________ (**дивидендный**) выгоды и анализируют исключительно доходность изменения цены акции (прироста капитала).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дивидендные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'будущие', 
                          title = '#### Покупатель постарается занизить стоимость земли, принимая во внимание ____________ (**будущий**) налоги, которые придется платить за нее, и эти ожидаемые налоги отразятся на цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'будущие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процессе', 
                          title = '#### Российская Федерация и ее дальневосточные территории принимают участие в ____________ (**процесс**) азиатской экономической интеграции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процессе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'решения', 
                          title = '#### Затем мы остановимся на проблеме, связанной с механизмом общественного принятия решения, которая заключается в том, что все стороны имеют стимул оказывать влияние на принимаемые ____________ (**решение**) с учетом своих интересов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'решения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'оплату', 
                          title = '#### При этом служащие принимают на себя ____________ (**оплата**) расходов на медицинское обслуживание каждый год в размере первых 200 долл.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'оплату',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'попытка', 
                          title = '#### Впервые в отечественной науке была предпринята ____________ (**попытка**) обосновать принципы таксономии районов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'попытка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Несмотря на все эти трудности, остается возможность построить для США функции ____________ (**спрос**), которые принимают во внимание, но не объясняют очевидные изменения спроса на деньги в середине 70-х — начале 80-х гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в качестве', 
                          title = '#### В модели Курно каждая фирма принимает ____________ ____________ (**в, качество**) заданной величины количественные объемы продукции, производимые ее соперниками.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в качестве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'решения', 
                          title = '#### Для обеспечения открытости деятельности институтов управления нужно создать действенные каналы влияния регионального сообщества на принимаемые ____________ (**решение**) через публичные обсуждения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'решения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'отсутствие нейтральности', 
                          title = '#### Мы расширяем классическую модель, принимая во внимание ____________ ____________ (**отсутствие, нейтральность**) денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отсутствие нейтральности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'смене', 
                          title = '#### В мае 2006 г. внеочередное собрание акционеров ОАО «Сибнефть» приняло решение о ____________ (**смена**) названия компании - на «Газпромнефть» и места ее регистрации - не в Омске, а в Санкт-Петербурге.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'смене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'постоянные', 
                          title = '#### При выработке решения об оптимальном объеме производства фирма принимает во внимание ____________ (**постоянный**) и переменные затраты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'постоянные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внимание', 
                          title = '#### Дополнительные продажи связа- ны с повышенными издержками производства, и это также следует принимать во ____________ (**внимание**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внимание',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инфляцию', 
                          title = '#### Налоговый кодекс не принимает во внимание ____________ (**инфляция**) и обязывает вас уплатить налог с дохода в $ 40.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инфляцию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'воздействие', 
                          title = '#### Так как наличный запас жилищного фонда представляет собой значительную величину по сравнению с уровнем инвестирования в жилищное строительство, то можно не принимать во внимание ____________ (**воздействие**) текущего предложения новых домов на цену жилищного фонда в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'воздействие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внимание различие', 
                          title = '#### Из данного примера следует сделать следующий вывод: полный анализ налоговой политики должен выходить за рамки простой кейнсианской функции потребления; следует принимать во ____________ ____________ (**внимание, различие**) между постоянным и временным доходом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внимание различие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внимание', 
                          title = '#### Увеличение объема продаж означает увеличение из держек производства, что также необходимо принимать во ____________ (**внимание**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внимание',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'защите', 
                          title = '#### В 1997 г. был принят закон о ____________ (**защита**) интересов третьих лиц в случае ущерба, произошедшего на предприятии в результате аварийной ситуации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'защите',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расчет', 
                          title = '#### Информацию этого блока необходимо принимать в ____________ (**расчет**) прежде всего потому, что представленные в нем документы носят обязательный для исполнения характер.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расчет',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'второй', 
                          title = '#### Ситуация дошла до того, что правительству пришлось принять решение о ____________ (**второй**) денежной реформе, с помощью которой можно было решить проблему зависимости китайской экономики от серебра.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'второй',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внимание', 
                          title = '#### По этой причине для определения внешних воздействий непригодна рекомендация Градостроительного кодекса, согласно которой в схемах территориального планирования должны приниматься во ____________ (**внимание**) «основные направления реализации государственной политики в области градостроительства с учетом особенностей социально-экономического развития и природно-климатических условий районов».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внимание',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'проблема доверия', 
                          title = '#### В данном анализе не принимается во внимание ____________ ____________ (**проблема, доверие**) центральному банку.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'проблема доверия',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стране', 
                          title = '#### Помимо увеличения дохода в принимающей ____________ (**страна**) молодые квалифицированные мигранты, скорее всего, станут налогоплательщиками в принимающей стране.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стране',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'количестве', 
                          title = '#### Поскольку мы рассмотрели поведение репрезентативной фирмы на рынке труда, то можно предположить, что все фирмы в экономике, принимая решения о ____________ (**количество**) нанимаемых работников, действуют подобным образом, и функция спроса на труд во всей экономике такая же, как и для отдельной фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'количестве',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внимание', 
                          title = '#### Не принимается во ____________ (**внимание**) то, что деньги сами могут являться товаром.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внимание',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стране', 
                          title = '#### К работающим не по контракту относятся работники, срок пребывания которых в принимающей ____________ (**страна**) четко не определен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стране',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'покупках', 
                          title = '#### Так как домашние хозяйства и фирмы, принимая решения о ____________ (**покупка**) и продажах, ориентируются прежде всего на цены, они, сами того не зная, оценивают социальные блага и издержки своих действий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'покупках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объеме', 
                          title = '#### Мы предположили, что наши два дуополиста принимают решения об ____________ (**объем**) выпуска одновременно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объеме',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'риск дефолта', 
                          title = '#### Кто принимает на себя ____________ ____________ (**риск, дефолт**) в этом случае?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'риск дефолта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

