```{r}
checkdown::check_question(answer = 'процентных ставок', 
                          title = 'При повышении рыночных ____________ (**процентный, ставка**) курс любых ценных бумаг с фиксированным доходом понижается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'При любом ожидаемом уровне инфляции рост реальной ____________ (**процентный, ставка**) приводит к росту номинальной процентной ставки и вызывает снижение величины спроса на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентном отношении', 
                          title = 'Государ­ственный долг в ____________ (**процентный, отношение**) к годовому ВВП вырос с 26% в 1980 г. до 51% в 1995 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентном отношении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = 'Если инфляция равна 4%, то реальная ____________ (**процентный, ставка**) будет равна разнице номинальной процентной ставки 4% и уровня инфляции 4%, т. е. 0%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Снижение ____________ (**процентный, ставка**) стимулирует потребление и, следовательно, совокупный спрос и производственные инвестиции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставкой', 
                          title = 'Реальная ставка доходности представляет собой разницу между номинальной ____________ (**процентный, ставка**) и уровнем инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставкой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'В долгосрочной перспективе оценки равновесной ____________ (**процентный, ставка**) в соответствии с различными условиями частного равновесия ведут себя по-разному.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Любые попытки изменить количество денег в обращении меняют уровень ____________ (**процентный, ставка**), что приводит к изменению потоков капитала и нарушению равновесия платежного баланса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Невозможность одновременного контроля денежного предложения и уровня ____________ (**процентный, ставка**) называется дилеммой целей кредитно-денежной политики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентные выплаты', 
                          title = 'Поскольку долг накапливается во времени, то ____________ (**процентный, выплата**) по долгу возрастают и далее будут возрастать.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентные выплаты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставкой', 
                          title = 'Процентная ставка по займам совпадает с ____________ (**процентный, ставка**) по сбережениям.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставкой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Рост ____________ (**процентный, ставка**) заставил многих потенциаль­ных заемщиков отказаться от планов строительства новых домов или предприя­тий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставок', 
                          title = 'На уровень ____________ (**процентный, ставка**), устанавливаемых на региональных рынках ссудного капитала, могут оказывать влияние ограничения мобильности спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = 'Пока люди будут пытаться продать принадлежащие им неденежные активы, реальная ____________ (**процентный, ставка**) будет продолжать расти.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентное изменение', 
                          title = 'Эластичность предложения — это ____________ (**процентный, изменение**) величины предложения в ответ на изменение цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентное изменение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставок', 
                          title = 'Кредитные гарантии снижают риск дефолта по кредиту и могут повлечь за собой снижение ____________ (**процентный, ставка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = 'Ожидаемая реальная ____________ (**процентный, ставка**) равна разности номинальной процентной ставки и ожидаемого уровня инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Снижение внутренней ____________ (**процентный, ставка**) ниже мировой приводит к оттоку капитала из страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Когда размер инвестиций является эндогенным, реакция кредитного спреда на изменение ____________ (**процентный, ставка**) не столь очевидна.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставок', 
                          title = 'Как отреагирует население на повышение ____________ (**процентный, ставка**) по депозитам?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставках', 
                          title = 'Банк обязан ежемесячно раскрывать данные о ____________ (**процентный, ставка**) по вкладам физических лиц в рублях, долларах США и евро по срокам привлечения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Если объем производства останется на первоначальном уровне, то рост реальной ____________ (**процентный, ставка**) приведет к ситуации, когда величина совокупного предложения товаров превысит величину совокупного спроса на товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Умеренным считается шок ____________ (**процентный, ставка**) в размере 1%, агрессивным – 2%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставок', 
                          title = 'Альтернативным индикатором долгосрочных ____________ (**процентный, ставка**) служат доходности государственных облигаций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = 'Более высокая ____________ (**процентный, ставка**) по денежным средствам увеличивает спрос на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставках', 
                          title = 'Оценки издержек на создание резервов на основании только лишь разницы в ____________ (**процентный, ставка**) могут быть сильно завышены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Сокращение спроса и объема производства приводит к понижению внутренней ____________ (**процентный, ставка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентное изменение', 
                          title = 'Эластичность спроса по цене в любой точке кривой спроса изменяет ____________ (**процентный, изменение**) величины спроса при повышении цены на товар на 1%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентное изменение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Это повышение ____________ (**процентный, ставка**) приводит к увеличению альтернативных издержек хранения денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставок', 
                          title = 'Изменение рыночных ____________ (**процентный, ставка**) приводит к изменению в противоположном направлении рыночных цен всех существующих финансовых инструментов с фиксированными доходами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Чем выше степень неприятия риска среди населения, тем выше премия за риск и ниже величина безрисковой ____________ (**процентный, ставка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кредитам', 
                          title = 'Банки в силу ограничений по достаточности капитала вынуждены повышать процентные ставки по ____________ (**кредит**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кредитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'депозитов', 
                          title = 'Снижающиеся ставки сокращают процентный доход от ____________ (**депозит**), что ухудшает положение богатых домохозяйств, так как большая доля их доходов зависит от сбережений на депозитах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'депозитов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кредит', 
                          title = 'Информационная функция дает участникам рынка через постоянно меняющиеся цены и процентные ставки на ____________ (**кредит**) объективную информацию о спросе и предложении товаров и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кредит',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = '____________ (**процентный, ставка**) для заемщиков и кредиторов различается, поскольку последние несут на себе издержки мониторинга действий заемщиков, чтобы избежать дефолта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставок', 
                          title = 'Увеличение реальных ____________ (**процентный, ставка**) произошло в период, когда большинство развивающихся стран выталкивалось с международных рынков капитала в связи с кризисом международной задолженности и их сложными внутрихозяйственными проблемами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентную ставку', 
                          title = 'Денежные власти устанавливают номинальную ____________ (**процентный, ставка**) с помощью правила Тейлора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентную ставку',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентную ставку', 
                          title = 'Однако при постоянной реальной ставке процента более высокий уровень инфляции будет увеличивать номинальную ____________ (**процентный, ставка**), заставляя людей сокращать свои реальные денежные остатки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентную ставку',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'государственному долгу', 
                          title = 'Высокие процентные ставки увеличивают процентные выплаты по ____________ ____________ (**государственный, долг**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'государственному долгу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'депозитам', 
                          title = 'При этом вероятность дефолта каждого отдельного банка оказывает влияние на агрегированный показатель вероятности дефолта в банковской системе и на процентные ставки по ____________ (**депозит**) и кредитам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'депозитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентному изменению', 
                          title = 'Перекрестная эластичность спроса — отношение процентного изменения спроса на один товар к ____________ (**процентный, изменение**) цены на другой товар.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентному изменению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = 'Чем выше степень этого риска, тем выше ____________ (**процентный, ставка**), которую должен обещать заемщик своим инвесторам для того, чтобы они согласились приобрести его ценные бумаги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = 'Реальная ____________ (**процентный, ставка**) – это изменение покупательной способности процентного дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентное изменение', 
                          title = 'Эластичность спроса по доходу — это ____________ (**процентный, изменение**) величины спроса, возникающее в результате увеличения дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентное изменение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Чему равны равновесные значения выпуска, потребления, инвестиций, реальной ____________ (**процентный, ставка**) и уровня цен?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = 'Чем больше люди предпочитают потреблять товаров и услуг сегодня, не оставляя эту возможность на будущее, тем выше ____________ (**процентный, ставка**) в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставке', 
                          title = 'Это может произойти только в том случае, когда потребление и инвестиции не реагируют на изменение процентной ставки, т.е. их эластичность по отношению к ____________ (**процентный, ставка**) равна нулю.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = 'Процентная ставка, выплачиваемая государством, обычно служит ориентиром для остальных процентных ставок в ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кредитам', 
                          title = 'Реальная процентная ставка, которую мы используем, – процентная ставка по ____________ (**кредит**), скорректированная на инфляцию, измеряемую дефлятором ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кредитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'Рост ____________ (**процентный, ставка**) приводит к значительному снижению региональной занятости в большинстве регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентное изменение', 
                          title = 'Спрос считается эластичным, если данное ____________ (**процентный, изменение**) цены ведет к еще большему процентному изменению количества запрашиваемых товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентное изменение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'В долгосрочной перспективе устойчивое изменение темпов роста денежной массы ведет к изменению роста инфляции и номинальной ____________ (**процентный, ставка**) в том же направлении и на ту же величину.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки', 
                          title = 'доходов, сберегая оставшуюся часть, логичным допущением будет, что 0 < cY < 1. В соответствии с уравнением 9А.8 рост располагаемых доходов вызывает уве личение желаемого потребления, а рост реальной ____________ (**процентный, ставка**) вызывает снижение желаемого потребления (и увеличение желаемых сбережений). Дру гие факторы, которые оказывают воздействие на величину желаемого потреб',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставкой', 
                          title = 'Под номинальной ____________ (**процентный, ставка**) понимается показатель доходности сбережений или стоимости пользования ссудой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставкой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

