```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'Так как для покупки и установки нового оборудования требуется время, вводится понятие ожидаемого будущего ____________ (**предельный, продукт**) капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'На этом уровне чистый ____________ (**предельный, продукт**) капитала равен темпу прироста производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной выручки', 
                          title = 'Монополист определяет свой выпуск исходя из равенства предельных затрат и ____________ (**предельный, выручка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной выручки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'Монополист будет увеличивать занятость до тех пор, пока ____________ (**предельный, продукт**) труда не сравняется с конкурентной ставкой заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным издержкам', 
                          title = 'Эти посетители пришли в ресторан, поскольку они ожидают, что предельная выгода, или удовлетворение от еды, которую покупают, будет равна ____________ (**предельный, издержка**) или превысит их.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным издержкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной полезности', 
                          title = 'Теория ____________ (**предельный, полезность**) определяет существующие на рынке закономерности поведения потребителей, формирование спроса и вид кривой самого спроса на графике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной полезности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = '____________ (**предельный, издержка**) слишком велики по сравнению с предельной выгодой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'ОПЕК в течение смогла поднять цены на нефть намного выше ____________ (**предельный, издержка**) производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная норма', 
                          title = 'Если ____________ (**предельный, норма**) технического замЕщения капитала трудом равна 9 ед., то каков будет предельный продукт капитала?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная норма',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'Когда спрос и предложение на труд находятся в состоянии равновесия, заработная плата равна стоимости ____________ (**предельный, продукт**) труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Посетители сравнивают ____________ (**предельный, издержка**) и предельные выгоды, пытаясь получить за потраченные деньги наибольшее личное удовлетворение или блага.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'Для конкурентоспособной фирмы стоимость ____________ (**предельный, продукт**) капитала равна цене продукции, умноженной на предельный продукт капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная норма', 
                          title = 'Производственная экономика будет эффективной, если ____________ (**предельный, норма**) технического замЕщения одинакова для всех изготовителей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная норма',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный доход', 
                          title = 'Максимизирующий прибыль уровень занятости для фирмы обеспечивается, когда ____________ (**предельный, доход**) продукта труда равен номинальной заработной плате.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный доход',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'Фирма, сдающая капитал в аренду, извлекает прибыль, только если ____________ (**предельный, продукт**) капитала больше, чем издержки на единицу капитала и терпит убытки, если предельный продукт капитала меньше издержек на единицу капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'Так как шок предложения носит временный характер, то не ожидается, что он будет оказывать влияние на ____________ (**предельный, продукт**) труда в будущем или на ставку реальной заработной платы в будущем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной полезности', 
                          title = 'Методология Дж. Хикса соответствует основным положениям порядковой теории ____________ (**предельный, полезность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной полезности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'Чтобы найти размер вклада работника в общий доход фирмы, мы должны перевести ____________ (**предельный, продукт**) труда в стоимость предельного продукта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'объем выпуска таков, что ____________ (**предельный, издержка**) равны цене продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'Фирма выбирает число наемных работников, при котором заработная плата рав­на стоимости ____________ (**предельный, продукт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным издержкам', 
                          title = 'При монополии равновесие возникает тогда, когда предельный доход равняется ____________ (**предельный, издержка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным издержкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного', 
                          title = 'Кривая ____________ (**предельный**) продукта труда имеет отрицательный наклон.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной выручки', 
                          title = 'Цена олигополиста изменится лишь в том случае, если кривая сдвинется настолько, что она "выйдет" за пределы разрыва кривой ____________ (**предельный, выручка**) и пересечет верхний или нижний ее нисходящий сегмент.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной выручки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные', 
                          title = 'На практике довольно трудно определить ____________ (**предельный**) издержки и предельные выгоды.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Общие и ____________ (**предельный, издержка**) равны нулю.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Если ____________ (**предельный, издержка**) выше предельного дохода, фирма может увеличить прибыль, снизив объем выпуска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Многие из покупателей заплатили бы за товар сумму, которая выше ____________ (**предельный, издержка**) фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Фермеры могут определить максимизирующий прибыль объем выпуска путем сравнения предель­ного дохода и ____________ (**предельный, издержка**) производства каждой новой единицы продук­ции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'Снижение уровня реальной заработной платы приводит к изменению ценности ____________ (**предельный, продукт**) труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным издержкам', 
                          title = 'Чтобы определить эффективный уровень предоставления общественного блага, мы должны затем приравнять сумму этих предельных выгод к ____________ (**предельный, издержка**) производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным издержкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной', 
                          title = 'Принцип убывающей ____________ (**предельный**) полезности часто называют первым законом Госсена.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного дохода', 
                          title = 'Использование дополнительного оборудования вызывает смЕщение кривой ____________ (**предельный, доход**) продукта труда вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = '____________ (**предельный, продукт**) капитала является положительной величиной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной выручки', 
                          title = 'Кривая спроса на продукцию отдельного предприятия в условиях совершенной конкуренции является одновременно кривой его средней и ____________ (**предельный, выручка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной выручки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = '____________ (**предельный, продукт**) труда работника равен его реальной заработной плате.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным издержкам', 
                          title = 'Совокупный объем производства должен быть таким, чтобы предельный доход от реализации продукции каждой группе потребителей равнялся ____________ (**предельный, издержка**) производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным издержкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Когда цена увеличивается, фирма следует своей кривой краткосрочных ____________ (**предельный, издержка**) и увеличивает объем производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным издержкам', 
                          title = 'Наклон границы производственных возможностей выражает отношение предельных издержек производства одного товара к ____________ (**предельный, издержка**) производства другого товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным издержкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Издержки на производство каждой дополнительной единицы продукции представлены кривой ____________ (**предельный, издержка**) фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным издержкам', 
                          title = 'Прибыль максимальна, когда предельный доход равняется ____________ (**предельный, издержка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным издержкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'объем дополнительных поступлений зависит как от цены на товар, так и от ____________ (**предельный, продукт**) труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'Если ____________ (**предельный, продукт**) капитала превышает издержки на единицу капитала, то фирме выгодно увеличить запас капитала. Если предельный продукт капитала меньше, чем издержки на единицу капитала, то фирма уменьшает свой запас капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной полезности', 
                          title = 'Оба столбца отражают закон убывающей ____________ (**предельный, полезность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной полезности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'Каждый фактор будет оплачиваться в соответствии со стоимостью его ____________ (**предельный, продукт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного', 
                          title = 'В краткосрочном периоде равновесное состояние на рынке монополистической конкуренции достигается при соблюдении равенства ____________ (**предельный**) дохода и предельных издержек.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Если фирма покупает ресурсы на чисто конкурентных рынках, то ____________ (**предельный, издержка**) на их приобретение будут равны их ценам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Общие ____________ (**предельный, издержка**) добычи исчерпаемых ресурсов выше, чем предельные издержки их извлечения из земных недр.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного', 
                          title = 'Стоимость ____________ (**предельный**) продукта любого ресурса — это произведение предель­ного продукта ресурса и рыночной цены товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного', 
                          title = 'Стоимость ____________ (**предельный**) продукта фактора производства равна предельному доходу от предельного продукта фактора производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной полезности', 
                          title = 'Однако в современной экономической теории принят иной подход, ведущий свое начало с работ представителей теории ____________ (**предельный, полезность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной полезности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная полезность', 
                          title = 'С увеличением объема потребления товара ____________ (**предельный, полезность**) товара понижается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная полезность',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным издержкам', 
                          title = 'Монополист находится в равновесии, когда предельный доход равняется ____________ (**предельный, издержка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным издержкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных затрат', 
                          title = 'Монополист максимизирует прибыль, производя и продавая такой объем продукции, который соответствует равенству предельной выручки и ____________ (**предельный, затрата**) длительного периода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных затрат',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная выгода', 
                          title = '____________ (**предельный, выгода**) от часа труда равняется предельным издержкам ее получения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная выгода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного дохода', 
                          title = 'Мы называем этот принцип максимизации прибыли правилом равенства ____________ (**предельный, доход**) и предельных издержек.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'Давайте рассмотрим влияние сокращения населения на ____________ (**предельный, продукт**) труда и предельный продукт земли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'При формулировке условий максимизации прибыли необходимо учитывать и такую величину, как ____________ (**предельный, продукт**) фактора в денежном выражении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Краткосрочные кривые ____________ (**предельный, издержка**) применяются к конкретному заводу; долгосрочные кривые предельных издержек применяются ко всем заводам любых размеров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Соотношение ____________ (**предельный, издержка**) и предельного дохода - это своего рода сигнальная система, которая информирует предпринимателя о том, достигнут ли оптимум производства или можно ожидать дальнейшего роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного', 
                          title = 'Теперь давайте применим правило равенства ____________ (**предельный**) дохода и предельных издержек, или, поскольку мы рассматриваем чистую конкуренцию, правило равенства цены и предельных издержек.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная полезность', 
                          title = '____________ (**предельный, полезность**) денег убывает с меньшей скоростью, чем предельная полезность товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная полезность',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная полезность', 
                          title = 'Перераспределение должно быть прекращено, когда ____________ (**предельный, полезность**) дохода для одного индивида будет равна предельной полезности дохода для другого индивида.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная полезность',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных', 
                          title = 'Предельная норма трансформации, которая представляет собой соотношение ____________ (**предельный**) издержек на производство одежды и предельных издержек на производство продуктов, более не равна соотношению цен на товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный доход', 
                          title = 'Фирме следует увеличивать рекламные расходы до тех пор, пока ____________ (**предельный, доход**) от рекламы не станет в точности равным 1.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный доход',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Непрерывный участок кривой ____________ (**предельный, издержка**) фирмы - это и есть кривая краткосрочного предложения фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Предельный доход должен равняться предельным издержкам в точке, где кривая ____________ (**предельный, издержка**) возрастает.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Правило максимизации прибыли конкурентной фирмой заключается в выборе такого объема выпуска продукции, при котором ____________ (**предельный, издержка**) равны цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Кривая ____________ (**предельный, издержка**) фирмы является кривой предложения конкурентной фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный', 
                          title = 'Победитель установит монопольную цену на обслуживание, соответствующую количеству, при котором ____________ (**предельный**) доход равняется предельным издержкам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного дохода', 
                          title = 'Кривая ____________ (**предельный, доход**) продукта труда идет вниз.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного', 
                          title = 'Маржинальная отдача – предельная выручка от ____________ (**предельный**) продукта труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным', 
                          title = 'Если фирма вообще производит какой-то объем продукции, она должна поддерживать уровень производства, при котором предельный доход равняется ____________ (**предельный**) издержкам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной полезности', 
                          title = 'Вывод Парето означал отказ от концепции ____________ (**предельный, полезность**) в ее первоначальном виде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной полезности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Когда предельный продукт труда убывает, ____________ (**предельный, издержка**) производства возрастают, и наоборот.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'В одном случае действует полный перенос высоких кредитных спредов в ____________ (**предельный, издержка**) и цены на товары, во другом случае – только частичный.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного', 
                          title = 'Увеличение занятости может увеличить предельный продукт какого-либо другого переменного ресурса, что в свою очередь приведет к увеличению ____________ (**предельный**) продукта труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного дохода', 
                          title = 'Количество труда, которое обеспечило бы работникам максимальную ренту, определяется пересечением кривых ____________ (**предельный, доход**) и предложения труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного дохода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Если ____________ (**предельный, издержка**) на Заводе 1 выше, чем на Заводе 2, фирма может снизить общие издержки, сохранив прежний объем производства, если уменьшит объем продукции на Заводе 1 и увеличит его на Заводе 2.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'Привлечение дополнительной единицы труда прекратится тогда, когда ____________ (**предельный, продукт**) труда в денежном выражении сравняется с величиной заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная норма', 
                          title = 'Для каждого экономически эффективного способа ____________ (**предельный, норма**) технического замЕщения ресурсов равна соотношению их цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная норма',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной', 
                          title = 'Теория ____________ (**предельный**) полезности исследует аспект ценообразования в связи с эффективностью потребления про- дуктов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный доход', 
                          title = 'Что касается Фирмы 1, то ее ____________ (**предельный, доход**) равняется нулевым предельным издержкам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный доход',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Величина этих ____________ (**предельный, издержка**) составит повременную ставку рентных платежей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный продукт', 
                          title = 'Изменения в фискальной политике не влияют на производственную функцию или на ____________ (**предельный, продукт**) труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный продукт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных затрат', 
                          title = 'Такой сдвиг кривой ____________ (**предельный, затрата**) показан на рисунке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных затрат',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Кривая ____________ (**предельный, издержка**) в краткосрочном периоде пройдет горизонтально и будет равна рыночной ставке рентных платежей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Так как цена превышает ____________ (**предельный, издержка**), дополнительная единица продукции означает большую прибыль.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Если ____________ (**предельный, издержка**) на приобретение фактора больше, чем его предельный продукт в денежной форме, для максимизации прибыли фирме следует уменьшить количество данного фактора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным', 
                          title = 'Наклон границы производственных возможностей выражает отношение предельных издержек производства одного товара к ____________ (**предельный**) издержкам производства другого товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельная норма', 
                          title = 'Все комбинации факторов производства должны лежать на кривой оптимальных вариантов производства, чтобы ____________ (**предельный, норма**) технологического замЕщения труда капиталом для каждого производителя была одинаковой при производстве каждого из двух товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельная норма',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Монополия назнача­ет цену выше ____________ (**предельный, издержка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельным издержкам', 
                          title = 'Предельный доход равен ____________ (**предельный, издержка**) при производстве 8 тыс. ед. продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельным издержкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельных издержек', 
                          title = 'Соотношение между кривой ____________ (**предельный, издержка**) и кривой средних со­вокупных издержек показано на рисунке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные издержки', 
                          title = 'Экономический анализ говорит нам, что не стоит предпринимать действия, если сопряженные с ними ____________ (**предельный, издержка**) превышают предельную прибыль.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные издержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельные нормы', 
                          title = 'Если ____________ (**предельный, норма**) замены совпадают при любых комбинациях благ, то они выражают одну и ту же систему предпочтений индивидов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельные нормы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельной', 
                          title = 'Согласно теории ____________ (**предельный**) полезности потребитель может индивидуально определить полезность блага для себя.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный доход', 
                          title = 'Мы должны определить чистый ____________ (**предельный, доход**) фирмы от продажи.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный доход',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'В условиях совершенной конкуренции и на товарном, и на факторном рынке спрос предприятия на какой-либо переменный ресурс зависит от его цены, от величины его ____________ (**предельный, продукт**) и от рыночной цены товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный доход', 
                          title = 'Для каждой дополнительной единицы ____________ (**предельный, доход**) падает, а предельные издержки растут.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный доход',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельными издержками', 
                          title = 'Олигополист, максимизирующий прибыль, должен уравнять предельный доход с ____________ (**предельный, издержка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельными издержками',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельного продукта', 
                          title = 'Равновесная цена покупки земли или капитала зависит от теку­щей стоимости их ____________ (**предельный, продукт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельному', 
                          title = 'Монополист выбирает тот уровень производства, при котором предельные издержки равны ____________ (**предельный**) доходу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельному',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный', 
                          title = 'Прибыль максимальна, когда ____________ (**предельный**) доход равняется предельным издержкам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предельный доход', 
                          title = 'В этом случае ____________ (**предельный, доход**) ниже предельных издержек.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предельный доход',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

