
```{r}
checkdown::check_question(answer = stringr::str_split('труднодоступная центральная и южная Эвенкия; - территория, где связь с; остальными районами и даже между; населенными пунктами осуществляется прежде всего малой авиацией', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'труднодоступная центральная и южная Эвенкия; - территория, где связь с; остальными районами и даже между; населенными пунктами осуществляется прежде всего малой авиацией',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('одним из; главных показателей; выступает расстояние; между населенными пунктами', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'одним из; главных показателей; выступает расстояние; между населенными пунктами',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('пример показывает, сколько процентов; реального годового ВНП следует; принести в жертву ради; сокращения инфляции на один процентный пункт', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пример показывает, сколько процентов; реального годового ВНП следует; принести в жертву ради; сокращения инфляции на один процентный пункт',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('тип центра устанавливался; на основе обобщения; информации о размещении; в населенном пункте хозяйственных и социальных объектов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'тип центра устанавливался; на основе обобщения; информации о размещении; в населенном пункте хозяйственных и социальных объектов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('обращает на; себя внимание; разная продолжительность; безработицы по типам населенных пунктов', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обращает на; себя внимание; разная продолжительность; безработицы по типам населенных пунктов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'населенных пунктов', 
                          title = '#### Обращает на себя внимание разная продолжительность безработицы по типам ____________ (**населенный, пункт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'населенных пунктов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'населенными пунктами', 
                          title = '#### Одним из главных показателей выступает расстояние между ____________ (**населенный, пункт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'населенными пунктами',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'пункта, п', 
                          title = '#### Например, в 1992 г. уровень безработицы составлял 7,4%, то есть на 1,4 процентного пункта превышал предполагаемый естественный уровень, равный примерно 6%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пункта, п',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'населенном пункте', 
                          title = '#### Тип центра устанавливался на основе обобщения информации о размещении в ____________ (**населенный, пункт**) хозяйственных и социальных объектов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'населенном пункте',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'населенными пунктами', 
                          title = '#### Труднодоступная центральная и южная Эвенкия - территория, где связь с остальными районами и даже между ____________ (**населенный, пункт**) осуществляется прежде всего малой авиацией.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'населенными пунктами',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```
