```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'В результате специфической региональной политики правительства Тайваня сформировалась некоторая территориальная неравномерность ____________ (**экономический, развитие**). В последнее десятилетие правительство уделяло больше внимания развитию ее северной части по сравнению с южной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'условия для развития', 
                          title = 'На территории макрорегиона могут быть созданы идеальные правовые ____________ (**условие, для, развитие**) человеческого потенциала, бизнеса, институтов гражданского общества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'условия для развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'показателями развития', 
                          title = 'Взаимосвязь нормальной и избыточной дифференциации доходов населения с ____________ (**показатель, развитие**) региональных экономик.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'показателями развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'ЕС является первым интеграционным объединением стран с рыночной экономикой, имеющих различный уровень и темпы ____________ (**экономический, развитие**), в рамках которого создан общий бюджет для реализации совместных задач развития.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'перспективах развития', 
                          title = 'Нельзя делать окончательные выводы о ____________ (**перспектива, развитие**) высокотехнологичного сектора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'перспективах развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'проектов по развитию', 
                          title = 'Сохраняются возможности для финансирования перспективных ____________ (**проект, по, развитие**) инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'проектов по развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расходы на развитие', 
                          title = 'Государственные ____________ (**расход, на, развитие**) системы образования, здравоохранение, культуру не компенсируют недостаток индивидуальных вложений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расходы на развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитии страны', 
                          title = 'Уникальность и значимость Сибири в ____________ (**развитие, страна**) должны предопределять приоритетность и высокий уровень социального развития ее регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитии страны',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития инфраструктуры', 
                          title = 'Присоединение к ВТО сможет улучшить транзитные возможности России при условии ____________ (**развитие, инфраструктура**) и принятия мер по повышению конкурентоспособности предоставляемых транспортных услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития инфраструктуры',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитие экономики', 
                          title = 'С 1980 по 1982 г. на ____________ (**развитие, экономика**) в основном влияли эффекты монетарного сжатия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитие экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияние на развитие', 
                          title = 'Эти ученые оказали наибольшее ____________ (**влияние, на, развитие**) мировой экономической мысли, вошедшие в учебники по истории экономических учений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние на развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Нужно интегрировать задачу снижения климатических рисков в стратегию устойчивого ____________ (**экономический, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономическое развитие', 
                          title = 'Многим экономистам и политикам пришлось признать, что война вынуждает государство использовать мобилизационные методы в организации производства и общества для нужд обороны. А для этого требуется вмешательство государства в ____________ (**экономический, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономическое развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровню развития', 
                          title = 'До последнего времени по ____________ (**уровень, развитие**) человеческого потенциала выделяли четыре группы стран.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровню развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитие экономики', 
                          title = 'Инвестиционная деятельность — это комплекс функций, связанных с какими-либо вложениями в ____________ (**развитие, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитие экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Многие критики считают, что региональный принцип организации сберегательного дела тормозит возможности ____________ (**экономический, развитие**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'устойчивого развития', 
                          title = 'Большое значение для ____________ (**устойчивый, развитие**) экономики регионов Севера имеет восполнение запасов минерального сырья.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивого развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'становления и развития', 
                          title = 'В минерально-сырьевом секторе начальный этап формирования предпосылок для ____________ (**становление, и, развитие**) кластеров, как правило, связан с деятельностью крупной (транснациональной или трансрегиональной) компании.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'становления и развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития производительных сил', 
                          title = 'Характер и уровень ____________ (**развитие, производительный, сила**) определяют экономические взаимоотношения людей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития производительных сил',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'устойчивому развитию', 
                          title = 'Основным направлением Арктического совета является содействие ____________ (**устойчивый, развитие**) Арктики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивому развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'формировании и развитии', 
                          title = 'Выявление зон влияния городов представляется нам одним из важнейших этапов в ____________ (**формирование, и, развитие**) экономики и социальной сферы любого города.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'формировании и развитии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития инфраструктуры', 
                          title = 'Отмечается низкий уровень ____________ (**развитие, инфраструктура**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития инфраструктуры',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'устойчивого развития', 
                          title = 'Для ____________ (**устойчивый, развитие**) экономики в долгосрочной перспективе необходимо именно сотрудничество, а не только соперничество экономических субъектов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивого развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиций в развитие', 
                          title = 'Масштаб отечественных и зарубежных ____________ (**инвестиция, в, развитие**) Дальнего Востока впечатляет, однако отдача от них пока не слишком значительная.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиций в развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роль в развитии', 
                          title = 'Приграничные регионы (главное, Дальневосточный регион России и провинция Хэйлунцзян Китая) играют важную ____________ (**роль, в, развитие**) политических и экономических отношений между двумя странами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роль в развитии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономическое развитие', 
                          title = 'В условиях произошедшей модернизации экономики и общества ____________ (**экономический, развитие**) и общественное благосостояние стимулируются не ростом средней плотности населения самой по себе, а ее повышением в рамках урбанизации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономическое развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'поддержания и развития', 
                          title = 'Высокая и устойчивая загрузка мощностей — наиболее благоприятный режим для ____________ (**поддержание, и, развитие**) компетенций компании. Иными словами, постоянная загрузка в 60% мощностей лучше, чем 100% — в один период и 20% — в другой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'поддержания и развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнях развития', 
                          title = 'Создание единого рынка приводит к тому, что капитал и рабочая сила в значительных масштабах размещаются в районах, с более привлекательными физическими и экономическими условиями. Различия в ____________ (**уровень, развитие**) между регионами внутри стран ЕС часто являются очевидными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнях развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнях развития', 
                          title = 'Концепция равного партнерства проповедует создание системы равной взаимозависимости развивающихся и западных стран, при этом сложно не замечать разрыв в ____________ (**уровень, развитие**) двух подсистем мирового хозяйства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнях развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'этапа развития', 
                          title = 'Выводы делаются с учетом местных особенностей и особенностей современного ____________ (**этап, развитие**) российской экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'этапа развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'устойчивое развитие', 
                          title = 'Принципы из Декларации ориентированы на ____________ (**устойчивый, развитие**) через либерализацию торговли, борьбу с бедностью, вопросы защиты окружающей среды и др.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивое развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень развития', 
                          title = 'В стратегии размЕщения инвестиций должны найти отражение следующие факторы: наличие эффективных инвестиционных проектов, ____________ (**уровень, развитие**) инфраструктуры (производственной, рыночной, социальной), трудовые ресурсы и их квалификация, финансовый климат.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'регионального развития', 
                          title = 'Эффективность институтов региональной власти является важным фактором ____________ (**региональный, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'регионального развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'В результате вместо политики территориального развития, основанной на директивах «сверху», пришло «локальное развитие», основанное на поиске локальных, внутренних факторов ____________ (**экономический, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальное развитие', 
                          title = 'Как увеличить человеческий капитал и его вклад в экономическое и ____________ (**социальный, развитие**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальное развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального развития', 
                          title = 'Органы власти и бизнес взаимодействуют в решении общих проблем в пользу экономического и ____________ (**социальный, развитие**) региона.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Устройство современной денежно-кредитной системы вызывает немало вопросов, особенно в периоды финансовых кризисов. Теория предпочтения ликвидности Дж.М.Кейнса и теория ____________ (**экономический, развитие**) Й.Шумпетера дают надежные ориентиры, позволяющие прояснить ключевые аспекты этой важной темы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'показателей развития', 
                          title = 'Состояние внешнеторговых связей – один из важнейших ____________ (**показатель, развитие**) интеграционных процессов на территории Евразийского экономического союза.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'показателей развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияние на развитие', 
                          title = 'Важно учитывать ____________ (**влияние, на, развитие**) отрасли инвестиционных фондов динамики финансовых рынков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние на развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'вклад в развитие', 
                          title = 'Любое системное получение знаний может и должно рассматриваться как ____________ (**вклад, в, развитие**) человеческого потенциала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'вклад в развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень развития', 
                          title = 'Отсутствие инфраструктуры, низкий ____________ (**уровень, развитие**) человеческого капитала и плохое качество институтов доверия ограничивают приток капитала в такие страны из мировой экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Две компании  во многом определяют динамику доходов регионального бюджета и, в конечном счете, возможности ____________ (**экономический, развитие**) региона.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'региональное развитие', 
                          title = 'Может ли экономическая открытость положительно влиять на ____________ (**региональный, развитие**) и снижение уровня бедности?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'региональное развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Количество прямых иностранных инвестиций снизилось до 21% в 2001 г. Причиной этого стало снижение темпов ____________ (**экономический, развитие**) практически во всех странах и сокращение прибыльности компаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Наиболее высокие темпы национального дохода характерны для перехода страны к более высокому уровню ____________ (**экономический, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальноэкономического развития', 
                          title = 'Индивидуальное благосостояние выдвинулось в качестве одной из основных проблем социально-экономического развития. Обязанностью общества становятся контроль за мерой труда и потребления, сокращение неравенства в доходах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальноэкономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роль в развитии', 
                          title = 'Важную ____________ (**роль, в, развитие**) современных теорий спроса на деньги сыграла кейнсианская теория предпочтения ликвидности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роль в развитии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень развития', 
                          title = 'Главной причиной отставания экономики северо-восточных провинций Китая остается низкий ____________ (**уровень, развитие**) рыночных механизмов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стратегией развития', 
                          title = 'Стратегии развития субъектов РФ и федеральных округов должны базироваться и согласовываться со ____________ (**стратегия, развитие**) экономики страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стратегией развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'становлении и развитии', 
                          title = 'Какова роль денег как ликвидного актива в ____________ (**становление, и, развитие**) рыночной экономики?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'становлении и развитии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития страны', 
                          title = 'Представление об основных показателях экономического ____________ (**развитие, страна**) дает таблица 5.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития страны',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предпосылки для развития', 
                          title = 'С одной стороны, развитие инфраструктуры создает ____________ (**предпосылка, для, развитие**) сектора производства товарной продукции, и чем меньше степень экономической освоенности территории, тем важней для нее развитие инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предпосылки для развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономическое развитие', 
                          title = 'Оценка реальных размеров ресурсного сектора и его вклада в ____________ (**экономический, развитие**) является непростой задачей для российской экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономическое развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'устойчивому развитию', 
                          title = 'Кризис 2020 года меняет отношение инвесторов к ____________ (**устойчивый, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивому развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровню развития', 
                          title = 'Можно сделать вывод, что регионом-лидером по ____________ (**уровень, развитие**) цифровой экономики являлся Санкт-Петербург.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровню развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпы развития', 
                          title = 'Социализм сохранился (Китай, Вьетнам и др.), причем высокие ____________ (**темп, развитие**) этих стран в последние десятилетия привели к усилению его мощи и влияния.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпы развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'воздействие на развитие', 
                          title = 'Реализация масштабного проекта окажет положительное ____________ (**воздействие, на, развитие**) всех отраслей экономики региона.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'воздействие на развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Нормально работающие институты и инфраструктура важны для ____________ (**экономический, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'моделей развития', 
                          title = 'Экономика Китая переживает решающий период трансформации ____________ (**модель, развитие**) и структурной оптимизации, демонстрируя хорошие перспективы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'моделей развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Темпы ____________ (**экономический, развитие**) федеральных округов могут зависеть от количества региональных банков, зарегистрированных на их территории.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'этапа развития', 
                          title = 'Особенностью современного ____________ (**этап, развитие**) рыночной экономики является переход к новому типу экономического роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'этапа развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития экономики', 
                          title = 'Анализируя исторические факты ____________ (**развитие, экономика**) в условиях большого бюджетного дефицита, экономисты не могут сделать однозначные выводы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'способствовать развитию', 
                          title = 'Консолидация ресурсов будет ____________ (**способствовать, развитие**) жизненно важных отраслей производственной инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'способствовать развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'В конце прошлого столетия уровень ____________ (**экономический, развитие**) мировой периферии повысился. Однако в ряде районов развивающегося мира численность населения увеличивалась быстрее, чем производство.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем развития', 
                          title = 'В целом ряде стран с низким ____________ (**уровень, развитие**) в общественном секторе значительное место занимают производственные предприятия, чистый доход которых является источником государственных расходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предпосылки для развития', 
                          title = 'В промышленно развитых странах для поддержания социальной безопасности перераспределяется 15—22% ВВП, что создает ____________ (**предпосылка, для, развитие**) человека. Основное место в этих расходах занимает социальное обеспечение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предпосылки для развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития страны', 
                          title = 'Еще одним ключевым элементом государственной концепции социально-экономического ____________ (**развитие, страна**) в долгосрочной перспективе является модернизация общего курса в пользу усиления инновационных механизмов в экономике и производстве.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития страны',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'функционирование и развитие', 
                          title = 'Все меры обеспечивают устойчивое ____________ (**функционирование, и, развитие**) экономики страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функционирование и развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'формировании и развитии', 
                          title = 'В ____________ (**формирование, и, развитие**) политической экономии как науки выдающуюся роль сыграли такие ученые, как уже названный нами Франсуа Кенэ, английские экономисты Уильям Петти , Адам Смит.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'формировании и развитии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стратегии развития', 
                          title = 'Результаты исследования могут быть использованы при разработке ____________ (**стратегия, развитие**) отдельных секторов отечественной экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стратегии развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ресурсов для развития', 
                          title = 'ценные бумаги заключается в обеспечении соблюдения пра- вил действия всех субъектов рынка ценных бумаг в целях мобилизации свободных ____________ (**ресурс, для, развитие**) экономики и формирования надежных и доходных инструментов сбере- жения для населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ресурсов для развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития экономики', 
                          title = 'Как заметил известный экономист Роберт Солоу: «Компьютеры изменили в нашей жизни все, кроме показателя роста производительности труда». Каковы же перспективы ____________ (**развитие, экономика**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальноэкономического развития', 
                          title = 'Еще одним ключевым элементом государственной концепции социально-экономического развития страны в долгосрочной перспективе является модернизация общего курса в пользу усиления инновационных механизмов в экономике и производстве.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальноэкономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'условий для развития', 
                          title = 'Необходимо выполнить задачу по созданию «цифровой экономики» и ____________ (**условие, для, развитие**) «виртуального бизнеса».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'условий для развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'индекс развития', 
                          title = 'В таблице представлен индекс конкурентоспособности, индекс экономики знаний и ____________ (**индекс, развитие**) человеческого потенциала отдельных стран мира.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекс развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'по мере развития', 
                          title = 'Если прежде в графике мирового распределения доходов наблюдался существенный разрыв между экономиками развитых и развивающихся стран, то ____________ (**по, мера, развитие**) глобальной торговли разрыв стал снижаться.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по мере развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'получила развитие', 
                          title = 'Теория трансакционных издержек ____________ (**получить, развитие**) в теории цепочек создания стоимости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'получила развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'устойчивому развитию', 
                          title = 'Переход к ____________ (**устойчивый, развитие**) Дальнего Востока возможен в том случае, если будет обеспечено устойчивое развитие всех его регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивому развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стратегического развития', 
                          title = 'Перспективы ____________ (**стратегический, развитие**) региона предопределяются величиной и эффективностью использования его социально-экономического потенциала, а также внешними факторами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стратегического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'воздействие на развитие', 
                          title = 'Развитие всех остальных отраслей сектора услуг оказывает лишь положительное ____________ (**воздействие, на, развитие**) мировой экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'воздействие на развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономическом развитии', 
                          title = 'Роль конкуренции в ____________ (**экономический, развитие**) не подвергается сомнению.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономическом развитии',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем развития', 
                          title = 'Почти 30% населения России проживает в регионах с высоким ____________ (**уровень, развитие**) человеческого потенциала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'вложения в развитие', 
                          title = 'При доходности в десятки и сотни тысяч процентов____________ (**вложение, в, развитие**) производства потеряли всякий смысл.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'вложения в развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития стран', 
                          title = 'Дайте определение финансовой грамотности и ее роли в повышении качества жизни населения и экономического ____________ (**развитие, страна**)ы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития стран',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитие инфраструктуры', 
                          title = 'Муниципальные власти обладают меньшими возможностями инвестирования в ____________ (**развитие, инфраструктура**) общественного транспорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитие инфраструктуры',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'С расширением производства и экспорта минерального сырья во многом связывал перспективы ____________ (**экономический, развитие**) страны правящий диктаторский режим в 70-90-е годы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитие экономики', 
                          title = 'Люди могут инвестировать страховые средствав ____________ (**развитие, экономика**). Поэтому в развитых странах страховые компании являются крупнейшими инвесторами для бизнеса и государства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитие экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'создания и развития', 
                          title = 'Экономические интересы - это та платформа, которая служит основанием и главным стимулом для ____________ (**создание, и, развитие**) организаций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'создания и развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'этапе развития', 
                          title = 'Роль патентной защиты интеллектуальной собственности и на этапе создания, и на ____________ (**этап, развитие**) оценивается всеми невысоко.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'этапе развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня развития', 
                          title = 'Проведены моделирование и оценка влияния ____________ (**уровень, развитие**) социальной инфраструктуры на продолжительность жизни населения в регионах России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'проекты по развитию', 
                          title = 'Также одной из важных тем, вызывающих особый интерес у китайских партнеров, стало развитие сотрудничества в инновационной сфере, включая проекты в топливно-энергетическом комплексе, ____________ (**проект, по, развитие**) инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'проекты по развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'перспективам развития', 
                          title = 'Основное внимание уделяется проблемам и ____________ (**перспектива, развитие**) отдельных муниципальных образований.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'перспективам развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Явление, когда более бедная страна при прочих равных условиях может обеспечить более высокие темпы экономического роста и со временем догнать по уровню ____________ (**экономический, развитие**) более богатую страну, получило название эффекта быстрого старта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития экономики', 
                          title = 'Банки не просто формируют собственные ресурсы, они обеспечивают внутреннее накопление средств для ____________ (**развитие, экономика**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'создание и развитие', 
                          title = 'Одним из направлений реформирования отечественных субъектов хозяйствования становится ____________ (**создание, и, развитие**) корпоративной формы собственности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'создание и развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Выделяется группа новых индустриализующихся стран. К ним относятся страны с относительно высоким уровнем ____________ (**экономический, развитие**) и существенным, развивающимся, многоотраслевым по структуре промышленным сектором (20% ВВП).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'толчок к развитию', 
                          title = 'Значительный ____________ (**толчок, к, развитие**) получила сфера услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'толчок к развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'по мере развития', 
                          title = 'Отдача от опыта возрастает ____________ (**по, мера, развитие**) экономики, указывает на возможности развивающихся экономик сократить отставание от развитых стран.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по мере развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'устойчивому развитию', 
                          title = 'Новые цели финансовой политики ориентированы на увеличение конкурентоспособности и содействие ____________ (**устойчивый, развитие**) регионов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'устойчивому развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем развития', 
                          title = 'ПеремЕщение России в 2004 г. в группу стран с высоким ____________ (**уровень, развитие**) человеческого потенциала и ее закрепление там в последующие годы объясняются главным образом ростом ВВП на душу населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Конкурентная привлекательность округа обеспечивается высоким уровнем ____________ (**экономический, развитие**)  и развития человеческого потенциала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'В выборке для анализа есть неравные доли государств с разным уровнем ____________ (**экономический, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня развития', 
                          title = 'Возможности поддержки населения и бизнеса у регионов зависят от ____________ (**уровень, развитие**) их экономики и социальной сферы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'темпы развития', 
                          title = 'С начала 80-х гг. Китаю удается поддерживать высокие ____________ (**темп, развитие**), примерно 10% прироста ВВП в год.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'темпы развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'индекс развития', 
                          title = 'Расчет индекса человеческого развития (до 2013 г. -____________ (**индекс, развитие**) человеческого потенциала, ИРЧП)  является одним из наиболее универсальных показателей для сравнения стран между собой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекс развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'В приморских районах во время рыночных реформ была реализована экспортно ориентированная модель ____________ (**экономический, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Особенности современного экономического роста заключаются в усилении его неустойчивости в условиях турбулентности мирового ____________ (**экономический, развитие**), расхождении траекторий роста развитых и развивающихся стран.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'На современном уровне ____________ (**экономический, развитие**) индустриальных стран предельный рост экономических аспектов благосостояния может быть меньше экономического роста, так как для определенных приростов благосостояния требуются большие приросты ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем развития', 
                          title = 'Исследуются проблемы освоения минерально-сырьевой базы ресурсного региона с низким ____________ (**уровень, развитие**) производственной инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня развития', 
                          title = 'Как учитывается влияние ____________ (**уровень, развитие**) социальной инфраструктуры при прогнозировании демографических процессов в регионах Российской Федерации?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'перспективы развития', 
                          title = 'Ближайшие ____________ (**перспектива, развитие**) экономики в зоне Крайнего Севера связаны с освоением новых месторождений особо ценного минерального сырья.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'перспективы развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'способствовать развитию', 
                          title = 'Предполагалось, что данная мера будет ____________ (**способствовать, развитие**) мини-гостиниц и частных отелей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'способствовать развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'В результате различий в экономической динамике обозначились крупные различия в уровне ____________ (**экономический, развитие**) среди групп стран и регионов. Если в промышленно развитых странах Запада различия в уровнях дохода на душу населения сократились за последние полвека, то на периферии мирового хозяйства они увеличились.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития производительных сил', 
                          title = 'Большое значение играет концепция ____________ (**развитие, производительный, сила**) Дальнего Востока.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития производительных сил',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем развития', 
                          title = 'Значимость финансовых услуг возрастает вместе с ____________ (**уровень, развитие**) страны. Чем более развитой является экономика, тем больше становится доля финансового сектора в ней, возрастает уровень финансовой глубины.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'технологического развития', 
                          title = 'Вице-премьер российского правительства назвал три основные задачи ____________ (**технологический, развитие**) России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'технологического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитию инфраструктуры', 
                          title = 'В современных условиях все больше внимания уделяется совместной реализации крупных инвестиционных проектов, проектов по ____________ (**развитие, инфраструктура**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитию инфраструктуры',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономического развития', 
                          title = 'Все еще сохраняется неопределенность перспектив мирового ____________ (**экономический, развитие**) после кризиса 2009 г., которая получила название «новая нормальность» (или «новая реальность»).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

