
```{r}
checkdown::check_question(answer = stringr::str_split('рассчитывается; как; разница; между', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рассчитывается; как; разница; между',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('нефтегазовый дефицит федерального; бюджета представляет собой; разницу между объемом; доходов и объемом расходов федерального бюджета', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'нефтегазовый дефицит федерального; бюджета представляет собой; разницу между объемом; доходов и объемом расходов федерального бюджета',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('доход инвестора возникает; за счет разницы; между ценой погашения; облигации (номиналом) и ценой ее приобретения', '; ') |> unlist(), 
                          type = 'in_order',
                          alignment = 'vertical',
                          right = 'все верно!',
                          title = '#### Поставьте фрагменты предложений в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доход инвестора возникает; за счет разницы; между ценой погашения; облигации (номиналом) и ценой ее приобретения',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'валовым доходом', 
                          title = '#### Экономическую прибыль надо отличать от бухгалтерской прибыли, которая представляет собой разницу между ____________ ____________ (**валовой, доход**) и явными издержками на ресурсы, используемые в производстве.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'валовым доходом',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'годовым "потолком', 
                          title = '#### Маржа представляет собой разницу между ____________ ____________ (**годовой, ", потолок**)" MFF и годовым бюджетом ЕС.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'годовым "потолком',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'суммой', 
                          title = '#### Банковская прибыль определяется как разница между ____________ (**сумма**) процентов, взимаемых с заемщиков за предоставленный кредит, и суммой процентов, выплачиваемых вкладчикам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'суммой',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'разницы', 
                          title = '#### Доход инвестора возникает за счет ____________ (**разница**) между ценой погашения облигации (номиналом) и ценой ее приобретения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'разницы',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```

```{r}
checkdown::check_question(answer = 'ценой', 
                          title = '#### Если инвестор продает облигацию, не дожидаясь погашения, то величина Р представляет собой разницу между ____________ (**цена**) продажи и ценой приобретения облигации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценой',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')                          
```
