```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Иммигранты конкурируют с коренными жителями на рынке редких видов работ; снижают средний уровень ____________ (**реальный**) заработной платы и пополняют списки на получение государственных пособий за счет налогоплательщиков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальная', 
                          title = '#### Какова же будет ____________ (**реальный**) ставка доходности, если номинальная процентная ставка составляет 8% в год, а уровень инфляции, который изменяется пропорционально изменению индекса потребительских цен, — 5% в год?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Ранее среднегодовые темпы роста ____________ (**реальный**) заработной платы работников бюджетной сферы в 2014-2016 гг. оценивались на уровне 2,7% вместо 7,6% согласно программе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Растущий уровень ____________ (**реальный**) заработной платы вызывает оживление инвестирования в основной капитал.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальные', 
                          title = '#### Как отмечают эксперты МВФ, в странах с развитой экономикой ____________ (**реальный**) доходы верхнего 1% населения возрастали в годовом исчислении в три раза быстрее по сравнению с остальной частью населения за последние тридцать лет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальном', 
                          title = '#### Замедленная экономическая динамика обусловила повышенные темпы сокращения численности занятых в экономике (в 2000 г. по сравнению с 1995 г. в округе - 94,7% против 97,3% в целом по России), пониженные темпы роста номинальной заработной платы (к 2000 г. превышение среднего по стране уровня уже почти символическое - 102,1%, а в ____________ (**реальный**) выражении она стала даже ниже).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальном',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных', 
                          title = '#### Ситуация усугубляется тем, что начиная с 2014 г. отмечается падение ____________ (**реальный**) денежных доходов населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиций реальный', 
                          title = '#### В связи с этим возникает необходимость разработки действенных механизмов, обеспечивающих приток инвестиций в реальный сектор экономики, которые должны быть выгодными как для субъекта бизнеса, так и для государства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиций реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальная', 
                          title = '#### Предположим, что ____________ (**реальный**) заработная плата падала всякий раз, когда имелся избыток предложения труда, и росла, когда наблюдался избыток спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Используйте понятие эффекта дохода и эффекта замЕщения для объяснения того, почему временный рост ____________ (**реальный**) заработной платы увеличивает предложение труда, а ее постоянное увеличение уменьшает предложение труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Снижение уровня ____________ (**реальный**) заработной платы приводит к изменению ценности предельного продукта труда, предприниматели повышают спрос на труд.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальный', 
                          title = '#### Уровень инфляции будет увеличивать номинальную процентную ставку, заставляя людей сокращать свои реальные денежные остатки. Таким образом, вырастет ли ____________ (**реальный**) доход от сеньоража в случае более быстрого темпа роста денежной массы, зависит от того, перевешивает ли рост инфляции снижение реальных денежных остатков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Для России в целом и для всех регионов страны темпы роста ____________ (**реальный**) заработной платы за период 2003-2012 гг. превышали темпы роста производительности труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального', 
                          title = '#### Темп прироста ____________ (**реальный**) дохода на душу населения в качестве главного измерителя экономического роста называет и Э. Хелпман.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального', 
                          title = '#### Спрос на деньги, в таком случае, определяется только трансакционным мотивом. Считается, что данный случай отражает радикальный взгляд монетаристов по поводу того, что уровень ____________ (**реальный**) дохода зависит исключительно от реального предложения денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальном', 
                          title = '#### В настоящей главе было показано, что на динамику цен финансовых активов на рынке могут оказывать влияние и кризисы в ____________ (**реальный**) секторе экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальном',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальный', 
                          title = '#### Поскольку вы продаете свой дом за ту же реальную цену, по которой вы его купили, ваш ____________ (**реальный**) доход равен нулю и вы не должны платить никакого налога.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных', 
                          title = '#### Кредиты банков выступают как одна из наиболее распространенных форм внешнего финансирования ____________ (**реальный**) инвестиций в тех случаях, когда компании не могут обеспечить их реализацию за счет собственных средств и эмиссии ценных бумаг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальный', 
                          title = '#### Финансово-экономическая оценка инвестиционных проектов занимает важное место в процессе обоснования и выбора возможных вариантов вложения денежных средств в ____________ (**реальный**) сектор экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальном', 
                          title = '#### Из презентаций данных и прогнозов можно сделать вывод, что серьезные экзогенные шоки, скорее всего, не привели к существенным структурным сдвигам в ____________ (**реальный**) секторе экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальном',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального', 
                          title = '#### Выпуск большего фактического объема продукции в час означает распределение большего ____________ (**реальный**) дохода на каждый отработанный час.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Ставка процента, выраженная в терминах корзины товаров, называется ____________ (**реальный**) ставкой процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Для спроса на труд любого уровня ____________ (**реальный**) заработной платы спрос фирм на труд возрастает после благоприятного шока предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальная', 
                          title = '#### Если реальный курс ценных бумаг по истечении года составит всего 40 долл., какова будет ваша ____________ (**реальный**) ставка доходности?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Воздействие временного снижает величину спроса на труд при любом уровне неблагоприятного шока ставки ____________ (**реальный**) заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных', 
                          title = '#### Повсеместно произошло падение ____________ (**реальный**) доходов населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Теория эффективной заработной платы объясняет, почему некоторые фирмы хотели бы устанавливать ставки ____________ (**реальный**) заработной платы выше рыночного уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Во-вторых, увеличение ____________ (**реальный**) заработной платы делает работников ощутимо богаче, так как за то же самое количество времени работы они теперь получают более высокий доход.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальный', 
                          title = '#### Теперь давайте разберемся. как смЕщение кривых совокупного спроса и совокупного предложения влияет на ____________ (**реальный**) объем производства и уровень цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальный', 
                          title = '#### При вложении средств в ____________ (**реальный**) сектор экономики движение инвестиций осуществляется в форме кругооборота производительного капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Если сохранится подобная тенденция, то уровень ____________ (**реальный**) заработной платы в 2030 г. будет соответствовать уровню 2016 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Определено, что временное увеличение ____________ (**реальный**) заработной платы, увеличивающее количество предлагаемого труда, является результатом действия эффекта замЕщения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальный', 
                          title = '#### В соответствии с работами, посвященными оценке воздействия изменчивости инфляции на ____________ (**реальный**) сектор экономики, предельный негативный эффект волатильности инфляции может увеличиваться по мере роста ее уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Благоприятные шоки предложения сдвигают кривую MPN вверх и вправо, вызывая рост величины спроса на труд при любой данной ____________ (**реальный**) заработной плате.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальные', 
                          title = '#### В отличие от предыдущего кризиса ____________ (**реальный**) доходы населения сокращались как за счет заработной платы, так и за счет социальных трансфертов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальная', 
                          title = '#### Если для измерения уровня цен мы используем индекс потребительских цен (ИПЦ), то ____________ (**реальный**) ставка процента показывает, от какого объема потребления нам придется отказаться в следующем периоде, чтобы потреблять больше сегодня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальная', 
                          title = '#### Для упрощения расчетов предположим, что ____________ (**реальный**) ставка процента равна нулю.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальный', 
                          title = '#### Но вы можете быть уверены в том, что ваш номинальный доход будет возрастать темпом, не меньшим, чем уровень инфляции. Таким образом, ваш ____________ (**реальный**) доход, по крайней мере, не снизится.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных', 
                          title = '#### Потери ____________ (**реальный**) доходов населения в результате инфляции, называют инфляционным налогом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального', 
                          title = '#### Условием качественной подготовки и переподготовки кадров является сотрудничество образовательных организаций ДПО и предприятий ____________ (**реальный**) сектора экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### И в том и в другом случае равновесие восстанавливается за счет изменения равновесного уровня ____________ (**реальный**) заработной платы, что ведет к изменению равновесного количества труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Денежные ставки заработной платы остались бы неизменными, и экономика осталась бы в положении полной занятости. Конечно, уровень ____________ (**реальный**) заработной платы оказался бы ниже, но в конце концов он все равно бы упал.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальная', 
                          title = '#### Здесь же достаточно лишь заметить, что ____________ (**реальный**) ставка процента измеряет действительные издержки заимствования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных', 
                          title = '#### Это подразумевает снижение уровня бедности, ускоренное формирование среднего класса, переключение акцента в инвестициях в пользу человеческого капитала, рост ____________ (**реальный**) доходов населения и на этой основе увеличение степеней свободы экономического поведения резидентов края.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных', 
                          title = '#### Спрос на реальные балансы зависит от уровня ____________ (**реальный**) доходов и уровня ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Если инфляция снижается и, таким образом, становится ниже темпа роста номинальной денежной массы, тогда рост ____________ (**реальный**) денежной массы теперь станет положительным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Так же как растет количество труда, предлагаемого индивидуумами при увеличении их ставки ____________ (**реальный**) заработной платы, совокупное предложение труда растет при увеличении ставки реальной заработной платы в целом по экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Но прошествии достаточного времени более низкий уровень цен Р, способствовавший увеличению ____________ (**реальный**) заработной платы, приведет к палению номинальной зарплаты до уровня, при котором реальная заработная плата вернется на прежний уровень.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Поведение работника в случае, когда предельная норма замЕщения досугом потребительских благ превышает величину ____________ (**реальный**) заработной платы С — потребительские блага, N — досуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных', 
                          title = '#### Падение ____________ (**реальный**) доходов населения вместе с сокращением потребительского кредитования привело к уменьшению оборота розничной торговли и спроса на жилье.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального', 
                          title = '#### В соотвегствии с результатами С. Голдфельда на краткосрочном периоде (один квартал) эластичность спроса от ____________ (**реальный**) дохода равна 0,19. Это означает, что увеличение реального дохода на 1% увеличивает спрос на деньги на 0,19%, что значительно меньше, чем пропорциональное увеличение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальном', 
                          title = '#### Вероятно запасы денежных средств в ____________ (**реальный**) выражении приходят в соответствие с издержками хранения денег на руках постепенно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальном',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальная', 
                          title = '#### В главе 14 мы уточнили, что при решении о размере инвестиций важна не номинальная, а ____________ (**реальный**) ставка процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальные', 
                          title = '#### Если реальный капитал увеличивается за счет инвестиций в ____________ (**реальный**) активы, то финансовый капитал может прирастать без дополнительных инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального', 
                          title = '#### Вообще говоря, для любого значения объема производства увеличение ____________ (**реальный**) спроса на деньги вызывает рост реальной процентной ставки, обеспечивающей равновесие на рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Постоянный уровень ____________ (**реальный**) заработной платы является допустимой аппроксимацией действительного характера изменений заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальный', 
                          title = '#### Несмотря на тот факт, что ваш ____________ (**реальный**) доход от капитала равен нулю, вы выплачиваете высокий налог.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальный',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Совместное воздействие эффекта замЕщения и эффекта дохода: долгосрочный рост ____________ (**реальный**) заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных', 
                          title = '#### В целом политика государства и отдельных корпораций в отношении северных регионов остается дискриминационной, о чем свидетельствуют крайне низкий рост ____________ (**реальный**) доходов, отрицательное сальдо миграции населения и истощение разведанной ресурсной базы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального', 
                          title = '#### Вообще говоря, для любого значения объема производства увеличение ____________ (**реальный**) предложения денег снижает реальную процентную ставку, обеспечивающую равновесие на рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### Заметим, что эффекты замЕщения и дохода более высокой ____________ (**реальный**) заработной платы действуют в противоположных направлениях: эффект замЕщения увеличивает количество предлагаемого труда, а эффект дохода уменьшает его.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальной', 
                          title = '#### По аналогии с тем, что мы используем понятие естественный уровень для характеристики ВВП в среднесрочной перспективе, введем соответствующее понятие и для ____________ (**реальный**) ставки процента, r n — естественная реальная ставка процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального', 
                          title = '#### Помимо роста ____________ (**реальный**) дохода, единственной причиной, по которой население может увеличивать запасы номинальных денег, является стремление компенсировать инфляцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

