```{r}
checkdown::check_question(answer = 'рынок', 
                          title = 'Менеджеры должны обладать соответствующими компетенциями, чтобы грамотно использовать этот инструмент продвижения товара на мировой ____________ (**рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок', 
                          title = 'Судя по очень резкой реакции Банка России, правительства, можно сказать, что даже часть средств, которые выделили Банк России и правительство для финансового оздоровления в условиях кризиса, было направлено банками на валютный ____________ (**рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынка заемных средств', 
                          title = 'Несовершенство ____________ (**рынок, заемный, средства**), в случае когда мы говорим о человеческом капитале, ведет к тому, что не все индивиды могут принять оптимальное решение об уровне образования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынка заемных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок представляет собой', 
                          title = 'Рассматривая виды рынков, следует отметить, что внутренний ____________ (**рынок, представлять, себя**) форму товарообмена для потребителей данной страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок представляет собой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'с формирующимися рынками', 
                          title = 'Boissay et al. (2006) также изучают вопрос о равновесном уровне кредитной задолженности частного сектора и возможной чрезмерности роста кредитования в странах ____________ (**с, формировать, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'с формирующимися рынками',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на внешних рынках', 
                          title = 'В силу сокращения в 80-е и 90-е годы доходов страны от сырьевого экспорта существенно изменились возможности приобретения элементов основного и оборотного капитала ____________ (**на, внешний, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на внешних рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок', 
                          title = 'Доля импорта в поставках на внутренний ____________ (**рынок**) покрывает свыше половины спроса на ЭВМ и конторское оборудование, точную механику и оптику, цветную металлургию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на международном рынке', 
                          title = 'В целях увеличения своей доли ____________ (**на, международный, рынок**), Китай проводил политику занижения экспортных цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на международном рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на', 
                          title = 'Бюджеты ГВФ рассматриваются и утверждаются в форме федеральных законов одновременно с принятием федерального зако____________ (**на**) о федеральном бюджете на очередной финансовый год и плановый период.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на внутренних рынках', 
                          title = 'Конкуренция ____________ (**на, внутренний, рынок**) включает в себя: 1) конкуренцию регионов за привлечение компаний по переработке углеводородов; 2) конкуренцию компаний за использование ресурсов и за позиции на внутреннем рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на внутренних рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на валютном рынке', 
                          title = 'В чем проявляется различие между арбитражерами, хеджерами и спекулянтами, действующими ____________ (**на, валютный, рынок**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на валютном рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесие на рынке', 
                          title = 'Так как увеличение дохода вызывает рост реального спроса на деньги, что приводит к увеличению реальной процентной ставки, обеспечивающей ____________ (**равновесие, на, рынок**) активов, кривая LМ наклонена вверх.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесие на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на валютном рынке', 
                          title = 'Большую часть этого периода Банк России не проводил операции ____________ (**на, валютный, рынок**), а операции Минфина России в рамках бюджетного правила начались с начала 2017 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на валютном рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок представляет собой', 
                          title = 'Финансовый ____________ (**рынок, представлять, себя**) систему международных экономических отношений, которые связаны с торговлей, производством и инвестиционным сотрудничеством.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок представляет собой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынках факторов производства', 
                          title = 'На некоторых ____________ (**рынок, фактор, производство**) отдельные покупатели обладают монопсонической властью, т. е. они могут повлиять на цену.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынках факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предложения на рынке', 
                          title = 'Адаптивный механизм реализуется через согласование спроса и ____________ (**предложение, на, рынок**) труда и отражает степень удовлетворенности ЭА «Домохозяйства» сложившимися условиями.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предложения на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировых рынках', 
                          title = 'Операции на открытом рынке происходят, когда: а) страна увеличивает объем продаж ____________ (**на, мировой, рынок**); 6) коммерческие банки покупают и продают иностранную валюту;',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'и рынок товаров', 
                          title = 'Поэтому наклон кривой АД отражает степень, с которой изменение реальных балансов меняет равновесный уровень расходов, принимая во внимание как рынок активов, так ____________ (**и, рынок, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'и рынок товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'и рынок активов', 
                          title = 'Для обеспечения общего равновесия ставки процента и уровни дохода должны быть такими, чтобы как рынок товаров, так ____________ (**и, рынок, актив**) были в равновесии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'и рынок активов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок заемных средств', 
                          title = 'Поскольку финансовый капитал полностью универсален в своем применении, то ____________ (**рынок, заемный, средства**) может рассматриваться как почти буквальное воплощение идеи полностью однородного, стандартизированного продукта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок заемных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынки товаров и', 
                          title = 'Кривая совокупного спроса АД показывает при каждом уровне цен уровень выпуска, при котором ____________ (**рынок, товар, и**) активов находятся в равновесии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынки товаров и',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок товаров', 
                          title = 'На уровень конкурентоспособности экономики АЗРФ и устойчивость развития макрорегиона ощутимое воздействие оказывает также весь комплекс внешних факторов, в том числе характер структурной и региональной политики Правительства Российской Федерации, текущие темпы инфляции, валютный курс рубля, ставка рефинансирования Центрального банка, размер и стабильность тарифов на услуги естественных монополий, общий уровень либерализации экономики, конъюнктура на глобальных рынках товаров и услуг, наличие нетарифных ограничений во внешней торговле и т.д.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на внутреннем рынке', 
                          title = 'Далее рассмотрим элементы институциональных соглашений ____________ (**на, внутренний, рынок**) ТБД, обеспечившие достижение высокого уровня качества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на внутреннем рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'структура рынка и', 
                          title = 'В завершении главы была предложена ____________ (**структура, рынок, и**) описан процесс адаптации базовой модели для российского фондового рынка.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'структура рынка и',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конкуренции на рынке', 
                          title = 'В качестве ключевой гипотезы о взаимодействии и взаимосвязанности участников угольного кластера принимается предположение об их ____________ (**конкуренция, на, рынок**) конечной продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конкуренции на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынки', 
                          title = 'Глубокие кризисы 70—80-х годов в мировом хозяйстве, резкие сдвиги в структуре производства и международного разделения труда, усложнение экономических и социальных условий выхода развивающихся стран на мировые ____________ (**рынок**), огромная внешняя задолженность привели к серьезным нарушениям воспроизводства и усилению воздействия внешних факторов на их развитие.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ситуацию на рынке', 
                          title = 'Активные меры по обеспечению безработных временной занятостью в 2009-2010 гг. стали доминирующим элементом государственной политики по преодолению кризисных явлений в экономике и важным сдерживающим фактором, позволившим купировать последствия экономического спада и стабилизировать ____________ (**ситуация, на, рынок**) труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ситуацию на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынке заемных средств', 
                          title = 'Теперь можно на одном графике совместить кривые спроса и предложения на ____________ (**рынок, заемный, средства**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынке заемных средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'выйти на рынок', 
                          title = 'На основании пунктов 3) и 4) произведите позиционирование товара, с которым туристическая фирма должна ____________ (**выйти, на, рынок**) (назовите страну и разряд отеля).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выйти на рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировом рынке', 
                          title = 'При не увеличивающейся потребности в коксующихся углях со стороны металлургии и при отсутствии роста угольной генерации в энергетике, а также при мизерном использовании угля в углехимии (менее 1% от общего потребления) приросты производства в отрасли получили экспортную направленность. Этому благоприятствовал взлет цен угля ____________ (**на, мировой, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировом рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на финансовом рынке', 
                          title = 'Такая ситуация сохранялась и в 2006-2007 гг., когда стоимость кредитов банков снижалась, и снижалась значительно, и после, когда кризис ликвидности ____________ (**на, финансовый, рынок**) во второй половине 2007 г. стал предпосылкой повышения стоимости кредитов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на финансовом рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияние на рынок', 
                          title = 'Наблюдающееся в действительности несовершенство информированности, безусловно, оказывает ____________ (**влияние, на, рынок**) и рыночную цену.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние на рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок товаров', 
                          title = 'До сих пор мы сосредоточивали внимание на рынках готовой продукции (т. е. рынках товаров и услуг), которую фирмы продают, а потребители покупают.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок факторов производства', 
                          title = 'Дело в том, что ____________ (**рынок, фактор, производство**) складывается из трех видов рынка: рынка труда, рынка земли, рынка капиталов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на рынке жилья', 
                          title = 'Однако коэффициенты корреляции между ценами ____________ (**на, рынок, жилье**) и большинством показателей экономического развития заметно выше, между ними существует устойчивая положительная связь.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на рынке жилья',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'активов', 
                          title = 'В точке Е на рисунке экономика находится в равновесии при данном уровне цен, потому что и рынок товаров, и рынок ____________ (**актив**) находятся в равновесии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'активов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок товаров и', 
                          title = 'Поэтому в краткосрочном периоде главным рынком является ____________ (**рынок, товар, и**) услуг, а не рынок труда, как в среднесрочном/долгосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок товаров и',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на мировых рынках', 
                          title = 'Для современной России это важнейшее направление государственной политики, которое обеспечит не только снижение негативного воздействия на окружающую среду, но и повышение конкурентоспособности отечественной промышленной продукции ____________ (**на, мировой, рынок**) за счет модернизации основных фондов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на мировых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок', 
                          title = 'Условие равновесия на товарном рынке не всегда соблюдается, мощные рыночные силы оказывают воздействие на производтелей, достаточно быстро приводя товарный ____________ (**рынок**) в состояние равновесия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на фондовом рынке', 
                          title = 'Особую группу ____________ (**на, фондовый, рынок**) составляют различные финансовые и кредитные институты: коммерческие и инвестиционные банки, страховые компании, инвестиционные и пенсионные фонды.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на фондовом рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на международном рынке', 
                          title = 'Учитывая достоинства свободной торговли, как может быть оправдано государственное вмешательство ____________ (**на, международный, рынок**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на международном рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок инфляционных свопов', 
                          title = 'Для такой страны, как Япония, где ____________ (**рынок, инфляционный, своп**) не столь ликвиден, оценка инфляционных ожиданий по данным более ликвидных иностранных рынков свопов представляется оправданной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок инфляционных свопов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предложение на рынке', 
                          title = 'Какой же курс доллара уравновесит спрос и ____________ (**предложение, на, рынок**) обмена валюты?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предложение на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок инфляционных свопов', 
                          title = 'В настоящей работе мы рассчитываем ежедневные индикаторы долгосрочных инфляционных ожиданий на данных финансовых рынков для восьми стран, где отсутствует ____________ (**рынок, инфляционный, своп**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок инфляционных свопов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на международные рынки', 
                          title = 'В 2006 г. были выпущены облигации (СATMEX) с покрытием 14074 млн долл. с целью передачи риска ____________ (**на, международный, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на международные рынки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок капитала', 
                          title = 'Если ____________ (**рынок, капитал**) носит конкурентный характер, ставка аренды должна быть равна стоимости использования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок капитала',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок', 
                          title = 'Кроме того, и само предприятие-монополист может проводить такую политику цен, которая делает вход на ____________ (**рынок**) малопривлекательным для потенциальных конкурентов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'новых фирм', 
                          title = 'Но выход на рынок ____________ (**новый, фирма**) вызывает сдвиг кривой предложения вправо. Так как увеличившийся объем производства отрасли не влияет на цены факторов производства, выход на рынок новых фирм не прекращается, пока не достигнута первоначальная цена.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новых фирм',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияния на рынок', 
                          title = 'Знаковым последствием антимонопольного ____________ (**влияние, на, рынок**) стало то, что конкурирующие стороны вынуждены учитывать законные интересы друг друга.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияния на рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на валютных рынках', 
                          title = 'В 1978-1979 гг. доллар США обесценивался ____________ (**на, валютный, рынок**), хотя проводилась крупная валютная интервенция.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на валютных рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесие на рынках', 
                          title = 'Жесткость цен ведет к тому, что ____________ (**равновесие, на, рынок**) устанавливается, но не на уровне полной занятости экономических ресурсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесие на рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на внешнем рынке', 
                          title = 'Недостаточный спрос на продукцию АБФК ____________ (**на, внешний, рынок**) связывается с высоким уровнем налогообложения и недостатком квалифицированной рабочей силы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на внешнем рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на финансовых рынках', 
                          title = 'Информационная асимметрия ____________ (**на, финансовый, рынок**) возникает, когда одна сторона располагает большей информацией о продукте, чем другая.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на финансовых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок совершенной конкуренции', 
                          title = 'Достаточно придать протяженность "точке", которой, по определению Г. Хотеллинга, подобен ____________ (**рынок, совершить, конкуренция**), чтобы прийти к модели монополистической конкуренции в пространстве, обладающей некоторыми чертами олигополии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок совершенной конкуренции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'и рынок капитала', 
                          title = 'При этом в финансовом рынке принято выделять денежный рынок (как рынок краткосрочных инструментов заимствования) ____________ (**и, рынок, капитал**) (как относительно долгосрочный).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'и рынок капитала',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на фондовых рынках', 
                          title = 'Были ли верными ожидания ____________ (**на, фондовый, рынок**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на фондовых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок', 
                          title = 'Другим примером может послужить Организация стран-экспортеров нефти — ОПЕК, чья деятельность оказала доминирующее влияние на ____________ (**рынок**) нефти и нефтепродуктов в 1970—2000 гг., когда ОПЕК неоднократно резко ограничивала поставки нефти на мировой рынок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конкуренция на рынке', 
                          title = 'На каких четырех главных признаках базируется совершенная ____________ (**конкуренция, на, рынок**) трудовых ресурсов ?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конкуренция на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынке товаров и', 
                          title = 'На ____________ (**рынок, товар, и**) труда и продавцы и покупатели испытывают сильное желание исказить реальную картину своих предложений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынке товаров и',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынке обмена иностранной валюты', 
                          title = 'На графике показано, что рост чистых иностранных инвестиций увеличил предложение песо на ____________ (**рынок, обмен, иностранный, валюта**) от значения S1 до S2.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынке обмена иностранной валюты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок совершенной конкуренции', 
                          title = 'Еще до появления понятия «____________ (**рынок, совершить, конкуренция**)», термин «конкуренция» широко использовался экономистами, однако в него вкладывался различный смысл, что приводило к некой путанице.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок совершенной конкуренции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесия на рынке', 
                          title = 'Вычислите параметры ____________ (**равновесие, на, рынок**) данного товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесия на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок', 
                          title = 'ТНК — это крупные международные корпорации, оказывающие существенное влияние на мировой ____________ (**рынок**) товаров и факторов их производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на международных рынках', 
                          title = 'Сегодня практически в каждом субъекте Федерации СФО имеется от одного до нескольких проектов, реализация которых не только обеспечивает конкурентоспособность регионов ____________ (**на, международный, рынок**) труда, товаров и услуг, но и способствует технологической, экономической и демографической безопасности страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на международных рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на международные рынки', 
                          title = 'Эффективное развитие инновационных систем национального и регионального уровней для подготовки кадров и реализации высокотехнологичных инновационных проектов становится конкурентным преимуществом России, позволяющим выйти ____________ (**на, международный, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на международные рынки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на фондовом рынке', 
                          title = 'Кроме того, ____________ (**на, фондовый, рынок**) неоднократно наблюдался неоправданно высокий спрос на необеспеченные облигации, который всегда заканчивался падением рынка при ухудшении экономической ситуации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на фондовом рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на внешний рынок', 
                          title = 'Из всех сценариев развития Дальнего Востока единственно возможный и реальный - это ориентация ____________ (**на, внешний, рынок**) стран АТР.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на внешний рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок', 
                          title = 'Монополия может существовать лишь постольку, поскольку вход на ____________ (**рынок**) представляется другим предприятиям невыгодным или невозможным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на фондовых рынках', 
                          title = 'В задаче мы будем использовать данные о кривой доходности, для того чтобы оценить, действительно ли ____________ (**на, фондовый, рынок**) ожидали, что Волкер сможет снизить темпы инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на фондовых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынке совершенной конкуренции', 
                          title = 'Вход новых фирм снижает прибыли до нуля как на ____________ (**рынок, совершить, конкуренция**), так и на рынке монополистической конкуренции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынке совершенной конкуренции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на валютных рынках', 
                          title = 'Сегодня масштабы сделок ____________ (**на, валютный, рынок**), международных фондовых рынках и рынках ссудного капитала многократно превышают объемы международной торговли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на валютных рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конкуренция на рынке', 
                          title = 'Чистая монополия, олигополия и монополистическая ____________ (**конкуренция, на, рынок**) продукции означают, что кривая спроса на продукцию фирмы плавно понижается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конкуренция на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на внешних рынках', 
                          title = 'Третья группа авторов исследует ценовую конкурентоспособность продукции тех или иных отраслей экономики КНР ____________ (**на, внешний, рынок**), рассматривая в числе прочих факторов динамику текущего курса юаня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на внешних рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынка товаров и', 
                          title = 'Изменения на денежном рынке прямо связаны с состоянием ____________ (**рынок, товар, и**) услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынка товаров и',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынке обмена иностранной валюты', 
                          title = 'Еще раз напомним, что наша модель отражает состояния спроса и предложения на двух рынках — рынке заемных средств и ____________ (**рынок, обмен, иностранный, валюта**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынке обмена иностранной валюты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесие на рынках', 
                          title = 'Равновесный исход предполагает, таким образом, максимизацию полезности каждого потребителя, максимизацию прибыли каждого производителя и ____________ (**равновесие, на, рынок**) всех благ и факторов производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесие на рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на финансовые рынки', 
                          title = 'Рынки, указывает, что посредники часто направляют финансовые потоки ____________ (**на, финансовый, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на финансовые рынки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на внешние рынки', 
                          title = 'В 2009 г. в регионах Сибири произошло сокращение величины почти всех индексов, кроме индексов, отражающих инновационную инфраструктуру и выход ____________ (**на, внешний, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на внешние рынки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок товаров', 
                          title = 'В этой связи ряд сторонников неоклассического направления (П. Кругман и др.), несмотря на различие в подходах, признают основную предпосылку Р. Пребиша и Г. Зингера о том, что фундаментальную долговременную асимметрию между двумя глобальными подсистемами нелегко преодолеть с помощью либерализации международных рынков товаров и капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынке факторов производства', 
                          title = 'Домашние хозяйства продают труд, землю и капитал фирмам на ____________ (**рынок, фактор, производство**), которые используют их для производства товаров и услуг, которые, в свою очередь, приобретаются домашними хозяйствами на соответствующих рынках.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынке факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок факторов производства', 
                          title = 'Основным методом распределения дохода при рыночной экономике является ____________ (**рынок, фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на внешнем рынке', 
                          title = 'Сохранение такого дисбаланса значительно сокращает возможности ценовой конкуренции ____________ (**на, внешний, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на внешнем рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на международных рынках', 
                          title = 'В течение перестроечных лет роль России ____________ (**на, международный, рынок**) круглого леса динамично менялась и была весьма значительной (особенно после 1998 г.), при этом быстрый рост объемов экспорта происходил в основном за счет увеличения экспорта хвойных деревьев.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на международных рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'выйти на рынок', 
                          title = 'Для предприятий это условие означает, что фирма может без проблем ____________ (**выйти, на, рынок**), если увидит возможность получения прибыли, и уйти с него, если начнет терять деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выйти на рынок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ситуацию на рынке', 
                          title = 'Отметим, что хотя характеристики устойчивости и стабильности лидирующего положения имеют отношение к отдельным фирмам, предлагаемые коэффициенты являются интегральными, отражают ____________ (**ситуация, на, рынок**) в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ситуацию на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

