
```{r}
checkdown::check_question(answer = stringr::str_split('переход; к; рыночным; отношениям', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'переход; к; рыночным; отношениям',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('переход; к; рыночной; экономике', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'переход; к; рыночной; экономике',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('в; условиях; рыночной; экономики', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в; условиях; рыночной; экономики',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('рыночная; власть; крупных; корпораций', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночная; власть; крупных; корпораций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('рыночная; реформа; государственных; расходов', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночная; реформа; государственных; расходов',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```
