```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Так как количество товаров и услуг, на которое предъявляется спрос при каждом данном уровне цен, увеличивает­ся, кривая ____________ (**совокупный, спрос**) сдвигается вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного выпуска', 
                          title = '#### В долгосрочном периоде меняется потенциальный уровень ____________ (**совокупный, выпуск**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного выпуска', 
                          title = '#### Естественному уровню безработицы соответствует естественный уровень ВВП, т.е. уровень ____________ (**совокупный, выпуск**) при естественном уровне занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупное предложение', 
                          title = '#### Воздействие налогов на ____________ (**совокупный, предложение**) подробно исследовал американский экономист.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупное предложение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных издержек', 
                          title = '#### Если цена ниже средних ____________ (**совокупный, издержка**), прибыль отрицательна.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### В этом разделе мы представляем четыре основные модели ____________ (**совокупный, предложение**) в порядке, соответствующем хронологии их разработки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Краткосрочная функция ____________ (**совокупный, предложение**) описывает соотношение между темпом инфляции и уровнем выпуска, когда ожидаемый уровень инфляции постоянен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Множество событий, обусловливающих сдвиг долгосрочной кривой ____________ (**совокупный, предложение**), определяют и сдвиги кратко­срочной кривой совокупного предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного продукта', 
                          title = '#### Реальный ВВП отражает объем ____________ (**совокупный, продукт**) в текущих ценах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного продукта',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Показатели ____________ (**совокупный, предложение**) отрасли и единой рыночной цены выступают основными эндогенными/расчетными переменными, посредством которых осуществляется взаимная увязка макро- и микроуровней модели.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Кривая ____________ (**совокупный, предложение**) может быть получена суммированием кривых предложения всех производителей в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного выпуска', 
                          title = '#### Последующий отклик целевых показателей (обычно это показатели реального сектора экономики – параметры инвестиций, потребления, чистого экспорта, ____________ (**совокупный, выпуск**) и иных) – это неподконтрольный регулятору этап работы трансмиссионного механизма.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных расходов', 
                          title = '#### Финансовая политика – это политика регулирования совокупного спроса, осуществляемая путем воздействия на величину ____________ (**совокупный, расход**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупное предложение', 
                          title = '#### Экономисты часто выражают ____________ (**совокупный, предложение**) в виде соотношения, получившего название кривой Филлипса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупное предложение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Со стороны ____________ (**совокупный, предложение**) структурное качество экономического роста также может оцениваться различным образом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Одна из важнейших проблем состоит в том, что кривая ____________ (**совокупный, спрос**) не является прямой линией.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный спрос', 
                          title = '#### Экономический рост может носить устойчивый характер, когда ____________ (**совокупный, спрос**) и совокупное предложение растут синхронно, либо принимать различные неустойчивые формы, если нарушается динамическое равновесие между спросом и предложением.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Какое влияние окажет изменение ____________ (**совокупный, предложение**) на уровень цен и реальный объем производства?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Какое влияние окажет изменение совокупного предложения на ____________ ____________ (**уровень, цена**) и реальный объем производства?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупном спросе', 
                          title = '#### Изменения в целях были связаны с положением государства в ____________ (**совокупный, спрос**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупном спросе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Из уравнения ____________ (**совокупный, предложение**) мы получили кривую Филлипса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Увеличение ставки процента вызывает сокращение ____________ (**совокупный, спрос**) при данном уровне дохода, потому что рост ставки процента сокращает инвестиционные расходы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Мы будем называть увеличение ____________ (**совокупный, предложение**) сдвигом кривой «вправо».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Сокращение денежной массы приведет к сдвигу кривой ____________ (**совокупный, спрос**) влево и процессу дефляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Кривая ____________ (**совокупный, спрос**) показывает взаимосвязь между величиной совокупного спроса на товары и уровнем цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных издержек', 
                          title = '#### Прибыль равна разности валового дохода и ____________ (**совокупный, издержка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Если цены на товары гибкие, а цены на ресурсы жесткие, кривая краткосрочного совокупного предложения имеет положительный наклон, и увеличение ____________ (**совокупный, спрос**) приводит к росту величины равновесного выпуска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Равновесие в долгосрочном периоде достигается в точке пересечения кривой совокупного спроса с долгосрочной кривой ____________ (**совокупный, предложение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Уменьшение предложения ресурсов приведет к росту цен на них и смещению кривой ____________ (**совокупный, предложение**) влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного выпуска', 
                          title = '#### Валовой внутренний продукт (ВВП) (gross domestic product (GDP)) — измеритель ____________ (**совокупный, выпуск**) в системе национальных счетов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Смещение кривой указывает на увеличение ____________ (**совокупный, предложение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Величина ____________ (**совокупный, предложение**) в долгосрочном периоде абсолютно неэластична к уровню цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных расходов', 
                          title = '#### Если частный сектор сократит общий объем своей задолженности всего лишь на 5% за год, то это приведет к сокращению ____________ (**совокупный, расход**) на 2,7 трлн долл.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Импульсом к изменению ____________ (**совокупный, спрос**) может послужить осуществляемая правительством денежная экспансия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный выпуск', 
                          title = '#### При увеличении количества труда ____________ (**совокупный, выпуск**) увеличивается, однако при неизменной величине запаса капитала и уровне технологии с каждой дополнительной единицей труда прирост совокупного выпуска уменьшается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный выпуск',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного выпуска', 
                          title = '#### Эта модель была предложена американским экономистом Робертом Лукасом, который объяснил возможность отклонения величины ____________ (**совокупный, выпуск**) в краткосрочном периоде от своего потенциального уровня тем, что ошибаются не работники, а фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного выпуска', 
                          title = '#### Высокий уровень ____________ (**совокупный, выпуск**) или дохода соответствует высокому совокупному спросу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупными издержками', 
                          title = '#### В этой точке достигалась наибольшая разница между совокупным доходом и ____________ (**совокупный, издержка**), т. е. прибыль была максимальной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупными издержками',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный спрос', 
                          title = '#### Cчитается, что ____________ (**совокупный, спрос**) подвержен периодическим колебаниям вследствие изменений в факторах спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных затрат', 
                          title = '#### Это произошло за счет сокращения ____________ (**совокупный, затрата**) труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных затрат',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### В условиях стабильного совокупного предложения рост денежной массы вызовет сдвиг кривой ____________ (**совокупный, спрос**) вправо и инфляцию спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Кривая ____________ (**совокупный, спрос**) показывает комбинации уровня цен и уровня выпуска, при которых рынки товаров и рынки активов одновременно находятся в равновесии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный спрос', 
                          title = '#### Что такое ____________ (**совокупный, спрос**) и совокупное предложение?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный спрос', 
                          title = '#### Объем выпуска находится на равновесном уровне в том случае, если ____________ (**совокупный, спрос**) равен объему производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Всякий раз, когда изменение в одном из этих факторов воздействует на способность экономики производить товары и услуги, долго­срочная кривая ____________ (**совокупный, предложение**) сдвигается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупная производственная функция', 
                          title = '#### Функция может быть представлена как зависящая от двух переменных, например, ____________ (**совокупный, производственный, функция**) — это функция, отражающая зависимость совокупного выпуска от имеющихся в экономике запаса капитала и запаса труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупная производственная функция',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Такое расположение кривой совокупного предложения означает, что сдвиги кривой ____________ (**совокупный, спрос**) влияют только на уровень цен, но не воздействуют на величину совокупного дохода и объема производства товаров и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный спрос', 
                          title = '#### Совокупное предложение начинает сокращаться, несмотря на то, что ____________ (**совокупный, спрос**) остается на прежнем уровне, а порой и растет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Напротив, уменьшение основного капитала ведет к снижению производитель­ ности, сокращению объема предлагаемых товаров и услуг и сдвигу долгосрочной кривой ____________ (**совокупный, предложение**) влево. Мы обсуждали, что долгосрочный экономический рост детерминируют множество факторов, включая полити­ ку в отношении сбережений, инвестиций, образования, технологии, междуна­',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Никакое повышение уровня цен на этом вертикальном отрезке кривой ____________ (**совокупный, предложение**) не приведет к увеличению реального объема производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Последствия увеличения совокупного спроса зависят от того, на каком отрезке кривой ____________ (**совокупный, предложение**) оно происходит.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### В макроэкономической теории все линии на графике традиционно называются кривыми (curves), например, кривая долгосрочного ____________ (**совокупный, предложение**) (отображаемая вертикальной линией) или кривая совокупных расходов (отображаемая линией, имеющей положительный наклон).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупные расходы', 
                          title = '#### Более высокие ставки процента в свою очередь сократили бы ____________ (**совокупный, расход**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупном доходе', 
                          title = '#### Для оценки уровня самостоятельности бюджетов было проанализировано распределение доли полученных доходов в ____________ (**совокупный, доход**) местных бюджетов области.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупном доходе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменение', 
                          title = '#### Экономисты классической школы придерживаются мнения об отсутствии существенного воздействия шоков совокупного спроса на ____________ (**изменение**) объема производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### В краткосрочном смысле кривая ____________ (**совокупный, предложение**) будет иметь положительный наклон.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных расходов', 
                          title = '#### Потребительские расходы — это расходы домохозяйств на покупку товаров и услуг. В развитых странах они составляют примерно 2/3 ____________ (**совокупный, расход**) и являются основным компонентом совокупных расходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Из этих двух уравнений можно получить уравнение кривой ____________ (**совокупный, спрос**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Кривая ____________ (**совокупный, предложение**) принимает вид вертикальной прямой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный доход', 
                          title = '#### Статистика позволяет измерить ____________ (**совокупный, доход**) в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный доход',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных расходов', 
                          title = '#### Политика регулирования валютного курса национальной денежной единицы воздействует на экспорт и импорт, что влияет на величину ____________ (**совокупный, расход**) и поэтому на величину совокупного выпуска внутри страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Предположим, что изменения факторов предложения сдвигают кривую долгосрочного ____________ (**совокупный, предложение**) вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупные расходы', 
                          title = '#### та финансовой пирамиды. В конце концов, единственная категория лиц с кредитной историей, худшей, чем у жертв последнего пузыря, находится в местах заключения. Кроме того, задолженность частного сектора достигла таких размеров, которые оставляют мало надежд на действенность традиционных мер налоговой и денежно-кредитной политики в условиях экономического кризиса, вызванного тенденцией к сокращению этой задолженности. Для количественного анализа этого феномена необходимо рассмотреть факторы совокупного спроса с монетарной точки зрения, с которой спрос равняется номинальному ВВП плюс прирост долга1. Когда объем накопленной задолженности сравнительно мал по отношению к номинальному ВВП, вклад изменения задолженности в совокупный спрос можно не учитывать, однако по мере роста отношения задолженности к ВВП доля совокупных расходов, обеспечиваемых кредитованием, может стать весьма значительной. С учетом волатильности изменений уровня задолженности по отношению к ВВП можно предположить, что изменения уровня задолженности (особенно задолженности частного сектора) могут стать доминирующим фактором экономической активности в целом. Это проявляется в обратной корреляции между вкладом изменения объема задолженности в изменение совокупных расходов2 и уровня безработицы (рис. 9), и простом коэффициенте корреляции (рис. 10). Значение корреляции за весь рассматриваемый период незначительно и немного больше ноля. Однако с течением времени, по мере того как вклад задолженности в ____________ (**совокупный, расход**) возрастает с 4% почти до 20%, корреляция принимает большие отрицательные значения. Такая же связь прослеживается и в данных по США (рис. 11, 12), где рост частной задолженности на пике ее накопления давал более 25% совокупного спроса и где уже отмеченно сокращение задолженности, равно как и рост безработицы. Причинная связь между этими двумя показателями составляет суть влияния сокращения задолженности на экономику в целом. В случае США, на пике накопления задолженности частным сектором, ее изменение за год дало 4,7 трлн долл. США из 14 трлн общего объема ВВП. Таким образом, непосредственным эффектом прекращения роста задолженности частного сектора становится 25-процентный спад в уровне совокупных расходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Определите уравнение кривой ____________ (**совокупный, спрос**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный спрос', 
                          title = '#### ____________ (**совокупный, спрос**) нестабилен и иногда приводит к спаду, а иногда — к вызванной спросом инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного выпуска', 
                          title = '#### Отклонения фактического ____________ (**совокупный, выпуск**) от потенциального могут происходить, только если фактический уровень цен  отличается от ожидаемого уровня цен, а это возможно лишь в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Кривая ____________ (**совокупный, предложение**) имеет одинаковый вид.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Анализ краткосрочной кривой ____________ (**совокупный, предложение**) позволяет получить представление об объеме предложения товаров и услуг в краткосрочном периоде при каждом данном уровне цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного выпуска', 
                          title = '#### Основными показателями ____________ (**совокупный, выпуск**) и совокупного дохода являются: валовой внутренний продукт (ВВП); валовой национальный продукт (ВНП); чистый внутренний продукт (ЧВП); чистый национальный продукт (ЧНП).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного выпуска',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Рост ____________ (**совокупный, спрос**) ведет к избыточному спросу на товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный спрос', 
                          title = '#### Можно скорректировать сам подход, т.е. рассмотреть условия, при ко­торых ____________ (**совокупный, спрос**) будет функцией не только от среднего, но и от дисперсии доходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупные расходы', 
                          title = '#### и прочие товары, инвестирует в накопление капитала здоровья и прочего капита- ла. Домохозяйства решают две проблемы оптимизации. Во-первых, они миними- зируют ____________ (**совокупный, расход**) и решают, сколько потребить товаров для здоровья и прочих товаров. Во-вторых, они максимизируют функцию полезности при ус- ловии соблюдения бюджетных ограничений, согласно которым все доходы в опре-',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Увеличение чистого экспорта также сдвигает кривую ____________ (**совокупный, спрос**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Именно дополненную ожиданиями функцию ____________ (**совокупный, предложение**) мы используем для изучения характера изменений объема выпуска и инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупные расходы', 
                          title = '#### значенное как С., сокращается на 15 млрд дол. при каждом уровне ВВП. Сравнивая величину реального продукта и ____________ (**совокупный, расход**) в столбцах (1) и (9), мы видим, что совокупные объемы производства и потребления равны только при уровне ВВП в',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупные расходы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Увеличение предложения денег приводит к сдвигу кривой ____________ (**совокупный, спрос**) вправо, а уменьшение предложения денег сдвигает кривую совокупного спроса влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Благоприятный шок предложения или увеличение совокупных запасов капитала сдвигает кривую ____________ (**совокупный, спрос**) на труд вверх и вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных расходов', 
                          title = '#### Снижение уровня цен смещает график ____________ (**совокупный, расход**) вверх и увеличивает реальный ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Для количественного анализа этого феномена необходимо рассмотреть факторы ____________ (**совокупный, спрос**) с монетарной точки зрения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Настроения фирм могут привести к увеличению инвестиционных расходов, а значит, и сдвигу кривой ____________ (**совокупный, спрос**) вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Инфляционные ожидания — один из факторов, определяющих положение краткосрочной кривой ____________ (**совокупный, предложение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного предложения', 
                          title = '#### Каждая точка на кривой краткосрочного ____________ (**совокупный, предложение**) показывает различные парные сочетания величины совокупного выпуска и уровня цен, при которых прибыль фирм максимальна.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Правительство может смягчать циклические колебания, вызванные резкими изменениями ____________ (**совокупный, спрос**) или совокупного предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных издержек', 
                          title = '#### Кривая предельных издержек пересекается с кривыми средних переменных и средних ____________ (**совокупный, издержка**) в точках их минимумов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производство', 
                          title = '#### Предположим, что совокупные расходы на ____________ (**производство**) общественного товара составляют 900 долларов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производство',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупных расходов', 
                          title = '#### Когда один из этих компонентов изменяется, смещается и график ____________ (**совокупный, расход**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупных расходов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного объема', 
                          title = '#### Кривая совокупного предложения увязывает величину предлагаемого ____________ (**совокупный, объем**) производства с уровнем цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного объема',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

