```{r}
checkdown::check_question(answer = 'социальной сфере', 
                          title = '#### Новые законы способствуют расширению ответственности государства в ____________ (**социальный, сфера**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной сфере',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального', 
                          title = '#### После выхода на пенсию фонд ____________ (**социальный**) страхования выплачивает индивиду ежегодную пенсию в размере 60% зарплаты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных проблем', 
                          title = '#### Развитие производства, рост производительности общественного труда в современных условиях невозможны без решения ____________ (**социальный, проблема**) общества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных проблем',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального', 
                          title = '#### Много работ исследователя посвящены экономическому анализу семьи – ____________ (**социальный**) института который еще недавно практически игнорировался экономистами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальные нужды', 
                          title = '#### Расходы на ____________ (**социальный, нужда**) являются первыми по величине расходами консолидированного бюджета Российской Федерации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальные нужды',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'обеспечения', 
                          title = '#### Члены из неполных семей живут за счет программ социального ____________ (**обеспечение**) и зачастую за счет наркотиков и преступлений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'обеспечения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальное страхование', 
                          title = '#### С 1 января 2010 г. были введены страховые взносы на обязательное ____________ (**социальный, страхование**) на случай временной нетрудоспособности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальное страхование',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных сетей', 
                          title = '#### Посты и комментарии пользователей ____________ (**социальный, сеть**) могут стать основой экономических индикаторов, сопоставимых с традиционными индексами потребительской уверенности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных сетей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной сферы', 
                          title = '#### Регионы и муниципалитеты не имеют достаточных ресурсов для развития экономической и ____________ (**социальный, сфера**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной сферы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных', 
                          title = '#### На фоне демографических изменений предпринимательство людей старших возрастов должно рассматриваться как драйвер ____________ (**социальный**) инноваций и фактор повышения благосостояния населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальная', 
                          title = '#### Нужна активная ____________ (**социальный**) политика государства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной поддержки', 
                          title = '#### Требуются комплексные изменения архитектуры ____________ (**социальный, поддержка**) пожилых граждан.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной поддержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных', 
                          title = '#### Машинное обучение и данные ____________ (**социальный**) сетей – прекрасный источник идей для исследователя.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального доверия', 
                          title = '#### Население скандинавских стран в целом демонстрирует высокий уровень ____________ (**социальный, доверие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального доверия',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных', 
                          title = '#### В интересы акционеров компании может входить решение ____________ (**социальный**) проблем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальному обеспечению', 
                          title = '#### д) выплата жалования чиновнику. 651. Выплата пособия по ____________ (**социальный, обеспечение**) считается частью: а) государственных закупок;',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальному обеспечению',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных услуг', 
                          title = '#### Экономический рост должен осуществляться без снижения качества ____________ (**социальный, услуга**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных услуг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального', 
                          title = '#### Состояние системы ____________ (**социальный**) обеспечения влияет на продолжительность жизни и смертность.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной ответственности', 
                          title = '#### Судоходной отрасли необходимы более четкие меры корпоративной ____________ (**социальный, ответственность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной ответственности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальный прогресс', 
                          title = '#### Все страны обязаны инвестировать в ____________ (**социальный, прогресс**), чтобы создать фундамент для экономического роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальный прогресс',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных инноваций', 
                          title = '#### Были построены модели развития ____________ (**социальный, инновация**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных инноваций',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной ответственности', 
                          title = '#### Компании, которые уделяли больше внимания корпоративной ____________ (**социальный, ответственность**) в целом, лучше прошли и глобальный финансовый кризис.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной ответственности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального', 
                          title = '#### К 2018 г. доходы системы ____________ (**социальный**) страхования будут меньше, чем ее выплаты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального страхования', 
                          title = '#### Большинство людей выходит на пенсию с накоплениями, не превышающим пенсию фонда ____________ (**социальный, страхование**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального страхования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных инноваций', 
                          title = '#### Готовность внедрить цифровые технологии зависит от множества факторов: качества управления, навыков рабочей силы, ____________ (**социальный, инновация**) как в бизнесе, так и в государственном управлении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных инноваций',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной инфраструктуры', 
                          title = '#### Городская архитектура и планирование могут повлиять на повышение экономической связанности граждан. Имеющиеся примеры переустройства ____________ (**социальный, инфраструктура**) включают в себя публичные библиотеки, детсады, городские парки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной инфраструктуры',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального страхования', 
                          title = '#### Меры поддержки, которые использовали государства на фоне коронавируса, могут повлиять на будущие программы ____________ (**социальный, страхование**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального страхования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной напряженности', 
                          title = '#### Закономерно, что нарастание ____________ (**социальный, напряженность**) и социальной тревожности проецируется на оценку деятельности власти.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной напряженности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального', 
                          title = '#### показатели ____________ (**социальный**) развития нередко используются для описания актуальных социальных проблем, которые представляют особый интерес.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной напряженности', 
                          title = '#### Отсутствие массовых увольнений - результат давления со стороны региональных или местных властей, опасающихся роста ____________ (**социальный, напряженность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной напряженности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальный капитал', 
                          title = '#### ____________ (**социальный, капитал**) сотрудников представляет для компании ценный ресурс, который конвертируется в рост ее рыночной стоимости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальный капитал',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной защиты', 
                          title = '#### Достижение целей демографической политики во многом зависит от успешного решения широкого круга задач социально-экономического развития, включая повышение благосостояния населения, снижение уровня бедности, создание эффективной социальной инфраструктуры (здравоохранения, образования, ____________ (**социальный, защита**) населения), гибкого рынка труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной защиты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальную напряженность', 
                          title = '#### Платформы социальных сетей нередко обвиняют в том, что они усиливают ____________ (**социальный, напряженность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальную напряженность',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной сфере', 
                          title = '#### Cитуация обостряется существенной неоднородностью развития страны как в экономической, так и в ____________ (**социальный, сфера**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной сфере',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ответственности', 
                          title = '#### В последние несколько лет среди инвесторов резко возрос интерес к теме социальной ____________ (**ответственность**) бизнеса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ответственности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных институтов', 
                          title = '#### Исследователи обращали внимание на то, что коррупция компенсирует недостатки плохо работающих государственных и ____________ (**социальный, институт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных институтов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальному страхованию', 
                          title = '#### Правительство может изменить законы, определяющие порядок и размеры выплат по ____________ (**социальный, страхование**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальному страхованию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной ответственности', 
                          title = '#### Наиболее острые дискуссии касаются условий формирования ____________ (**социальный, ответственность**) бизнеса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной ответственности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной', 
                          title = '#### Пандемия показала недофинансированность существенных сегментов здравоохранения и ____________ (**социальный**) инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальное обеспечение', 
                          title = '#### Дана заработная плата за вычетом взносов на ____________ (**социальный, обеспечение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальное обеспечение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной напряженности', 
                          title = '#### Ухудшение макроэкономических условий нередко приводит к ____________ (**социальный, напряженность**) и конфликтам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной напряженности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной защиты', 
                          title = '#### Существуют также региональные системы ____________ (**социальный, защита**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной защиты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальную политику', 
                          title = '#### Доля расходов на ____________ (**социальный, политика**) в общем объеме расходов федерального бюджета будет расти.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальную политику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'поддержки', 
                          title = '#### меры социальной ____________ (**поддержка**) были направлены на замещение потерянного дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'поддержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных сетей', 
                          title = '#### Сегодня о решениях центрального банка можно узнать из ____________ (**социальный, сеть**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных сетей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальное обеспечение', 
                          title = '#### Правительства штатов тратят средства в основном на ____________ (**социальный, обеспечение**) и образование.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальное обеспечение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального развития', 
                          title = '#### В докладе исследовательской группы ООН были представлены дополнительные статистические показатели экономического и ____________ (**социальный, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных', 
                          title = '#### Необходимость развития социального предпринимательства обусловлена потребностью в новых ____________ (**социальный**) услугах и сервисах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального доверия', 
                          title = '#### Рост экономики после ее долгого коллапса не привел к восстановлению ____________ (**социальный, доверие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального доверия',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальным услугам', 
                          title = '#### Люди могут перехать в другой город, сохранив доступ к рабочим местам и к ____________ (**социальный, услуга**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальным услугам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальные нужды', 
                          title = '#### Различные убеждения по поводу того, насколько большим должен быть вклад бизнеса в общество, могут влиять на отчисления той или иной компании на ____________ (**социальный, нужда**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальные нужды',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального страхования', 
                          title = '#### Люди вынуждены сберегать деньги из-за системы ____________ (**социальный, страхование**) и других отчислений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального страхования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной инфраструктуры', 
                          title = '#### В статье проанализировано влияние уровня развития ____________ (**социальный, инфраструктура**) при прогнозировании демографических процессов в регионах Российской Федерации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной инфраструктуры',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной инфраструктуры', 
                          title = '#### Международные финансовые организации выдают инвестиционные кредиты на развитие ____________ (**социальный, инфраструктура**) – транспорта, электроэнергетики, включая повышение качества медицинских и образовательных услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной инфраструктуры',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных инноваций', 
                          title = '#### Формирование и развитие ____________ (**социальный, инновация**) является одним из ключевых факторов эволюции и трансформации социально-экономических систем в долгосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных инноваций',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных инноваций', 
                          title = '#### Наименьшее количество ____________ (**социальный, инновация**) в представленной выборке относится к муниципальному уровню.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных инноваций',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной', 
                          title = '#### Самое сложное в осуществлении ____________ (**социальный**) политики государства заключается в нахождении приемлемой «социальной цены», или платы, за более равномерное распределение доходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальное развитие', 
                          title = '#### После железных дорог второй по значимости воздействия на экономическое и ____________ (**социальный, развитие**) сибирских регионов является автодорожная инфраструктура.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальное развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальном', 
                          title = '#### Больше женщин работает в медицине, в ____________ (**социальный**) обслуживании населения, образовании, общественном транспорте, торговле продуктами питания.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальном',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального обеспечения', 
                          title = '#### Данные о занятости были взяты из статистики о числе работников, зарегистрированных в системе ____________ (**социальный, обеспечение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального обеспечения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального', 
                          title = '#### В Соединенных Штатах система ____________ (**социальный**) обеспечения собирает вклады от работников и фирм и распределяет их пенсионерам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальный капитал', 
                          title = '#### Мероприятия для нетворкинга позволяют профессионалам инвестировать в свой ____________ (**социальный, капитал**), укреплять доверие и обмениваться информацией.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальный капитал',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных институтов', 
                          title = '#### Исследовательская группа изучает влияние ____________ (**социальный, институт**) на заработки и мобильность работников.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных институтов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального страхования', 
                          title = '#### Нужно учитывать налоговые отчисления в фонд ____________ (**социальный, страхование**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального страхования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных инноваций', 
                          title = '#### Важным аспектом ____________ (**социальный, инновация**) является микроуровень, формирующий шаблоны поведений экономических агентов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных инноваций',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных', 
                          title = '#### Большинство ____________ (**социальный**) инноваций предназначены для повышения адаптивности институтов в условиях быстрой смены потребностей населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной поддержки', 
                          title = '#### Социальную напряженность помогают снизить меры ____________ (**социальный, поддержка**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной поддержки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной поддержке', 
                          title = '#### Нелегальный бизнес не платит налоги и не участвует в ____________ (**социальный, поддержка**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной поддержке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальному', 
                          title = '#### Cемьи живут на фиксированные пособия по ____________ (**социальный**) обеспечению.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальному',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальные', 
                          title = '#### Здесь ____________ (**социальный**) инновации видятся как неотъемлемая часть социально-экономической политики, которая позволила бы находить более эффективные модели функционирования государства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной защиты', 
                          title = '#### В отношении ____________ (**социальный, защита**) безработных государство использует комплекс мер налоговой, денежно-кредитной политики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной защиты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальное развитие', 
                          title = '#### Обучение – только одна из ценностей университетского образования, другие включают в себя живое общение и ____________ (**социальный, развитие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальное развитие',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной', 
                          title = '#### Возможности ____________ (**социальный**) политики адаптироваться к системным шокам часто ограничены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальных проблем', 
                          title = '#### Активно финансируются исследования и инновации, направленные на решение ____________ (**социальный, проблема**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальных проблем',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сетей', 
                          title = '#### В будущем социальным сетям не нужно будет полагаться на централизованные платформы, которые устанавливают правила для своих экосистем и обеспечивают взаимодействие между поставщиками (рекламодателями) и потребителями (пользователями социальных ____________ (**сеть**)).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сетей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальная политика', 
                          title = '#### В целом ____________ (**социальный, политика**) государства в рыночной экономике призвана способствовать социальной стабильности и смягчению социальной напряженности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальная политика',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной политики', 
                          title = '#### Равенство возможностей для детей – центральный вопрос ____________ (**социальный, политика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной политики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной динамики', 
                          title = '#### Описаны основные характеристики ____________ (**социальный, динамика**) наемных работников в России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной динамики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальное', 
                          title = '#### ____________ (**социальный**) обслуживание — это государственная поддержка отдельных категорий граждан.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальное',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальную сферу', 
                          title = '#### Города, испытавшие вызванные вирусом бедствия и политическую нестабильность, более решительно стремились к инвестициям в ____________ (**социальный, сфера**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальную сферу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социального прогресса', 
                          title = '#### Одним из ключевых показателей ____________ (**социальный, прогресс**) является уровень жизни населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социального прогресса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальная', 
                          title = '#### Нобелевский лауреат и экономист Милтон Фридман утверждал, что ____________ (**социальный**) ответственность бизнеса – наращивать прибыль.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальная',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной защиты', 
                          title = '#### Фонд обязательного социального страхования играет большую роль в системе ____________ (**социальный, защита**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной защиты',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'социальной напряженности', 
                          title = '#### При ухудшении макроэкономических условий крупный бизнес будет отказываться от неформальных социальных обязательств, сокращая издержки, что приведет к повышению уровня ____________ (**социальный, напряженность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'социальной напряженности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

