```{r}
checkdown::check_question(answer = 'рост спроса', 
                          title = '#### Импортеры скорее склонны повышать цены в ответ на ____________ (**рост, спрос**), чем снижать цены в ответ на его падение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Когда уменьшение цены одного товара ведет к повышению ____________ (**спрос**) на другой товар, такие товары называют взаимодополняющими.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'линия спроса', 
                          title = '#### Повышение цен только на красные автомобили вызывает переключение спроса покупателей с красных автомобилей на автомобили другого цвета. Поэтому ____________ (**линия, спрос**) на красные автомобили имеет довольно пологий ха­рактер.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'линия спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Выведите уравнение кривой ____________ (**совокупный, спрос**) и постройте ее график.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низкий спрос', 
                          title = '#### Более высокая ставка процента предполагает более ____________ (**низкий, спрос**) на деньги центрального банка по двум причинам: 1) спрос на наличную валюту падает; 2) спрос на чековые депозиты также падает, вызывая снижение спроса банков на резервы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низкий спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'функций спроса', 
                          title = '#### Существуют и другие предста­вления о характере ____________ (**функция, спрос**) и его эластичности, которые служат психологической основой для других стратегий ценообра­зования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функций спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на инвестиции', 
                          title = '#### Снижение расходов на электроэнергию приведет к сдвигу кривой ____________ (**спрос, на, инвестиция**) вправо. Рост затрат, напротив, будет смещать кривую влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на инвестиции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величину спроса', 
                          title = '#### При этой более высокой заработной плате фирмы захотят нанять меньше работников и сократят ____________ (**величина, спрос**) на труд до LD2 (точка В), а домохозяйства захотят предложить больше труда, и величина предложения труда возрастет до L2S (точка С).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величину спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на нефть', 
                          title = '#### Расширение использования альтернативных источников энергии (таких, как уголь, солнечная и атомная энергия) сократили ____________ (**спрос, на, нефть**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на нефть',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на нефть', 
                          title = '#### Растущий ____________ (**спрос, на, нефть**) столкнется с ограниченным предложением.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на нефть',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стимулирует спрос', 
                          title = '#### Потребители ощущают возросшее богатство, что ____________ (**стимулировать, спрос**) на потребительские товары, а сниже­ние процентных ставок стимулирует спрос на инвестиционные товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стимулирует спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на благо', 
                          title = '#### Эффект присоединения к большинству — однонаправленное изменение объема ____________ (**спрос, на, благо**) одним потребителем в ответ на изменение объема спроса других потребителей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на благо',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на продукцию', 
                          title = '#### Импортозамещение порождает дополнительный ____________ (**спрос, на, продукция**) производственного назначения, полуфабрикаты, вспомогательные материалы. При ограниченности капиталов это ведет к увеличению импорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на продукцию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Если абсолютные наклоны линий ____________ (**спрос**) и предложения одинаковы, всякое первоначальное отклонение ведет к колебаниям цен и объемов одинаковой амплитуды вокруг равновесного уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупный спрос', 
                          title = '#### Рост государственных закупок увеличивает ____________ (**совокупный, спрос**) (сдвиг кривой АД вправо), а их снижение — сокращает.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем спроса', 
                          title = '#### Равновесие достигается при такой процентной ставке, при которой ____________ (**объем, спрос**) равен объему предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Функция ____________ (**спрос**) на деньги (уравнение 7.3) определяет важнейшие макроэкономические факторы, оказывающие воздействие на величину спроса на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривая спроса', 
                          title = '#### Рисунок иллюстрирует эффект сноба. Кривая D2 — это ____________ (**кривать, спрос**), которая возникает, когда потребители уверены, что только 2000 человек владеют некоторым товаром. Когда они понимают, что этим товаром владеют 4000 человек, он становится менее эксклюзивным, и поэтому его ценность для сноба уменьшается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на импорт', 
                          title = '#### При данном обменном курсе импортные пошлины снижают внутренний ____________ (**спрос, на, импорт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на импорт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Функциональная зависимость между величиной заработной платы и объемом ____________ (**спрос**) на труд выражается в кривой спроса на труд.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Снижение предложения денег сдвигает кривую ____________ (**совокупный, спрос**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос зависит от', 
                          title = '#### В реальности ____________ (**спрос, зависеть, от**) многих факторов и зависимость его величины от цены носит нелинейный характер.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос зависит от',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'чувствительность спроса', 
                          title = '#### Как мы видели там, фискальная экспансия ведет к тем более высокому уровню дохода и расходов, чем больше ____________ (**чувствительность, спрос**) на деньги к ставке процента, чем меньше чувствительность совокупного спроса к ставке процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'чувствительность спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению спроса', 
                          title = '#### Высокая инфляция стимулирует перевод накоплений в наличную валюту, что ведет к ____________ (**повышение, спрос**) на нее и, как следствие, к падению курса рубля, а затем росту цен, вызывая асимметрию во взаимодействии государственного и частного секторов экономики, поскольку заставляет каждого из них функционировать по разным правилам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению спроса', 
                          title = '#### Бегство капитала из страны приводит к ____________ (**увеличение, спрос**) на иностранную валюту. Даже высокий уровень валютных резервов может оказаться неспособным удовлетворять нарастающий спрос.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стимулирует спрос', 
                          title = '#### Рост мировой экономической активности в результате глобального несырьевого шока ____________ (**стимулировать, спрос**) на сырье, что выражается в росте цен на сырьевые товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стимулирует спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на газ', 
                          title = '#### В следующем году Китай будет наращивать ____________ (**спрос, на, газ**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на газ',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величина спроса', 
                          title = '#### Деньги являются "ликвидным" активом - они удобны для совершения любых сделок. Теория предпочтения ликвидности утверждает, что ____________ (**величина, спрос**) на деньги зависит от ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величина спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Изменение уровня цен не сдвигает кривую ____________ (**совокупный, спрос**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос зависит от', 
                          title = '#### Можно ожидать, что ____________ (**спрос, зависеть, от**) цены товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос зависит от',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### О высоком уровне общего потребительского ____________ (**спрос**) на региональном рынке говорят и относительно высокие темпы роста цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'чувствительность спроса', 
                          title = '#### Поскольку кривая ГМ имеет вид вертикали только в тех случаях, когда спрос на деньги не зависит от ставки процента, ____________ (**чувствительность, спрос**) на деньги к ставке процента становится важным вопросом в определении эффективности той или иной политики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'чувствительность спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'линии спроса', 
                          title = '#### Если ____________ (**линия, спрос**) и предложения имеют нормальный (соответственно отрицательный и положительный) наклон, равнове­сие стабильно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'линии спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличивают спрос', 
                          title = '#### Если люди ожидают роста уровня цен, то они ____________ (**увеличивать, спрос**) на товары и услуги, стремясь купить их как можно больше по относительно низким ценам в настоящем (так называемая инфляционная психология).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличивают спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предъявляется спрос', 
                          title = '#### Так как увеличение объема государственных закупок приводит к увеличению совокупного объема производства товаров, на которые ____________ (**предъявлять, спрос**) при любом уровне цен, вся кривая сдвигается вверх и вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предъявляется спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'избыточном спросе', 
                          title = '#### Чтобы вернуть к равновесию рынки труда, где дефицит стал нормой, потребуется повышение зарплат даже для тех рабочих мест, где хватает рабочих рук. Это вызовет на некоторое время инфляционное давление – но при ____________ (**избыточный, спрос**) оно будет расти постоянно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'избыточном спросе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### В этой точке наблюдается избыточный ____________ (**спрос**) на деньги, что вызывает повышение процентной ставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'формирования спроса', 
                          title = '#### Однако исследование закономерностей функционирования денежного рынка, ____________ (**формирование, спрос**) на деньги и предложения денег очень важно для макроэкономического анализа.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'формирования спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Мы используем модель рационального выбора для построения кривой индивидуального потребительского ____________ (**спрос**) на товар.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### При каждом данном уровне цен домашние хозяйства и фирмы желают приобретать меньшее количество товаров и услуг, и кривая ____________ (**совокупный, спрос**) смещается влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению спроса', 
                          title = '#### Увеличение доходов государств и населения приводит к ____________ (**повышение, спрос**) на качественную окружающую среду.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рост спроса', 
                          title = '#### Таким образом, ____________ (**рост, спрос**) на землю (смещение вправо кривой спроса) ведет к повышению арендной платы и экономической ренты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на ресурс', 
                          title = '#### Более того, возросший ____________ (**спрос, на, ресурс**)ы означает более высокие цены на ресурсы в этой отрасли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на ресурс',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на товары', 
                          title = '#### Так как снижение реальной процентной ставки увеличивает спрос домашних хозяйств на потребление и спрос фирм на инвестиции, величина совокупного ____________ (**спрос, на, товар**) растет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внутреннего спроса', 
                          title = '#### Опыт Китая заключается в расширении ____________ (**внутренний, спрос**) в условиях сокращения экспорта и является для остальных стран примером успешного преодоления кризисных тенденций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутреннего спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Эластичность ____________ (**спрос**) по цене — это процентная величина изменения величины спроса, возникающего в результате изменения цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### Номинальный ____________ (**спрос**) на деньги определяет величину спроса на деньги в стоимостном выражении (долларах, иенах, евро и т. п.).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внутренний спрос', 
                          title = '#### Экономика регионов Сибири не может замкнуться на ____________ (**внутренний, спрос**) как из-за специфики продукции, так и из-за малой численности населения, а это определяет необходимость поиска внешних рынков сбыта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутренний спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Увеличение ____________ (**спрос**) на жилье, например, возникшее в результате снижения ставки процента, повышает цены на жилье и инвестиции в жилищное строительство.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению спроса', 
                          title = '#### Насильственное повышение уровня заработной платы выше равновесного приведет к росту предложения и ____________ (**снижение, спрос**) на труд представителей данных профес­сий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ростом спроса', 
                          title = '#### Бизнес собирается увеличить выпуск в связи с ____________ (**рост, спрос**) на свою продукцию. Для увеличения производства ему необходимо использовать больше производственных ресурсов: труда, капитала и пр.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ростом спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'линий спроса', 
                          title = '#### При этом стабильность равновесия будет зависеть от абсолютных наклонов ____________ (**линия, спрос**) и предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'линий спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросом и предложением', 
                          title = '#### Что же определяет стоимость денег? Оказывается, как и многое в экономике, стоимость денег определяется ____________ (**спрос, и, предложение**). Точно так же как цена на бананы определяется спросом и предложением бананов, так и спрос и предложение денег определяют их стоимость.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросом и предложением',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительского спроса', 
                          title = '#### Какова связь между объемом и структурой ____________ (**потребительский, спрос**) и экономическим ростом?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительского спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Из-за резких различий в эластичности ____________ (**спрос**) выше и ниже точки текущей цены происходит разрыв.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величине спроса', 
                          title = '#### Равновесие есть набор цен, при котором величина предложения равна ____________ (**величина, спрос**) на каждом рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величине спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величине спроса', 
                          title = '#### Рынок активов находится в равновесии, если величина предложения денег равна ____________ (**величина, спрос**) на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величине спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Независимость объема ____________ (**спрос**) на каждое благо от цены другого блага означает, что блага независимы в потреблении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительский спрос', 
                          title = '#### ____________ (**потребительский, спрос**) в ближайшее время может и не стать драйвером восстановления экономики. Доходы населения не растут, а потребительские настроения находятся на рекордно низких уровнях.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительский спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'удовлетворить спрос на', 
                          title = '#### На этом рынке обращаются деньги, которые призваны ____________ (**удовлетворить, спрос, на**) них экономических агентов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'удовлетворить спрос на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросу на товары', 
                          title = '#### Рост совокупного спроса ведет к избыточному ____________ (**спрос, на, товар**). Фирмы, которые пытаются увеличить выпуск, нанимают болыше рабочих, поднимая заработную плату и издержки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросу на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночного спроса', 
                          title = '#### В состоянии равновесия каждый из дуополистов покрывает своей продукцией треть ____________ (**рыночный, спрос**) при единой цене. Покрывая совместно две трети рыночного спроса, каждый дуополист обеспечивает максимум своей, но не отраслевой прибыли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Рост уровня цен в стране по сравнению с мировым уровнем ведет к увеличению импорта и снижению экспорта, следовательно, к снижению ____________ (**совокупный, спрос**) и сдвигу кривой совокупного спроса влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупном спросе', 
                          title = '#### При таком предположении изменения в ____________ (**совокупный, спрос**) оказывают влияние на равновесный объем ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупном спросе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величины спроса', 
                          title = '#### Для того чтобы ____________ (**величина, спрос**) имели какое-то значение, они должны относиться к определенному отрезку времени — дню, неделе, месяцу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величины спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предъявляется спрос', 
                          title = '#### Поскольку количество товаров и услуг, на которое ____________ (**предъявлять, спрос**) при каждом данном уровне цен, возрастает, происходит сдвиг кривой совокупного спроса вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предъявляется спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Вспомним, что кривая ____________ (**спрос**) отражает ценность товара для потребителей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросом на деньги', 
                          title = '#### При очень низком значении процентной ставки весь прирост предложения денег поглощается спекулятивным ____________ (**спрос, на, деньги**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросом на деньги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предъявляется спрос', 
                          title = '#### Так как количество товаров и услуг, на которое ____________ (**предъявлять, спрос**) при каждом данном уровне цен, увеличивает­ся, кривая совокупного спроса сдвигается вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предъявляется спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышение спроса', 
                          title = '#### Нет гарантий, что в результате падения цены будет наблюдаться ____________ (**повышение, спрос**) на хлеб.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышение спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросом', 
                          title = '#### Банковская система не справляется с возросшим ____________ (**спрос**) на услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросом',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Фирма, как правило, будет приспосабливаться к падению ____________ (**спрос**) на продукцию, временно увольняя некоторое число работников.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предъявляют спрос', 
                          title = '#### Показана имеющая отрицательный наклон кривая спроса на труд, которая означает, что фирмы ____________ (**предъявлять, спрос**) на тем большее количество труда, чем ниже реальная заработная плата.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предъявляют спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Равновесие стабильно, если кривая ____________ (**спрос**) пересекает кривую предложения сверху. В этом случае избыток спроса действует в сторону снижения цены, а избыток предложения, или отрицательного спроса, в сторону ее снижения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросу', 
                          title = '#### Равновесие на финансовых рынках требует того, чтобы предложение денег было равно ____________ (**спрос**) на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту спроса', 
                          title = '#### При данном предложении денег рост дохода ведет к ____________ (**рост, спрос**) на деньги и к росту ставки процента. Рост предложения денег ведет к снижению ставки процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сокращению спроса', 
                          title = '#### Повышение цены данного товара с P 3 до P 2 приведет к ____________ (**сокращение, спрос**) почти в 2 раза, тогда как ее снижение с P 3 до P 4 дает ничтожно малый его прирост. Таким образом, спрос на данный товар может оказаться весьма эластичным при повышении цены, но почти неэластичным при ее снижении (или наоборот).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сокращению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на деньги', 
                          title = '#### Именно ____________ (**спрос, на, деньги**) как ликвидный актив и средство сохранения стоимости обеспечивает обратную зависимость между ценой товара и совокупным спросом на него и таким образом достижение динамического равновесия на товарных рынках.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на деньги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'удовлетворения спроса', 
                          title = '#### В стране достаточно сахара для ____________ (**удовлетворение, спрос**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'удовлетворения спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на газ', 
                          title = '#### Страны Евросоюза окончательно утвердили решение о добровольном снижении ____________ (**спрос, на, газ**) на 15%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на газ',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем спроса', 
                          title = '#### Левая часть уравнения характеризует влияние изменения цены РX на ____________ (**объем, спрос**) на товар. Правая представляет сумму эффектов дохода и замены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### Мигранты предъявляют ____________ (**спрос**) на товары, увеличивая продажи местных предприятий, а также открывают свои предприятия, создавая новые рабочие места.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Указывая на то, что товар имеет «высокую» ценовую эластичность ____________ (**спрос**), всегда имеют в виду большую абсолютную величину эластичности, что означает высокую чувствительность спроса к изменениям цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижение спроса', 
                          title = '#### Фирмы настроены пессимистически в отношении будущего экономики, и этот пессимизм заставляет их строить меньше новых заводов. Такое ____________ (**снижение, спрос**) на инвестиционные товары вызывает сдвиг графика инвестиционной функции влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос и предложение', 
                          title = '#### Второе допущение основано на положении о гибкости цен и заработной платы. Согласно этой предпосылке цены и заработная плата корректируются, уравновешивая ____________ (**спрос, и, предложение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос и предложение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Данное изменение количества денег имеет наибольший эффект, когда кривая ____________ (**спрос**) на деньги относительно крутая, а кривая спроса на инвестиции относительно пологая.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'перекрестной эластичности спроса', 
                          title = '#### Перекрестная эластичность спроса по цене характеризует относительное изменение объема спроса на один товар при изменении цены другого. Коэффициентом ____________ (**перекрестный, эластичность, спрос**) по цене называют отношение относительного изменения спроса на товар 1 к относительному изменению цены товара 2.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'перекрестной эластичности спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Сдвиг кривой совокупного ____________ (**спрос**) вправо непосредственно связан со смещением кривой совокупных расходов вверх.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос по доходу', 
                          title = '#### ____________ (**спрос, по, доход**) будет абсолютно эластичным, если при малейшем изменении дохода величина спроса изменяется очень сильно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос по доходу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличивается спрос', 
                          title = '#### До сих пор нет единого мнения о взаимосвязи миграции и цен на недвижимость. С одной стороны, с ростом числа иммигрантов ____________ (**увеличиваться, спрос**) на недвижимость, с другой – снижается привлекательность района для коренного населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличивается спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Медленная реакция заработной платы и цен означает, что рынки долгое время могут находиться в неравновесном состоянии, когда величина ____________ (**спрос**) и предложения не совпадает.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличения спроса', 
                          title = '#### Результатом ____________ (**увеличение, спрос**) на труд стало повышение и равновесной реальной заработной платы, и равновесного уровня занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличения спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'растет спрос', 
                          title = '#### Снижается спрос на выполнение рутинных операций, которые автоматизируются, и ____________ (**расти, спрос**) на работников, выполняющих сложные аналитические и нестандартные задачи.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'растет спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на экспорт', 
                          title = '#### Международный финансовый кризис повлек за собой снижение внешнего ____________ (**спрос, на, экспорт**) из-за снижения доходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на экспорт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичность спроса', 
                          title = '#### Однако не следует забывать, что ____________ (**эластичность, спрос**) по цене у монополистического конкурента невысока, и получить сверхприбыль от расширения объема продаж затруднительно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объему спроса', 
                          title = '#### Конкурентный рынок находится в равновесии, когда объем предложения равен ____________ (**объем, спрос**), потому что в этом случае каждая фирма ведет себя наилучшим образом — она продает все, что производит, и максимизирует свою прибыль.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объему спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Комплементарные блага — взаимодополняемые блага: увеличение цены одного блага ведет к падению ____________ (**спрос**) на другое благо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величины спроса', 
                          title = '#### Рост процентной ставки по деньгам увеличивает желание людей удерживать денежные средства и поэтому приводит к росту ____________ (**величина, спрос**) на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величины спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичности спроса', 
                          title = '#### Что можно сказать об ____________ (**эластичность, спрос**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичности спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### При первоначальном уровне цен теперь существует избыточный ____________ (**спрос**) на товары. Цены растут, и таким образом реальная денежная масса уменьшается до своего первоначального уровня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Факторы, которые вызывают сдвиг кривой ____________ (**совокупный, спрос**) или совокупного предложения труда, оказывают воздействие как на равновесную ставку реальной заработной платы, так и на уровень полной занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Для анализа поведения рыночных цен можно использовать кривые рыночного ____________ (**спрос**) и предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичность спроса', 
                          title = '#### Иначе говоря, перекрестная ____________ (**эластичность, спрос**) между продуктами монополиста и любым другим товаром либо равна нулю, либо пренебрежимо мала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на импорт', 
                          title = '#### Прослеживается связь между укреплением национальной валюты и ростом ____________ (**спрос, на, импорт**): повышение реального обменного курса на 1% ведет к замещению отечественных товаров импортными на 0,77% в среднем по экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на импорт',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичностью спроса', 
                          title = '#### Для каждого блага с ____________ (**эластичность, спрос**) по доходу, меньшей единицы, должно существовать благо с > 1 для конкретного потребителя (Закон Энгеля).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичностью спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночного спроса', 
                          title = '#### На рисунке представлена кривая ____________ (**рыночный, спрос**) на труд.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Коэффициент перекрестной эластичности ____________ (**спрос**) показывает, на сколько процентов изменится объем спроса одного блага при изменении цены другого блага на один процент.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на ресурсы', 
                          title = '#### Эффект объема производства также помогает объяснить нисходящий характер кривой ____________ (**спрос, на, ресурс**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на ресурсы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночного спроса', 
                          title = '#### Эластичность ____________ (**рыночный, спрос**) при таком выпуске равна единице, а общая выручка достигает максимума, что при нулевых затратах тождественно максимуму прибыли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### Согласно функции ____________ (**спрос**)а на деньги, реальный спрос на деньги зависит от объема производства и номинальной процентной ставки по альтернативным, неденежным активам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижения спроса', 
                          title = '#### Политика получила название ‘“грабь ближнего своего”, поскольку увеличение спроса на товары отечественного производства достигается за счет ____________ (**снижение, спрос**) на зарубежные товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижения спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'линия спроса', 
                          title = '#### Если население больше курит, то ____________ (**линия, спрос**) на сигареты сдвигается вправо. Если увеличится число людей, которые ведут здоровый образ жизни, то линия спроса на сигареты сдвинется влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'линия спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'формирования спроса', 
                          title = '#### Замедление роста производительности исследоваители объясняют более медленным формированием спроса на новые специализации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'формирования спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на землю', 
                          title = '#### Изменение спроса на продукты сельского хозяйства вызывает изменение ____________ (**спрос, на, земля**) при любой данной арендной ставке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на землю',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объема спроса', 
                          title = '#### Характер же спроса меняется тогда, когда изменяются факторы, имевшие ранее постоянные величины. Графически изменение ____________ (**объем, спрос**) выражается в “движении” по кривой спроса вниз или вверх.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объема спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичности спроса', 
                          title = '#### При изменении доходов спрос на товары изменяется по-разному. В связи с этим мы говорим об ____________ (**эластичность, спрос**) в зависимости от дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичности спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению спроса', 
                          title = '#### При увеличении объема производства увеличивается объем трансакций людей, что приводит к ____________ (**увеличение, спрос**) на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'растущий спрос', 
                          title = '#### ____________ (**расти, спрос**) на социальную мобильность и равенство возможностей вызовет изменения в экономической политике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'растущий спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величины спроса', 
                          title = '#### Процент изменения ____________ (**величина, спрос**) больше процента изменения цены товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величины спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительского спроса', 
                          title = '#### Действие ограничительных мер и падение внешнего спроса приводят к снижению промежуточного и инвестиционного потребления и дополнительному снижению конечного ____________ (**потребительский, спрос**) из-за сокращения заработных плат.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительского спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Отрицательный наклон кривой совокупного ____________ (**спрос**) поэтому также не может быть объяснен эффектами, объясняющими отрицательный наклон кривых индивидуального и рыночного спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Отрицательный наклон кривой ____________ (**совокупный, спрос**) означает, что снижение общего уровня цен в экономике ведет к увеличению предъявляемого спроса на общее количество товаров и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичность спроса', 
                          title = '#### Допустим, мы обдумываем увеличение цены на товар с $8 до $10 и ожидаем, что величина спроса при этом упадет с 6 единиц до 4. Как нам рассчитать ценовую ____________ (**эластичность, спрос**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту спроса', 
                          title = '#### Допустим, что увеличение ВВП ведет к ____________ (**рост, спрос**), но в меньшей пропорции, чем 1:1.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### Повышение числа молодых семей вызвал в 80-е годы повышенный ____________ (**спрос**) на жилье и товары длительного пользования, что приводило к снижению нормы сбережений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### Как могут влиять изменения в распределении дохода между потребителями на рыночный ____________ (**спрос**) на продукт?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Изменения кредитно-денежной, бюджетно-налоговой политики и условий равновесия на рынках денег и товаров вызывают сдвиги кривой совокупного ____________ (**спрос**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на жилье', 
                          title = '#### Кредитно-денежная политика сильно влияет на инвестиции в жилищное строительство, поскольку ____________ (**спрос, на, жилье**) чувствителен к ставке процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на жилье',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на жилье', 
                          title = '#### При изменении ____________ (**спрос, на, жилье**) меняется равновесное значение цены жилья, что, в свою очередь, сказывается на инвестициях в жилищное строительство. Кривая спроса на жилье может сместиться в силу многих причин.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на жилье',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Кривая предложения денег сдвигается влево, уровень цен падает, расходы увеличиваются, кривая совокупного ____________ (**спрос**) сдвигается вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального спроса', 
                          title = '#### При значении реальной процентной ставки 3% и объеме производства 4000 величина ____________ (**реальный, спрос**) на деньги владельцев богатства составляет 1000, которая равна величине реального предложения денег центральным банком.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величине спроса', 
                          title = '#### Альтернативным способом выражения равновесия на товарном рынке является следующее условие: величина предложения товаров должна быть равна ____________ (**величина, спрос**) на товары домашних хозяйств, фирм и государства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величине спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предъявляется спрос', 
                          title = '#### Чтобы построить кривую совокупного спроса, мы рассмотрим, что произойдет с объемом производства товаров, на которые ____________ (**предъявлять, спрос**) при изменении уровня цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предъявляется спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величины спроса', 
                          title = '#### Два товара являются субститутами, если увеличение цены одного из них ведет к увеличению ____________ (**величина, спрос**) на другой товар.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величины спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'шок спроса', 
                          title = '#### ____________ (**шок, спрос**) на кредит не менее важен в объяснении макроэкономической динамики, чем спрос на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'шок спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличению спроса', 
                          title = '#### При высокой безработице правительство должно увеличивать объем закупок товаров и услуг, что приведет к ____________ (**увеличение, спрос**) на продукцию производителей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупным спросом', 
                          title = '#### Модели равновесия между ____________ (**совокупный, спрос**) и совокупным предложением также  являются основой макроэкономического анализа колебаний уровня экономической активности, занятости, инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупным спросом',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросом на деньги', 
                          title = '#### Связь между национальным продуктом и ____________ (**спрос, на, деньги**) страны играет центральную роль в количественной теории денег. Уравнение количественной теории исходит из того, что предложение денег любой страны равно спросу на деньги, который прямо пропорционален стоимости ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросом на деньги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на благо', 
                          title = '#### Когда товар является неконкурентным, общественная предельная выгода от потребления, представленная кривой спроса D, определяется вертикальным сложением отдельных кривых ____________ (**спрос, на, благо**), D 1 и D 2 . В точке эффективного уровня выпуска кривая спроса и кривая предельных издержек пересекаются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на благо',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'растет спрос', 
                          title = '#### В мире ____________ (**расти, спрос**) на альтернативу долгу, номинированному в долларах США.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'растет спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на инвестиции', 
                          title = '#### Мотивационным фактором ____________ (**спрос, на, инвестиция**) является чистая прибыль.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на инвестиции',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'формирование спроса', 
                          title = '#### И сегодня важной задачей является ____________ (**формирование, спрос**) на инновационную продукцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'формирование спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### При предположении, что функция ____________ (**спрос**) носит линейный характер, уравнение кривой спроса может быть представлено в следующем общем виде: Q D = a- b . Р',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### В последнее десятилетие благодаря расширению внутреннего ____________ (**спрос**) и росту масштабов инвестиций высокими темпами в Китае развивается промышленность.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Для анализа экономических последствий вводится шок ____________ (**спрос**) на экспорт.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличивает спрос', 
                          title = '#### Таблица показывает, что рост производительности ____________ (**увеличивать, спрос**) на труд при данной реальной заработной плате.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличивает спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'функции спроса', 
                          title = '#### Кривая общей выручки при линейной ____________ (**функция, спрос**) имеет куполо­образную форму.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функции спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению спроса', 
                          title = '#### Увеличение ставки процента с 8 до 10 % снижает максимальный объем ссуды с 95368 дол. до 79766 дол. - на 16%. Таким образом, увеличение ставки процента приводит к ____________ (**снижение, спрос**) на жилье, что, в свою очередь, снижает цены жилья и инвестиции в жилищное строительство.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на землю', 
                          title = '#### Рост ____________ (**спрос, на, земля**) (смещение вправо кривой спроса) ведет к повышению арендной платы и экономической ренты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на землю',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривая спроса', 
                          title = '#### Что произойдет, если спрос на труд данного вида увеличит­ся, т. е. если ____________ (**кривать, спрос**) на него сдвинется вверх и вправо? Такой сдвиг кривой спроса на труд допустим вследствие повышения цены на конечный товар, в производстве которого он используется.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'функции спроса', 
                          title = '#### Решение задачи находится путем решения системы двух уравнений для линейной ____________ (**функция, спрос**) .',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функции спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на землю', 
                          title = '#### Сельскохозяйственный ____________ (**спрос, на, земля**) зависит от предложения земли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на землю',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на услуги', 
                          title = '#### Профсоюзы могут содействовать росту ____________ (**спрос, на, услуга**) труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на услуги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросе на деньги', 
                          title = '#### Резкие изменения в ____________ (**спрос, на, деньги**) (нестабильная скорость обращения денег) делают таргетирование роста денежной массы неэффективной стратегией.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросе на деньги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению спроса', 
                          title = '#### При этом роботизация ведет к снижению спроса на низкоквалифицированную рабочую силу и к увеличению спроса на высококвалифицированную рабочую силу, но не к ____________ (**падение, спрос**) на работников средней квалификации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Что происходит, когда фирмы реагируют на рост ____________ (**спрос**) увеличением производства? Более высокий уровень производства ведет к более высокой занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на газ', 
                          title = '#### Рост ____________ (**спрос, на, газ**) к 2030 году составит до 10%, который во многом будет обеспечен за счет увеличения его использования в промышленности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на газ',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'общий спрос', 
                          title = '#### Условие говорит, что в равновесии общее предложение и ____________ (**общий, спрос**) на деньги должны быть равны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'общий спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объем спроса', 
                          title = '#### Точка Е является равновесной. Следовательно, в этой точке наступает равновесие на денежном рынке, когда ____________ (**объем, спрос**) на деньги равен объему денежного предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объем спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### Анализ кривой совокупного ____________ (**спрос**)а позволяет нам получить представление о коли­честве товаров и услуг, на который предъявляется спрос при каждом данном уровне цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривая спроса', 
                          title = '#### Когда доллар, выраженный в других валютах, стоит дороже, люди требуют меньше долларов, поэтому ____________ (**кривать, спрос**) имеет отрицательный наклон.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### При неизменном объеме предложения денег рост уровня цен ведет к снижению дохода. Увеличение предложения денег приводит к сдвигу кривой ____________ (**совокупный, спрос**) вправо, а уменьшение предложения денег сдвигает кривую совокупного спроса влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупного спроса', 
                          title = '#### Так как количество товаров и услуг, на которое предъявляется спрос при каждом данном уровне цен, умень­шается, кривая ____________ (**совокупный, спрос**) смещается влево.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупного спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичность спроса', 
                          title = '#### Можно сказать, что ____________ (**эластичность, спрос**) равна единице, когда небольшое снижение цены повлечет за собой пропорционально равное увеличение спроса, или, проще говоря, когда сокращение цены на 1% увеличивает продажи на 1%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичностью спроса', 
                          title = '#### Положение, что для каждого блага с ____________ (**эластичность, спрос**) по доходу меньше 1(0 < EJD < 1) должно существовать благо с EJD > 1 для конкретного потребителя, называется законом Энгеля.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичностью спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупным спросом', 
                          title = '#### Инфляция – это дисбаланс между ____________ (**совокупный, спрос**) и совокупным предложением, представляет собой устойчивое повышение общего уровня цен, когда падает покупательная способность денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупным спросом',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению спроса', 
                          title = '#### Увеличение объемов торговли со слаборазвитыми странами с низкой заработной платой и изменения технологии привели к ____________ (**снижение, спрос**) на неквалифицирован­ный труд и увеличению потребности в квалифицированных работниках в самих США.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на нефть', 
                          title = '#### Рост потребности развивающихся азиатских стран в энергоресурсах  составит до 45% перспективного прироста мирового ____________ (**спрос, на, нефть**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на нефть',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'растет спрос', 
                          title = '#### Китай выводит число международных патентных заявок на рекордно высокий уровень, ____________ (**расти, спрос**) на охрану товарных знаков и промышленных образцов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'растет спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'величиной спроса', 
                          title = '#### Рисунок показывает соотношение между ценой на продукты питания и ____________ (**величина, спрос**) на них. По горизонтальной оси откладывается количество потребляемого продовольствия, а по вертикальной оси отображается цена продовольствия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'величиной спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'шок спроса', 
                          title = '#### Масштабный ____________ (**шок, спрос**) на рынке труда во время пандемии способен влиять на уровень безработицы долгие годы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'шок спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'функция спроса', 
                          title = '#### Однако в последние 15 лет изменения функции спроса на деньги поставили ряд сложных вопросов. До 1973 г. в исследовательских работах была построена очень стабильная простая ____________ (**функция, спрос**) на деньги, в которой величина реальных остатков, на которые предъявлялся спрос, возрастала вместе с уровнем дохода и убывала вместе со ставкой процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функция спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту спроса', 
                          title = '#### Американское правительство выдает студентам кредиты под низкие проценты, что позволяет им учиться. Эти кредиты способствуют ____________ (**рост, спрос**) на высшее образование.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на ресурсы', 
                          title = '#### Фирмы предъявляют ____________ (**спрос, на, ресурс**), так как именно с их помошью они производят товары и услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на ресурсы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'избыточный спрос', 
                          title = '#### Ситуация побуждает продавцов снижать цены на товары. Если цена ниже равновесного значения, возникают неудовлетворенность у покупателей и ____________ (**избыточный, спрос**). Такая ситуация побуждает продавцов повышать цены на товары. Стабильность на рынке устанавливается только в том случае, если избыточное предложение и избыточный спрос равны 0.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'избыточный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'эластичность спроса', 
                          title = '#### Реклама часто влияет на ____________ (**эластичность, спрос**) по цене, и это нужно принимать в расчет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'эластичность спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению спроса', 
                          title = '#### Государственные закупки продукции ведут к ____________ (**повышение, спрос**) дру­гих фирм.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса и предложения', 
                          title = '#### Мы используем график с кривыми ____________ (**спрос, и, предложение**), который облегчает нам понимание влияния сдвигов на равновесную цену и объем предлагаемого и приоб­ ретаемого товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса и предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Потребителям требуется меньшее количество мороженого при каждой возможной цене. В результате кривая ____________ (**спрос**) сдвигается влево (или, что эквивалентно, вниз).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышенный спрос', 
                          title = '#### Наращивание дивидендных выплат – относительно рискованная стратегия корпоративного управления, которая предполагает ____________ (**повысить, спрос**) на на акции эмитентов со стороны инвесторов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышенный спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предъявляют спрос', 
                          title = '#### Почему иностранцы ____________ (**предъявлять, спрос**) на доллары на валютном рынке?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предъявляют спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос', 
                          title = '#### Введение выплаты процента на широкий круг депозитов увеличило привлекательность активов, повысило реальный ____________ (**спрос**) на эти активы при каждом уровне дохода и привело, таким образом, к снижению скорости обращения денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на ресурс', 
                          title = '#### В каком случае кривая ____________ (**спрос, на, ресурс**) более эластична: в случае совершенной конкуренции или в случае монополии?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на ресурс',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Часто нужно различать кривые рыночного ____________ (**спрос**) и кривые спроса для отдельной фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'удовлетворить спрос на', 
                          title = '#### Rolex построит три мануфактуры в Швейцарии, чтобы ____________ (**удовлетворить, спрос, на**) продукцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'удовлетворить спрос на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'объемом спроса', 
                          title = '#### Что лежит за обратной зависимостью между уровнем цен и ____________ (**объем, спрос**) на товары и услуги?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'объемом спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'линии спроса', 
                          title = '#### Из рисунка видно, что сдвиг ____________ (**линия, спрос**) ведет к изменению объема спроса при некоторой постоянной цене Р.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'линии спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внутренний спрос', 
                          title = '#### Как показано на рисунке, ____________ (**внутренний, спрос**) на пшеницу относительно незластичен по цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутренний спрос',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса', 
                          title = '#### Это приведет к сокращению ____________ (**спрос**) на рынке товаров и повлечет за собой давление на цены в сторону их снижения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

