```{r}
checkdown::check_question(answer = 'и средних предприятиях', 
                          title = '#### Отмечается сохранение высокого уровня регистрируемой безработицы в сочетании с недостаточным уровнем показателя занятости на малых ____________ (**и, средний, предприятие**), а также максимальным показателем удельного веса занятых в бюджетной сфере.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'и средних предприятиях',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'и средние предприятия', 
                          title = '#### Элементы «слепой» конкуренции, при которой предприниматели сначала производят, а затем ищут потребителя производственной продукции, сохранились только в сравнительно ограниченных сферах хозяйства, где действуют мелкие ____________ (**и, средний, предприятие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'и средние предприятия',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в среднем за', 
                          title = '#### Поскольку статистика для более раннего периода отсутствует, сегрегация регионов осуществлялась по критерию превышения 30%-й доли добычи полезных ископаемых в отраслевой структуре ВДС ____________ (**в, среднее, за**) 2004-2014 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в среднем за',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривая долгосрочных средних издержек', 
                          title = '#### Обычно ____________ (**кривая, долгосрочный, средний, издержка**) представляет собой сочетание всех трех приведенных выше кривых.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая долгосрочных средних издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в среднем по', 
                          title = '#### В других регионах Азиатского Севера различия в продолжительности жизни мужчин и женщин были меньше, чем ____________ (**в, среднее, по**) России, составляя от 9,7 года в Чукотском АО до 12,6 года в Магаданской области.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в среднем по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в среднесрочном периоде', 
                          title = '#### Этот процесс будет продолжаться до тех пор, пока совокупный выпуск ____________ (**в, среднесрочный, период**) не вернется на свой потенциальный уровень.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в среднесрочном периоде',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'и средних предприятиях', 
                          title = '#### В качестве повышения объективизации оценки структуры экономического развития монопрофильных территорий проведено сопоставление уровня занятости на крупных ____________ (**и, средний, предприятие**) с показателями развития малого бизнеса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'и средних предприятиях',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'среднедушевых денежных доходов населения', 
                          title = '#### Как результат, превышение уровня ____________ (**среднедушевой, денежный, доход, население**) на Дальнем Востоке над среднероссийским уровнем уменьшилось с примерно 26% в 1995 г., что было связано с высокими номинальными доходами в районах Крайнего Севера, до 7% в 2019 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'среднедушевых денежных доходов населения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривая долгосрочных средних издержек', 
                          title = '#### Кривые пересекаются в точке А, где ____________ (**кривая, долгосрочный, средний, издержка**) достигает своего минимума.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривая долгосрочных средних издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в среднем за', 
                          title = '#### Наиболее высоки соответствующие показатели в результате миграционного обмена с Республикой Татарстан (668 чел. ____________ (**в, среднее, за**) 2014-2016 гг.), затем - с Москвой (261 чел.) и Пермским краем (162 чел.).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в среднем за',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'и средних предприятий', 
                          title = '#### Прибыль уменьшается достаточно резко у некоторых крупных ____________ (**и, средний, предприятие**), что существенно сказывается на таком финансовом положении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'и средних предприятий',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'и средним предприятиям', 
                          title = '#### При финансовой поддержке регионального бюджета было создано более 100 гарантийных органов, 40 из которых оказывали финансовую помощь малым ____________ (**и, средний, предприятие**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'и средним предприятиям',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'кривой средних переменных издержек', 
                          title = '#### Напомним, что вертикальная разница между кривой средних и ____________ (**кривая, средний, переменный, издержка**) равнозначна величине средних фиксированных издержек.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'кривой средних переменных издержек',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в среднем по', 
                          title = '#### В Ненецком АО, Архангельской области, Республике Карелии, Республике Коми и Республике Тыве коэффициент смертности уменьшился значительнее, чем ____________ (**в, среднее, по**) стране.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в среднем по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в среднем на', 
                          title = '#### Когда Вы или кто-либо из Ваших друзей ищете работу на полставки, сколько недель ____________ (**в, среднее, на**) это уходит?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в среднем на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'со средним уровнем', 
                          title = '#### Несмотря на то что максимальный риск одобряемых кредитов снижается из-за ухода «плохих» банков, чаще всего принимавших такой риск, сегмент инвестиционных проектов ____________ (**с, средний, уровень**) риска получает меньше ресурсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'со средним уровнем',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

