```{r}
checkdown::check_question(answer = 'ставка процента равна нулю', 
                          title = '#### Реальная ____________ (**ставка, процент, равный, нуль**), ожидается, что она останется равной нулю в будущем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка процента равна нулю',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставку процента по', 
                          title = '#### Дж. Кейнс, по имени которого получил название данный эффект, дал ему объяснение, используя в качестве промежуточной переменной ____________ (**ставка, процент, по**) кредитам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставку процента по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентная ставка', 
                          title = '#### Высокая ____________ (**процентный, ставка**) поощряет стремление людей к сбережениям, что приводит к росту предложения заемных средств.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставка процента равна нулю', 
                          title = '#### Поскольку номинальная ____________ (**ставка, процент, равный, нуль**), расширительная монетарная политика становится бессильной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка процента равна нулю',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставке процента по', 
                          title = '#### Процентная ставка по краткосрочным инструментам может быть выше, ниже или равной ____________ (**ставка, процент, по**) долгосрочным инструментам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставке процента по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставка процента по', 
                          title = '#### Для проверки этого предсказания на рис. 3-11 также показана ____________ (**ставка, процент, по**) долгосрочным государственным облигациям, называемым в Великобритании консолями.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка процента по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'значения реальной процентной ставки', 
                          title = '#### Какими будут ____________ (**значение, реальный, процентный, ставка**), уровня цен, потребления и инвестиций в состоянии всеобщего равновесия?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'значения реальной процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки налога на', 
                          title = '#### Налоговая система Японии поощряет сбережения, предусматривая невысокие ____________ (**ставка, налог, на**) доходы от капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки налога на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставок по депозитам', 
                          title = '#### Pedersen (2016) приходит к выводу, что реакция ____________ (**ставка, по, депозит**) и кредитам является симметричной при росте и падении ключевой ставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставок по депозитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки реальной заработной платы', 
                          title = '#### Так же как растет количество труда, предлагаемого индивидуумами при увеличении их ____________ (**ставка, реальный, заработный, плата**), совокупное предложение труда растет при увеличении ставки реальной заработной платы в целом по экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки реальной заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки процента по', 
                          title = '#### В связи с этим ____________ (**ставка, процент, по**) рисковым и безрисковым активам будут различными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки процента по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставкой по', 
                          title = '#### Если проект рассчитан на 10 лет, то фирма может воспользоваться годовой ____________ (**процентный, ставка, по**) 10-летним государственным облигациям, чтобы рассчитать NPV для проекта с помощью уравнения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставкой по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставка по займу', 
                          title = '#### Было показано, что реальная процентная ____________ (**ставка, по, займ**) связана с номинальной процентной ставкой следующим соотношением: 1 + номинальная процентная ставка = (1 + реальная процентная ставка) Х (1 + уровень инфляции).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка по займу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ожидаемая реальная процентная ставка', 
                          title = '#### Теория называется паритетом реальных процентных ставок (real interest-rate parity), согласно которой ____________ (**ожидать, реальный, процентный, ставка**) по безрисковым займам будет одинаковой в любой точке земного шара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая реальная процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки по кредитам', 
                          title = '#### В другом случае предполагается, что рынки существуют, однако не являются совершенными: процентные ____________ (**ставка, по, кредит**) и депозитам могут различаться, также могут иметь место ограничения на максимальную сумму заимствования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки по кредитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки по кредитам', 
                          title = '#### Для резидентов Арктической зоны, чей инвестиционный проект удовлетворяет ряду критериев, устанавливаются нулевая ставка по федеральной и сниженная по региональной части налога на прибыль, предоставляются субсидии для возмещения процентной ____________ (**ставка, по, кредит**) и т.д.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки по кредитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставка по займу', 
                          title = '#### Нет ничего удивительного в том, что когда процентная ____________ (**ставка, по, займ**) установлена заранее, дебиторы рады непредвиденной инфляции, а кредиторы нет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка по займу',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'по процентным ставкам', 
                          title = '#### Однако замещение вкладов капиталом означает, что стоимость банковского финансирования меняется незначительно (что отражается в рядах данных ____________ (**по, процентный, ставка**) по обеспеченным и необеспеченным кредитам) и общий объем кредитов и капитала растет, усиливая последствия шока цены на нефть для ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по процентным ставкам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставкой процента по', 
                          title = '#### Предприниматель всегда сравнивает ожидаемый уровень дохода на капитал (в процентном выражении) с текущей рыночной ____________ (**ставка, процент, по**) ссудам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставкой процента по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставок по вкладам', 
                          title = '#### Сплошная синяя линия на рисунке – результат применения критериев Банка России к выгрузке предложений ____________ (**ставка, по, вклад**) с сайта-агрегатора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставок по вкладам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентных ставок по', 
                          title = '#### Ограничение максимального предела ____________ (**процентный, ставка, по**) ним может стать основополагающим фактором существенного ухудшения финансового положения данных структур в период возникновения кризиса ликвидности на рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентных ставок по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентную ставку по', 
                          title = '#### Определите, какую ____________ (**процентный, ставка, по**) кредиту установит и какую прибыль получит банк.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентную ставку по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставка процента по', 
                          title = '#### Заметим, что 1,6% в месяц все же намного больше, чем ежемесячная ____________ (**ставка, процент, по**) облигациям США (около 0,2%).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка процента по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличение реальной процентной ставки', 
                          title = '#### А как влияет ____________ (**увеличение, реальный, процентный, ставка**)на национальные сбережения?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение реальной процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки по вкладам', 
                          title = '#### Банки, использующие ПВР (переменная IRB), в предыдущие периоды предлагавшие в среднем более низкие ____________ (**ставка, по, вклад**), при росте ключевой ставки при прочих равных подняли ставки на 0,8 п. п. относительно банков, которые не используют ПВР.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки по вкладам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставка процента равна нулю', 
                          title = '#### В любом из этих случаев первоначальная номинальная ____________ (**ставка, процент, равный, нуль**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка процента равна нулю',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ожидаемая реальная процентная ставка', 
                          title = '#### Реальная процентная ставка, которая учитывается при принятии решений о сбережениях, — это ____________ (**ожидать, реальный, процентный, ставка**) после налогообложения, показывающая реальную доходность, которую могут ожидать субъекты сбережений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ожидаемая реальная процентная ставка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'по темпам роста', 
                          title = '#### Оценки параметров социально-экономического развития федеральных округов на период до 2024 г., предполагающие реализацию мер структурно-инвестиционной политики и выполнение приоритетных задач Указа-2018 (стабильный рост доходов населения, развитие жилищного строительства, увеличение затрат на образование, здравоохранение, науку), показывают, что целевые установки указа ____________ (**по, темп, рост**) национальной экономики могут быть достигнуты даже при условии относительно невысоких темпов в 2019-2021 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по темпам роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентными ставками по кредитам', 
                          title = '#### Оценки стационарности разрывов между среднероссийскими и «кластерными» средневзвешенными ____________ (**процентный, ставка, по, кредит**) показывают, что все полученные значения р удовлетворяют условию |р| < 1, а p-значение теста Филипса-Перрона не превышает 0,01.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентными ставками по кредитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставок по кредитам', 
                          title = '#### Региональные банки охотно участвуют в государственных программах поддержки приоритетных отраслей экономики, реализуемых посредством механизма субсидирования процентных ____________ (**ставка, по, кредит**), программах поддержки малообеспеченных слоев населения, детства, материнства и т.д.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставок по кредитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки налога на', 
                          title = '#### Примером финансовой тактики являются снижение ____________ (**ставка, налог, на**) добавленную стоимость и налога на прибыль, упорядочение функций федеральных органов исполнительной власти в бюджетном процессе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки налога на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальная ставка процента равна', 
                          title = '#### В соответствии с эффектом Фишера, если номинальная ставка процента составляет 7%, а темп инфляции равен 5%, то ____________ (**реальный, ставка, процент, равный**) 12%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальная ставка процента равна',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентную ставку по', 
                          title = '#### В итоге, учитывая более высокие уровни премии за риск, равновесную реальную безарбитражную ____________ (**процентный, ставка, по**) состоянию на 2016 г. можно оценить на уровне около 2,7%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентную ставку по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставку налога на', 
                          title = '#### Венгрия одобрила законодательство, которое снижает ____________ (**ставка, налог, на**) прибыль с 16% до 15% с 2016 года.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставку налога на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентными ставками по', 
                          title = '#### Значение разрыва между ____________ (**процентный, ставка, по**) кредитам и депозитам в России является одним из самых высоких среди стран Европы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентными ставками по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставкой', 
                          title = '#### Под реальной ____________ (**процентный, ставка**) понимается номинальная ставка на трехлетние облигации Казначейства за вычетом ожидаемой инфляции, представленной в виде среднего темпа дефлятора ВНП для последнего года, текущего года и следующего года (предполагая 3,9% для 1989 г.).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставкой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентной ставки по', 
                          title = '#### В число основных механизмов входят следующие: субсидирование ____________ (**процентный, ставка, по**) привлекаемым банковским кредитам; предоставление бюджетного кредита за счет средств областного бюджета; предоставление налоговых льгот в отношении создаваемого имущества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентной ставки по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки налогов на', 
                          title = '#### В начале 80-х гг. максимальные ____________ (**ставка, налог, на**) личные доходы в целом ряде стран превышали 70%, после нескольких снижений, по данным на 2017 г. в среднем по ЕС этот показатель составляет 39%, в Дании и Швеции – 57%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки налогов на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки по вкладам', 
                          title = '#### Собственно, исходя из этого, Банк России и ограничивает максимальные ____________ (**ставка, по, вклад**) – такая политика регулятора призвана дестимулировать «серийных» вкладчиков, которые несут деньги в малонадежные банки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки по вкладам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентные ставки по', 
                          title = '#### Вспомним, что цены на неденежные активы и ____________ (**процентный, ставка, по**) ним связаны обратно пропорциональной зависимостью.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентные ставки по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставок по вкладам', 
                          title = '#### Используя новые данные о предложениях ____________ (**ставка, по, вклад**), а не о ставках из отчетности, мы можем подтвердить вывод Перевышина и Перевышиной (2015) о неполном переносе ключевой ставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставок по вкладам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесной процентной ставки', 
                          title = '#### В итоге мы получаем оценки ____________ (**равновесный, процентный, ставка**) для России в рамках основных существующих подходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесной процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставок по кредитам', 
                          title = '#### Повышение Банком России ключевой ставки до 17%, высокий уровень инфляционных ожиданий и резкие колебания валютного курса неизбежно ведут к росту процентных ____________ (**ставка, по, кредит**) и серьезно тормозят инвестиционную активность российских предпринимателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставок по кредитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки реальной заработной платы', 
                          title = '#### Увеличение ____________ (**ставка, реальный, заработный, плата**) имеет своим следствием возникновение действующих в противоположных направлениях эффектов предложения труда — замещения и дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки реальной заработной платы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'по темпам роста', 
                          title = '#### По мере развития страхового рынка в первую очередь достигается точка оптимума ____________ (**по, темп, рост**) экономики (Y1), затем по волатильности темпов роста ВВП (Y2) и, наконец, по показателю системных банковских кризисов (Y4).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'по темпам роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'процентные ставки', 
                          title = '#### После разграничения понятий номинальной и реальной ставок можно еще раз вернуться к вопросу о том, почему ____________ (**процентный, ставка**) положительны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'процентные ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличение реальной процентной ставки', 
                          title = '#### Покажите воздействие, которое оказывает ____________ (**увеличение, реальный, процентный, ставка**) на бюджетную линию и точку оптимального потребления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличение реальной процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставки налогов на', 
                          title = '#### ____________ (**ставка, налог, на**) отдельные виды природных ресурсов, акцизов на отдельные виды минерального сырья и таможенных пошлин устанавливаются Правительством России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставки налогов на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставками по кредитам', 
                          title = '#### Оценки стационарности разрывов между средневзвешенными процентными ____________ (**ставка, по, кредит**) в кластерах и г. Москвой показывают, что все полученные значения р удовлетворяют условию |р| < 1.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставками по кредитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставка налога на', 
                          title = '#### Во многих случаях налоги штатов и местные налоги аналогичны федеральным, в других они различаются (например, ____________ (**ставка, налог, на**) заработную плату устанавливается значительно ниже ставки налога на банковские проценты или дивиденды).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка налога на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рост реальной процентной ставки', 
                          title = '#### Большинство широко распространенных заключений говорит о том, что ____________ (**рост, реальный, процентный, ставка**) снижает уровень текущего потребления и увеличивает сбережения, но этот эффект не очень стойкий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост реальной процентной ставки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставку налога на', 
                          title = '#### В настоящее время субъекты Федерации могут снизить ____________ (**ставка, налог, на**) прибыль в части суммы налога, зачисляемого в их бюджеты, только на 4,5 п.п. (т.е. до 13,5%).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставку налога на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставка по депозитам', 
                          title = '#### В III–IV кварталах 2013 г. средняя процентная ____________ (**ставка, по, депозит**) и ключевая ставка пересеклись.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставка по депозитам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ставкой процента по', 
                          title = '#### За время, прошедшее с 50-х гг., изменились акценты, которые ФРС придавала контролю над ____________ (**ставка, процент, по**) сравнению с контролем над объемом денежной массы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ставкой процента по',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

