
```{r}
checkdown::check_question(answer = stringr::str_split('баланс; счета; текущих; операций', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'баланс; счета; текущих; операций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('дефицит; счета; текущих; операций', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'дефицит; счета; текущих; операций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('сальдо; счета; текущих; операций', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сальдо; счета; текущих; операций',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = stringr::str_split('текущий; счет; платежного; баланса', '; ') |> unlist(), 
                          type = 'in_order',
                          right = 'все верно!',
                          title = '#### Поставьте слова в правильном порядке:',
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'текущий; счет; платежного; баланса',
           hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```
