```{r}
checkdown::check_question(answer = 'покупку товаров длительного пользования', 
                          title = '#### Рост ставки процента сокращает потребительские расходы, поскольку кредит берут не только фирмы, но и домохозяйства (потребительский кредит), особенно на ____________ (**покупка, товар, длительный, пользование**), и его удорожание ведет к сокращению потребительского спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'покупку товаров длительного пользования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительских товаров', 
                          title = '#### Это дает возможность расширить производство одновременно как инвестиционных, так и ____________ (**потребительский, товар**) путем более эффективного использования ограниченного объема факторов производства, т. е. расширить рамки потенциального ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительских товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конечных товаров', 
                          title = '#### Валовой внутренний продукт (ВВП) представляет собой показатель совокупной рыночной стоимости всех ____________ (**конечный, товар**) и услуг, произведенных в экономике в конкретном году.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конечных товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на товар', 
                          title = '#### С одной стороны, некоторые потребители могут сокращать свой ____________ (**спрос, на, товар**) при снижении его цены, поскольку данный товар становится более доступным, масштабы его потребления растут, а данная категория потребителей не хочет быть «как все».',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на товар',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'для производства товара', 
                          title = '#### Предпринимательская способность — способность человека использовать определенное сочетание ресурсов ____________ (**для, производство, товар**), принимать последовательные решения, создавать новшества и идти на риск.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'для производства товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительских товаров', 
                          title = '#### В этом случае принимается допущение о том, что на рынке благ действуют четыре независимых покупателя: домохозяйства (покупатели ____________ (**потребительский, товар**)), фирмы (покупатели инвестиционных товаров), государство (покупатель общественных благ) и внешний мир («покупатель» чистого экспорта).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительских товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товары длительного пользования', 
                          title = '#### На рисунке показаны кривые спроса на ____________ (**товар, длительный, пользование**) (такие, как автомобили) в краткосрочном и долгосрочном периодах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товары длительного пользования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'импорта товаров', 
                          title = '#### Увеличение национального дохода в одной стране в условиях интернационализации обмена способствует росту ____________ (**импорт, товар**) и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'импорта товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предложение товаров', 
                          title = '#### Ставка процента уравновешивает спрос и ____________ (**предложение, товар**) и услуг (или, аналогично, спрос и предложение заемных средств).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предложение товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на импортные товары', 
                          title = '#### Цены ____________ (**на, импортный, товар**) повышаются, снижая степень конкуренции для внутренних фирм, производящих аналогичные товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на импортные товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экспорта товаров', 
                          title = '#### В то же время отмечалось снижение удельного веса ____________ (**экспорт, товар**) и услуг на 6,94%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экспорта товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'закупок товаров', 
                          title = '#### В 2002 г. федеральные инвестиционные расходы составили $107,2 млрд (около 15% федеральных ____________ (**закупка, товар**) и услуг), из которых 4/7 инвестиционных расходов пошло на национальную оборону и 3/7 на не связанные с обороной государственные основные фонды.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закупок товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товары длительного пользования', 
                          title = '#### В реальной жизни существует множество различных активов, как реальных (жилые и офисные здания, потребительские ____________ (**товар, длительный, пользование**)), так и финансовых (вклады в банках, государственные обязательства).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товары длительного пользования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'для производства товара', 
                          title = '#### Можно также говорить об эластичности предложения по таким переменным, как ставка процента, уровень заработной платы, цены на сырье и полуфабрикаты, используемые ____________ (**для, производство, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'для производства товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на рынках товаров', 
                          title = '#### Посредством монетарной политики Центральный банк обеспечивает благоприятные условия экономического роста и осуществляет: регулирование темпов экономического роста; смягчение циклических колебаний ____________ (**на, рынок, товар**), капитала и рабочей силы; сдерживание инфляции; достижение сбалансированности платежного баланса страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на рынках товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'произведенных товаров', 
                          title = '#### Это становится возможным благодаря тому, что все хозяйствующие субъекты находятся в одной системе и для государства не составит труда создать несколько автоматических контуров проверки, например учитывающие потребленные ресурсы, количество ____________ (**произвести, товар**) и услуг, средние нормативы по отрасли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'произведенных товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товаров длительного пользования', 
                          title = '#### Продолжительность коротких циклов Китчина – 2–3 года, и связаны они с массовым обновлением потребителями ____________ (**товар, длительный, пользование**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товаров длительного пользования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросу на товары', 
                          title = '#### Равновесие на товарном рынке (equilibrium in the goods market) — условие, что предложение товаров должно быть равно ____________ (**спрос, на, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросу на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товаров длительного пользования', 
                          title = '#### К дискреционным покупкам относится приобретение ____________ (**товар, длительный, пользование**): телевизоров, холодильников, автомобилей и т.п.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товаров длительного пользования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'выпуска товаров', 
                          title = '#### ВВП всего лишь отражает объем годового ____________ (**выпуск, товар**)  и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выпуска товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены на товар', 
                          title = '#### При единичной эластичности спроса ____________ (**цена, на, товар**) выросли на 2%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены на товар',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на отечественные товары', 
                          title = '#### Это будет верно только при условии, что все дополнительные расходы пошли ____________ (**на, отечественный, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на отечественные товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'импорта товаров', 
                          title = '#### Торговая политика представляет собой относительно самостоятельное направление бюджетно-налоговой политики государства, нацеленное на стимулирование экспорта или ____________ (**импорт, товар**) и услуг посредством налогов, сборов, субсидий и других инструментов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'импорта товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'закупки товаров', 
                          title = '#### Следует различать понятия “государственные ____________ (**закупка, товар**) и услуг” и “государственные расходы”.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закупки товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'фиксированного набора потребительских товаров', 
                          title = '#### К числу таких факторов были отнесены уровень жизни населения, уровень образования населения, уровень безработицы, демографические показатели, показатели, характеризующие состояние ресурсной базы здравоохранения, доходы консолидированного бюджета региона, стоимость ____________ (**фиксированный, набор, потребительский, товар**) и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'фиксированного набора потребительских товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товара на рынке', 
                          title = '#### Как изменятся равновесные цены и количество ____________ (**товар, на, рынок**) морских продуктов?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товара на рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товаров внутреннего производства', 
                          title = '#### Иностранные товары отличаются от ____________ (**товар, внутренний, производство**), поэтому мы не можем просто вычесть объем импорта: если бы мы так сделали, мы бы вычитали яблоки (иностранные товары) из апельсинов (внутренних товаров).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товаров внутреннего производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'за единицу товара', 
                          title = '#### Государство установило на данный товар фиксированную цену в три денежные единицы ____________ (**за, единица, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'за единицу товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производимых товаров', 
                          title = '#### Стремление России стать полноценным членом международной торговой системы вызывает необходимость соответствия ____________ (**производить, товар**) и услуг мировым требованиям.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производимых товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'закупок товаров', 
                          title = '#### Дж. М. Кейнс предложил следующее решение: при высокой безработице правительство должно увеличивать объем ____________ (**закупка, товар**) и услуг, что приведет к увеличению спроса на продукцию производителей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закупок товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на товары', 
                          title = '#### После снижения реальной процентной ставки увеличивается совокупный ____________ (**спрос, на, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'доступ к товару', 
                          title = '#### Фирма получит максимальную прибыль, если установит цену Р за использование товара на уровне предельных издержек, а плату за ____________ (**доступ, к, товар**) назначит равной всему излишку потребителя.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'доступ к товару',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены на товары', 
                          title = '#### Экономисты обычно исходят из того, что ____________ (**цена, на, товар**) и услуги изменяются в соответствии с задачей уравновешивания спроса и предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на рынках товаров', 
                          title = '#### Доход и ставка процента реагируют на неравновесие ____________ (**на, рынок, товар**) и активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на рынках товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительские товары', 
                          title = '#### Этот процесс ведет к росту производственной эффективности, снижению цен на ____________ (**потребительский, товар**) и большей специализации в соответствии со сравнительными преимуществами партнеров по ССТ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительские товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'импорт товаров', 
                          title = '#### Первые две строки отражают экспорт и ____________ (**импорт, товар**) и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'импорт товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценами на товары', 
                          title = '#### Приобретать ресурсы целесообразно, если цены на них ниже по сравнению с ____________ (**цена, на, товар**), которые производятся с помощью этих ресурсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценами на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценах на товары', 
                          title = '#### Приведенная стоимость определяет стоимость платежей, произведенных в будущем, в сегодняшних ____________ (**цена, на, товар**) и услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценах на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на рынке товара', 
                          title = '#### Одна пара кривых описывает поведение монопсониста-монополиста на рынке фактора, а другая — ____________ (**на, рынок, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на рынке товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цена на товар', 
                          title = '#### Предположим, например, что ____________ (**цена, на, товар**) поднялась на 10% и в результате потребители решили уменьшить совокупный запас на 5%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена на товар',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'заплатить за товар', 
                          title = '#### Так как кривая спроса отражает готовность покупателей ____________ (**платить, за, товар**), мы можем использовать ее для определения потребительского излишка.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'заплатить за товар',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены на товары', 
                          title = '#### Теория полезности объясняет процесс формирования ____________ (**цена, на, товар**) и услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товары внутреннего производства', 
                          title = '#### Рост чистого экспорта повышает спрос на ____________ (**товар, внутренний, производство**), а следовательно, приводит к росту ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товары внутреннего производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'импорт товаров', 
                          title = '#### В 1730-е гг. ____________ (**импорт, товар**)из Индии достиг 2,8 млн песо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'импорт товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стоимость товаров', 
                          title = '#### Государственные закупки - это общая ____________ (**стоимость, товар**) и услуг, приобретаемых Федеральным правительством, правительствами штатов и местными органами управления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стоимость товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'импорт товаров', 
                          title = '#### За последнее десятилетие экспорт и ____________ (**импорт, товар**) и услуг росли более быстрыми темпами по сравнению с внутренними компонентами ВВП: частным потреблением, государственными расходами и инвестициями.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'импорт товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на импортные товары', 
                          title = '#### С 15 января 1992 г. в соответствии с постановлением Правительства РФ № 32 «О таможенных пошлинах ____________ (**на, импортный, товар**)» было отменено взимание пошлин и других сборов, кроме платы за таможенные процедуры при ввозе товаров на территорию России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на импортные товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товаров длительного пользования', 
                          title = '#### Потребление дезагрегируется в три компонента: покупку ____________ (**товар, длительный, пользование**), товаров краткосрочного пользования и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товаров длительного пользования',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'товаров внутреннего производства', 
                          title = '#### Реальный валютный курс — это относительная цена иностранных товаров, выраженная в количестве ____________ (**товар, внутренний, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'товаров внутреннего производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на продовольственные товары', 
                          title = '#### За счет импорта обеспечивается 35—37% спроса ____________ (**на, продовольственный, товар**), в том числе на 60% — на мясо, на 50% — на сливочное масло.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на продовольственные товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на товары', 
                          title = '#### В точке Е, однако, нет избыточного ____________ (**спрос, на, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на товары', 
                          title = '#### Какой вариант будет лучше стабилизировать выпуск в модели IS-LM, если все шоки в экономике возникают в связи с экзогенными изменениями ____________ (**спрос, на, товар**) и услуги?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на сырьевые товары', 
                          title = '#### С более высоким уровнем применения инструментов МПП (Чили и Колумбия) чувствительность динамики темпов общего и валютного кредитования к шокам цен ____________ (**на, сырьевой, товар**) ниже, что также свидетельствует в пользу более активного внедрения МПП в ресурсных странах с формирующимися рынками.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на сырьевые товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'выпуска товаров', 
                          title = '#### Показатель ВРП является агрегированным и включает в себя стоимость всего объема конечного ____________ (**выпуск, товар**) и услуг в производственной и непроизводственной сферах региона за один год.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'выпуска товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стоимость товаров', 
                          title = '#### Промежуточное потребление – ____________ (**стоимость, товар**) и услуг, израсходованных в процессе производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стоимость товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на сырьевые товары', 
                          title = '#### Во многих странах такое есть. Равно как и схемы, при которых ____________ (**на, сырьевой, товар**) налоги повышаются, а на высокотехнологическую продукцию снижаются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на сырьевые товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'за единицу товара', 
                          title = '#### По вертикальной оси расположена цена товара Р, измеряемая в долларах ____________ (**за, единица, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'за единицу товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производить товары', 
                          title = '#### Все происходит в соответствии с одним из Десяти принципов экономики, утверждающих, что уровень жизни населения страны зависит от возможностей экономики ____________ (**производить, товар**) и услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производить товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экспорт товаров', 
                          title = '#### На рисунке показано, что обменный курс валюты изменяется таким образом, чтобы чистый ____________ (**экспорт, товар**) и услуг уравновесил этот приток капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экспорт товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценах на товары', 
                          title = '#### По характеру протекания различают открытую инфляцию, отличающуюся продолжительным ростом цен, и подавленную, возникающую при твердых замороженных розничных ____________ (**цена, на, товар**) и услуги при одновременном росте денежных доходов населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценах на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросом на товары', 
                          title = '#### Кейнс совершенно правильно указывал, что спрос на деньги не исчерпывается ____________ (**спрос, на, товар**), поскольку во всяком обществе люди воспринимают и используют деньги как форму богатства, накопление которой снижает беспокойство относительно неопределенного будущего.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросом на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на товар', 
                          title = '#### В соответствии формулировкой закона Антуана Огюстена Курно ____________ (**спрос, на, товар**) составляет некоторую функцию цены, причем, как правило, убывающую.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на товар',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расходы на товары', 
                          title = '#### Влияние изменения трудовых доходов на совокупные потребительские расходы и ____________ (**расход, на, товар**) кратковременного пользования снижается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расходы на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'предложения товаров', 
                          title = '#### Мы прошли полный круг в диаграмме кругооборота, начав наш путь с рассмотрения ____________ (**предложение, товар**) и услуг, и завершв его анализом спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'предложения товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производимых товаров', 
                          title = '#### Спрос и предложение определяют количество ____________ (**производить, товар**) и цену, по которой продаются продукты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производимых товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'импорта товаров', 
                          title = '#### В торговом балансе отражается соотношение экспорта и ____________ (**импорт, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'импорта товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительские товары', 
                          title = '#### Таким образом, предполагалось, что спрос на инвестиции и ____________ (**потребительский, товар**) длительного пользования будет высок, а значит спада не будет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительские товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'расходов на товары', 
                          title = '#### Отрицательный чистый экспорт влечет за собой уменьшение совокупных ____________ (**расход, на, товар**) отечественного производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'расходов на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спросом на товары', 
                          title = '#### С другой стороны, если настаивать, что спрос на деньги не исчерпывается ____________ (**спрос, на, товар**), что денежные накопления в достаточно весомой части вовсе не являются отложенным спросом на товары, имеет смысл отказаться от понятия денег как средства обмена.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спросом на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'конечных товаров', 
                          title = '#### Потребление — это расходы находящихся на территории страны домашних хозяйств на покупку ____________ (**конечный, товар**) и услуг, включая и те, которые произведены за границей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'конечных товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на приобретение товаров', 
                          title = '#### По мере роста доходов население тратит больше денег ____________ (**на, приобретение, товар**) и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на приобретение товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен на товары', 
                          title = '#### Фирмы могут нанимать дополнительных рабочих, не повышая номинальную ставку заработной платы, следовательно, издержки фирм не меняются, и нет предпосылок для изменения уровня ____________ (**цена, на, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен на товары',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'для производства товаров', 
                          title = '#### Всякое предприятие соединяет под своим управлением факторы производства — капитал, землю и труд, которые оно использует ____________ (**для, производство, товар**) и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'для производства товаров',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

