```{r}
checkdown::check_question(answer = 'спрос на факторы', 
                          title = 'Отсюда вытекает, что ____________ (**спрос, на, фактор**) производства является взаимозависимым.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на факторы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спроса на факторы', 
                          title = 'Производный характер ____________ (**спрос, на, фактор**) со стороны фирмы предопределяет его зависимость и от производительности факторов, и от уровня цен на продукцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спроса на факторы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'совокупной производительности факторов', 
                          title = 'Запасы капитала могут расти без какого-либо прироста продукции, что предполагает снижение ____________ (**совокупный, производительноста, фактор**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'совокупной производительности факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цена фактора производства', 
                          title = 'Итак, ____________ (**цена, фактор, производство**) — труда, земли или капитала — равна стоимости предельного продукта этого фактора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена фактора производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на факторы', 
                          title = 'Поскольку ____________ (**спрос, на, фактор**) производства является производным от спроса на блага, в производстве которых он используется, спрос на факторы и их цены зависят и от строения рынка факторов, и от строения рынка благ.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на факторы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'с учетом факторов', 
                          title = 'Они проводят симуляционный анализ, который показывает, что использование в ДКП концепции равновесной ставки ____________ (**с, учет, фактор**) финансовой стабильности позволяет обеспечить более стабильную траекторию ВВП и инфляции в среднем на длительном промежутке времени.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'с учетом факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'с учетом фактора', 
                          title = 'Поскольку стратегическое планирование связано с оценкой затрат и доходов ____________ (**с, учет, фактор**) времени, то его в значительной степени относят к финансовым решениям.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'с учетом фактора',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен факторов производства', 
                          title = 'Как мы видели на рисунке, возрастание ____________ (**цена, фактор, производство**) смещает кривые предельных издержек фирм вверх.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынках факторов производства', 
                          title = 'Открытость на ____________ (**рынок, фактор, производство**) - это возможность для фирм выбирать, где размещать производство, а для рабочих — выбирать, где работать.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынках факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'из важнейших факторов', 
                          title = 'Одним ____________ (**из, важный, фактор**), определяющих спрос на жилье, является реальная ставка процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'из важнейших факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияние географических факторов', 
                          title = 'Количественная оценка факторов роста через региональные различия в географических особенностях, институциональных факторах, человеческом капитале, реализованная с помощью модели одновременных уравнений, учитывающей пространственные связи и наличие пространственной корреляции экономического роста, показала существенное ____________ (**влияние, географический, фактор**) на экономический рост.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние географических факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в качестве факторов', 
                          title = 'Если в качестве двух товаров берется пшеница и сукно, а ____________ (**в, качество, фактор**) производства - земля и труд, и соотношение между факторами таковы, что владельцы земли, которая интенсивно используется при производстве пшеницы, получают выигрыш, то он не может быть компенсирован эффектом замещения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в качестве факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок факторов производства', 
                          title = 'Дело в том, что ____________ (**рынок, фактор, производство**) складывается из трех видов рынка: рынка труда, рынка земли, рынка капиталов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы влияют на', 
                          title = 'Что понимается под справедливой ценой биржевого опциона, какие ____________ (**фактор, влиять, на**) формирование этой цены на рынке?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы влияют на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цена фактора производства', 
                          title = 'Более высокая ____________ (**цена, фактор, производство**) заставляет фирму снижать свой объем производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена фактора производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы влияют на', 
                          title = 'Обозначенные ____________ (**фактор, влиять, на**) характер этих двух видов исследований, а также выбор компонентов системы как аналитических единиц.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы влияют на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'учет фактора неопределенности', 
                          title = 'Центральным методологическим элементом доклада явился ____________ (**учет, фактор, неопределенность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'учет фактора неопределенности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынков факторов производства', 
                          title = 'Оказалось, что предположение о совершенной интеграции ____________ (**рынок, фактор, производство**) приводит к бесконечной скорости сходимости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынков факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спрос на факторы', 
                          title = 'Вообще в рыночной экономике предложение факторов производства (труда, капитала, земли, предпринимательских услуг) осуществляют домашние хозяйства, а ____________ (**спрос, на, фактор**) производства предъявляют фирмы (бизнес).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спрос на факторы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынки факторов производства', 
                          title = 'Мы перечислим условия, которые должны выполняться, чтобы обмен, ____________ (**рынок, фактор, производство**) и рынки готовой продукции были экономически эффективными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынки факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внешних факторов', 
                          title = 'Схожий принцип упорядочивания переменных применялся в работах (Barnett, et al., 2016), (Khan & Ahmed, 2011), посвященных анализу внутренних и ____________ (**внешний, фактор**) изменения валютного курса при помощи страновых моделей векторной авторегрессии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внешних факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в качестве факторов', 
                          title = 'В статье, посвященной анализу индийской экономики, ____________ (**в, качество, фактор**) формирования налоговых доходов рассматривались рост ВВП, рост отдельных отраслей (сельское хозяйство, промышленность, сфера услуг), уровни инфляции и безработицы, плотность населения, расходы населения, национальный доход на душу населения, а также объемы экспорта и импорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в качестве факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внешних факторов', 
                          title = 'Прогрессивный ход развития экономики зависит от внутренних и ____________ (**внешний, фактор**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внешних факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производительности факторов производства', 
                          title = 'Каковы на самом деле были причины падения совокупной ____________ (**производительноста, фактор, производство**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производительности факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внешние факторы', 
                          title = 'Систематизированы внутренние и ____________ (**внешний, фактор**) стагнации российской экономики в 2012 – 2016 гг., раскрыта специфика структурных факторов, уточнено качество экономического роста российской экономики в период 2000-х гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внешние факторы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен факторов производства', 
                          title = 'Важную роль играют и возможные структурные изменения общественных ____________ (**цена, фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены факторов производства', 
                          title = 'Небольшие изменения в выпуске продукции отрасли не будут оказывать влияния на ____________ (**цена, фактор, производство**) в большинстве отраслей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'использования факторов производства', 
                          title = 'Значение сравнительной эффективности ____________ (**использование, фактор, производство**) в рамках определенных территорий становится существенно больше, чем в период централизованного планирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'использования факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынков факторов производства', 
                          title = 'В работе 2007-ого года Абель Фелин и Фосс отмечают наличие легендарного интереса к микроуровню и достигнутые в этой сфере результаты (достижения в области исследования захвата ценности [Coff, 1999; Lippman, Rumelt, 2003; Barney, 2001], динамики ____________ (**рынок, фактор, производство**) [Makadok, Barney, 2001], организационной гетерогенности [Abell, Felin, Foss, 2008, Felin, Hesterly, 2006; Gavetti,2005].',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынков факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внешние факторы', 
                          title = 'Наступление этого этапа определяют разнохарактерные внутренние и ____________ (**внешний, фактор**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внешние факторы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'как фактор повышения', 
                          title = 'Направления реализации перечисленных принципов включают: подчинение пространственного развития экономики региона интересам социального развития его территорий; усиление роли экономики сельских поселений в формировании потребительского рынка региона ____________ (**как, фактор, повышение**) конкурентоспособности производства; ориентацию на широкое развитие внутрирегиональных и межмуниципальных связей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'как фактор повышения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены факторов производства', 
                          title = 'В отрасли с постоянными издержками ____________ (**цена, фактор, производство**) не изменяются, когда изменяются условия на рынке продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынок факторов производства', 
                          title = 'Фирмы, в свою очередь, направляя полученные средства на ____________ (**рынок, фактор, производство**), производят оплату труда работников, осуществляют арендные платежи, а также выплачивают прибыль своим владельцам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынок факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на рынках факторов', 
                          title = 'В краткосрочном и среднесрочном периодах (что является объектом изучения в этой и следующих трех главах) открытость ____________ (**на, рынок, фактор**) производства играет гораздо меньшую роль, чем открытость на товарных и финансовых рынках.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на рынках факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторы развития межбюджетных отношений', 
                          title = 'Ключевые ____________ (**фактор, развитие, межбюджетный, отношение**) других уровней далеко не всегда сопровождалась передачей последним финансовых средств, необходимых для выполнения возлагаемых на них обязательств.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторы развития межбюджетных отношений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'из важнейших факторов', 
                          title = 'Развитие межрегионального рынка является одним ____________ (**из, важный, фактор**) стимулирования экономического роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'из важнейших факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'факторам влияющим на', 
                          title = 'Систематизация позволяет выделять и точечно обращаться к проблемам развития институтов, а также к ____________ (**фактор, влиять, на**) данные институты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'факторам влияющим на',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рынках факторов производства', 
                          title = 'Модель экономического роста Р.Солоу основывается на неоклассических предпосылках и предполагает гибкость цен как на рынке благ, так и на ____________ (**рынок, фактор, производство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рынках факторов производства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'на рынке факторов', 
                          title = 'Поскольку MRTS LK — это наклон изокванты фирмы, то конкурентное равновесие ____________ (**на, рынок, фактор**) может возникнуть только в том случае, если каждый производитель использует труд и капитал так, что наклоны изоквант равны друг другу и отношению цен двух факторов производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'на рынке факторов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

