```{r}
checkdown::check_question(answer = 'финансовых результатах', 
                          title = '#### Затраты отображаются в отчете о ____________ (**финансовый, результат**) деятельности корпорации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых результатах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых', 
                          title = '#### Кредитование малого и среднего бизнеса повышаетдоступность ____________ (**финансовый**) услуг для населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой стабильности', 
                          title = '#### Климатические стресс-тесты – одно из важнейших направлений деятельности центробанков по обеспечению ____________ (**финансовый, стабильность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой стабильности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой устойчивостью', 
                          title = '#### управление ____________ (**финансовый, устойчивость**) является важнейшим аспектом работы финансово-экономической службы компании.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой устойчивостью',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой', 
                          title = '#### В качестве инструмента для анализа рисков после глобального кризиса стало широко использоваться стресс-тестирование – как для оценки рисков индивидуальных банков, так и для анализа рисков ____________ (**финансовый**) системы в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системы', 
                          title = '#### Финансы предприятий разных форм собственности являются базисом и источником денежных фондов всей ____________ (**финансовый, система**) государства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых средств', 
                          title = '#### В целом в экономике страны уровень доступных ____________ (**финансовый, средство**) вернулся к уровню начала года.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой отчетности', 
                          title = '#### Мы наблюдаем значительное снижение частоты упоминания государственной программы в ____________ (**финансовый, отчетность**) публичных компаний после 2018 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой отчетности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых рынков', 
                          title = '#### Эффект недостаточной реакции наблюдается, когда участники ____________ (**финансовый, рынок**) на относительно коротких временных интервалах недостаточно полно учитывают поступающую информацию о финансовом активе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых рынков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых', 
                          title = '#### Финансовые инновации включают в себя создание новых ____________ (**финансовый**) инструментов и технологий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый', 
                          title = '#### Хотя расширение союза может занять время, предполагаемый масштаб необходимых изменений решительно изменит ____________ (**финансовый**) баланс внутри блока.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые обязательства', 
                          title = '#### Все банки смогут выполнить ____________ (**финансовый, обязательство**) перед вкладчиками.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые обязательства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых показателей', 
                          title = '#### Компания объяснила ухудшение своих ____________ (**финансовый, показатель**) в текущем году.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых показателей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых инструментов', 
                          title = '#### Перед финансово-экономическим кризисом 2007-2009 гг. в США появилось много новых производных ____________ (**финансовый, инструмент**) и считалось, что риски падают, так как участники финансовых отношений могли лучше страховаться от риска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых инструментов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой поддержке', 
                          title = '#### Новую IT-профессию можно получить при ____________ (**финансовый, поддержка**) государства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой поддержке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системы', 
                          title = '#### Сегодня можно измерить уровень стресса ____________ (**финансовый, система**) и строить прогнозы с помощью машинного обучения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой грамотности', 
                          title = '#### В стране проводится работа по повышению ____________ (**финансовый, грамотность**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой грамотности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых рынках', 
                          title = '#### Кризис рубля можно сравнить с другими кризисами, многие из которых были вызваны большими дисбалансами, образовавшимися по разным причинам на ____________ (**финансовый, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовом рынке', 
                          title = '#### Объектами отношений на ____________ (**финансовый, рынок**) выступают денежно-кредитные ресурсы и ценные бумаги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовом рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых активов', 
                          title = '#### Очень много исследований рынков доказывают, что поведение основных экономических агрегатов определяет динамику цен ____________ (**финансовый, актив**) (акций и облигаций).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых активов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой грамотности', 
                          title = '#### Необходимо внедрить элементы ____________ (**финансовый, грамотность**) в образовательные школьные программы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой грамотности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового развития', 
                          title = '#### Авторы проанализировали макроэкономические показатели, в том числе темпы роста ВВП и инфляцию, а также уровень ____________ (**финансовый, развитие**) более чем 100 стран за 2000–2017 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых ресурсов', 
                          title = '#### В последние годы отчетливо проявляется тенденция снижения налоговой базы и оттока ____________ (**финансовый, ресурс**) из региона.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых ресурсов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых потоков', 
                          title = '#### Происходит перераспределение ____________ (**финансовый, поток**) в пользу основных бенефициаров крупных корпораций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых результатах', 
                          title = '#### Компенсации в виде акций компании-работодателя или опционов позволяют высококвалифицированным работникам получать вознаграждение, основанное на ____________ (**финансовый, результат**) компании.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых результатах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых', 
                          title = '#### Первая и главная функция финансового запаса фирмы — это накопление ____________ (**финансовый**) ресурсов и их распределение в целях повышения финансовой устойчивости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системы', 
                          title = '#### Уровень стресса ____________ (**финансовый, система**) в стране в апреле составил 1,2 пункта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовому развитию', 
                          title = '#### Центральные банки могут внести свой вклад в создание более справедливого общества с помощью немонетарных мер: содействие ____________ (**финансовый, развитие**), продвижение финансовой доступности, защита потребителей финансовых услуг, поощрение финансовой грамотности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовому развитию',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых ресурсов', 
                          title = '#### Американские компании также наделены правом выпускать необеспеченные долговые обязательства в целях привлечения ____________ (**финансовый, ресурс**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых ресурсов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые', 
                          title = '#### отраслевые ____________ (**финансовый**) потоки указывают на стабилизацию экономической активности в апреле.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой устойчивости', 
                          title = '#### На фоне негативного информационного фона об ухудшении ____________ (**финансовый, устойчивость**) столкнулись с оттоком депозитов многие американские банки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой устойчивости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых ресурсов', 
                          title = '#### Главной целью финансового прогнозирования является определение реально возможного объема ____________ (**финансовый, ресурс**) и их потребности в прогнозируемом периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых ресурсов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый цикл', 
                          title = '#### Монетарная политика США значимо влияет на глобальный ____________ (**финансовый, цикл**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый цикл',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой устойчивости', 
                          title = '#### На стадии начала бизнеса основным фактором обеспечения ____________ (**финансовый, устойчивость**) фирмы выступает результативность производственного процесса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой устойчивости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых потоков', 
                          title = '#### Мировые финансовые центры – экономики, чья основная роль в международной финансовой системе в том, чтобы выступать посредниками в распределении ____________ (**финансовый, поток**) из стран-источников в страны-реципиенты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'с', 
                          title = '#### Директивный финан____________ (**с**)овый механизм разрабатывается государством и используется участниками финансовых отношений в обязательном порядке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'с',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых показателях', 
                          title = '#### Из-за особенностей отчетности далеко не все убытки от процентного риска отражаются в ____________ (**финансовый, показатель**) банков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых показателях',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые ресурсы', 
                          title = '#### Олигополистические отрасли обычно имеют значительные ____________ (**финансовый, ресурс**), которые позволяют им более активно заниматься неценовой конкуренцией.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые ресурсы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовым', 
                          title = '#### Глубокая интеграция рынков позволяет ____________ (**финансовый**) шокам быстрее передаваться между экономиками.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовым',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой', 
                          title = '#### шок ____________ (**финансовый**) стабильности вынуждает центробанк тратить ресурсы, которые он позже не сможет использовать для поддержки стабильности ценовой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'активов', 
                          title = '#### Основной ресурсной базой роста незадействованных финансовых ____________ (**актив**) в России выступают сбережения физических лиц.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'активов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системе', 
                          title = '#### Если значимость банков в ____________ (**финансовый, система**) снизится, то и инструменты монетарной политики, такие как предоставление банкам ликвидности, могут стать неэффективными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой стабильности', 
                          title = '#### Тесты выявляют и измеряют риски ____________ (**финансовый, стабильность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой стабильности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых', 
                          title = '#### В странах с развитыми рынками в последние годы наблюдался массированный рост цен ____________ (**финансовый**) активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системы', 
                          title = '#### Война стала огромным испытанием не только для людей, но и для ____________ (**финансовый, система**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой устойчивостью', 
                          title = '#### Представлены механизмы управления ____________ (**финансовый, устойчивость**) фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой устойчивостью',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового сектора', 
                          title = '#### Среди прочих подходов для анализа структуры ____________ (**финансовый, сектор**) используется теория графов, позволяющая отразить взаимодействие между участниками рынка.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового сектора',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового шока', 
                          title = '#### Борьба с пандемией ставит экономику под тройной удар: шоков предложения, спроса и ____________ (**финансовый, шок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового шока',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового', 
                          title = '#### При ухудшении ____________ (**финансовый**) состояния банковского сектора снижение экономической активности запускает кредитное сжатие.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые обязательства', 
                          title = '#### Чтобы выполнить ____________ (**финансовый, обязательство**), государство все чаще стало обращаться к эмиссии денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые обязательства',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых средств', 
                          title = '#### Банки получили приток ____________ (**финансовый, средство**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых средств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых показателей', 
                          title = '#### Часто для выявления привлекательных компаний в рамках одной отрасли ____________ (**финансовый, показатель**) не достаточно.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых показателей',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой отчетности', 
                          title = '#### Существуют проблемы диагностирования кредитного и инвестиционного рисков по данным стандартной ____________ (**финансовый, отчетность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой отчетности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый', 
                          title = '#### ____________ (**финансовый**) сектор оказался способен довольно успешно адаптироваться к значительному внешнему давлению.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых', 
                          title = '#### У людей есть много представлений – и заблуждений – о ____________ (**финансовый**) рынках.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые', 
                          title = '#### Предлагаемые клиентам через диалоговых ботов ____________ (**финансовый**) услуги могут содержать неуместные советы и предложения неподходящего продукта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой сфере', 
                          title = '#### Применение искусственного интеллекта в ____________ (**финансовый, сфера**) требует тщательного человеческого контроля.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой сфере',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый цикл', 
                          title = '#### Денежно-кредитная политика влияет на ____________ (**финансовый, цикл**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый цикл',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового', 
                          title = '#### Немаловажным фактором, повлиявшим на динамику числа участников ____________ (**финансовый**) рынка , является ужесточение регулятивных и надзорных мер со стороны Банка России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системе', 
                          title = '#### Развитие оффшорных операций, снижение регулирующей роли государства увеличили возможности проведения чисто спекулятивных действий в мировой ____________ (**финансовый, система**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой грамотности', 
                          title = '#### Сохранение инфляции вблизи целевого уровня, улучшение коммуникации с рынком и повышение уровня ____________ (**финансовый, грамотность**) составляют необходимые элементы борьбы с повышенными инфляционными ожиданиями в стране.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой грамотности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых ресурсов', 
                          title = '#### Одним из инструментов перераспределения ____________ (**финансовый, ресурс**) являются межбюджетные трансферты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых ресурсов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в финансовом отношении', 
                          title = '#### Домохозяйство, стесненное ____________ (**в, финансовый, отношение**), может сильно увеличивать траты при любом дополнительном доходе, в то время как домохозяйства, имеющие доступ к сбережениям или кредитам, с большей вероятностью будут откладывать дополнительный доход или использовать его для погашения долга.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в финансовом отношении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой устойчивости', 
                          title = '#### Сейчас для развивающихся экономик наступил момент заняться повышением ____________ (**финансовый, устойчивость**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой устойчивости',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовом секторе', 
                          title = '#### Новая реальность потребует еще одной волны изменения бизнес-моделей в ____________ (**финансовый, сектор**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовом секторе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых рынках', 
                          title = '#### Причинами роста экономической неопределенности могут быть экономические события, например паника на ____________ (**финансовый, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый шок', 
                          title = '#### В ответ на негативный глобальный ____________ (**финансовый, шок**) страны с более прочными институтами ослабляют денежно-кредитную политику и не истощают валютные резервы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый шок',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых рынках', 
                          title = '#### Условия на мировых ____________ (**финансовый, рынок**) ужесточаются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых рынках', 
                          title = '#### Глобальная ориентация инвесторов на устойчивое развитие и устойчивое инвестирование становится основной силой на всех мировых ____________ (**финансовый, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых ресурсов', 
                          title = '#### Формы использования ____________ (**финансовый, ресурс**) субъектов хозяйствования в настоящее время в меньшей степени регламентируются государством.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых ресурсов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые активы', 
                          title = '#### Доля взрослого населения, инвестирующего в ____________ (**финансовый, актив**), составляет в США 40%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые активы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системы', 
                          title = '#### Критерием эффективности ____________ (**финансовый, система**) и денежно-кредитной политики должна стать не «успешность» противодействия инфляции, а обеспеченность производственных структур финансовыми ресурсами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовом', 
                          title = '#### Некоторые корпорации более надежны в ____________ (**финансовый**) отношении и обладают меньшей вероятностью дефолта, чем облигации других компаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовом',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые активы', 
                          title = '#### В работах Марковица, по сути, была изложена методология принятия решений в области ннвестирования в ____________ (**финансовый, актив**) и предложен соответствующий научиый инструментарий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые активы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые годы', 
                          title = '#### Правительство представило новые бюджетные правила на ____________ (**финансовый, год**) 2021-2025.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые годы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой стабильности', 
                          title = '#### Переход к режиму свободного плавания валютного курса может представлять опасность для ____________ (**финансовый, стабильность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой стабильности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые ресурсы', 
                          title = '#### Любая компания, которая сможет интегрировать генеративный искусственный интеллект в бизнес-модель,  сможет получить дополнительные ____________ (**финансовый, ресурс**) для развития и масштабирования бизнеса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые ресурсы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых потоков', 
                          title = '#### Центральный банк поделился результатами мониторинга отраслевых ____________ (**финансовый, поток**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых потоков',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового рынка', 
                          title = '#### Построенные модели ____________ (**финансовый, рынок**) являются упрощениями реального рынка.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый', 
                          title = '#### Оставшиеся после этого средства составляют чистых доход организации, направляемый на уплату налогов, относимых на ____________ (**финансовый**) результат деятельности и формирование прибыли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'в финансовом отношении', 
                          title = '#### Преимущество портфельных инвестиций определяется преобладанием в этой стране населения, грамотного ____________ (**в, финансовый, отношение**). В экономически слаборазвитых странах население менее склонно к инвестированию и более склонно к потреблению.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'в финансовом отношении',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых', 
                          title = '#### Отраслевые кодексы поведения и стандарты защищают права потребителей ____________ (**финансовый**) услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых отношений', 
                          title = '#### Специфика финансов домашних хозяйств определена тем, что эта сфера ____________ (**финансовый, отношение**) в наименьшей степени регламентирована государством.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых отношений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового состояния', 
                          title = '#### В настоящее время анализ ____________ (**финансовый, состояние**) предприятия хорошо систематизирован, а его процедуры имеют унифицированный характер и проводятся по единой методике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового состояния',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовым годом', 
                          title = '#### Год, следующий за текущим ____________ (**финансовый, год**), называется очередным финансовым годом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовым годом',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовыми', 
                          title = '#### Многие крупные технологические компании все активнее осваивают кредитование, выдавая своим клиентам займы как напрямую, так и в партнерстве с ____________ (**финансовый**) институтами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовыми',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые активы', 
                          title = '#### Одновременные продажи нескольких инвестиционных фондов могут привести к обвальному падению цен на ____________ (**финансовый, актив**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые активы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой', 
                          title = '#### Может ли измениться финансовое поведение населения под влиянием работы по повышению ____________ (**финансовый**) грамотности?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовым инструментам', 
                          title = '#### В качестве индикаторов, характеризующих денежно-кредитные условия, используются  номинальные и реальные процентные ставки по различным ____________ (**финансовый, инструмент**) (от операций на денежном рынке до банковских кредитов и депозитов);.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовым инструментам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый год', 
                          title = '#### Идет формирование бюджета на очередной ____________ (**финансовый, год**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый год',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовом секторе', 
                          title = '#### В фазе кризиса начавшаяся в ____________ (**финансовый, сектор**) дефляция к концу 2008 г. охватила все развитые экономики и все их рынки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовом секторе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой грамотности', 
                          title = '#### Различия в уровне ____________ (**финансовый, грамотность**), предпринимательских способностях, состоянии здоровья, структуре семьи – все эти факторы влияют на динамику благосостояния человека.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой грамотности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовом', 
                          title = '#### Нелюбимая работа обедняет человека, отбирая его время, даже если делает благополучным в ____________ (**финансовый**) отношении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовом',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового поведения', 
                          title = '#### В сравнении два региона имеют одинаковые динамику и уровень объективных показателей ____________ (**финансовый, поведение**) населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового поведения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые потоки', 
                          title = '#### Исследуются прямые и обратные ____________ (**финансовый, поток**) между регионами и федеральным центром.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые потоки',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой финансовой системе', 
                          title = '#### Роль доллара в ____________ (**мировой, финансовый, система**) превосходит роль американской экономики в мировом производстве и торговле.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой финансовой системе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовую поддержку', 
                          title = '#### Глобальная сеть финансовой безопасности – это международная система финансовых механизмов и институтов, которые оказывают ____________ (**финансовый, поддержка**) странам в случае финансового кризиса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовую поддержку',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой стабильности', 
                          title = '#### Риски для ____________ (**финансовый, стабильность**) снова оказались в центре внимания регуляторов из-за событий, связанных с кризисными явлениями в банковском секторе развитых стран.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой стабильности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'при принятии финансовых решений', 
                          title = '#### Миллионы людей ____________ (**при, принятие, финансовый, решение**) пользуются советами, которые предлагаются в популярных книгах и шоу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'при принятии финансовых решений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые', 
                          title = '#### ____________ (**финансовый**) временные ряды представляют собой объемные массивы информации по котировкам и объемам торгов акций, валют и других биржевых и внебиржевых инструментов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового состояния', 
                          title = '#### Усугубление дефляционных процессов может нести в себе риски ухудшения ____________ (**финансовый, состояние**) предприятий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового состояния',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой стабильности', 
                          title = '#### Усилия центральных банков сконцентрированы на обеспечении ____________ (**финансовый, стабильность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой стабильности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового', 
                          title = '#### Положительные значения показателя соответствуют расширительной фазе глобального ____________ (**финансовый**) цикла, тогда как отрицательные значения – фазе сжатия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых ресурсов', 
                          title = '#### Проект требует значительного объема ____________ (**финансовый, ресурс**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых ресурсов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовым инструментам', 
                          title = '#### К биржевым производным ____________ (**финансовый, инструмент**) относятся фьючерсы и ​​​​​​​опционы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовым инструментам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых активов', 
                          title = '#### Какие количественные показатели характеризуют высокий уровень инвестиционной привлекательности ____________ (**финансовый, актив**) в той или иной стране?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых активов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовом рынке', 
                          title = '#### В странах с развитой экономикой главными игроками являются инвестиционные фонды, привлекающие деньги на ____________ (**финансовый, рынок**) и предоставляющие долгосрочные инвестиции частному сектору.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовом рынке',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового сектора', 
                          title = '#### Цели Банка России состоят в минимизации издержек и рисков для ____________ (**финансовый, сектор**) с точки зрения поддержания финансовой стабильности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового сектора',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовое поведение', 
                          title = '#### Люди, которые начинают пользоваться электронными платежами, могут влиять на ____________ (**финансовый, поведение**) окружающих.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовое поведение',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых обязательств', 
                          title = '#### В данном случае активы окупаются в течение пяти лет, и амортизация является источником покрытия ____________ (**финансовый, обязательство**) перед инвесторами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых обязательств',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых институтов', 
                          title = '#### Большинство мировых ____________ (**финансовый, институт**) ждут увеличения расходов в связи с санкциями на 10-25%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых институтов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой грамотности', 
                          title = '#### Многие региональные банки проводят семинары и мастер-классы по повышению ____________ (**финансовый, грамотность**) индивидуальных предпринимателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой грамотности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового сектора', 
                          title = '#### При сравнении стран, особенно по качеству развития ____________ (**финансовый, сектор**) экономики, необходимо учитывать сложившуюся правовую среду.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового сектора',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых инструментов', 
                          title = '#### Существуют разные методы количественной оценки риска с учетом классификации рисков отдельных ____________ (**финансовый, инструмент**) инвестирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых инструментов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых', 
                          title = '#### Секьюритизация представляет собой процесс, при котором некоторые виды активов объединяются в пул, с тем чтобы их можно было переоформить в виде процентных ценных бумаг (производных ____________ (**финансовый**) инструментов).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых рынках', 
                          title = '#### На самом деле, проблема чрезмерного использования кредитных средств существует и на ____________ (**финансовый, рынок**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых рынках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых временных рядов', 
                          title = '#### Прогнозирование ____________ (**финансовый, временный, ряд**) всегда представляло особый интерес для инвесторов-практиков.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых временных рядов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые ресурсы', 
                          title = '#### Старение населения влияет на банковские риски посредством изменения спроса на ____________ (**финансовый, ресурс**) и их предложение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые ресурсы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый', 
                          title = '#### Во многих развивающихся странах ____________ (**финансовый**) сектор частично долларизован – компании и банки занимают и кредитуют в иностранной валюте.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового', 
                          title = '#### Как правило, активным управлением портфелем занимаются крупные профессиональные участники ____________ (**финансовый**) рынка: банки, инвестиционные фонды и др., обладающие большими финансовыми возможностями.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых решений', 
                          title = '#### Очень часто люди, далекие от фондового рынка, используют для принятия ____________ (**финансовый, решение**) информацию, основанную на котировках ценных бумаг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых решений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовую поддержку', 
                          title = '#### Стихийные бедствия вынуждают правительства наращивать госрасходы – на медицинскую помощь, ____________ (**финансовый, поддержка**) населения, восстановление инфраструктуры.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовую поддержку',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системы', 
                          title = '#### Криптовалюты могут использоваться для отмывания денег, финансирования терроризма и ухода от налогов, что создает риски для ____________ (**финансовый, система**) страны и ее отношений с зарубежными странами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой', 
                          title = '#### Дисконтирование широко применяется в ____________ (**финансовый**) сфере, например, при инвестировании.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового рынка', 
                          title = '#### За прошедшее десятилетие участники ____________ (**финансовый, рынок**) привыкли к очень низким ставкам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового рынка',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового сектора', 
                          title = '#### Группа инновационных компаний работает в области информационных технологий для ____________ (**финансовый, сектор**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового сектора',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовый результат', 
                          title = '#### Открытие доступа к иностранному рынку должно обеспечить устойчивый ____________ (**финансовый, результат**) от инвестирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовый результат',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовое', 
                          title = '#### Стремление поддерживать уровень потребления не ниже, чем у знакомых, способно провоцировать довольно опасное ____________ (**финансовый**) поведение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовое',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой стабильности', 
                          title = '#### Высокие ставки усиливают риск потери ____________ (**финансовый, стабильность**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой стабильности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовую', 
                          title = '#### Механизмы влияния сырьевого цикла на ____________ (**финансовый**) стабильность в странах – сырьевых экспортерах обсуждаются в том числе и в работах Банка России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовую',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых решений', 
                          title = '#### Высокий доход позволяет людям быть менее внимательными при принятии ____________ (**финансовый, решение**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых решений',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системе', 
                          title = '#### Деятельность инвестиционных фондов является важной частью процессов, происходящих в мировой ____________ (**финансовый, система**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системе',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового состояния', 
                          title = '#### Для анализа ____________ (**финансовый, состояние**) предприятия используется множество финансовых показателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового состояния',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансового года', 
                          title = '#### В документах отражен остаток средств на начало текущего ____________ (**финансовый, год**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансового года',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовых институтов', 
                          title = '#### Необходимо ввести ограничения на владение криптоактивами для ____________ (**финансовый, институт**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовых институтов',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой отчетности', 
                          title = '#### Метод расчета по данным ____________ (**финансовый, отчетность**) и наблюдения за банковскими условиями привлечения финансирования наименее предпочтителен при прогнозе ставок доходности на развивающихся рынках.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой отчетности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой системы', 
                          title = '#### Финансовые кризисы показали необходимость перестройки мировой ____________ (**финансовый, система**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой системы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовые ресурсы', 
                          title = '#### Конкуренция между заемщиками за ____________ (**финансовый, ресурс**) вызовет рост реальной процентной ставки до тех пор, пока она не достигнет уровня 6%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовые ресурсы',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'финансовой', 
                          title = '#### Банк международных расчетов (BIS) представил свое видение будущей денежной и ____________ (**финансовый**) системы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'финансовой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

