```{r}
checkdown::check_question(answer = 'шока цен', 
                          title = '#### Производительность в России была низкой и снижалась еще до двойного шока 2014 года – ____________ (**шок, цена**) на нефть и санкционного шока.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'шока цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### В отличие от реакции спроса на деньги при изменении ____________ (**уровень, цена**) рост величины спроса на деньги не пропорционален увеличению реальных доходов',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### В отдаленных регионах средний ____________ (**уровень, цена**) пониженный.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цена', 
                          title = '#### Реальная рыночная ____________ (**цена**) окажется ниже равновесной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценам', 
                          title = '#### Предположим, что мы предлагаем снять квоту на импорт автомобилей в США. Потребители США, были бы рады более низким ____________ (**цена**) и большему выбору машин, но некоторые работники автомобильной промышленности потеряли бы свои места.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Важно подчеркнуть, что полученные в ходе нашего анализа результаты представляют собой краткосрочные последствия макроэкономической политики при предположении, что общий ____________ (**уровень, цена**) остается неизменным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цене', 
                          title = '#### Определите объем продаж, цену и прибыль монополиста при продаже товара по единой ____________ (**цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Эти меры способствуют повышению ____________ (**уровень, цена**) в условиях спада производства и сокращения совокупного спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'относительных цен', 
                          title = '#### На изменения пространственной структуры существенно влияли изменения ____________ (**относительная, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'относительных цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'неизменных ценах', 
                          title = '#### МВФ полагает, что при ____________ (**неизменная, цена**) на нефть будет падать долгосрочный темп роста российской экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'неизменных ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### При снижении уровня ____________ (**цена**) фактический выпуск продукции увеличивается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'контроль над ценами', 
                          title = '#### В период войн и других кризисов правительства часто вводят ____________ (**контроль, над, цена**) на жизненно важные товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'контроль над ценами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценах', 
                          title = '#### ВВП взят в рыночных ____________ (**цена**), включающих чистые налоги на продукты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### При повышении ____________ (**цена**) на 5–10% на весь комплексный товар, а не на его часть, стоит ожидать более существенной реакции потребителей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Изменения совокупного спроса не влияют на величину равновесного выпуска, а воздействуют только на изменение равновесного ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста цен', 
                          title = '#### Не всякий рост цен и не всякое обесценение денег вызывают инфляцию. Инфляцию характеризуют такие темпы ____________ (**рост, цен**), которые превышают темпы роста доходов в экономике за определенный период (обычно год).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияние на цены', 
                          title = '#### Инфляционная компонента валютного канала характеризует то, как изменение курса валюты отражается на стоимости экспортных и импортных товаров (непосредственное ____________ (**влияние, на, цены**)).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияние на цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночную цену', 
                          title = '#### При совершенной конкуренции покупате­ли и продавцы должны принимать ____________ (**рыночный, цена**) как нечто данное.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночную цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительских цен', 
                          title = '#### И индекс ____________ (**потребительская, цена**), и индекс цен производителей статистически подсчитываются как индексы с весами (объемами) базового года.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительских цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Когда уровень ____________ (**цена**) возрастает, рабочие еще не знают об этом. Все, что они могут видеть, это то, что номинальная заработная плата, которая им предлагается, возросла.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низким ценам', 
                          title = '#### Рынок ценных бумаг оказывается в равновесии в результате действий трейдеров, которые могут покупать ценные бумаги у банков по ____________ (**низкая, цена**) в периоды «горячих продаж» (fire sale).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низким ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Кривая предложения денег сдвигается влево, ____________ (**уровень, цена**) падает, расходы увеличиваются, кривая совокупного спроса сдвигается вправо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внутренних цен', 
                          title = '#### Вместе с тем на ряд сырьевых товаров и, прежде всего, на энергоносители в 1992 г. были введены экспортные пошлины. Цель этой меры — сдерживание ____________ (**внутренние, цены**) на энергию и сырье ниже мировых для постепенной адаптации отечественных предприятий к открытию национальной экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутренних цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'относительных ценах', 
                          title = '#### В 1490—1500 гг. соответствующий показатель в Китае составлял 550—600 долл. в ____________ (**относительная, цена**) 1980 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'относительных ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Предположим, что капитал является абсолютно мобильным, уровень ____________ (**цена**) фиксирован, а обменный курс плавает.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену товара', 
                          title = '#### Косвенные налоги частично или полностью переносятся на ____________ (**цена, товар**) или услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### При движении вдоль кривой АД более низкие ____________ (**цена**) увеличивают реальную стоимость денежной массы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Потребитель сокращает покупки картофеля и начинает покупать больше мяса. Это вызывает рост ____________ (**цен**) на мясо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночную цену', 
                          title = '#### Фирма реализует на рынке столь незначительную долю в общем объеме продукции, что это не оказывает никакого влияния на ____________ (**рыночный, цена**) товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночную цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокой цене', 
                          title = '#### Производители хотели бы производить больше при более ____________ (**высокий, цена**), но потребители теперь покупают меньше.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокой цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночная цена', 
                          title = '#### Предположим, ____________ (**рыночный, цена**) равна всего 81 долл.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночная цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'текущих ценах', 
                          title = '#### Сальвадор – одна из самых бедных стран Латинской Америки: по ВВП на душу населения она находится на 28-м месте, этот показатель в стране в 2020 г. составлял чуть менее $3800 (в ____________ (**текущая, цена**)).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'текущих ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'единой цены', 
                          title = '#### Если известно, что 1 долл. США равен 100 иенам, а 1 фунт стерлингов — 200 иенам, то в соответствии с законом ____________ (**единый, цена**) один фунт стерлингов будет равен двум долларам США.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'единой цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Повышение ____________ (**уровень, цена**) приводит к смешению графика совокупных расходов вниз.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировые цены', 
                          title = '#### Падение мирового спроса породило «избыток нефти» и серьезно ослабило способность ОПЕК контролировать ____________ (**мировая, цена**) на нефть.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировые цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста цен', 
                          title = '#### Снижение темпов ____________ (**рост, цен**) отнюдь не означает увеличение реальных доходов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Существует высокая вероятность значительных изменений ____________ (**цены**) на финансовые активы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению цены', 
                          title = '#### Когда экономисты говорят об эластичном спросе, они не имеют в виду, что потребители абсолютно чувствительны к ____________ (**изменение, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровню цен', 
                          title = '#### Темп инфляции равен отношению разницы уровня цен (например, дефлятора ВВП) текущего и предыдущего года к ____________ (**уровень, цена**) предыдущего года, выраженному в процентах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровню цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### Взаимозависимые продавец и покупатель исключительно связаны в бизнесе и в своих взаимоотношениях, что серьезно может повлиять на ____________ (**цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Рост уровня ____________ (**цена**) обгонит рост их денежных доходов участников профсоюза.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличения цены', 
                          title = '#### Предположим, что до ____________ (**увеличение, цена**) на нефть кривые совокупного спроса и совокупного предложения представлены кривыми AD и AS.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличения цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесной цены', 
                          title = '#### Увеличение спроса приводит к повышению и ____________ (**равновесный, цена**), и равновесного количества товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесной цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Если вы имеете облигацию номиналом в 1000 долл., то при повышении ____________ (**уровень, цена**) в 2 раза реальное богатство, представленное этой облигацией, уменьшается в 2 раза.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'гибкости цен', 
                          title = '#### Большинство макроэкономистов считает, что предположение о ____________ (**гибкость, цена**) является вполне оправданным для исследования долгосрочных явлений, например, таких как экономический рост.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'гибкости цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### При данном уровне ВВП рост ожидаемого ____________ (**уровень, цена**) приводит к повышению заработной платы, что ведет к росту цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цене', 
                          title = '#### Рост цен акций вызывают спекулятивные пузыри, когда инвесторы покупают акции по высокой ____________ (**цена**), надеясь перепродать их по более высокой цене в будущем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесных цен', 
                          title = '#### Изменения положения кривых спроса и предложения являются причиной наблюдаемых сезонных изменений ____________ (**равновесная, цена**) и количества товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесных цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменения цены', 
                          title = '#### Структура потребления меняется в результате ____________ (**изменение, цена**) одного из товаров, входящих в потребительский выбор.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменения цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне цен', 
                          title = '#### Фирмы будут сокращать выпуск при каждом ____________ (**уровень, цена**), что графически отображается сдвигом влево кривой краткосрочного совокупного предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### При дополнительных предпосылках, согласно которым ожидаемый ____________ (**уровень, цена**) равен фактическому, равновесие на рынке труда определяет уровень безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Оценки совокупного предложения в моделях обычно основываются на уравнении кривой Филлипса, связывающего изменения безработицы с изменением ____________ (**уровень, цена**) и заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### Фирма принимает рыночную ____________ (**цена**) как заданную.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Если уровень ____________ (**цена**) выше, чем ожидалось, производители ошибочно считают, что относительные цены товаров, которые они поставляют на рынок, выросли.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низким ценам', 
                          title = '#### Если ожидается рост цен, люди стремятся купить как можно больше товаров по относительно ____________ (**низкая, цена**) в настоящем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низким ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительских цен', 
                          title = '#### Реальные доходы зависят от соотношения темпов роста располагаемых доходов и индекса ____________ (**потребительский, цена**) за определенный период.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительских цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной ценой', 
                          title = '#### Излишек потребителя, который выражает общую выгоду всех потребителей, — это заштрихованная область между кривой спроса и ____________ (**рыночный, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной ценой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Федеральный бюджет должен быть защищен от таких внешних воздействий, как изменение мировых ____________ (**цена**) на экспортные товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'относительных цен', 
                          title = '#### Исследователи отмечают, что стандартная модель «затраты-выпуск» не учитывает подстройку экономики в ответ на шоки, например, через изменение ____________ (**относительная, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'относительных цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ниже цена', 
                          title = '#### Потребитель готов покупать тем большее его количество, чем ____________ (**низкий, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ниже цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'форвардными ценами', 
                          title = '#### Рассмотрим теперь связь между ____________ (**форвардный, цена**) и ценами спот для акций S&P.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'форвардными ценами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту цены', 
                          title = '#### Данный вид ценных бумаг имеет тенденцию к ____________ (**рост, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Эластичность показывает, на сколько процентов изменится спрос при увеличении ____________ (**цена**) товара на 1%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокие цены', 
                          title = '#### Была неопределенность относительно будущих цен на бензин: более ____________ (**высокие, цены**) на горючее снизили бы спрос на тяжелые транспортные средства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокие цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены товара', 
                          title = '#### Изменение объема спроса имеет место при изменении ____________ (**цена, товар**) и неизменном характере зависимости объема спроса от цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Явная способность мировой экономики покупать нефть по существующей высокой ____________ (**цен**)е не оставляют надежды на снижение цены ниже 30 долл. за баррель в обозримой перспективе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночным ценам', 
                          title = '#### Паи торгуются на фондовой бирже по ____________ (**рыночный, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночным ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Ожидаемый ____________ (**уровень, цена**) будет повышаться.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Рост совокупного спроса приведет к повышению ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем цен', 
                          title = '#### Каждая кривая представляет собой взаимосвязь между общим ____________ (**уровень, цена**) Р, отложенным по вертикальной оси, и объемом производства Y, отложенным по горизонтальной оси.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### При анализе спроса нас часто интересует не его абсолютный объем, а его изменения в ответ на изменение ____________ (**цена**) товара или какого-то другого параметра, определяющего объем спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену товара', 
                          title = '#### Налог на объем выпуска не влияет на рыночную ____________ (**цена, товар**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росте цены', 
                          title = '#### Закон предложения – объем предложения товара увеличивается при ____________ (**рост, цена**) и уменьшается при ее снижении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росте цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Закон единой ____________ (**цена**) предполагает, что цены на торгуемые товары, выраженные в одной валюте, должны быть одинаковыми во всех странах с поправкой на транзакционные издержки и стоимость транспортировки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровню цен', 
                          title = '#### Более высокая номинальная заработная плата ведет к более высокому ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровню цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### На совершенно конкурентном рынке действует достаточно много продавцов и покупателей товара, и поэтому ни один продавец или покупатель в отдельности не может повлиять на ____________ (**цена**) товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цена', 
                          title = '#### У каждого продавца объем предложения будет меняться в зависимости от цены: чем выше ____________ (**цена**), тем, при прочих равных условиях, выше размер предложения на рынке данного товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокой цены', 
                          title = '#### Ожидания более ____________ (**высокий, цена**) акции в будущем приводят к росту цены акции уже сегодня.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокой цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменение цены', 
                          title = '#### Между эластичным и неэластичным спросом находится пограничная ситуация, когда процентное ____________ (**изменение, цена**) и сопровождающее его процентное изменение спроса равны между собой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### При повышении ____________ (**цен**) на нефть, стоимость топлива для автомобилей также возрастает, что может привести к увеличению затрат на транспортировку товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Более высокий ____________ (**уровень, цена**) повышает спрос на деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Парадокс Гиффена описывает увеличение величины спроса на товар при росте ____________ (**цена**) на него.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'относительных цен', 
                          title = '#### Торговый баланс нормальным образом реагирует на изменение ____________ (**относительная, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'относительных цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной ценой', 
                          title = '#### Дано графическое изображение зависимости по цене между ____________ (**рыночный, цена**) блага и количеством этого блага, которое готовы продать производители в данный момент времени.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной ценой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценам', 
                          title = '#### Преимущество для потребителей состоит в том, что фирма предоставляет услуги по более низким ____________ (**цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению цены', 
                          title = '#### Когда мы говорим о долгосрочном периоде, мы подразумеваем, что у потребителей или производителей достаточно времени, чтобы полностью приспособиться к ____________ (**изменение, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### При повышении ____________ (**уровень, цена**) в 2,5 раза покупательная способность денег снизится в 2,5 раза.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рост цен', 
                          title = '#### Еще в 2007 г. наблюдался резкий ____________ (**рост, цен**) на продовольствие, дополненный ростом цен на топливо.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Если два ресурса являются исключительно дополнителями, то в случае изменения ____________ (**цена**) одного из них наблюдается только эффект выпуска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'постоянных ценах', 
                          title = '#### Определяем значения амортизации в ____________ (**постоянная, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'постоянных ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### В 60-е годы началось постепенное увеличение ____________ (**цена**). Общий индекс цен на сырьевые товары в 1970 г. по сравнению с 1960 г. поднялся на 9,1%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падением цен', 
                          title = '#### В периоды кризисов, которые сопровождались также ____________ (**падение, цен**) на нефть, происходило падение внутреннего спроса, причем в 2015 – 2016 гг. оно было глубже, чем общее падение ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падением цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировые цены', 
                          title = '#### ОПЕК является международным картелем стран-производителей нефти, который в течение десятилетия успешно повышал ____________ (**мировая, цена**) на нефть до уровня, сильно превышающего тот, на котором они находились бы без него.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировые цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Олигополисты понимают, что их поведение оказывает ощутимое влияние на ____________ (**цены**), которые могут получить за свою продукцию соперники.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росте цены', 
                          title = '#### Обычно при ____________ (**рост, цена**) на товар покупатели ограничивают его приобретение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росте цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Номинальные зарплаты падают вместе с занятостью, но снижение номинальных зарплат не препятствует росту зарплат в реальном выражении, поскольку падение уровня ____________ (**цена**) намного превосходит падение уровня оплаты труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цене', 
                          title = '#### Магазины установят свою надбавку к ____________ (**цена**) для последующей продажи товара потребителям.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Общий ____________ (**уровень, цена**) остается неизменным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Таким образом, снижение ____________ (**уровень, цена**) не обязательно вызывает эффект дохода.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Приведены данные увеличения количества денег и инфляции по индексу потребительских ____________ (**цена**)на февраль 2003 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем цен', 
                          title = '#### Совокупный спрос - это зависимость между количеством произведенной продукции, на которое предъявляется покупательский спрос, и общим ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Сокращение обьема кредитов на приобретение жилья привело к падению ____________ (**цен**) на жилье.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экспортных цен', 
                          title = '#### Указан уровень ____________ (**экспортная, цена**) на продукцию (в долларах).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экспортных цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночным ценам', 
                          title = '#### Значительная часть продукции (картофеля) реализуется конечным потребителям по ____________ (**рыночная, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночным ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Аналогично профсоюзы могут также повысить спрос на труд путем поддержания общественных акций по снижению ____________ (**цен**) на дополняющие ресурсы. Например, профсоюзы в отраслях, где используются большие количества энергии, могут активно выступать против увеличения коммунального налога на газ и электроэнергию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Неожиданные изменения совокупного спроса приводят к изменению уровня ____________ (**цена**), в результате чего фирмы в краткосрочном периоде изменяют объемы производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижении цены', 
                          title = '#### При ____________ (**снижение, цена**) на 2% и росте дохода на 2% спрос увеличится.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижении цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Фактический верхний предел ____________ (**цена**) определяется не спросом и производственными возможностями, а риском новой конкуренции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Кривая краткосрочного совокупного предложения SRAS — это кривая, показывающая величину совокупного выпуска, которую все производители (фирмы) в экономике намерены произвести при каждом возможном уровне ____________ (**цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цене', 
                          title = '#### Товар продается по единой ____________ (**цена**). Любые формы ценовой дискриминации запрещены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировых цен', 
                          title = '#### Сложное положение нефтедобывающих компаний характеризовалось одновременными шоками падения ____________ (**мировая, цена**) на энергоресурсы и добровольными ограничениями в рамках сделки ОПЕК+.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировых цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### К внешним шокам относятся санкции (в первую очередь финансовые и технологические), а также динамика ____________ (**цена**) на нефть и другие российские экспортируемые товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышении цены', 
                          title = '#### Спрос на товар может оказаться весьма эластичным при ____________ (**повышение, цена**), но почти неэластичным при ее снижении (или наоборот).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышении цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низких цен', 
                          title = '#### Все три автомобильные компании будут продавать больше машин, но их прибыли сократятся из-за более ____________ (**низкая, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низких цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста цен', 
                          title = '#### В центре внимания общественности и политиков два основных показателя состоя­ния экономики — темпы инфляции и уровень безработицы. Некоторые журналис­ты, суммируя показатели темпов ____________ (**рост, цен**) и уровня безработицы, получают так называемый индекс бедствия — он служит показателем «здоровья» эко­номики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### При возникновении отраслевого шока изменение относительных ____________ (**цена**) может достаточно сильно влиять на объемы валовой добавленной стоимости и выпуска, а также на динамику импорта и инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Импортирт серебра по высоким ____________ (**цен**)ам мог бы привести к росту цен на внутреннем рынке. Когда цена на серебро во всем мире упала, оно хлынуло в Китай и подстегнуло развитие экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменением цены', 
                          title = '#### Деятельность субъектов рынка в международной сфере сопряжена с многочисленными рисками. В их числе риски, связанные, например, с ____________ (**изменение, цена**) товара после заключения контракта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменением цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низкой ценой', 
                          title = '#### Каршеринг-компании стараются выделиться более удобным сервисом, более ____________ (**низкий, цена**), новыми моделями автомобилей или бонусами для своих клиентов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низкой ценой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### больше, чем $200 000 за дом, который для меня на самом деле стоит $250 000. Продавец готов расстаться с домом за любую ____________ (**цена**) выше $180 000, но хотел бы получить самую высокую цену, которую он сможет. Если я единственный поку- патель дома, как я могу заставить продавца думать, что я скорее уйду, чем запла- чу больше $200 000?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Постоянное снижение уровня ____________ (**цена**) – дефляция – обходится очень дорого. Это повышает актуальность мягкой монетарной политики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низкая цена', 
                          title = '#### Вашему конкуренту выгодна более ____________ (**низкий, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низкая цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'постоянных ценах', 
                          title = '#### Совокупное богатство за период 2000-2017 гг. выросло на 73% до 1306000 млрд руб. (в ____________ (**постоянная, цена**) 2017 г.).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'постоянных ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Уровень инфляции, который представляет собой темпы роста ____________ (**уровень, цена**), тесно связан с темпами роста номинального предложения денег.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Налог на какой-либо товар может влиять на ____________ (**цены**) и объем продажи других товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоких цен', 
                          title = '#### Экспорт из Кореи заметно улучшился не только количественно, но и качественно. Установление более ____________ (**высокие, цены**) на экспортируемые товары стало возможным благодаря их более высокой добавленной стоимости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоких цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Эффект замещения, субституции — изменение структуры потребления в результате изменения ____________ (**цена**) одного из товаров, входящих в потребительский набор.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокими ценами', 
                          title = '#### Президент пообещал, что страна справится с ____________ (**высокие, цены**) на бензин.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокими ценами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту цены', 
                          title = '#### При прочих равных условиях такие изменения способны привести к ____________ (**рост, цена**) облигаций правительства, одновременно снижая дисконтные процентные ставки по этим бумагам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росте цен', 
                          title = '#### Если известно, что семья тратила на питание 10 000 р., а затем стала тратить 15 000 р., это не говорит о том, что резко улучшилось количество или качество потребляемых продуктов. Возможно, все дело в полуторакратном ____________ (**рост, цен**) на продовольствие.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росте цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### Фирма принимает рыночную ____________ (**цена**) товара как данность, выбирая объем выпуска с учетом допущения о том, что этот выбор не окажет влияния на цену.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияет на цены', 
                          title = '#### Деловая активность ____________ (**повлиять, на, цену**) акций, но и цены акций влияют на деловую активность, воздействуя на потребление и инвестиции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияет на цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменение цены', 
                          title = '#### Дуговая эластичность — показатель средней реакции спроса на ____________ (**изменение, цена**) товара, выраженной кривой спроса на некотором отрезке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### ФРС хочет сохранить стабильный ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низкую цену', 
                          title = '#### Ни одна фирма не будет устанавливать более ____________ (**низкий, цена**), потому что она может продать все, что пожелает, по рыночной цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низкую цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесные цену', 
                          title = '#### Найдите ____________ (**равновесный, цена**) и объем продаж, а также предельные издержки каждой фирмы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесные цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Посторонние инвесторы могут истолковать повышение размеров денежных дивидендов, выплачиваемых компанией, как положительный знак, и вследствие этого прирост дивиденда может привести к повышению ____________ (**цена**) акций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цене', 
                          title = '#### Падающая эффективность сегментов внешнего рынка выражается в том, что каждая дополнительная единица экспорта реализуется по все более низкой ____________ (**цена**), а каждая дополнительная единица импорта приобретается по все более высокой цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'жесткость цен', 
                          title = '#### Кейнсианцы согласны, что ____________ (**жесткость, цена**) на рынке совершенной конкуренции не возникнет, но указывают, что совершенная конкуренция существует в относительно небольшой части экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'жесткость цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Рост ____________ (**уровень, цена**) провоцирует повышение заработной платы, а рост заработной платы служит основой для дальнейшего повышения уровня цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем цен', 
                          title = '#### Определяется прямая зависимость между размером денежной массы и ____________ (**уровень, цена**). Если в заданных условиях денежная масса увеличится, то произойдет обесценение денежной единицы и уровень цен повысится.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличении цены', 
                          title = '#### Эффект дохода при ____________ (**увеличение, цена**) на соль очень незначителен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличении цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценах', 
                          title = '#### Объем производства ВРП и налоговые поступления на душу населения измеряются в сопоставимых ____________ (**цены**) 2002 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменения цены', 
                          title = '#### Влияние ____________ (**изменение, цена**) на бюджетную линию увеличится.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменения цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### В данный момент времени работница знает, что текущая ставка заработной платы равна 12 долларов в час, но она не знает всех ____________ (**цена**) в экономике и, следовательно, не знает общего уровня цен, а поэтому не знает реальную заработную плату.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### На сколько процентов будет отличаться равновесный ____________ (**уровень, цена**) от первоначального уровня?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменение цены', 
                          title = '#### Точно так же процентное ____________ (**изменение, цена**) здесь незначительно, потому что исходная цена, на основе которой это изменение рассчитывается, велика.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне цен', 
                          title = '#### Избыток реального производства будет снижать уровень цен. Равновесие происходит при ____________ (**уровень, цена**), при котором кривые А5 и АР пересекаются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению цен', 
                          title = '#### Государства адаптируются к ____________ (**падение, цен**) на нефть.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Сдвиг кривой LM вызывается изменением ____________ (**уровень, цена**), что приводит к изменению величины реального предложения денег и поэтому воздействует на равновесие на рынке активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'разным ценам', 
                          title = '#### Кривая спроса – кривая, показывающая, какое количество экономического блага готовы приобрести покупатели по ____________ (**разный, цена**) в данный момент времени.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'разным ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоким ценам', 
                          title = '#### Серебряный юань утекал из Китая в то время, как китайское правительство должно было постоянно импортировать серебро по ____________ (**высокие, цены**) для удовлетворения спроса на деньги внутри страны. В итоге это могло бы привести к росту цен на внутреннем рынке. Когда цена на серебро во всем мире упала, оно хлынуло в Китай и подстегнуло развитие экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоким ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Ожидание изменения уровня ____________ (**цена**) — если люди ожидают роста уровня цен, то они увеличивают спрос на товары и услуги, стремясь купить их как можно больше по относительно низким ценам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменения цены', 
                          title = '#### Мы также будем использовать эластичность в среднесрочном перноде т.е. эластичность, которая характеризует изменение спроса и предложения через три — шесть лет после ____________ (**изменение, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменения цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'текущей ценой', 
                          title = '#### Будущая доходность актива положительно коррелирует с ____________ (**текущий, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'текущей ценой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменению цены', 
                          title = '#### Торговля товарами приводит к ____________ (**изменение, цена**) факторов производства, что вызывает их межстрановое перемещение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменению цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Не все ____________ (**цена**)ы приспосабливаются к своим равновесным значениям и все же средний уровень цен в краткосрочном периоде растет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низким ценам', 
                          title = '#### Фирма получит требуемый объем продаж в значительной степени за счет двух своих конкурентов, потому что будет продавать по более ____________ (**низкая, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низким ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменения цены', 
                          title = '#### Даже для товара, который составляет большую долю бюджета, эффект дохода от ____________ (**изменение, цена**) иногда будет небольшим.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменения цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Фирмы пересматривают цены на свою продукцию из-за изменения общего ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Объем выпуска в краткосрочном периоде увеличивается до Т, а ____________ (**уровень, цена**) снижается до Р.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночная цена', 
                          title = '#### Известнатекущая ____________ (**рыночный, цена**) активов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночная цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рост цен', 
                          title = '#### Одним из наиболее серьезных шоков предложения после Второй мировой войны был резкий ____________ (**рост, цена**) на нефть и другие виды топливно-энергетических ресурсов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### В прошлом году общий ____________ (**уровень, цена**) вырос на 4,4%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Произошло падение ____________ (**цена**)ы на взаимодополняющий товар.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Потребители отвечают на рост ____________ (**цен**) большей экономией.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальные цены', 
                          title = '#### Негативное влияние обоих шоков на ____________ (**реальная, цена**) на импортные материалы должно быть более явным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальные цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### ____________ (**цен**)тробанки предпринимают усилия по повышению темпов роста цен в своих экономиках.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'динамика цен', 
                          title = '#### ____________ (**динамика, цена**) на нефть не вносит значимых изменений в динамику экспорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'динамика цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению цены', 
                          title = '#### Люди и организации пытаются получить больше денег путем продажи облигаций. Поэтому предложение облигаций возрастает, что приводит к ____________ (**снижение, цена**) на них и повышению процентной ставки.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Объемы сделок между экономическим агентами снижаются, а ____________ (**уровень, цена**) возрастает.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Более высокий ____________ (**уровень, цена**) поднимает краткосрочную кривую совокупного предложения из SRAS1 в SRAS2.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### Отдельный продавец или покупатель не может повлиять на ____________ (**цена**) фактора производства, каждый агент на рынке принимает цену как данную.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены товара', 
                          title = '#### Мы отмечали, что изменение ____________ (**цена, товар**) соответствует движению вдоль кривой спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Увеличившийся объем производства отрасли не влияет на ____________ (**цену**) факторов производства, выход на рынок новых фирм не прекращается, пока не достигнута первоначальная цена.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'продаются по цене', 
                          title = '#### Новые машины ____________ (**продаваться, по, цена**) 4000 долл. каждая. Если не учитывать износа от использования машины, то какой будет стоимость подержанного автомобиля?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'продаются по цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'верхний предел цены', 
                          title = '#### Мы упоминали, что ____________ (**верхний, предел, цена**) и дефицит способствуют формированию нежелательного механизма распределения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'верхний предел цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Мы увидим, что уровень ____________ (**цена**) равен ожидаемому уровню цен в среднесрочном периоде, но обычно не равен ожидаемому уровню цен в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоким ценам', 
                          title = '#### Риск выражается в том, что товаропроизводитель стремится предугадать спрос, сформировать его и выпустить продукцию по ____________ (**высокие, цены**), когда рынок еще не насыщен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоким ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Теория реального экономического цикла (ТРЭЦ) исходит из предпосылки о гибкости ____________ (**цена**) и заработной платы как в краткосрочном, так и долгосрочном периоде, независимости реальных показателей от номинальных.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цена', 
                          title = '#### Монополист покинет рынок лишь в том случае, если ____________ (**цена**) окажется ниже средних переменных затрат при оптимальном, т. е. прибылемаксимизирующем, выпуске.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### По о____________ (**цен**)кам авторов падение цен на нефть является более важным фактором стагнации: оно ведет к потере 8,5 проц. пункта суммарного роста за 2014 – 2017 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижение цен', 
                          title = '#### Часто более сильные участники картеля в погоне за повышением прибыли идут на ____________ (**снижение, цен**) путем увеличения количества продаваемых товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижение цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночную цену', 
                          title = '#### Фирма может оказывать влияние на ____________ (**рыночный, цена**), т. е. осуществлять рыночную власть.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночную цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Так же, как спрос на хлеб зависит от его ____________ (**цена**), спрос на деньги зависит от цены, которую приходится платить за хранение денег на руках.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Фактический уровень ____________ (**цена**) оказывается выше ожидаемого уровня цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### Чтобы увеличить объем продаж, монополия должна снизить ____________ (**цена**) на свой товар.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценам', 
                          title = '#### Компании, из­держки производства которых повышаются, имеют меньше прибыли, платят более низкую заработную плату, продают товары по более высоким ____________ (**цены**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Увеличение объема национального производства сопровождается ростом ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночную цену', 
                          title = '#### Ценополучатель (price taker) — это участник рынка, который принимает ____________ (**рыночный, цена**) как данность.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночную цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночная цена', 
                          title = '#### Если ____________ (**рыночный, цена**) на автомобиль повышается, то спрос на него может снизиться из-за недоступности для некоторых покупателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночная цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Совершенно эластичиый спрос — ситуация, при которой изменение величины спроса не требует изменения ____________ (**цена**) товара; ситуация, при которой покупатели готовы покупать весь имеющийся на рынке товар по неизменной цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'соотношении цен', 
                          title = '#### Изокоста отражает возможности предприятия приобретать ресурсы при ____________ (**соотношение, цен**) Х.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'соотношении цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Кривая АД, сдвигается влево до АД, и ____________ (**уровень, цена**) падает до Р.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падение цен', 
                          title = '#### Предположим, произошло резкое ____________ (**падение, цен**) на акции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падение цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительских цен', 
                          title = '#### Ожидается снижение индекса ____________ (**потребительский, цена**) в будущем.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительских цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночных цен', 
                          title = '#### Особенно важное значение имело введение ____________ (**рыночная, цена**) и распространение частной экономической деятельности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночных цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменения цены', 
                          title = '#### Определите общий эффект от ____________ (**изменение, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменения цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низкие цены', 
                          title = '#### МЭР закладывает в свой прогноз более ____________ (**низкая, цена**) на нефть.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низкие цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Мировая экономика предполагается закрытой, и с учетом гибкости зарплат и ____________ (**цена**) на сырье таргетирование взвешенного индекса цен на торгуемые и неторгуемые товары является в данной экономике оптимальной политикой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной цены', 
                          title = '#### Лидер регулирует уровень ____________ (**рыночный, цена**) и берет на себя ответственность за приспособление цены к изменяющимся условиям рынка.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'росту цен', 
                          title = '#### Рост государственных расходов в экономике с полным использованием ресурсов усиливает конкуренцию на рынке товаров и ведет к ____________ (**рост, цен**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'росту цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Спрос на товар убывает при росте ____________ (**цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне цен', 
                          title = '#### При более высоком ____________ (**уровень, цена**) Р, экономика окажется на новой кривой краткосрочного совокупного предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокой цене', 
                          title = '#### Фирмами используется стратегия продажи товаров высокого качества по ____________ (**высокий, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокой цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной цене', 
                          title = '#### Текущая доходность (current yield) — отношение суммы платежа по годовому купону к ____________ (**рыночный, цена**) облигации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### В результате 10%-ного увеличения номинальной денежной массы ____________ (**уровень, цена**) вырос на 10%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительских цен', 
                          title = '#### В качестве показателя уровня цен используется дефлятор ВВП, но так же можно использовать индекс ____________ (**потребительский, цена**) и индекс промышленных цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительских цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценами', 
                          title = '#### Мы в реальности не наблюдаем экономику с гибкими ____________ (**цена**), а статистические данные мы получаем из экономики фактической – с жесткими ценами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальных цен', 
                          title = '#### По вертикальной оси виден темп прироста ____________ (**реальная, цена**) на акции в следующие 20 лет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальных цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Мы устанавливаем параметр жесткости ____________ (**цена**) в секторе прочих товаров равным 0,8, то есть цены остаются неизменными в среднем в течение пяти кварталов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Более низкие издержки производства позволяют внутренним производителям устанавливать более низкие ____________ (**цена**) на свою продукцию и таким способом увеличивать ее экспорт на мировой рынок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'соотношения цен', 
                          title = '#### При фиксированных функции полезности и доходе структура покупок целиком зависит от ____________ (**соотношение, цен**) товаров.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'соотношения цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'гибкости цен', 
                          title = '#### В долговременном периоде экономика сохра­няет стабильность при производстве внутреннего про­дукта, обеспечивающем полную занятость ресурсов благодаря ____________ (**гибкость, цена**) и заработной платы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'гибкости цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Как только торговля будет разрешена, внутренние ____________ (**цены**) на сталь сравняются с мировой ценой. Если мировая цена выше внутренних цен на сталь, последние возрастут.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сопоставимых ценах', 
                          title = '#### За 1980–1991 гг. природные явления повлекли $693 млрд убытков (в ____________ (**сопоставимые, цены**) 2018 г.). Дальнейший рост среднемировой температуры и повышение уровня мирового океана, как ожидается, лишь ухудшат ситуацию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сопоставимых ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменение цен', 
                          title = '#### Волатильность реагирует на ____________ (**изменение, цены**) на нефть.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### Некоторые потребители заплатят более высокую ____________ (**цена**) в условиях дискриминирующей монополии, чем при недискриминирующей монополии.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияет на цены', 
                          title = '#### Проект ____________ (**повлиять, на, цену**), с помощью которых исчисляется его эффективность, что является плохой практикой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияет на цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Потребление некоторых товаров, например соли, почти не зависит от изменения ____________ (**цена**), а потребление других, таких, как жилье, оказывается в гораздо большей зависимости от ее изменения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Увеличение темпов роста ____________ (**цен**) непродовольственных товаров ускоряет инфляцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### С ростом ____________ (**уровень, цена**) пропорционально растет и объем предложения национального продукта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'средняя цена', 
                          title = '#### Всемирный банк прогнозирует, что глобальный ВВП вырастет в 2021 г. на 5,6%, а ____________ (**средний, цена**) на нефть составит $62 за баррель.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'средняя цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### В краткосрочном периоде ____________ (**уровень, цена**) является фиксированным и что фирмы желают предлагать любое количество продукции по этим ценам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### В экономике наблюдается спад, но ____________ (**уровень, цена**) остается неизменным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Ожидаемый ____________ (**уровень, цена**) приспосабливается к фактическому уровню цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Ценовые факторы (изменение общего ____________ (**уровень, цена**)) влияют при прочих равных условиях на величину совокупного предложения в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### Мы использовали модель IS-LM для объяснения краткосрочных изменений национального дохода, исходя из предпосылки, что ____________ (**уровень, цена**) фиксирован.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровню цен', 
                          title = '#### Естественный уровень безработицы — это такой уровень безработицы, при котором фактический уровень цен равен ожидаемому ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровню цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровни цен', 
                          title = '#### Таким образом, ____________ (**уровень, цен**) в развивающихся странах с меньшими реальными душевыми доходами оказываются в среднем ниже, чем в развитых экономиках.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровни цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменении цены', 
                          title = '#### Эластичность спроса по цене (price elasticity of Эффективность (efficiency) — использование об­ demand) — показатель, измеряющий, как изме­ ществом ограниченных ресурсов, направленное нится объем спроса при ____________ (**изменение, цена**) товара. на максимизацию общего излишка, получаемо­ Рассчитывается как отношение изменения объе­ го всеми членами общества (гл. 1,7). ма спроса, выраженного в процентах, к измене­ Эффективный масштаб (efficient scale) — объем',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменении цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировая цена', 
                          title = '#### Страна будет экспортировать определенную продукцию, если ____________ (**мировой, цена**) превышает внутреннюю цену; она будет импортировать продукцию, если мировая цена ниже внутренней.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировая цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияет на цену', 
                          title = '#### Мы увидели, как налог на товар ____________ (**влиять, на, цена**) и количество проданного товара.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияет на цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокой цене', 
                          title = '#### Как правило, повышение качества продукции сопровождается сдвигом кривой спроса на нее вправо, т. е. при той же цене величина спроса увеличится или тот же объем продукции будет запрашиваться по более ____________ (**высокий, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокой цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Правительство выбрало путь сохранения стабильного ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низкой цене', 
                          title = '#### Если вы стремитесь максимизировать чистую выгоду от покупки товара, вам лучше купить меньшее количество товара, но по более ____________ (**низкий, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низкой цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценами', 
                          title = '#### Потери являются следствием возникшей в результате контроля над ____________ (**цена**) неэффективности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокие цены', 
                          title = '#### Государственные предприятия устанавливают более ____________ (**высокие, цены**) на продукцию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокие цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'установления цен', 
                          title = '#### Рассмотрим возможность ____________ (**установление, цена**) на продукты выше предельных затрат таким образом, чтобы в точности покрыть и постоянные затраты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'установления цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'надбавку к цене', 
                          title = '#### Почему владельцы приобретаемой фирмы запрашивают ____________ (**надбавка, к, цена**) своих акций?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'надбавку к цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокую цену', 
                          title = '#### Компании стремятся получить самую ____________ (**высокий, цена**). При этом чем выше цена товара, тем активнее они будут пытаться продать большее количество товара, т.е. увеличить предложение.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокую цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Рост номинального спроса на объем производства вызывает увеличение ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Инфляция — это устойчивый рост общего ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снизить цену', 
                          title = '#### Ценовая политика монополии заключается в установлении высокой первоначальной цены на новый товар, чтобы обслужив покупателей с высоким уровнем дохода, затем ____________ (**снизить, цена**) и привлечь менее платежеспособных покупателей. Подобные действия продолжаются до тех пор, пока не будет охвачен весь рынок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снизить цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### В то же время индексы ____________ (**цена**) и товарооборот оказались более чувствительны к внутренним шокам, вклад которых достигает 50%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровень цен', 
                          title = '#### До сих пор наш анализ предполагал, что ____________ (**уровень, цена**) является фиксированным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровень цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'динамики цен', 
                          title = '#### Использование стандартных статистических и эконометрических методов в исследовании ____________ (**динамика, цена**) на акции может оказаться ненадежным.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'динамики цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценах', 
                          title = '#### Объем помощи в неизменных ____________ (**цена**) не превышает показатели середины 80-х годов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценам', 
                          title = '#### Фирмы могут позволить себе платить более высокую номинальную заработную плату, если сумеют продать свои товары по более высоким ____________ (**цены**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночную цену', 
                          title = '#### Тарифы и импортные квоты увеличивают ____________ (**рыночный, цена**) товара, уменьша­ют благосостояние внутренних потребителей и увеличивают благосостояние отечественных производителей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночную цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цене', 
                          title = '#### Кривая спроса для этой фирмы — горизонтальная линия при Р* = 20. Это означает, что фирма может продавать больше или меньше продукции при рыночной ____________ (**цена**) 20 долл. за единицу продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### При росте ____________ (**уровень, цена**) фактический объем выпуска снижается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'индекса цен', 
                          title = '#### Рисунок показывает динамику дивидендов и цен на акции в Японии с 1980 по 2001 г. Верхняя кривая отражает динамику ____________ (**индекс, цена**) на акции (Nikkei); нижняя кривая отражает динамику, соответствующую индексу дивидендов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'индекса цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Стагфляция — инфляция, сопровождаемая стагнацией производства и высоким уровнем безработицы в стране; одновременное повышение ____________ (**уровень, цена**) и уровня безработицы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне цен', 
                          title = '#### Так как фирмы удовлетворяют более высокий спрос при неизменном ____________ (**уровень, цена**), занятость тоже растет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительских цен', 
                          title = '#### Согласно индексу ____________ (**потребительский, цена**) цены росли на 11,2 % в год.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительских цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Структура потребительских расходов меняется в соответствии с изменениями соотношения ____________ (**цен**) на различные товары.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'текущих ценах', 
                          title = '#### Для расчета использовались данные о валовом выпуске товаров и услуг в ____________ (**текущая, цена**), млн руб., за 1998, 2001 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'текущих ценах',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### В марте 2020 г. Банком России была анонсирована вторая «цена отсечения» мировой ____________ (**цена**) на нефти марки Urals в размере 25 долларов за баррель.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цена товара', 
                          title = '#### Рыночный объем производства возрастает, и рыночная ____________ (**цена, товар**) падает.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цена товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесные цены', 
                          title = '#### Индивид 1 располагает единицей блага Y, а индивид 2 — единицей блага X. Рассчитайте ____________ (**равновесная, цена**) и равновесное размещение благ между индивидами.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесные цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем цен', 
                          title = '#### Устанавливается прямая связь между предложением денег и общим ____________ (**уровень, цена**) в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Исследователи полагали, что обес____________ (**цен**)ение банкнот и повышение цен на золото объясняется в первую очередь неурегулированностью торговых оборотов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### При данном ожидаемом уровне ____________ (**цена**) фактический уровень цен является возрастающей функцией от уровня ВВП и от ожидаемого уровня цен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной цене', 
                          title = '#### Фирма может продать по ____________ (**рыночный, цена**) любое количество продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### Акцизные налоги оказывают влияние на предложение, а следовательно, и на равновесную ____________ (**цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Дефлятор ВНП и индекс потребительских ____________ (**цена**) дают различную информацию об общем уровне цен в экономике.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Основной с____________ (**цена**)арий предусматривает падение мировых цен на сырую нефть на 10%, на природный газ на 3% и на нефтепродукты на 8%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низких цен', 
                          title = '#### Часто потери происходили вследствие ____________ (**низкая, цена**) на продукцию государственных предприятий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низких цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### В работе изучается роль динамики мировых ____________ (**цена**) на нефть в накоплении рисков финансовой стабильности и, как следствие, в волатильности макропоказателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'зависит от цены', 
                          title = '#### Аналогично экономист предполагает, что количество хлеба, предлагаемое пекарнями, ____________ (**зависеть, от, цена**) хлеба и цены муки, которая используется при производстве хлеба.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'зависит от цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровню цен', 
                          title = '#### Уровень цен равен ожидаемому ____________ (**уровень, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровню цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падения цен', 
                          title = '#### В условиях ____________ (**падение, цен**) на нефть и низкого курса рубля, а также дальнейшего ухудшения международных отношений стало заметно меньше желающих вкладывать деньги в российскую экономику.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падения цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Падение мировой ____________ (**цена**) на алюминий также привело к снижению его производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низкую цену', 
                          title = '#### Продавцы получают более ____________ (**низкий, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низкую цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне цен', 
                          title = '#### Эффект объясняет различия в ____________ (**уровень, цена**) в разных регионах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низкой цене', 
                          title = '#### Арбитраж - это приобретение чего-либо по ____________ (**низкий, цена**) с целью немедленной его перепродажи по более высокой цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низкой цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### На величину номинальных показателей оказывает влияние изменение ____________ (**уровень, цена**), т.е. инфляционные процессы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'средняя цена', 
                          title = '#### Согласно прогнозу ВБ, ____________ (**средний, цена**) на нефть тех же марок составит $71 за баррель на период 2019–2020 гг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'средняя цена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'относительные цены', 
                          title = '#### Объемы импорта и экспорта меняются медленно: необходимо время, чтобы потребители осознали, что ____________ (**относительная, цена**) изменились, чтобы фирмы переключились на более дешевых поставщиков и т.п.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'относительные цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### В условиях совершенной конкуренции все фирмы выпускают одинаковую продукцию, и каждая фирма столь мала по отношению ко всей отрасли, что ее решения в области производства не влияют на рыночную ____________ (**цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Индекс потребительских ____________ (**цена**) на протяжении первых десяти месяцев 2009 г. сокращался, увеличившись лишь в ноябре и декабре в связи с ростом цен на продукты питания и жилье.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'равновесные цену', 
                          title = '#### Пересечение кривых спроса и предложения, знаменитый маршаллианский крест, определяет ____________ (**равновесный, цена**) и объем выпуска только на гипотетическом рынке совершенной конкуренции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'равновесные цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровнем цен', 
                          title = '#### Изображена кривая совокупного предложения, отражающая зависимость между ____________ (**уровень, цена**) и величиной выпуска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровнем цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'внутренние цены', 
                          title = '#### В результате резких колебаний на рынке криптовалют ____________ (**внутренние, цены**) в стране, использующей такую валюту, могут быть очень нестабильными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'внутренние цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'динамику цен', 
                          title = '#### Изучение инвестиционных рынков строится на моделировании и тестировании факторов, определяющих ____________ (**динамика, цена**) на инвестиционные активы и поведение отдельных групп инвесторов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'динамику цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены товара', 
                          title = '#### При анализе спроса нас часто интересует не его абсолютный объем, а изменения его в ответ на изменение ____________ (**цена, товар**) или какого-то другого параметра, определяющего объем спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены товара',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Даже небольшое отклонение фактического ____________ (**уровень, цена**) от ожидаемого приводит в краткосрочном периоде к существенному отклонению фактического ВВП от потенциального ВВП.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Уровень ____________ (**цена**) снижается для возврата к состоянию всеобщего равновесия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'относительных цен', 
                          title = '#### Изменения ____________ (**относительная, цена**) на товары приводит к росту вознаграждения одних факторов производства за счет других.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'относительных цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышении цены', 
                          title = '#### Нам известно, что при ____________ (**повышение, цена**) на товар потребитель ограничивает его закупки, что выражается в снижении спроса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышении цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низким ценам', 
                          title = '#### Независимые олигополисты конкурируют по цене, а это ведет к более ____________ (**низкая, цена**) и более низким прибылям.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низким ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ростом цен', 
                          title = '#### Стагфляция наблюдалась в 1970-е гг. в развитых странах во время энергетических кризисов, вызванных ____________ (**рост, цен**) на нефть.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ростом цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'падению цен', 
                          title = '#### Безработица ведет к ____________ (**падение, цен**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'падению цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цену', 
                          title = '#### Доступная информация может повлиять на ____________ (**цена**) блага или ценной бумаги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Кейнсианская теория делает ак____________ (**цена**)т на негибкости и жесткости цен в краткосрочном периоде и подчеркивает, что фактический и потенциальный ВВП не всегда совпадают.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### В отличие от отрасли с неизменными затратами, в которой рост выпуска не влияет на ____________ (**цену**) продукции в длитель­ном периоде, в отрасли с возрастающими затратами рост объема выпуска сопровождается повышением цен продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Соотношение спроса и предложения позволяет получить величину равновесного уровня ____________ (**цена**) на товары и услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне цен', 
                          title = '#### Производители иногда обладают неполной информацией об общем ____________ (**уровень, цена**) и поэтому иногда трактуют изменения в общем уровне цен как изменения в относительных ценах товаров, которые они производят.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценами', 
                          title = '#### Например, контроль над ____________ (**цена**) на природный газ заставил потенциальных покупателей газа использовать вместо него нефть.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценами',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### Реакция потребители на повышение ____________ (**цена**) заключается в ограничении покупок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменение цены', 
                          title = '#### Различные товары отличаются друг от друга по степени реакции спроса и предложения на ____________ (**изменение, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменение цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'низким ценам', 
                          title = '#### Хозяйства с высокими затратами на производство продавали свою продукцию государству по высоким ценам, а хозяйства с низкими затратами — по ____________ (**низкая, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'низким ценам',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Кривая краткосрочного совокупного предло- жения имеет положительный наклон, поскольку предполагается, что при изменении ____________ (**уровень, цена**) номинальная зароботная плата остается постоянной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'увеличении цены', 
                          title = '#### Критерий издержек и выгод при ____________ (**увеличение, цена**) на изделие будет удовлетворять все меньшее количество потенциальных покупателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'увеличении цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'единой цены', 
                          title = '#### Предположим, что в нарушение закона ____________ (**единый, цена**) долларовая цена иены составляет 0,009 долл., а не 0,01 долл.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'единой цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Возникает вопрос, каким образом данная страна может приспособиться к потерям на экспортных рынках? Один путь заключается в том, чтобы осуществить корректировку через уменьшение внутренних ____________ (**цены**) и заработной платы, так как высокая безработица постепенно уменьшит заработную плату или замедлит темпы ее роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снизить цену', 
                          title = '#### Экспортные субсидии — правительственные платежи с целью ____________ (**снизить, цена**) на ряд продуктов для иностранных покупателей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снизить цену',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровне цен', 
                          title = '#### Со временем, когда контракты пересматриваются или перезаключаются на новых условиях, номинальные зарплаты вырастут, чтобы компенсировать повышение цен. При любом ____________ (**уровень, цена**) рост номинальной зарплаты также повышает реальную зарплату, побуждая фирмы нанимать меньше рабочих и произодить меньше продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровне цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цене', 
                          title = '#### Короткие продажи устроены так: инвестор занимает акцию и продает ее по текущей ____________ (**цена**), а когда приходит срок ее отдавать – покупает на рынке и отдает. Если цена к этому времени упала – инвестор в выигрыше. А если выросла – то он теряет деньги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цене',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'потребительских цен', 
                          title = '#### Эти уравнения показывают, что и в дефляторе ВНП и в индексе ____________ (**потребительский, цена**) сравнивается текущая цена определенного набора товаров с ценой того же набора в базисном году.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'потребительских цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Эффект обменного курса - когда снижение ____________ (**уровень, цена**) приводит к уменьшению ставки процента, инвесторы перемещают часть своих капиталов за границу, что вызывает ослабление национальной валюты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной ценой', 
                          title = '#### Экономическая рента также определяется как разница между минимальной ценой труда и ____________ (**рыночный, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной ценой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'повышению цен', 
                          title = '#### Анализ спроса и предложения обнаруживает, что протекционистские пошлины приводят к ____________ (**повышение, цен**) и снижают объемы товаров, на которые эти пошлины распространяются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'повышению цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня цен', 
                          title = '#### Чистый экспорт и спрос на отечественные товары зависят от их относительной цены. Этот спрос зависит также от ____________ (**уровень, цена**), поскольку это влияет на предложение реальных денег и отсюда на ставку процента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цен', 
                          title = '#### Эффект богатства (эффект Лигу): снижение уровня ____________ (**цена**) ведет к повышению реальной ценности денежных резервов домашних хозяйств, что, в свою очередь, стимулирует потребительские расходы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цен',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'снижению цены', 
                          title = '#### При любой более высокой цене прибыль будет положительна, вырастет краткосрочное предложение, и это приведет к ____________ (**снижение, цена**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'снижению цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цены', 
                          title = '#### При изменении ____________ (**цена**) на товар-субститут перекрестный коэффициент эластичности оказывается больше нуля (рост цен на кофе вызовет рост спроса на чай); при изменении цены товара-комплемента перекрестный коэффициент эластичности оказывается меньше нуля (рост цены на фото- пленку ведет к уменьшению спроса на фотоаппараты).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цены',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

