```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Ресурсы Международного банка реконструкции и развития формируются главным образом за счет заимствований на мировом финансовом рынке путем эмиссии ____________ (**ценный, бумага**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Физические лица предприниматели правом выпуска ____________ (**ценный, бумага**) не обладают.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Финансирование путем продажи ____________ (**ценный, бумага**) имеет определенные преимущества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### При росте количества разнообразных ____________ (**ценный, бумага**) в портфеле уровень риска портфеля ценных бумаг может быть уменьшен.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценные бумаги', 
                          title = '#### Россия выпустила свои первые государственные ____________ (**ценный, бумага**) в 1769 г. для покрытия расходов в войне с Турцией.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценные бумаги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Наклон линии доходности рынка ____________ (**ценный, бумага**) соответствует премии за риск рыночного портфеля.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценные бумаги', 
                          title = '#### Крупные банки вкладывались в ипотечные ____________ (**ценный, бумага**), падение стоимости которых привело одни банки к банкротству.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценные бумаги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценные бумаги', 
                          title = '#### Цель портфельных инвестиций — вложение средств инвесторов в ____________ (**ценный, бумага**) наиболее прибыльных предприятий.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценные бумаги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценные', 
                          title = '#### Точке F соответствует ситуация, когда портфель на 100% состоит из инвестиций в безрисковые ____________ (**ценный**) бумаги с доходностью 0,06 годовых.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценные бумаги', 
                          title = '#### Инвестору доступны безрисковые ____________ (**ценный, бумага**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценные бумаги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Построить портфель можно, в частности, из некоторога количества базового актива и безрисковых ____________ (**ценный, бумага**) (например, государственных облигаций).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Существенная доля долговых ____________ (**ценный, бумага**) и акций, выпущенных нефинансовыми фирмами, принадлежит инвесторам, имеющим леверидж.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных', 
                          title = '#### Многие промышленные компании перешли на принципы прямого финансирования (выпуск ____________ (**ценный**) бумаг, особенно акций и других инструментов).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Данное выражение описывает так называемую линию доходности рынка ____________ (**ценный, бумага**), или ЛДРЦБ (security market line, SML).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### На долю США приходится половина всех торговых расчетов и две трети глобального выпуска ____________ (**ценный, бумага**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Лопнувший пузырь ипотечных ____________ (**ценный, бумага**) стал началом глобального кризиса 2008 года, погрузившего мировую экономику в Великую рецессию.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### На кредитном рынке, который делится на рынки банковских кредитов и долговых ____________ (**ценный, бумага**), также совершается немало краткосрочных сделок.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Небольшие изменения зачастую могут приводить к существенной корректировке стоимости ____________ (**ценный, бумага**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Стратегия инвестирования заключается в формировании портфеля из ____________ (**ценный, бумага**) компаний, которые демонстрируют хорошие показатели экономической эффективности (темпы роста, маржа прибыли).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### VAR-модели с включенным показателем процентных ставок доходности ____________ (**ценный, бумага**) объясняют лишь незначительную часть общей вариации инфляции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### В российском законодательстве деятельность на рынке ____________ (**ценный, бумага**), осуществляемая без лицензии, является незаконной.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Менеджер управляет портфелем ____________ (**ценный, бумага**) клиента.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Большинство видов ____________ (**ценный, бумага**) обращается на внебиржевом рынке.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценные', 
                          title = '#### Если ____________ (**ценный**) бумаги не купит сторонний инвестор, инвестиционный банк приобретет их у эмитента по заранее определенной, т.е. гарантированной цене.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценные',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Процесс увеличения количества видов ____________ (**ценные, бумаги**) в портфеле, результатом которого является уменьшение риска портфеля без уменьшения его ожидаемой доходности, называют диверсификацией портфеля.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Заемный капитал — вложенные в компанию деньги, которые были получены из внешних источников на определенный срок путем выпуска ____________ (**ценный, бумага**) с фиксированной процентной ставкой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Власти могут влиять на ставки на параллельных рынках обмена валюты – как с помощью регулирования, так и посредством продажи ____________ (**ценный, бумага**) государственными организациями (за счет сокращения валютных резервов)',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценные бумаги', 
                          title = '#### Инвесторы передают полномочия по разработке структуры их инвестиций в ____________ (**ценный, бумага**) менеджерам фондов по управлению портфелями ценных бумаг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценные бумаги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Портфель ____________ (**ценный, бумага**) является тем инструментом, с помощью которого обеспечивается необходимое инвестору постоянство дохода при условиях минимального риска.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### С помощью операций на открытом рынке, то есть купли-продажи государственных ____________ (**ценный, бумага**), Центральный банк страны регулирует денежную массу в обращении.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценных бумаг', 
                          title = '#### Пенсионные фонды часто пользуются услугами нескольких разных менеджеров по управлению портфелями ____________ (**ценный, бумага**), причем каждый из них осуществляет управление только частью портфеля.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценных бумаг',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ценные бумаги', 
                          title = '#### К первичным финансовым инструментам относятся кредиты, займы, облигации, другие долговые ____________ (**ценный, бумага**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ценные бумаги',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

