```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Экономическим ростом принято считать увеличение объема производства товаров, работ, услуг в национальной ____________ (**экономика**) в течение определенного периода времени.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой экономике', 
                          title = '#### Новые инструменты стимулируют развитие финансового рынка в условиях резко меняющейся обстановки в ____________ (**мировой, экономика**) и международных экономических отношениях.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'функционирования экономики', 
                          title = '#### Пандемия коронавируса затронула практически все стороны ____________ (**функционирование, экономика**) и жизнедеятельности общества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функционирования экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Допустим, что скорость обращения денег является постоянной, и посмотрим, как в этом случае предложение денег воздействует на ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Компания прдоставляет возможности модернизации региональной ____________ (**экономика**), исходя из приоритетов национальной экономической политики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной экономикой', 
                          title = '#### Вероятно, что еще две страны с формирующейся ____________ (**рыночный, экономика**), а именно Иран и Индонезия, в скором времени примкнут к экономической группе БРИКС.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'диверсификации экономики', 
                          title = '#### Город обладает большим потенциалом для ____________ (**диверсификация, экономика**) и создания новых рабочих мест.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'диверсификации экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### На макроэкономическом уровне внешняя и внутренняя климатическая политика также оказывает существенное влияние на ____________ (**экономика**) России.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики предложения', 
                          title = '#### Главное правилотеории ____________ (**экономика, предложение**) заключается в том, что лучший регулятор рынка – сам рынок, а государственное регулирование и высокие налоги только мешают.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики предложения',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Модель IS-LM построена, чтобы лучше описывать поведение ____________ (**экономика**) в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Инвестиционная политика государства — комплекс взаимосвязанных целей и мероприятий по обеспечению необходимого уровня и структуры инвестиций в ____________ (**экономика**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'открытой экономики', 
                          title = '#### Цена давнего производителя обычно ниже издержек начинающегося, что блокирует начало производства в другой стране в условиях ____________ (**открытый, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'открытой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Каждому иностранцу, который вложит в ____________ (**экономика**) страны 3 биткоина, обещают гражданство.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиций в экономику', 
                          title = '#### Крепкий рубль, льготное налогообложение предпринимательства сформировали условия для привлечения отечественных и иностранных ____________ (**инвестиция, в, экономика**) Российской империи.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиций в экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### В конечном итоге карьерные достижения в условиях рыночной ____________ (**экономика**) с ее духом конкуренции признаются универсальным критерием жизненного успеха.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития экономики', 
                          title = '#### Уровень пространственного ____________ (**развитие, экономика**) регионов во многом определяет их конкурентные позиции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Появление теории ____________ (**экономика**) предложения было обусловлено серьезным кризисом государственного регулирования рыночной экономики на основе кейнсианских рецептов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'поведения экономики', 
                          title = '#### Исследователь сомневался в том, что понятие нейтральности денег примени­мо к анализу ____________ (**поведение, экономика**) в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'поведения экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### В закрытой ____________ (**экономика**) без государства инвестиции могут существляться только за счет собственных сбережений.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменений в экономике', 
                          title = '#### Многие специальные навыки рабочих вследствие структурных ____________ (**изменение, в, экономика**) оказались ненужными.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменений в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономикой', 
                          title = '#### Приток прямых иностранных инвестиций (ПИИ) в страны с переходной ____________ (**экономика**) в 2018 г. продолжал снижаться, сократившись на 28 %.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной экономики', 
                          title = '#### Нужно исследовать зоны риска экономической деятельности, характерные для ____________ (**рыночный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цифровой экономике', 
                          title = '#### Данные в ____________ (**цифровой, экономика**) - самый ценный ресурс.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цифровой экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'инвестиции в экономику', 
                          title = '#### Производственные фирмы производят товары и услуги, используя арендуемый капитал. Фирмы, сдающие капитал в аренду, осуществляют все ____________ (**инвестиция, в, экономика**); они покупают производственные фонды и сдают их в аренду производственным фирмам.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'инвестиции в экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономикой переходного периода', 
                          title = '#### Страны Европы с ____________ (**экономика, переходный, период**) представляют собой неоднородную группу.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономикой переходного периода',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Для развитых стран характерна меньшая волатильность ключевых показателей состояния ____________ (**экономика**) и банковского сектора.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Крупные инвестиционные проекты влияют на другие отрасли ____________ (**экономика**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'состояние экономики', 
                          title = '#### Общее экономическое равновесие определяется как такое ____________ (**состояние, экономика**), когда все рынки одновременно находятся в равновесии, а каждый субъект максимизирует свою целевую функцию, т. е. достигает своей собственной цели.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'состояние экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сбережений в экономике', 
                          title = '#### Равновесное состояние рынка товаров и услуг достигается тогда, когда желаемый уровень ____________ (**сбережение, в, экономика**) совпадает с желаемым уровнем инвестиций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сбережений в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'воздействия на экономику', 
                          title = '#### Свои регулирующие функции государство выполняет через определенные методы ____________ (**воздействие, на, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'воздействия на экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Пенсионеры начинают тратить накопления и перестают вносить свой вклад в ____________ (**экономика**) в виде производства товаров и услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'изменений в экономике', 
                          title = '#### Дан анализ структурных ____________ (**изменение, в, экономика**) России в условиях межотраслевой конкуренции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'изменений в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной экономикой', 
                          title = '#### Различные благотворительные организации составляют заметную долю в экономической деятельности в странах с ____________ (**рыночный, экономика**), особенно в сфере социальных услуг.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'производственных возможностей экономики', 
                          title = '#### На рисунке изображена кривая ____________ (**производственный, возможность, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'производственных возможностей экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой экономики', 
                          title = '#### Организация экономического сотрудничества и развития дает возможность странам-членам своевременно приспосабливаться к тенденциям развития ____________ (**мировой, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'открытой экономики', 
                          title = '#### Выбор переменных для модели малой ____________ (**открытый, экономика**) также представляется непростой задачей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'открытой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Зачастую для закрытой ____________ (**экономика**) характерна плановая система.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Развитые теории ____________ (**экономика**) федерализма должны основываться на разумных компромиссах между экономической эффективностью и социальной справедливостью, обеспечивать высокие темпы экономического роста национальной экономики, с одной стороны, и допускать небольшие различия между регионами страны - с другой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'отраслей экономики', 
                          title = '#### Ряд ____________ (**отрасль, экономика**) России характеризуются высокой зависимостью от импорта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отраслей экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Экономическая политика воздействует на малую открытую ____________ (**экономика**) с фиксированным обменным курсом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### В последние годы в связи с переходом к рыночным отношениям происходят глубокие изменения в ____________ (**экономика**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'занятых в экономике', 
                          title = '#### Количество ____________ (**занять, в, экономика**) к концу 2020 года снизилось до 70 млн человек.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'занятых в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Сырьевая направленность инвестиций в региональную экономику не обеспечивает должного эффекта, который бы позволил задействовать эндогенные факторы роста ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Внутренний лаг политики есть единовременное запаздывание, в течение которого политика не оказывает никакого влияния на ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### В условиях рыночной ____________ (**экономика**) в бухгалтерском учете выделяют две относительно самостоятельные ветви: финансовый и управленческий учеты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Инвестиционные кластеры способствуют росту эффективности как региональной, так и ____________ (**национальный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономике', 
                          title = '#### Долгосрочные тенденции неравенства доходов между группами населения в ____________ (**национальный, экономика**) определяются и объясняются в зависимости от экономического роста .',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### После становления рыночной ____________ (**экономика**) в России снова появился интерес к средне- и долгосрочному прогнозированию, возникла потребность в оценке долгосрочной перспективы экономического развития.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'занятого в экономике', 
                          title = '#### Важна стоимость основных фондов на одного ____________ (**занять, в, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'занятого в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной экономики', 
                          title = '#### Макроэкономические концепции и теории обобщают опыт многих десятилетий функционирования и развития ____________ (**рыночный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Развитие мобильных финансовых сервисов может снизить долю теневой ____________ (**экономика**) в ВВП на 2,4–4,3%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста экономики', 
                          title = '#### Характерной чертой изменения структуры обрабатывающих производств в условиях низких темпов ____________ (**рост, экономика**) является снижение технологического уровня производства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики страны', 
                          title = '#### Монополия сопряжена с целым букетом резко отрицательных последствий для ____________ (**экономика, страна**): недопроизводство, завышенные цены.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики страны',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Следующий наш шаг — это анализ рынка труда, товарного рынка и рынка активов в совокупности и рассмотрение равновесия в ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### В исследованиях используются модели закрытой ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Следует уменьшить трансакционные издержки субъектов региональной ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Мы вводим в модель государственное финансирование здравоохранения и оцениваем его воздействие на ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'теневой экономики', 
                          title = '#### В развивающихся странах с низкими доходами размер ____________ (**теневой, экономика**) будет выше, чем в развитых.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теневой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'восстановления экономики', 
                          title = '#### Банки продолжат осуществлять кредитование в период ____________ (**восстановление, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'восстановления экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Какое воздействие на ____________ (**экономика**) оказывает изменение объема номинальной денежной массы?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Главным драйвером социально-экономического развития должны стать инвестиции в основной капитал и вложения в ____________ (**экономика**) знаний, в особенности в человеческий капитал.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Экономическая агломерация не должна описываться в общем виде, так как ее интерпретация зависит от пространственного и исторического масштаба, на что указывают исследования в  других областях пространственной ____________ (**экономика**), таких как городская экономика, международная торговля.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Реальный объем ВНП снижается на 1%, указывая на спад в ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Образование влияет на отношение к рыночной ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### На первом этапе производится оценка сравнительного уровня развития цифровой ____________ (**экономика**) в каждом регионе округа.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировую экономику', 
                          title = '#### Стратегический план развития страны ориентирован на интеграцию в ____________ (**мировой, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировую экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'цифровой экономики', 
                          title = '#### Вслед за развитием ____________ (**цифровой, экономика**) активно развиваются и электронные платежи.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'цифровой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реальном секторе экономики', 
                          title = '#### Снижение спроса и цен на жилую недвижимость привело к спаду как в банковской сфере и негативно отразилось на ____________ (**реальный, сектор, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реальном секторе экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Половина жителей развитых стран задействованы в ____________ (**экономика**) обмена.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной экономики', 
                          title = '#### Ярко выраженный международный характер финансовых кризисов проявился в 30—90-е годы, относящиеся к фазе длинной волны развития ____________ (**рыночный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'закрытой экономики', 
                          title = '#### Проанализировано поведение ____________ (**закрытый, экономика**) в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закрытой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'переходной экономике', 
                          title = '#### В отличие от рыночной экономики, где националь­ная валюта является единственным средством денежно-кредитного обращения и сбережения, в ____________ (**переходный, экономика**) существует це­лый сегмент кредитно-денежной системы, связанный с твердой ва­лютой. На роль твердой валюты может претендовать доллар, евро.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'переходной экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой экономики', 
                          title = '#### Условная траектория роста страны рассчитана по данным о фактических темпах роста ____________ (**мировой, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ресурсных экономиках', 
                          title = '#### В ____________ (**ресурсный, экономика**) с плохими институтами в обществе решение проблемы распределения природной ренты осуществляют элиты.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ресурсных экономиках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Экономический рост является динамическим совокупным показателем и характеризует состояние ____________ (**экономика**) страны в целом во временном аспекте.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Структурные сдвиги в ____________ (**экономика**) возникают как качественные изменения связей, которые существуют между сопоставимыми элементами макроэкономической системы.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### В краткосрочном плане правительство сокращает дефицит бюджета или даже имеет его профицит, но при этом снижаются темпы роста основного и человеческого капиталов, ухудшаются их качественные характеристики, что подрывает основы роста ____________ (**экономика**) в долгосрочной перспективе.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Производительность и развитие ____________ (**экономика**) зависят от темпа накопления нематериального капитала (знаний).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономикой', 
                          title = '#### Уравнение обмена предназначено для решения узкого круга задач в управлении ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'реального сектора экономики', 
                          title = '#### Основу ____________ (**реальный, сектор, экономика**) составляет производство промышленной и сельскохозяйственной продукции.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'реального сектора экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику страны', 
                          title = '#### Государственное вмешательство ограничило воздействие мирового спада на ____________ (**экономика, страна**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику страны',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Чтобы оценить, как влияет на ____________ (**экономика**) «бегство» капитала, сравним исходное и новое состояние равновесия.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Государственное вмешательство в ____________ (**экономика**) является объективно необходимым для любого правительства независимо от того, рыночная в стране экономика или командно-административная.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Потенциальный ВВП – объем производства при полном использовании имеющихся в ____________ (**экономика**) ресурсов, при полной занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рост экономики', 
                          title = '#### Укрепление доллара может негативно повлиять на ____________ (**рост, экономика**) в период ее посткризисного восстановления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рост экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономика', 
                          title = '#### ____________ (**экономика**) находится на подъеме.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономика',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ресурсных экономиках', 
                          title = '#### Периоды роста цен на экспортируемое сырье в ____________ (**ресурсный, экономика**)  ведут к буму кредитования и росту внешнего долга, что осложняет обслуживание кредитов в иностранной валюте, когда ситуация на рынке сырья меняется.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ресурсных экономиках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальных экономик', 
                          title = '#### Сложившиеся непростые условия развития мировой экономики стимулируют государства к поиску мер, которые могли бы остановить замедление темпов роста ____________ (**национальный, экономика**) и создать импульс, обеспечивающий развитие.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальных экономик',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'переходной экономикой', 
                          title = '#### В 1990-х – начале 2000-х гг. в России и многих других странах с переходными экономиками чрезвычайно сложно было получить небольшой кредит на развитие бизнеса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'переходной экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Если нормальный темп роста равен 3%, то темп роста ____________ (**экономика**) соответственно должен составить 3% – 5% = –2% в году 1, т.е. будет наблюдаться спад.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой экономике', 
                          title = '#### Механизм экономического сотрудничества обеспечивают Европейскому Союзу важную роль в ____________ (**мировой, экономика**) и политике в качестве единого хозяйствующего субъекта.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Государство отказывается от дохода в виде части налога на прибыль в пользу увеличения степени конкурентоспособности национальной ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Эксперт оценивает потребности в инвестициях на модернизацию и развитие ____________ (**экономика**) знаний  в размере более 20 трлн руб.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'диверсификации экономики', 
                          title = '#### Эксперты положительно оценивают степень ____________ (**диверсификация, экономика**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'диверсификации экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'двухсекторной модели экономики', 
                          title = '#### В ____________ (**двухсекторный, модель, экономика**) сочетаются централизованное административно-плановое управление экономикой с рыночным саморегулированием.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'двухсекторной модели экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'вложений в экономику', 
                          title = '#### В развитых странах доля инвестиций в ВВП в среднем составляет 21%, а доля ____________ (**вложение, в, экономика**) знаний - более 30%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'вложений в экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'функционирования экономики', 
                          title = '#### Макроэкономика — это наука, которая изучает закономерности ____________ (**функционирование, экономика**) в целом, исследует взаимодействие экономических агентов и экономических рынков друг с другом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функционирования экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'нагрузки на экономику', 
                          title = '#### Рост социальных расходов на поддержку инфраструктуры, обслуживающей пожилое население, может потребовать резкого увеличения налоговой ____________ (**нагрузка, на, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'нагрузки на экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Численность занятых в ____________ (**экономика**) северных территорий в 2009 г. составляла 4333 тыс. чел.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'региональных экономик', 
                          title = '#### Развитие ____________ (**региональный, экономика**) в значительной мере определяется силой локальных кластеров, насколько жизнеспособны и многочисленны инновации.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'региональных экономик',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночную экономику', 
                          title = '#### Вхождение страны в ____________ (**рыночный, экономика**) предполагает создание цивилизованного рынка труда.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночную экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Модель IS-LM для открытой ____________ (**экономика**) похожа на модель для закрытой экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стабилизации экономики', 
                          title = '#### Снижение налогов может использоваться для ____________ (**стабилизация, экономика**) и борьбы с циклической безработицей в период спада, стимулируя деловую активность и уровень занятости.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стабилизации экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'закрытой экономики', 
                          title = '#### Предположим, что требуется определить краткосрочное воздействие сокращения денежной массы на ставку процента и объем инвестиций. В модели ____________ (**закрытый, экономика**) ставка процента растет, а инвестиции сокращаются. В модели малой открытой экономики ни то ни другое не изменяется.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'закрытой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### В долгосрочном периоде развитие банковского сектора потенциально может влиять на объем ВРП, его структуру, степень диверсификации ____________ (**экономика**) и даже численность населения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'регулирования экономики', 
                          title = '#### Индекс Херфиндаля-Хиршмана может использоваться правительственными органами ____________ (**регулирование, экономика**) в качестве легального ориентира антимонопольной или, как называют ее в США, антитрестовской, политики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'регулирования экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Рассмотрим структуру иностранных инвестиций в ____________ (**экономика**) .',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'шоков в экономике', 
                          title = '#### Неверная денежная политика может быть источником ____________ (**шок, в, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'шоков в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'открытой экономике', 
                          title = '#### Мы рассмотрели возможные последствия макроэкономической политики в малой ____________ (**открытый, экономика**) при разных режимах валютного курса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'открытой экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'вмешательства в экономику', 
                          title = '#### Рынок сам исправляет дисбалансы в масштабе национальной экономики, и никакого ____________ (**вмешательство, в, экономика**) со стороны государства не потребуется.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'вмешательства в экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Второй нефтяной кризис в 1979 году, повлиявший на мировую ____________ (**экономика**), стал причиной повышения цен на нефть более чем на 60%.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Чистый экспорт влияет на ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономика', 
                          title = '#### В долгосрочном периоде производители узнают правду об уровне цен, ____________ (**экономика**) возвращается к уровню полной занятости, а инфляция снова становится равной своему ожидаемому уровню.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономика',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста экономики', 
                          title = '#### В период с апреля по июнь темпы ____________ (**рост, экономика**) страны замедлились.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Китай считается успешным примером модернизации ____________ (**экономика**), и эта модель привлечет внимание политиков других стран.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### Повышающийся спрос побуждает увеличивать инвестиции в ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'управлении экономикой', 
                          title = '#### Изменилась роль государства в ____________ (**управление, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'управлении экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'сдвиги в экономике', 
                          title = '#### На основании данных о структуре производства, демографической и налоговой статистики оцениваются пространственные ____________ (**сдвиг, в, экономика**) региона.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'сдвиги в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Ожидаемая ставка доходности на вложенный капитал зависит от времени и места инвестирования: от состояния ____________ (**экономика**), степени доступности других факторов производства, таких как природные ресурсы и рабочая сила, уровня спроса на товары и услуги.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'функционирования экономики', 
                          title = '#### Необходимые для ____________ (**функционирование, экономика**) предприятия с госучастием должны быть в полной мере обеспечены финансированием.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'функционирования экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'открытую экономику', 
                          title = '#### Мы рассмотрим малую ____________ (**открытый, экономика**), которая обладает мобильностью капитала.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'открытую экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'переходной экономикой', 
                          title = '#### В 90-е годы 20 века процесс “утечки мозгов” приобрел особенно большие масштабы в странах с ____________ (**переходный, экономика**), когда научная элита потеряла около 40% специалистов мирового класса.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'переходной экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста экономики', 
                          title = '#### Замедление роста подушевого национального дохода в СССР относительно стран Западной Европы в 1960-е гг. было вызвано как замедлением темпов ____________ (**рост, экономика**) СССР, так и ускорением экономического роста в европейских странах.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'состояния экономики', 
                          title = '#### Независимо от ____________ (**состояние, экономика**) доходность портфеля акций компании равна 0,08.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'состояния экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'открытой экономики', 
                          title = '#### Для крупной экономики характерно сочетание черт как закрытой, так и малой ____________ (**открытый, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'открытой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Таким образом, для стабилизации ____________ (**экономика**) правительство должно либо увеличить государственные закупки на 15 млрд долларов, либо снизить налоги на 16 млрд долларов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'региональной экономики', 
                          title = '#### Произошло изменение качества экономического роста ____________ (**региональный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'региональной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Макроэкономическая теория открытой ____________ (**экономика**) (open-economy macroeconomics, OEM) стала обособленной областью исследований лишь в конце 1960-х годов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'спад в экономике', 
                          title = '#### Как известно, за подъемом закономерно начинается ____________ (**спад, в, экономика**), что неизбежно приводит сначала к ослаблению конъюнктуры инвестиционного рынка, а затем — к спаду.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'спад в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'воздействия на экономику', 
                          title = '#### Кейнс был убежден в том, что кредитно-денежная политика не может оказать серьезного ____________ (**воздействие, на, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'воздействия на экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'национальной экономики', 
                          title = '#### Показатели социального статуса, например, образование и профессия, часто зависят от состояния и тенденций развития ____________ (**национальный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'национальной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'открытой экономики', 
                          title = '#### В приложении дана модель большой ____________ (**открытый, экономика**) в краткосрочном периоде.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'открытой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономика', 
                          title = '#### ____________ (**экономика**) находится в стадии экономического роста.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономика',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Период восстановления ____________ (**экономика**) после пандемии оказался короче, чем предполагалось.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### В последние годы наблюдается сокращение государственных расходов в регулировании ____________ (**экономика**) страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономика', 
                          title = '#### Часть экономики находится «в тени» во всех странах, но размеры этой тени сильно различаются.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономика',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развития экономики', 
                          title = '#### Характер ____________ (**развитие, экономика**) регионов России будет определять и их будущую бюджетную доходность.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развития экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной экономике', 
                          title = '#### Производство в ____________ (**рыночный, экономика**) будет ориентировано на интересы потребителей.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Все экономические агенты располагают одинаковой информацией о состоянии ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'отрасли экономики', 
                          title = '#### Финансовая система обеспечивает способы перемещения экономических ресурсов во времени, из одного географического региона в другой, а также из одной ____________ (**отрасль, экономика**) в другую.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отрасли экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной экономики', 
                          title = '#### Финансовые пузыри превратились в закономерность современной ____________ (**рыночный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике обмена', 
                          title = '#### Рассмотрим равновесие при асимметричной информации по Вальрасу в ____________ (**экономика, обмен**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике обмена',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономикой', 
                          title = '#### Утечка мозгов (от англ. brain drain) - это термин, обозначающий эмиграцию наиболее образованных и квалифицированных специалистов из бедных стран и стран с переходной ____________ (**экономика**) в богатые страны, имеющие высокий уровень жизни.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Как Федеральная резервная система (ФРС) воздействует на состояние ____________ (**экономика**)?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'теневой экономики', 
                          title = '#### Снижение производства, высокий уровень ____________ (**теневой, экономика**) привели к тому, что страна постоянно испытывает трудности с погашением задолженности и ее обслуживанием.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теневой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике знаний', 
                          title = '#### В предкризисный период доля трудовых ресурсов в ____________ (**экономика, знание**) области составляла около 47% .',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике знаний',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Роль безналичных расчетов в теневой ____________ (**экономика**) постоянно растет.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### В будущем ожидается поступательный рост мировой ____________ (**экономика**) и адаптация страны к системе санкций.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста экономики', 
                          title = '#### Старение населения в большинстве развитых стран ведет к росту социальных расходов (на пенсионное обеспечение, здравоохранение и т. д.), замедлению ____________ (**рост, экономика**) и снижению доходов бюджета.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'вклад в экономику', 
                          title = '#### В связи с отсутствием государственной поддержки среднего бизнеса, ____________ (**вклад, в, экономика**) среднего бизнеса снижается.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'вклад в экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Способность генерировать большую норму прибыли является одним из мотивов к предпринимательской деятельности в реальном секторе ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'поведение экономики', 
                          title = '#### Макроэкономика изучает ____________ (**поведение, экономика**) в целом, а это означает, что макроэкономика изучает подъемы и спады, экономический рост и экономический цикл, инфляцию, безработицу, международную торговлю.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'поведение экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономикой', 
                          title = '#### После смены политического строя те организации, которые осуществляли функции государственного управления ____________ (**экономика**), просто прекращают свое существование.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ростом экономики', 
                          title = '#### Даны показатели, непосредственно связанные с ____________ (**рост, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ростом экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'отраслей экономики', 
                          title = '#### Государство оказывает поддержку отдельных ____________ (**отрасль, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отраслей экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Методы государственного регулирования ____________ (**экономика**) делятся на прямые и косвенные.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ресурсных экономиках', 
                          title = '#### Эта статья посвящена анализу взаимосвязи сырьевых и кредитных циклов в ____________ (**ресурсный, экономика**) с высоким уровнем развития.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ресурсных экономиках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Эти показатели используются для расчетов индекса ____________ (**экономика**) знаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Промышленность оказалась одной из наиболее динамично развивающихся отраслей ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'переходных экономиках', 
                          title = '#### Следует провести анализ доходов, расходов и сбережений на­селения в ____________ (**переходный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'переходных экономиках',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'региональной экономики', 
                          title = '#### Ожидается прирост реальных инвестиций со всеми прямыми и косвенными эффектами для ____________ (**региональный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'региональной экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'теневой экономике', 
                          title = '#### Невозможно получить данные о количестве занятых в ____________ (**теневой, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теневой экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике страны', 
                          title = '#### Из-за ослабления законодательства о банкротстве в ____________ (**экономика, страна**) оказалось 4300 дополнительных компаний-зомби.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике страны',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'мировой экономики', 
                          title = '#### Темп роста экспорта определялся в зависимости от темпов роста уровня внутренних цен и цен ____________ (**мировой, экономика**), обменного курса, а также темпа роста мировой экономики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'мировой экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Новые IT проекты будут создавать безопасный цифровой фундамент развития национальной ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Эконометрическая модель — это уравнение или множество уравнений с числовыми значениями параметров, определенными на основании поведения ____________ (**экономика**) в прошлом, которые описывают динамику экономики в целом.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'ростом экономики', 
                          title = '#### В части небанковского сектора задаются функции вероятности дефолта заемщика, которые монотонно возрастают пропорционально росту кредитования, однако монотонно снижаются с ____________ (**рост, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'ростом экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'модернизацию экономики', 
                          title = '#### Глобальный энергопереход дает шанс России на ____________ (**модернизация, экономика**), несмотря на ее зависимость от нефти.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'модернизацию экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'имеющихся в экономике', 
                          title = '#### Предел экстенсивного экономического роста определяется физическим запасом всех доступных ресурсов, ____________ (**иметься, в, экономика**) любой страны.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'имеющихся в экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'влияния на экономику', 
                          title = '#### На современном этапе очень актуально изучение ____________ (**влияние, на, экономика**) региона нефтегазовых компаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'влияния на экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'развитие экономики', 
                          title = '#### Человеческий капитал – движущая сила экономического роста. Все, что способствует неравенству возможностей и препятствует реализации талантов, сдерживает и ____________ (**развитие, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'развитие экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Сигналами к корректированию сформированного портфеля будут рыночные изменения в ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Сбережения служат источником финансирования инвестиций, а увеличение инвестиций увеличивает запас капитала в экономике, производственные возможности ____________ (**экономика**) растут, совокупный выпуск увеличивается, что ведет к увеличению совокупного потреб­ления.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'рыночной экономикой', 
                          title = '#### Умеренная (ползучая) инфляция, которая имеет невысокие темпы роста цен (до 10% в год) присуща большинству стран с развитой ____________ (**рыночный, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'рыночной экономикой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Рецессии часто возникают после шоков в ____________ (**экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'отраслям экономики', 
                          title = '#### После того, как проведена оценка инвестиционной привлекательности по ____________ (**отрасль, экономика**), важно выбрать наиболее эффективное с инвестиционной точки зрения предприятие.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'отраслям экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### Степень диверсификации ____________ (**экономика**) страны остается крайне низкой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### В XXI веке современная российская экономика трасформируется в в ____________ (**экономика**) знаний.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономика в которой', 
                          title = '#### Сформировалась смешанная ____________ (**экономика, в, который**) государственное регулирование выступает дополняющим элементом рыночного саморегулирования.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономика в которой',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономики', 
                          title = '#### В 70–80-е гг. 20 века среди макроэкономистов завоевала популярность теория ____________ (**экономика**) предложения.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономику', 
                          title = '#### В СССР уровень государственной нагрузки на ____________ (**экономика**) был очень высоким и составлял приблизительно ту же величину, что и в странах с развитой рыночной экономикой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономику',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста экономики', 
                          title = '#### Автономные инвестиции дают импульсдля ____________ (**рост, экономика**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'роста экономики', 
                          title = '#### Руководство страны решило, что для ____________ (**рост, экономика**)  все сделано, дальнейшие реформы не требуются, а теперь главное – это контролировать экономику, передавать все большую ее часть под контроль государства.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'роста экономики',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономике', 
                          title = '#### Переменная S представляет собой объем сбережений в ____________ (**экономика**), а Y – ВВП или национальный доход.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономике',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

