```{r}
checkdown::check_question(answer = 'стимулирования инновационного экономического роста', 
                          title = '#### Изученный зарубежный опыт США и Китая может иметь стратегическое значение при формировании дальнейшей налоговой политики ____________ (**стимулирование, инновационный, экономический, рост**) в Республике Казахстан с учетом развития социального и культурного капитала, с учетом национальной специфики.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стимулирования инновационного экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня экономического развития региона', 
                          title = '#### Одной из основных причин пониженного ____________ (**уровень, экономический, развитие, регион**), если этот уровень оценивать по душевым показателям ВРП, является очень низкая его доля в добавленной стоимости двух крупнейших в современной экономике видов деятельности - торговли и операций с недвижимостью, аренды и предоставления услуг, суммарный объем добавленной стоимости которых по России в целом уже превышает аналогичный показатель для всей промышленности.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня экономического развития региона',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокие темпы экономического роста', 
                          title = '#### Абстрактно ____________ (**высокий, темп, экономический, рост**) сами по себе не являются гарантией того, что общество получит экономику, способную решить проблему обеспечения качества жизни населения, параметры которого соответствуют общественным представлениям о необходимом уровне такого качества.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокие темпы экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'теория реального экономического цикла', 
                          title = '#### Как ____________ (**теория, реальный, экономический, цикл**) характеризует экономические последствия увеличения государственных закупок?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теория реального экономического цикла',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высокие темпы экономического роста', 
                          title = '#### В допандемийном 2019 г. низкокоррумпированные страны (с первых мест рейтинга ИВК) как Финляндия, Сингапур, Великобритания, США имели не____________ (**высокий, темп, экономический, рост**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высокие темпы экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'новой институциональной экономической теории', 
                          title = '#### Эволюция институциональной экономики долгое время происходила в двух магистральных направлениях: оригинальной институциональной экономической теории (OIE) и ____________ (**новый, институциональный, экономический, теория**) (NIE).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новой институциональной экономической теории',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'новая модель экономического роста', 
                          title = '#### Состоится ли ____________ (**новый, модель, экономический, рост**) в России?',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новая модель экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'уровня экономического развития региона', 
                          title = '#### Выявлены особенности, структура и типы измерителей ____________ (**уровень, экономический, развитие, регион**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'уровня экономического развития региона',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоким уровнем экономического развития', 
                          title = '#### Обладая большим экономическим потенциалом и довольно ____________ (**высокий, уровень, экономический, развитие**), Бразилия входит в число новых индустриализующихся стран.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоким уровнем экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'новой модели экономического роста', 
                          title = '#### Долгосрочная сбалансированность и устойчивость бюджетной системы — важнейшее условие формирования ____________ (**новый, модель, экономический, рост**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новой модели экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'теории реального экономического цикла', 
                          title = '#### Сторонники ____________ (**теория, реальный, экономический, цикл**), напротив, считают, что возможности государства в этой области ограничены, а если они и есть, то лучше их не использовать.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теории реального экономического цикла',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоким уровнем экономического развития', 
                          title = '#### Такая выборка позволит нам рассмотреть влияние трансмиссионных каналов на состояние региона с относительно ____________ (**высокий, уровень, экономический, развитие**), значительной сырьевой базой и развитой банковской системой.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоким уровнем экономического развития',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'новой модели экономического роста', 
                          title = '#### Либеральный подход к формированию ____________ (**новый, модель, экономический, рост**), предложенный Е. Ясиным, не учитывает ряд факторов, которые активно проявились в период после 2013 г.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'новой модели экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'пространственной связности экономической активности', 
                          title = '#### Чем выше уровень ____________ (**пространственный, связность, экономический, активность**) российских регионов с соседним территориями, тем больше выигрывают соседи.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'пространственной связности экономической активности',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоких темпов экономического роста', 
                          title = '#### Предусматривалось достижение ____________ (**высокий, темп, экономический, рост**) за счет перераспределения национального дохода, повышения нормы накопления при тесном сотрудничестве государства, национального и иностранного капиталов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоких темпов экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'высоких темпов экономического роста', 
                          title = '#### В случае направления бюджетных доходов от налогов на выбросы на инвестиции в долгосрочной перспективе удается достичь более ____________ (**высокий, темп, экономический, рост**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'высоких темпов экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'экономическая оценка эффективности инвестиций', 
                          title = '#### Во втором разделе учебника изучаются вопросы более прикладного характера: источники финансирования инвестиций, методы и формы финансирования инвестиций, ____________ (**экономический, оценка, эффективность, инвестиция**), в том числе цифровых методов.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'экономическая оценка эффективности инвестиций',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'теории реального экономического цикла', 
                          title = '#### Эффект межвременного замещения при выборе работниками режима занятости занимает в ____________ (**теория, реальный, экономический, цикл**) центральное место, и ответу на вопрос, на самом ли деле его роль настолько важна, посвящено множество исследований.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теории реального экономического цикла',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'стимулирования инновационного экономического роста', 
                          title = '#### Цифровизация оказывает противоречивое влияние на инструменты налогового ____________ (**стимулирование, инновационный, экономический, рост**).',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'стимулирования инновационного экономического роста',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

```{r}
checkdown::check_question(answer = 'теория реального экономического цикла', 
                          title = '#### Отказавшись от объяснения экономического цикла денежными причинами, ____________ (**теория, реальный, экономический, цикл**) должна выполнить две задачи.',
                          right = 'все верно!', 
                          wrong = 'к сожалению нет, попробуйте еще раз...',
                          button_label = 'проверить')
checkdown::check_hint(hint_text = 'теория реального экономического цикла',
                      hint_title = '🔎 Нажмите, чтобы посмотреть ответ')
```

